### PR TITLE
Improve instructions and wording

### PR DESCRIPTION
**Pull request by w0000000t**
Added case where user is in IDEA welcome screen, and there is no `File > Settings` menu available.

Fixes #replaceWithIssueNr, fixes #replaceWithIssueNr

Your PR description here.

### CODE REVIEW

**Review by ripcurlx — DISMISSED** [review]
utACK

**Comment by ripcurlx** [comment]
@w0000000t You have to sign your commits before I can merge this PR. See https://help.github.com/articles/signing-commits-using-gpg/

**Comment by w0000000t** [comment]
> @w0000000t You have to sign your commits before I can merge this PR. See https://help.github.com/articles/signing-commits-using-gpg/

I am sorry for the results; been this close to just give up, spent more than two hours on this signature stuff. Never used Java before, and pretty much same level with github as well.
So 3 commits instead of one is the best I could do for now 😞

**Comment by ripcurlx** [comment]
> > @w0000000t You have to sign your commits before I can merge this PR. See https://help.github.com/articles/signing-commits-using-gpg/
> 
> I am sorry for the results; been this close to just give up, spent more than two hours on this signature stuff. Never used Java before, and pretty much same level with github as well. So 3 commits instead of one is the best I could do for now 😞

No worries - git can be a hell in the beginning and especially using `rebase`. Here is what I did to squash your commits:

`git rebase -i HEAD~2` (to change your last two commits, the third is just a merge commit)
Bildschirmfoto 2022-01-25 um 10 26 55
Change one commit to squash it with the other commit. Using `i` command to edit.
Bildschirmfoto 2022-01-25 um 10 27 15
Click `ESC` and write `wq!` to save your changes.
Bildschirmfoto 2022-01-25 um 10 27 25
Adapt the commit message. I only deleted one of the messages by using the `dd` command for deleting lines.
Bildschirmfoto 2022-01-25 um 10 27 48
Click `ESC` and write `wq!` to save your changes.
Bildschirmfoto 2022-01-25 um 10 27 59
All squashed correctly. To be sure I checked with `git log` the commit history.
Bildschirmfoto 2022-01-25 um 10 28 15
Last step I force pushed the changes to your branch with: `git push --force w0000000t idea-import_improve`. In your case it probably would be `git push --force origin idea-import_improve`

**Review by ripcurlx — APPROVED** [review]
ACK

**Comment by w0000000t** [comment]
I have no shame admitting that the above post looks like Vogon dialect to me, but I understand you put a lot of efforts in my place 🙇

**Pull request merged**
