### PR TITLE
Various improvements in GetBlocks handling

### PR DESCRIPTION
**Pull request by chimp1984**

### CODE REVIEW

**Comment by chimp1984** [comment]
Seem Travis has issues. Did a full build/test locally and all was ok. Please ignore codacy warning.

**Comment by ripcurlx** [comment]
> Seem Travis has issues. Did a full build/test locally and all was ok. Please ignore codacy warning.

I removed the pattern. Please force push to re-trigger Codacy. Thanks!

**Comment by chimp1984** [comment]
@ripcurlx Force push does not work to re-trigger it from my last experience. You cannot merge when Codacy complains? I thouhgt its non-blocking? Btw. that PR should not get into 1.5.0, too risky to getting added that later.

**Comment by ripcurlx** [comment]
> @ripcurlx Force push does not work to re-trigger it from my last experience. You cannot merge when Codacy complains? I thouhgt its non-blocking? Btw. that PR should not get into 1.5.0, too risky to getting added that later.

It worked for me so far. It is configured as non-blocking, but that GitHub settings seems to be not working correctly. We'll get soon to a state where Codacy only will complain if there is a reason for it :wink:

**Comment by chimp1984** [comment]
Merged with master and resolved merge conflicts

**Comment by chimp1984** [comment]
Replaced by #4851 and #4850

**Pull request closed without merging**
