### PR TITLE
Start pricenode providers asynchronously

### LINKED ISSUE #4441: Bisq Pricenode crashes on startup if any providers are unavailable for first query
@cd2357 can you please look at this critical issue ASAP?

```
    __    _                             _                           __
   / /_  (_)________ _      ____  _____(_)_______  ____  ____  ____/ /__
  / __ \/ / ___/ __ `/_____/ __ \/ ___/ / ___/ _ \/ __ \/ __ \/ __  / _ \
 / /_/ / (__  ) /_/ /_____/ /_/ / /  / / /__/  __/ / / / /_/ / /_/ /  __/
/_.___/_/____/\__, /     / .___/_/  /_/\___/\___/_/ /_/\____/\__,_/\___/
                /_/     /_/  (v0.7.2-SNAPSHOT)
bisq/bisq/lib/pricenode-0.7.2-SNAPSHOT.jar started by bisq in /)
#033[0;39m#033[34mAug-27 02:32:43.569 [main] INFO  bisq.price.Main: No active profile set, falling back to default profiles: default
#033[0;39mWARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/bisq/bisq/lib/spring-core-4.3.14.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
#033[34mAug-27 02:32:45.191 [main] INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer: Tomcat initialized with port(s): 8080 (http)
#033[0;39m#033[34mAug-27 02:32:45.759 [main] INFO  b.p.s.p.Hitbtc: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.766 [main] INFO  b.p.s.p.Coinone: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.771 [main] INFO  b.p.s.p.Bitstamp: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.775 [main] INFO  b.p.s.p.Bitfinex: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.779 [main] INFO  b.p.s.p.CoinGecko: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.789 [main] INFO  b.p.s.p.Quoine: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.791 [main] INFO  b.p.s.p.Luno: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.794 [main] INFO  b.p.s.p.CoinMarketCap: will refresh every PT5M
#033[0;39m#033[34mAug-27 02:32:45.796 [main] INFO  b.p.s.p.Huobi: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.799 [main] INFO  b.p.s.p.Bitflyer: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.801 [main] INFO  b.p.s.p.IndependentReserve: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.804 [main] INFO  b.p.s.p.Paribu: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.806 [main] INFO  b.p.s.p.BitcoinAverage: will refresh every PT1H40M
#033[0;39m#033[34mAug-27 02:32:45.809 [main] INFO  b.p.s.p.Poloniex: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.811 [main] INFO  b.p.s.p.Bitbay: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.813 [main] INFO  b.p.s.p.Binance: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.816 [main] INFO  b.p.s.p.MercadoBitcoin: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.818 [main] INFO  b.p.s.p.Coinpaprika: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.823 [main] INFO  b.p.s.p.Exmo: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.825 [main] INFO  b.p.s.p.Bitpay: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.831 [main] INFO  b.p.s.p.Kraken: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.834 [main] INFO  b.p.s.p.BTCMarkets: will refresh every PT1M
#033[0;39m#033[34mAug-27 02:32:45.852 [main] INFO  b.p.m.p.MempoolFeeRateProvider$First: will refresh every PT2M
#033[0;39m#033[34mAug-27 02:32:45.856 [main] INFO  b.p.m.p.MempoolFeeRateProvider$Second: will refresh every PT2M
#033[0;39m#033[34mAug-27 02:32:51.363 [main] INFO  b.p.s.p.Hitbtc: refresh took 4772 ms.
#033[0;39m#033[34mAug-27 02:32:51.367 [main] INFO  b.p.s.p.Hitbtc: BTC/USD: 11384.16
#033[0;39m#033[34mAug-27 02:32:51.374 [main] INFO  b.p.s.p.Hitbtc: BTC/LTC: 0.0050699
#033[0;39m#033[34mAug-27 02:32:51.670 [main] INFO  b.p.s.p.Coinone: refresh took 295 ms.
#033[0;39m#033[34mAug-27 02:32:52.748 [main] INFO  b.p.s.p.Bitstamp: refresh took 1077 ms.
#033[0;39m#033[34mAug-27 02:32:52.750 [main] INFO  b.p.s.p.Bitstamp: BTC/LTC: 0.00507334
#033[0;39m#033[34mAug-27 02:32:52.751 [main] INFO  b.p.s.p.Bitstamp: BTC/USD: 11388.52
#033[0;39m#033[34mAug-27 02:32:54.302 [main] INFO  b.p.s.p.Bitfinex: refresh took 1550 ms.
#033[0;39m#033[34mAug-27 02:32:54.303 [main] INFO  b.p.s.p.Bitfinex: BTC/USD: 11402.0
#033[0;39m#033[34mAug-27 02:32:54.303 [main] INFO  b.p.s.p.Bitfinex: BTC/LTC: 0.0050748
#033[0;39m#033[34mAug-27 02:32:54.425 [main] INFO  b.p.s.p.CoinGecko: refresh took 122 ms.
#033[0;39m#033[34mAug-27 02:32:54.426 [main] INFO  b.p.s.p.CoinGecko: BTC/LTC: 0.00507406
#033[0;39m#033[34mAug-27 02:32:54.426 [main] INFO  b.p.s.p.CoinGecko: BTC/USD: 11392.673
#033[0;39m#033[34mAug-27 02:32:55.232 [main] INFO  b.p.s.p.Quoine: refresh took 805 ms.
#033[0;39m#033[34mAug-27 02:32:55.233 [main] INFO  b.p.s.p.Quoine: BTC/USD: 11410.33
#033[0;39m#033[34mAug-27 02:33:00.331 [main] INFO  b.p.s.p.Luno: refresh took 5098 ms.
#033[0;39m#033[34mAug-27 02:33:00.331 [main] INFO  b.p.s.p.CoinMarketCap: refresh took 0 ms.
#033[0;39m#033[34mAug-27 02:33:02.690 [main] INFO  b.p.s.p.Huobi: refresh took 2358 ms.
#033[0;39m#033[34mAug-27 02:33:02.691 [main] INFO  b.p.s.p.Huobi: BTC/LTC: 0.005067
#033[0;39m#033[31mAug-27 02:33:03.116 [main] WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'bitflyer'; nested exception is org.knowm.xchange.exceptions.ExchangeException: org.knowm.xchange.bitflyer.dto.BitflyerException: Under maintenance
#033[0;39m#033[1;31mAug-27 02:33:03.173 [main] ERROR o.s.b.SpringApplication: Application startup failed org.springframework.context.ApplicationContextException: Failed to start bean 'bitflyer'; nested exception is org.knowm.xchange.exceptions.ExchangeException: org.knowm.xchange.bitflyer.dto.BitflyerException: Under maintenance
#011at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
#011at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
#011at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348)
#011at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151)
#011at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114)
#011at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
#011at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
#011at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
#011at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
#011at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
#011at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
#011at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
#011at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
#011at bisq.price.Main.main(Main.java:36)
Caused by: org.knowm.xchange.exceptions.ExchangeException: org.knowm.xchange.bitflyer.dto.BitflyerException: Under maintenance
#011at org.knowm.xchange.bitflyer.service.BitflyerBaseService.handleError(BitflyerBaseService.java:48)
#011at org.knowm.xchange.bitflyer.service.BitflyerMarketDataServiceRaw.getMarkets(BitflyerMarketDataServiceRaw.java:32)
#011at org.knowm.xchange.bitflyer.BitflyerExchange.remoteInit(BitflyerExchange.java:53)
#011at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:107)
#011at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:78)
#011at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:36)
#011at bisq.price.spot.ExchangeRateProvider.doGet(ExchangeRateProvider.java:106)
#011at bisq.price.spot.providers.Bitflyer.doGet(Bitflyer.java:42)
#011at bisq.price.spot.providers.Bitflyer.doGet(Bitflyer.java:31)
#011at bisq.price.PriceProvider.refresh(PriceProvider.java:78)
#011at bisq.price.PriceProvider.start(PriceProvider.java:58)
#011at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175)
#011... 13 common frames omitted
Caused by: org.knowm.xchange.bitflyer.dto.BitflyerException: Under maintenance
#011at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
#011at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
#011at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
#011at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
#011at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
#011at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
#011at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228)
#011at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
#011at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:405)
#011at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
#011at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
#011at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
#011at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2896)
#011at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
#011at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
#011at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
#011at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
#011at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
#011at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
#011at com.sun.proxy.$Proxy102.getMarkets(Unknown Source)
#011at org.knowm.xchange.bitflyer.service.BitflyerMarketDataServiceRaw.getMarkets(BitflyerMarketDataServiceRaw.java:30)
#011... 23 common frames omitted
#033[0;39morg.springframework.context.ApplicationContextException: Failed to start bean 'bitflyer'; nested exception is org.knowm.xchange.exceptions.ExchangeException: org.knowm.xchange.bitflyer.dto.BitflyerException: Under maintenance
#011at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
#011at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
#011at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348)
#011at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151)
#011at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114)
#011at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
#011at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
#011at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
#011at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
#011at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
#011at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
#011at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
#011at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
#011at bisq.price.Main.main(Main.java:36)
Caused by: org.knowm.xchange.exceptions.ExchangeException: org.knowm.xchange.bitflyer.dto.BitflyerException: Under maintenance
#011at org.knowm.xchange.bitflyer.service.BitflyerBaseService.handleError(BitflyerBaseService.java:48)
#011at org.knowm.xchange.bitflyer.service.BitflyerMarketDataServiceRaw.getMarkets(BitflyerMarketDataServiceRaw.java:32)
#011at org.knowm.xchange.bitflyer.BitflyerExchange.remoteInit(BitflyerExchange.java:53)
#011at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:107)
#011at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:78)
#011at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:36)
#011at bisq.price.spot.ExchangeRateProvider.doGet(ExchangeRateProvider.java:106)
#011at bisq.price.spot.providers.Bitflyer.doGet(Bitflyer.java:42)
#011at bisq.price.spot.providers.Bitflyer.doGet(Bitflyer.java:31)
#011at bisq.price.PriceProvider.refresh(PriceProvider.java:78)
#011at bisq.price.PriceProvider.start(PriceProvider.java:58)
#011at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175)
#011... 13 common frames omitted
Caused by: org.knowm.xchange.bitflyer.dto.BitflyerException: Under maintenance
#011at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
#011at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
#011at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
#011at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
#011at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
#011at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
#011at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228)
#011at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
#011at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:405)
#011at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
#011at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
#011at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
#011at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2896)
#011at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
#011at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
#011at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
#011at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
#011at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
#011at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
#011at com.sun.proxy.$Proxy102.getMarkets(Unknown Source)
#011at org.knowm.xchange.bitflyer.service.BitflyerMarketDataServiceRaw.getMarkets(BitflyerMarketDataServiceRaw.java:30)
#011... 23 common frames omitted
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #4441

This guarantees that the pricenode will run even when there is a problem with a provider at startup.  It simply calls the initial `refresh()` asynchronously rather than blocking the bean startup routine.  To my point of view there is no difference between the first and subsequent calls to refresh, since providers can fail at any time.  When rates are requested any non-initialized provider is ignored.  

However I have not taken ownership of the pricenode and only have a superficial understanding of how the data is calculated.  I did enough testing to check that the price and fee data looks good, and that the automated tests pass.  There could certainly be edge cases that I'm not aware of.  @cd2357 is certainly free to flame me if this is a stupid change, as he put a lot more work into it than I did.

### CODE REVIEW

**Comment by wiz** [comment]
Thanks for working on this. I think the main concern is what price do you return if there is no data for a given asset? In that case I assume you don't return anything, or a null value, right?

**Comment by ghost** [comment]
If there is no data for a given asset, that asset would not be present in the JSON data.  

For example, running with only two providers: Kraken and Luno, the rate for ZAR is not present in the JSON data.  ZAR is provided by Luno (not Kraken), but Luno service is down.  If the Binance provider is included, the ZAR rate is present.

**Comment by ripcurlx** [comment]
@cd2357 Could you please give this code changes a quick ACK?

**Comment by cd2357** [comment]
My main concern is this:
- let's say a pricenode cannot connect to one or more exchanges, but still starts up
  - this means that, worst case, it won't provide a price feed for some "unlucky" currencies / assets, which were only available on the currently-not-reachable exchanges
- a Bisq node connects to this pricenode for price data
- if this node wants to start a trade (or has any ongoing trade) in any of the above "unlucky" currencies, this could result in failed trades, or the inability to create/accept new trades. Also, not sure what other side-effects this would have for clients in general (NPEs, errors in UI or trade protocol, etc).

This is now avoided by the simple fact that a pricenode always provides a price for all known / expected currencies :
- If an exchange is not reachable during pricenode startup, then the startup fails until that exchange is reachable again (not ideal, I know, but at least protects Bisq nodes from the scenario above).
- If a pricenode starts with all exchanges reachable, but some exchange becomes unreachable later on, the scenario above is still not an issue, because that pricenode will serve the "cached" (or last known) price for the affected currencies or assets -- until the problematic exchange comes back online again. Actually, I think the pricenode will provide an aggregated price for the affected currencies (if the aggregate price is an average of 3 prices from 3 exchanges, and one exchange goes offline, then the pricenode will serve an aggregate price based on the current data from the 2 working exchanges + the "cached" latest known price from the 3rd exchange, until that exchange comes back online).

I admit this is mainly a theoretical concern (I didn't test it out and see errors), but it seems reasonable that these risks are possible. Most "at risk" currencies are those with a small number of "inputs" in the aggregate price, like those depending on 1-2-3 exchanges: https://bisq.wiki/Bisq_Price_Indices . For example, lots of fiat currencies have only 1 provider (BitPay).

How do you see this?

Is this an acceptable risk, or maybe am I over-estimating it?

If not, how could it be mitigated? One possible solution that comes to mind is that pricenodes periodically persist to disk the latest-known prices for all supported currencies, then if they are restarted and some exchanges are temporarily unreachable, they could report the "cached" price for those currencies until the faulty exchanges come back online. (This cache approach is already in place, but the prices are cached in-memory, not persisted on-disk.)

cc @bisq-network/pricenode-operators

**Comment by ghost** [comment]
Good points.  When rates are not available Bisq displays the price as of the last trade:
image


If you try and take an offer this message prevents it:
image

Likewise making an offer it forces you to enter a fixed price:
image

Or of you had an already published market rate offer; your price feed is down and someone tries to take it they get this:
image

**Comment by cd2357** [comment]
What happens if
- user creates market rate offer (when pricefeed for that currency is available)
- user disables offer
- pricefeed for that currency becomes unavailable (user restarts Bisq, chooses a pricenode without that feed)
- user re-enables offer

Does re-enabling the offer fail graciously?

Also, if shortly after that the pricefeed becomes available again (Bisq client didn't restart, kept using same pricenode, but not pricenode starts providing the needed pricefeed) -- will the client detect that and allow the user to re-enable the offer / create new offers in that currency?

**Comment by ghost** [comment]
Per your first question, re-enabling the offer does not fail, you can disable/enable at will.  The status of the pricefeed is not taken into account.  The trading protocol would prevent a market based offer from being taken due to the price feed being N/A.

Per your second question, offers can still be created when the pricefeed is down.  If the pricefeed fails while Bisq is running, the user can still create market based offers.   If Bisq starts up with no pricefeed available the user is only allowed to create fixed price offers.

**Review by cd2357 — APPROVED** [review]

**Comment by cd2357** [comment]
In that case, it sounds good from my side. Thanks for the detailed answers @jmacxx.

@wiz do you want to coordinate more extensive tests on this first? Or is this fine and can be merged?

**Review by cd2357 — APPROVED** [review]

**Comment by ripcurlx** [comment]
As pricenode providers are running from specific master versions anyways I'm not merging this for v1.5.2. Waiting for testing by @wiz.

**Comment by ripcurlx** [comment]
@wiz ☝️

**Comment by ghost** [comment]
@wiz did this get installed to production?  It [seemed like a high priority](https://github.com/bisq-network/bisq/issues/4441#issuecomment-681774819) when you were ~~complaining about it~~ asking for it to be fixed.

**Comment by wiz** [comment]
@jmacxx sorry for the late reply, yes it was a high priority because it can cause pricenodes to completely fail to startup. I apologize I haven't had time to properly ACK the PR but IIRC it's running on my pricenode server for a while now. @emzy would you mind testing/reviewing this PR ?

**Comment by Emzy** [comment]
I have this PR as a test running on my pricenode "emzypricpidesmyqg2hc6dkwitqzaxrqnpkdg3ae2wef5znncu2ambqd.onion"

**Comment by ripcurlx** [comment]
@Emzy @wiz As soon as I have an ACK from either of you I'll move forward and merge this PR.

**Comment by Emzy** [comment]
ACK
No issues on my production pricenode.

**Review by ripcurlx — APPROVED** [review]
utACK - based on https://github.com/bisq-network/bisq/pull/4890#issuecomment-784217253

**Pull request merged**
