### PR TITLE
List pasc-coin

### PR DESCRIPTION
**Pull request by mordan**
- Official project URL: https://www.pascalcoin.org
- Official block explorer URL: http://explorer.pascalcoin.org

Charles-Philip Bentley mordan9@gmail.com

### CODE REVIEW

**Review by blabno — COMMENTED** [review]
Pretty trivial tests for that complex validator.

**Comment by mordan** [comment]
The check verification is pretty trivial since pascal coin addresses are super simple. From 0 onwards.

there are a just few border cases. Validator seems complex because of the checksum that is not mandatory.

**Comment by blabno** [comment]
Are all those edge cases covered with tests? Please check it, cause I'm going to run coverage check.

**Comment by mordan** [comment]
You were right. a few edge cases were not covered in the **public void testInvalidAddresses()**

Add those lines will fix it

     ```
        //checksum with characters
        assertInvalidAddress("3532-zZ");

        //trailing dash
        assertInvalidAddress("0-");
        assertInvalidAddress("-");

        //too big a number
        assertInvalidAddress("1000000000");
        assertInvalidAddress("1000000000-46");

```
Code coverage will show that there is a catch that never actually run. 
```
   } catch (StringIndexOutOfBoundsException e) {
                return AddressValidationResult.invalidAddress(ERROR_INVALID_CHECKSUM_STRUCTURE);
   }
```
It was put there as a defensive measure.

What do you want me to do?
          
Cheers

**Comment by mordan** [comment]
@blabno so what's the status?

**Comment by blabno** [comment]
@mordan Please rebase this branch against current master and resolve conflicts. Sorry for this, but delisting PR got merged meanwhile and it has introduced lots of changes.

**Comment by blabno** [comment]
btw. I've checked coverage and it does not cover exceptions and one of the `else` cases.

**Comment by ManfredKarrer** [comment]
Close as no response from dev. Also we have a code freeze for new release soon.

**Comment by mordan** [comment]
I can't build your project anymore with IntelliJ since your merge. Its riddled with errors due to Lombok Plug-in.
everything was fine when assets was on a separated repo

**Comment by devinbileck** [comment]
@mordan What version of IntelliJ? There may be issues with Lombok support in the latest IntelliJ 2018.3.
See https://github.com/mplushnikov/lombok-intellij-plugin/issues/556

**Comment by mordan** [comment]
it was not the latest.. i try not to update because updates break things.
never used Lombok. I followed a tuto on github to make it all work and somehow didn't work out.
why are people obsessed with those heavy frameworks that make you write less verbose code. we are back to dependency hell.
basically gave up. too bad for this pull request.

**Comment by devinbileck** [comment]
Did you follow the instructions in https://github.com/bisq-network/bisq/blob/master/docs/idea-import.md?

**Pull request closed without merging**
