### PR TITLE
Added script to install Java SE 10 target platform on OS rpm based

### PR DESCRIPTION
**Pull request by albpal**
Easy script to install the required java and perform ./gradlew build after that.

### CODE REVIEW

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Comment by ManfredKarrer** [comment]
@devinbileck Maybe you can have a look as well?

**Comment by devinbileck** [comment]
utACK
Looks fine to me. However, with only one line that differs from the other script, it should really be handled within a single script - less duplication and maintenance required.

**Comment by ManfredKarrer** [comment]
@devinbileck Agree. Would you be able to make that  merged scipt (after release)?

**Comment by devinbileck** [comment]
@ManfredKarrer yep I can clean that up later.

**Comment by ManfredKarrer** [comment]
@devinbileck Thanks. I will merge it in and later we consolidate those 2 files.

**Pull request merged**
