### PR TITLE
Update installation script

### PR DESCRIPTION
**Pull request by 81dr**
Resolves case as stated in [other PR](https://github.com/bisq-network/bisq/pull/4861). Additionally makes some minor corrections.

### CODE REVIEW

**Comment by ripcurlx** [comment]
@devinbileck Could you please have a look at this again? Thanks!

**Comment by ripcurlx** [comment]
@devinbileck ☝️ Thanks!

**Comment by devinbileck** [comment]
Sorry, I missed this. Will do!

**Review by devinbileck — APPROVED** [review]
utACK

**Review by ripcurlx — APPROVED** [review]
utACK based on https://github.com/bisq-network/bisq/pull/4893#pullrequestreview-560240276

**Pull request merged**
