### PR TITLE
Remove Slack notification in travis build config

### PR DESCRIPTION
**Pull request by freimair**
While I played around with the travis config in order to get a test coverage report, I noticed that there still is some configuration for Slack. We have not used Slack for quite some time now so I figured it is time to remove that remnant of old times as well.

### CODE REVIEW

**Review by chimp1984 — COMMENTED** [review]
utACK

**Review by ripcurlx — APPROVED** [review]
utACK

**Comment by ripcurlx** [comment]
@freimair You need to update your key which signed the commit as it is expired.

**Comment by freimair** [comment]
> @freimair You need to update your key which signed the commit as it is expired.

well that is a bummer. reuploaded the same exact key and all seems well again.

**Pull request merged**
