### PR TITLE
Target BitcoinJ version with "Reduce log level of two messages" patch

### PR DESCRIPTION
**Pull request by alejandrogarcia83**
This change targets BitcoinJ with the following commit included https://github.com/bisq-network/bitcoinj/pull/39.

### CODE REVIEW

**Comment by ghost** [comment]
I applied this patch but am not sure how to verify which BitcoinJ is in the build.  
The version shown is the same as before.  `BitcoinJ version 0.15.10.bisq.15 and hash of BitcoinJ commit 2a80db4 `
To see if the logging has improved I can run bisq for an extended period, but it is not easy to prove as the problem is intermittent and happens randomly to users.

**PRE:**

    Dec-26 23:10:26.632 [JavaFX Application Thread] INFO  b.c.a.WalletAppSetup: Initialize WalletAppSetup with BitcoinJ version 0.15.10.bisq.15 and hash of BitcoinJ commit 2a80db4 
    Dec-26 23:10:26.647 [JavaFX Application Thread] INFO  b.c.b.s.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=null 
    Dec-26 23:10:26.661 [JavaFX Application Thread] INFO  o.b.c.Context: Creating bitcoinj 0.15.10.bisq.15 context. 



**POST:**

    Jan-03 20:00:58.780 [JavaFX Application Thread] INFO  b.c.a.WalletAppSetup: Initialize WalletAppSetup with BitcoinJ version 0.15.10.bisq.15 and hash of BitcoinJ commit 2a80db4 
    Jan-03 20:00:58.799 [JavaFX Application Thread] INFO  b.c.b.s.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=localhost:46779	Version 5 
    Jan-03 20:00:58.804 [JavaFX Application Thread] INFO  o.b.c.Context: Creating bitcoinj 0.15.10.bisq.15 context.

**Review by ghost — DISMISSED** [review]
utACK based on https://github.com/bisq-network/bisq/pull/6497#issuecomment-1370417739

**Comment by alejandrogarcia83** [comment]
Do you want me to update the version number to make it more clear?

**Comment by alejandrogarcia83** [comment]
I'll update the version number and create new bitcoinj release. I don't have the necessary permissions. Waiting for @gabernard to add me.

**Comment by alejandrogarcia83** [comment]
@jmacxx I updated the version number.

**Review by alvasw — APPROVED** [review]
ACK

```
Jan-16 17:57:01.049 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: Init wallet 
Jan-16 17:57:01.050 [JavaFX Application Thread] INFO  bisq.core.app.WalletAppSetup: Initialize WalletAppSetup with BitcoinJ version 0.15.10.bisq.16 and hash of BitcoinJ commit 2a80db4 
Jan-16 17:57:01.060 [JavaFX Application Thread] INFO  b.core.btc.setup.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=localhost:37867	Version 5 
Jan-16 17:57:01.062 [JavaFX Application Thread] INFO  org.bitcoinj.core.Context: Creating bitcoinj 0.15.10.bisq.16 context. 
```

**Review by gabernard — APPROVED** [review]
utACK

**Pull request merged**
