### PR TITLE
Trade process refresh

### LINKED ISSUE #3905: Seller unable to confirm payment received
### Description
Many mediation cases lately are a result of seller not being able to confirm the payment has been received. On most cases the buyer confirms they have pressed ‘payment made’ but for some reason is not showing on the other end.

### How to fix
It's hard to reproduce and might be a result of a missed mailbox message. A simple option ask for a resend from the seller side might be enough. Thinking a bit further it would be nice to be able to confirm transmission failures of these messages. Not sure how that could be done though.

I can't think of any other reason that the seller wouldn't see the confirm payment button than a failed message.

### PR DESCRIPTION
**Pull request by sqrrm**
Fix #3905 

A seller can ask to refresh the trade process once every 24 hours. This step has been a problem causing a lot of mediation lately so this is a way to ask the buyer to resend the CounterCurrencyTransferStartedMessage

This fixes the problem when a mailbox message was lost. To test the seller need to not get the first CounterCurrencyTransferStartedMessage sent by the buyer, for example by letting the seednode drop it instead of sending to the seller. When button is pressed
- a RefreshTradeStateRequest is sent from seller to buyer
- the buyer receives the RefreshTradeStateRequest and
  - ignores it if it's not in FIAT_SENT phase
  - responds with a CounterCurrencyTransferStartedMessage if in FIAT_SENT phase and has already sent a CounterCurrencyTransferStartedMessage

### CODE REVIEW

**Comment by ripcurlx** [comment]
I tested it locally on Regtest and everything seems to work as expected (changed `REFRESH_INTERVAL`for testing purpose). I tested it with both clients on PR and backwards comp test with v1.2.3 client where it fails silently if not supported.
**Before refresh trade state is enabled**
Bildschirmfoto 2020-02-03 um 11 22 22
**After refresh trade state is enabled**
Bildschirmfoto 2020-02-03 um 11 21 54

But I fear we need some extra text next to the button to explain its functionality. @m52go  Do you have a good and compact wording for it?

**Comment by ripcurlx** [comment]
And as you just suggested in chat, probably don't show the inactive button if not needed. That way it sticks more out if it is displayed at some point.

**Comment by m52go** [comment]
Suggestion:

_Sometimes P2P network messages acknowledging payment are not delivered, causing trades to get stuck. Hit the button below to resend the last message._

**Comment by sqrrm** [comment]
Added text. Hide refresh section when not available

image
image

**Review by ripcurlx — APPROVED** [review]
ACK

Works as expected on Regtest. This should reduce our mediation/refund cases a lot (hopefully)!

**Comment by sqrrm** [comment]
I'm not sure this is the only step that's losing messages. I didn't want to try to implement a generic refresh option as it's not clear in every step that it's safe to refresh.

Another option might be to make the mailbox messages more robust. I have a feeling it should be possible but I'd have to take a deeper look at how they work.

**Comment by MwithM** [comment]
Why is it possible to referesh only every 24 hours? It's too long for fast payment methods like altcoins or sepa instant.

**Comment by sqrrm** [comment]
It's a good point that it should probably be proportional to the trade duration.

**Pull request merged**
