### PR TITLE
Moved one btc node to new host

### PR DESCRIPTION
**Pull request by Emzy**
Moved node2.emzy.de to a new host.
IP address updated.

Fixes #replaceWithIssueNr, fixes #replaceWithIssueNr

Your PR description here.

### CODE REVIEW

**Review by wiz — APPROVED** [review]
ACK
```
% ./bitcoin-service-check.py 62.171.129.32 8333
OK - 619067 /Satoshi:0.19.0.1/ 199.3ms|time=199.3
```

**Comment by ripcurlx** [comment]
> Moved node2.emzy.de to a new host.
> IP address updated.
> 
> Fixes #replaceWithIssueNr, fixes #replaceWithIssueNr
> 
> Your PR description here.

It seems the old IP is still reachable so I guess we don't need to do any filtering until the next release is out. @Emzy Do you have a plan already when the old IP won't be available anymore?

**Review by ripcurlx — APPROVED** [review]
utACK because of https://github.com/bisq-network/bisq/pull/4010#pullrequestreview-364865464

**Comment by Emzy** [comment]
> > Moved node2.emzy.de to a new host.
> > IP address updated.
> > Fixes #replaceWithIssueNr, fixes #replaceWithIssueNr
> > Your PR description here.
> 
> It seems the old IP is still reachable so I guess we don't need to do any filtering until the next release is out. @Emzy Do you have a plan already when the old IP won't be available anymore?

It is up until 3/24.

**Pull request merged**
