### PR TITLE
Fix shutdown persistence issue in Seednode

### PR DESCRIPTION
**Pull request by ghost**
Fix issue raised by @Emzy in Keybase ops.  Seednode v1.6.0 was not persisting on shutdown.

#5280 introduced a guard in PersistenceManager to not persist at shutdown if a valid app start was not seen.
Initialize PersistenceManager in Seednode app so that the expected persist on shutdown can occur.

@chimp1984 plz check.

[edit] per @chimp1984 suggestion below, moved the init call to `AppSetupWithP2P.onBasicServicesInitialized`

### CODE REVIEW

**Comment by chimp1984** [comment]
@jmacxx Ah thanks for spotting that!
I think its better to do it in 'AppSetupWithP2P.onBasicServicesInitialized'. There are some other headless apps using those old startup code as well I guess.

**Review by chimp1984 — APPROVED** [review]
utACK

**Comment by Emzy** [comment]
testedACK
Works on my seednodes
```
Apr-03 16:57:35.996 [SeedNodeMain] WARN  b.n.p.n.TorNetworkNode: We got called shutDown again and ignore it. 
Apr-03 16:57:35.998 [SeedNodeMain] INFO  b.n.p.n.NetworkNode: Shutdown 16 connections 
Apr-03 16:57:36.044 [SeedNodeMain] INFO  b.c.p.PersistenceManager: Start flushAllDataToDisk 
...
Apr-03 16:57:36.084 [SeedNodeMain] INFO  b.n.p.n.NetworkNode: Shutdown completed with all connections closed 
Apr-03 16:57:36.086 [SeedNodeMain] WARN  b.c.p.PersistenceManager: We got flushAllDataToDisk called again. This can happen in some
 rare cases. We ignore the repeated call. 
Apr-03 16:57:36.090 [SeedNodeMain] INFO  b.c.p.PersistenceManager: flushAllDataToDisk completed 

```

**Review by ripcurlx — APPROVED** [review]
utACK based on https://github.com/bisq-network/bisq/pull/5388#issuecomment-812877413

**Pull request merged**
