### PR TITLE
added a snippet to actually install the lfs package after adding the repository with the quick curl command

### PR DESCRIPTION
**Pull request by w0000000t**
Fixes #replaceWithIssueNr, fixes #replaceWithIssueNr

Your PR description here.

### CODE REVIEW

**Comment by ripcurlx** [comment]
@w0000000t But isn't that explained on https://git-lfs.github.com/ on how to install git lfs in the LInk "Install v3.02 via PackageCloud (Linux)? Also your solution would only work on Linux and not on all other supported platforms. Or was that the problem, that you followed the guide on the git lfs page and it didn't work for you in the end?

**Comment by asvdf** [comment]
Hello, and thank you for getting back to me.
I did follow that link, which on my Linux VM brought me to https://packagecloud.io/github/git-lfs/install
There, I used the oneliner provided for the deb quick install, yet after that I got the error message as per my PR.
I had to improvise for a while and at the end thought of manually running the `apt` command first to search for a lfs package and then to actually get lfs installed, that is the reason I thought it might be useful to include my findings in the repo.

**Comment by w0000000t** [comment]
Hello, and thank you for getting back to me.
I did follow that link, which on my Linux VM brought me to https://packagecloud.io/github/git-lfs/install
There, I used the oneliner provided for the deb quick install, yet after that I got the error message as per my PR.
I had to improvise for a while and at the end thought of manually running the `apt` command first to search for a lfs package and then to actually get lfs installed, that is the reason I thought it might be useful to include my findings in the repo.

**Comment by ripcurlx** [comment]
> Hello, and thank you for getting back to me. I did follow that link, which on my Linux VM brought me to https://packagecloud.io/github/git-lfs/install There, I used the oneliner provided for the deb quick install, yet after that I got the error message as per my PR. I had to improvise for a while and at the end thought of manually running the `apt` command first to search for a lfs package and then to actually get lfs installed, that is the reason I thought it might be useful to include my findings in the repo.

Sorry for my late reply on this. Maybe add the note on which OSes this workaround would fix the issue (it is obvious for most, but probably good to mention it anyways)

**Comment by w0000000t** [comment]
> Sorry for my late reply on this. Maybe add the note on which OSes this workaround would fix the issue (it is obvious for most, but probably good to mention it anyways)

I have very limited GH skills, and only ever access its functions from the web UI, so I should have made the requested updates, please let me know if something is amiss

**Comment by ripcurlx** [comment]
@w0000000t Yes, Git/GitHubs workflow can be overwhelming in the beginning. For the future to improve your commit messages please have a look at @cbeams article on git commit messages: https://cbea.ms/git-commit/

For this time I'll squash your commits into one during the merge.

**Review by ripcurlx — APPROVED** [review]
ACK

**Pull request merged**
