### PR TITLE
Add Bitcoin Cash, Bitcoin Gold and Bitcoin Clashic

### PR DESCRIPTION
**Pull request by mrosseel**
Adding missing 'airdrop' coins, so they can be transacted in a more privacy-preserving way on the Bisq exchange.

### CODE REVIEW

**Comment by sqrrm** [comment]
Builds fine and tests don't complain.

**Comment by nothingmuch** [comment]
What approach will be taken for BCH/BCHC replay protection? Bclashic has a large backlog but it appears to be processing most bcash txns

**Comment by mrosseel** [comment]
@nothingmuch since the Bisq exchange never touches either BCH or BCHC, replay protection cannot be done by Bisq. I do agree that selling BCHC might have the problem that someone steals your more valuable BCH. What is your suggestion, not listing BCHC ?

**Comment by nothingmuch** [comment]
I'm biased (I like Clashic, and full disclosure I've invested quite a bit of meme magic into it ;-), so I'd like to see it listed... However as far as I know doing this without special protection, the BCHC will be sent as BCH by default, as most txns are being replayed right now. BCH txns are a bit better off, since there is considerable amounts of spendable coinbase on that chain already, and btc.com has [a service for purchasing BCH only tainted coins](https://btc.com/tools/replay).

Furthermore, it will never be easy in principle, given the way that bcash hard forked away without replay protection, I think the onus would always be on the users' operating the clients, and given block times as they are on clashic right now, this might present problems for Bisq's deposit/arbitration process.

As part of trying to contribute to the https://chainspl.it project I've been trying to scope out some minimal APIs that might help in this situation, but from the point of view of Bisq users what would probably be in order is basic tools/services that people can use to check in advance which chains a txn is valid on, and the state of the UTXO sets on the two chains? Admittedly I haven't gotten very far, and I've only really been thinking about low level primitives.

At any rate, I think a noticeable warning that says that bitcoin clashic is not very actively mined, and that transacting on it is not safe if the UTXOs are also valid on bcash would probably be a good idea.

Finally, I'd like to add that I think that this is a very worthwhile opportunity for the entire ecosystem as a whole to learn how to handle these problems, as they may very well happen to more valuable chains

**Comment by ManfredKarrer** [comment]
@nothingmuch We can add a warning popup that the users need to inform themselves and need to be aware of the risks. Do you know a good source where those issues are discussed?

**Comment by nothingmuch** [comment]
Good technical resource, yes (chainsplit slack & associated google docs), but not a good resource for regular users, unfortunately (maybe Jimmy Song's replay protection explainer for 2x?).

However, having that kind of material is part of the chainspl.it project goals though, so I think it'd be a fruitful discussion to see how Bisq's users can be better accommodated?

**Comment by ManfredKarrer** [comment]
I added here some basic info which I linked in the warning popups:
https://forum.bisq.io/t/airdrop-coins-information-thread
Anyone is invited to add more info there...

**Comment by nothingmuch** [comment]
the link above now 404s for me, but this one works: https://forum.bisq.io/t/airdrop-coins-information-thread-bch-btg-bchc/3532

**Comment by ManfredKarrer** [comment]
For me it works. Maybe it was temp. not available?

**Comment by nothingmuch** [comment]
Hmm, I'm getting "Oops! That page doesn’t exist or is private." even when I disable all of my tin foil hat browser extensions

**Comment by ManfredKarrer** [comment]
Hm, weird... Can you access the Forum main page? And browse there?

**Comment by nothingmuch** [comment]
yep, that's how I found the post again and pasted the alternate link (also note that your original link *did* work for me yesterday)

**Comment by ManfredKarrer** [comment]
Ah sorry, I renamed title, did not know that the forum software does not support the link with the old title anymore...

**Pull request merged**
