### PR TITLE
Add BSQ burned column in monthly burningman status report.

### LINKED ISSUE #6730: Have a way to distinguish 'proof of burns' between ' burns by burning men' and 'burns for Bisq 2 reputation'
### Description

Similarly to https://github.com/bisq-network/bisq/issues/6729 it would be good if the section 'all proof of burn transactions' could be distinguished between:

- Burns by burning men
- Burns for Bisq 2 reputation
- Other burns

I would propose adding the the following data to the burns:

- Burning Men
- Bisq 2 reputation
- Other

When burning BSQ in 'DAO > Proof of Burn > Proof of Burn' users could be given the option of selecting a reason for the burn between 'Bisq 2 reputation' or 'Other'.

Capture2

Burning on 'Proof of Burn > Burning Men' could be automatically tagged as 'Burning Men'

Capture3

The reason for the burning of BSQ could then be shown in the 'all proof of burn transactions' section:

Capture

This would make for accounting easier as revenue between both Bisq 1 Burning Men and Bisq 2 burning for reputation could be quickly distinguished.  

For example an extra column on the image above to show the 'Reason' for the burning of BSQ.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #6730 

Implements, as requested by @pazza83 : "_Another way to distinguish 'proof of burns' between ' burns by burning men' and 'burns for Bisq 2 reputation' would be to include the amount of BSQ burned by burning men per month in the 'Report' function in DAO > Proof of Burn > Burning Men._"

image

### CODE REVIEW

**Comment by pazza83** [comment]
@jmacxx 

Thanks for this.

1. Does the report include the BSQ burnt in December 2022?
2. Would it be possible to have a 'Difference' column? the sum of the (Distributed BTC as BSQ) -(BSQ Burnt)?

**Comment by ghost** [comment]
>    Does the report include the BSQ burnt in December 2022?

[Used to](https://github.com/bisq-network/bisq/pull/6599), but after [re-architecting](https://github.com/bisq-network/bisq/pull/6647) by Hendrick it now starts January 2023.

>    Would it be possible to have a 'Difference' column? the sum of the (Distributed BTC as BSQ) -(BSQ Burnt)?

Super easy to do after you open the CSV in a spreadsheet.  :confused:

**Review by alvasw — APPROVED** [review]
ACK

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
