### PR TITLE
Bump tor to v0.4.5.7

### PR DESCRIPTION
**Pull request by cd2357**
Bump tor-binary and netlayer dependencies to the newest versions which package tor v0.4.5.7.

### CODE REVIEW

**Review by ripcurlx — APPROVED** [review]
ACK - on macOS 11.2.3.

**Comment by ripcurlx** [comment]
@devinbileck or @BtcContributor Could you. please run it on Windows if it is working for you on Mainnet as well? Thanks!

**Comment by BtcContributor** [comment]
@ripcurlx Tested ACK, no problem on latest Windows 10 while on Mainnet.

**Comment by cd2357** [comment]
ACK, also tested on Debian 10 on Mainnet.

**Pull request merged**
