### PR TITLE
Delist untraded assets

### PR DESCRIPTION
**Pull request by cbeams**
Per https://docs.bisq.network/exchange/howto/list-asset.html#inactive-assets-will-be-de-listed:

> At each new release we will check whether already-listed assets have been traded in the past 4 months. If this requirement is not met the asset will be removed. The Bisq trade statistics are used as a reference. Removal of an un-traded asset will not be announced outside of normal release notes.

@ManfredKarrer, can you put together a PR for this for 0.9.0? In subsequent releases, perhaps @blabno can keep an eye on this and put together similar PRs that follow the template you lay out in this first one.

And can you also include a description as to how you create the list of assets to be delisted based on the trade statistics? Again, this would be so that others can easily follow suit (and possibly automate it) in the future.

### CODE REVIEW

**Comment by cbeams** [comment]
I've implemented the necessary changes and converted this issue into a pull request. @ManfredKarrer, could you please review?

@blabno, for now we'll need to start adding newly listed assets to `TradeStatisticsManager#isWarmingUp` (as in 85caf02). This doesn't affect anything at runtime, but it makes sure that we can get accurate lists of which assets to delist in the future. It only strictly needs to be done at release boundaries.

**Comment by ManfredKarrer** [comment]
Thanks @cbeams ! I need to test what happens if a user has used a coin in his altcoin accounts and if we remove it from code. Will update after that...

**Comment by ManfredKarrer** [comment]
@cbeams I tested what happens if a asset get removed and there have been minor issues. Those are fixed with https://github.com/bisq-network/bisq/pull/1895. So I prefer to get that merged first thenI will merge that PR.

**Comment by cbeams** [comment]
Perfect, thanks.

**Comment by ManfredKarrer** [comment]
@cbeams Why is Koto and Obsidian not removed? Both have been added before 11. May.

EDIT: Ah I see they are removed from the registry but code is still there.

**Comment by ManfredKarrer** [comment]
Here the current lists with changed parmeter for required volume to 0.001 BTC.

Assets to remove:
TradeCurrency(code=GBYTE, name=Byte)
TradeCurrency(code=XCP, name=Counterparty)
TradeCurrency(code=XZC, name=Zcoin)


Insufficiently traded assets:
-

Not traded assets:
Byte (GBYTE)
Counterparty (XCP)
Zcoin (XZC)


New assets (in warming up phase):
01coin (ZOC): Trade amount: 0.0302 BTC, number of trades: 14
Actinium (ACM): Trade amount: 0.00 BTC, number of trades: 0
Aquachain (AQUA): Trade amount: 0.0015 BTC, number of trades: 2
BitCloud (BTDX): Trade amount: 0.00 BTC, number of trades: 0
Bitcoin 2 (BTC2): Trade amount: 0.00 BTC, number of trades: 0
Bitcoin Core (BTCC): Trade amount: 0.00 BTC, number of trades: 0
Bitcoin Instant (BTI): Trade amount: 0.00 BTC, number of trades: 0
Blur (BLUR): Trade amount: 0.00 BTC, number of trades: 0
Chaucha (CHA): Trade amount: 0.00 BTC, number of trades: 0
Credits (CRDS): Trade amount: 0.00 BTC, number of trades: 0
Croat (CROAT): Trade amount: 0.00 BTC, number of trades: 0
CryptoTari (TARI): Trade amount: 0.00 BTC, number of trades: 0
Cryptonodes (CNMC): Trade amount: 0.00 BTC, number of trades: 0
DACash (DAC): Trade amount: 0.0013 BTC, number of trades: 1
DRIP (DRIP): Trade amount: 0.00 BTC, number of trades: 0
Dragonglass (DRGL): Trade amount: 0.00 BTC, number of trades: 0
EtherStone (ETHS): Trade amount: 0.00 BTC, number of trades: 0
FuturoCoin (FTO): Trade amount: 0.00 BTC, number of trades: 0
Graft (GRFT): Trade amount: 0.00 BTC, number of trades: 0
GreenBlockCoin (GBK): Trade amount: 0.00 BTC, number of trades: 0
Kekcoin (KEK): Trade amount: 0.00 BTC, number of trades: 0
LikeCoin (LIKE): Trade amount: 0.00 BTC, number of trades: 0
Lobstex (LOBS): Trade amount: 0.00 BTC, number of trades: 0
Loki (LOKI): Trade amount: 0.00 BTC, number of trades: 0
MaxCoin (MAX): Trade amount: 0.00 BTC, number of trades: 0
MegaCoin (MEC): Trade amount: 0.00 BTC, number of trades: 0
MicroCoin (MCC): Trade amount: 0.00 BTC, number of trades: 0
MobitGlobal (MBGL): Trade amount: 0.00 BTC, number of trades: 0
Motion (XMN): Trade amount: 0.00 BTC, number of trades: 0
Myriadcoin (XMY): Trade amount: 0.00 BTC, number of trades: 0
Nano (NANO): Trade amount: 0.00 BTC, number of trades: 0
Neos (NEOS): Trade amount: 0.00 BTC, number of trades: 0
NewPowerCoin (NPW): Trade amount: 0.00 BTC, number of trades: 0
Nimiq (NIM): Trade amount: 0.00 BTC, number of trades: 0
PRiVCY (PRIV): Trade amount: 0.00 BTC, number of trades: 0
PZDC (PZDC): Trade amount: 0.00 BTC, number of trades: 0
Pix (PIX): Trade amount: 0.00 BTC, number of trades: 0
PixelPropertyToken (PXL): Trade amount: 0.00 BTC, number of trades: 0
QMCoin (QMCoin): Trade amount: 0.00 BTC, number of trades: 0
Quantum Resistant Ledger (QRL): Trade amount: 0.00 BTC, number of trades: 0
Radium (RADS): Trade amount: 0.00 BTC, number of trades: 0
Ryo (RYO): Trade amount: 0.00 BTC, number of trades: 0
SUB1X (SUB1X): Trade amount: 0.00 BTC, number of trades: 0
Starwels (MAI): Trade amount: 0.00 BTC, number of trades: 0
Triton (TRIT): Trade amount: 0.00 BTC, number of trades: 0
TurtleCoin (TRTL): Trade amount: 0.00 BTC, number of trades: 0
Wavi (WAVI): Trade amount: 0.00 BTC, number of trades: 0
Zero (ZER): Trade amount: 0.00 BTC, number of trades: 0


Sufficiently traded assets (17):
Bitcoin Cash (BCH): Trade amount: 6.927 BTC, number of trades: 26
Bitcoin Clashic (BCHC): Trade amount: 0.01 BTC, number of trades: 1
Dash (DASH): Trade amount: 0.4684 BTC, number of trades: 5
Decred (DCR): Trade amount: 0.26 BTC, number of trades: 3
Dogecoin (DOGE): Trade amount: 0.001 BTC, number of trades: 1
Ether (ETH): Trade amount: 7.187 BTC, number of trades: 18
Ether Classic (ETC): Trade amount: 0.01 BTC, number of trades: 1
Gridcoin (GRC): Trade amount: 0.0717 BTC, number of trades: 4
Litecoin (LTC): Trade amount: 1.9526 BTC, number of trades: 15
Monero (XMR): Trade amount: 1214.442 BTC, number of trades: 1514
Namecoin (NMC): Trade amount: 0.21 BTC, number of trades: 4
PIVX (PIVX): Trade amount: 0.10 BTC, number of trades: 1
Siafund (SF): Trade amount: 3.15 BTC, number of trades: 4
Spectrecoin (XSPEC): Trade amount: 0.742 BTC, number of trades: 8
Unobtanium (UNO): Trade amount: 0.049 BTC, number of trades: 3
Zcash (ZEC): Trade amount: 1.224 BTC, number of trades: 3
ZenCash (ZEN): Trade amount: 0.889 BTC, number of trades: 9

**Comment by ManfredKarrer** [comment]
I will merge it as it is now. Still wondering why there are some files left with deprecated annotation. And we should also remove the 3 remaining assets, but that can be done before release with an updated check.

**Comment by panterozo** [comment]
Hey guys! We were waiting the release with our coin (CHA) to start using Bisq. The merge was [this](https://github.com/bisq-network/bisq/pull/1745), but we wont see our CHA in the list with AltCoins from the BisQ software downloaded from the [download page](https://bisq.network/downloads/). Please, could you help us with this issue? That's why we havn't made any trade. 
I'm looking forward. 
Regards

**Comment by FernandoBatalha** [comment]
@cbeams @ManfredKarrer 

Would it be possible to list the Nano(NANO) again? When it was listed, much of the community did not know about Bisq.

Official project URL: https://nano.org
Official block explorer URL: https://www.nanode.co
Volume: https://coinmarketcap.com/currencies/nano/#markets

**Pull request merged**
