### PR TITLE
List [Polis] (POLIS)

### LINKED ISSUE #3779: List Polis
One of our exchanges is closing, and we want our community to trade on a true DEX.

### 1. Asset name
https://polispay.org
https://coinmarketcap.com/currencies/polis/
Polis

### 2. Ticker
POLIS

### 3. Block explorer URL
https://blockbook.polispay.org

### 4. Additional technical requirements (yes/no)
I'll create a PR with the technical requirements.

### 5. Initial coin offering (yes/no)
No

### PR DESCRIPTION
**Pull request by eabz**
Fixes #3779

Polis addition:
Website: https://polispay.org
BlockExplorer: https://blockbook.polispay.org

If there are additional requirements, please tell me.

### CODE REVIEW

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK

Your pull request doesn't fulfill our requirements:
- Build doesn't run with errors in Travis
- https://docs.bisq.network/exchange/howto/list-asset.html#step-5-create-a-well-formed-git-commit

**Comment by eabz** [comment]
@ripcurlx Sorry, I fixed the address.

**Comment by eabz** [comment]
Hello, any update with this?
The issue was fixed

**Comment by ripcurlx** [comment]
JFYI: Asset listing is on hold right now because of bisq-network/proposals#153

**Comment by eabz** [comment]
@ripcurlx Is coin addition still on hold?

**Comment by ripcurlx** [comment]
> @ripcurlx Is coin addition still on hold?

Atm unfortunately yes.

**Pull request closed without merging**
