### PR TITLE
Exploratory cleanup, Hi.

### PR DESCRIPTION
**Pull request by gubatron**
Hi, here's a branch with a bunch of cleanup/refactor commits I did as I was looking around what you've been building.

I'm a seasoned java/p2p developer with a huge interest on Bitcoin.

Here's my way of saying hi, feel free to cherry pick what you like.

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Hi, thanks a lot for the PR! Glad to see a FrostWire dev here!

**Comment by gubatron** [comment]
wow,, that was fast, thank you!

**Comment by ManfredKarrer** [comment]
Was easy to merge with your clear commit comments. All thanks back to you ;-). 
If you want to have a chat some day on our IRC (@freenode #bitsquare) or any other channel, just ping me... 

I would appreciate to get feedback regarding my custom P2P network (Tor hidden services + flooding network for data storage). I have an google doc describing the concept here: 
https://docs.google.com/document/d/1kdZf1ZaPuj8MmtueBhv0f8ztvnfd8hDJwNO1_TWH4MM
It is a bit outdated -  the code is the only real doc :-)
So if you have time to have a look that would be great!

**Comment by gubatron** [comment]
Thanks for sharing this, it's always interesting to read new approaches.

As soon as I have time I'll take a slow read at it, I'm curious to see how you deal with Symmetric NATs, and how it all plays with Tor (and if there's any mention in there of I2P which would've been my choice, specially for a Java implementation)

I also saw commit summaries with respect to a DHT implementation, I'll take a look at the extent of what you use it for, and I'll try to make a pitch for you to use ours. FrostWire connects to what I believe is the most successful and battle proven DHT network in the world, we made native java wrappers to libtorrent and a layer of higher abstraction that makes it Java programmer friendly to use.

We believe this DHT is great as a distributed store of small objects, which are usually represent pointers to objects on other networks. In our case, we use the DHT for announcing peers:ports around .torrent infohashes, this way we can create swarms without the need for centralized trackers, but you could pretty much index anything you want there.

The library also is the most efficient and fully featured Open Source library in the world, if you're having issues with the transport of decentralized stores of information, perhaps you should stop worrying about solving those problems, use a library that's more than proven, secure, fast and stable and focus on the core of your product: a decentralized exchange of tokens.

I think we all gain and move faster if we reuse stable components.

I'll get back to you as I get a breather, super hectic these days.

**Comment by gubatron** [comment]
https://github.com/frostwire/frostwire-jlibtorrent

**Comment by gubatron** [comment]
should be super easy to include as a dependency in your maven project, we publish binaries for it at [Sonatype/Maven](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.frostwire%22) for lots of CPU architectures for Linux, Windows, Mac and Android (arm 32/64)

**Comment by gubatron** [comment]
and last one, I promise... :) 

I'd try to stay away from Java serialization, I saw you had some other attempts there, not sure if you gave  protobuf a try, nobody I know has ever had issues. It's better if you keep the format language agnostic and allow for other people to join the bitsquare network.

**Comment by gubatron** [comment]
nvm last comment, perhaps this is something I could help with.
screen shot 2016-01-15 at 3 10 04 pm

**Comment by ManfredKarrer** [comment]
Hi @gubatron,
thanks a lot for all you input!

Re Symmetric NAT:
I have not tested it yet with sym nat, but I use Tor with Socks5Proxy and I assume Tor is in par with Bittorrent to get over all kind of NAT or firewall issues.
In fact the main reason why I moved from TomP2P (http://tomp2p.net) to a Tor based solution was because of those consistant NAT problems with TomP2P. 
I wrote here a hi-level summary regarding that topic: https://bitsquare.io/blog/new-p2p-network/

Re I2P:
I am not sure how mature and stable I2Ps hidden services are. I would love to support both, but that will be too much effort and is too complicate for that project. I got to the Tor solution as a friend who used that as well recommended it to me - so it was simply easier to start with. 
It uses a Tor binary and jTorCtl (https://github.com/JesusMcCloud/jtorctl) for communicating to the binary. jTorProxy (https://github.com/ManfredKarrer/jtorproxy) is another library for the proxy stuff and for the hidden services. So from the app the network part is kind of transparent (sockets), for dev-testing I use also a simple localhost tcp socket (non-Tor).
Those libs are stable so far but could need quite a bit of love :-). I also have added those libs directly in my project instead of using them as dependencies because I had stupid build problems and was too lazy/busy to fix those (its on my long todo list). 

Re DHT implementation:
I am not using a DHT anymore, that was the old TomP2P version. Now I use a flooding network similar like what is used in Bitcoin. I use a custom storage system which supports ownership protection (signature based). More details how that works is in the paper (or code).

Re Bittorrent:
I was considering Bittorrent a few times. But earlier TomP2P seemed to be the best solution for my use cases and now I use Tor and Tor does not support UPnP. 
I need both a messaging system and a storage system, so Bittorrent would have only solved one part. One unsolved problem I had with the previous DHT (Kademlia style) solution was sybil attacks (if node ID creation is free and decentralized, attackers can take over storage partitions). With Tor hidden services I have a kind of Proof of Work as it takes 30-40 sec to publish a HS, so some sort of sybil protection. But of course that might be not enough. But I hope I get some time until this becomes a real problem and there are several ideas/possibilities to be further investigated (see in the google doc)

Re Java serialization:
I discussed that already with a few java devs. Nobody likes Java serialization but no one could tell me a clear reason why it is so bad. At least versioning (which is an important requirement) works not that bad (you can add fields without breaking old versions). My main reason was that I don't need any parsing/scheme definition, so it was super easy for development when things changed often.
But that it is not language agnostic is an issue I am aware of. For that reason I am considering to move to another format, but as I am the only dev at the moment I need to focus on other priorities.

As background info:
I am working now to release a beta version (next days) and need to get the project out to the public soon (will start testing with friends and then with smaller groups). 
I am very aware that there are a lot of open stuff left for improvements or missing features - one of the most important is the decentralized arbitration system, which will take another few months of work.
But I need to get the project out soon in a form which is safe and stable enough to run it with real bitcoin to start earning some money (trading fees) with it as my savings are getting exhausted :-(.
But of course I need to take care to not have fundamental flaws which will be too hard to change later. 
The Java serialization might be one of those parts which should be changed soon, so if you feel to work on that, that would be great! 
Though I am not sure if I will be able to merge that easily as it affects quite a huge part (network object and local storage objects). The crappy local storage solution I am using would probably be needed to be changed as well then. 
It will be difficult from testing perspective when I have tested with the current version and then remove the Java serialization to another solution as I need to repeat a lot of testing again (with many users, network environments...). Building P2P apps is really a challenge in many aspects...

I am not very biased between JSON and ProtoBuffer but as performance is not an issue (Tor is the bottleneck) and data size neither (data objects are small) I would prefer JSON as it is readable (for the non-encrypted data at least) and more widley used.

I would love to work more in all those improvements but with the above mentioned plans to release soon I need to stay focused on the current version without changing too much and use my time for testing and promoting it.

**Comment by gubatron** [comment]
re: JSON/Protobuf

You'll want to save every bit possible, specially if you already have that
bottleneck you mention, why ad more overhead on the wire knowingly, much
more so if you're using a flooding protocol, it counts for every node.

libtorrent developers have learned the hard way to move away to save bytes
spent by TCP (with UDP) even at the IP level, as your network grows if you
can serialize an object with protobuf using 50% of the data it goes a long
way, you can always create decoding utilities if you need easier debugging.

If your vision is grand, the pie in the sky would be a decentralized forex
and you'll want it to be scalable enough to handle thousands or tens of
thousands of orders per second (think gigabit internet a few years from now
and breakthroughs in processing, storage, memory, etc.), how beautiful
would that be. JSON? I don't think so. You already made the right choice of
platform with Java, I'm glad this is not another slow python project. :)

I truly hope I can make the time to help, I'm already on 3 projects and
managing several online publications, wife and kids :p

I think you're building something very valuable here, I suppose that "a
decentralized bitcoin exchange" is only the beginning, as you've already
added support for what people thought wasn't possible, fiat, so adding
other cryptocurrencies should be doable, this would be a shapeshift killer,
it'd be amazing adding support for the rest of the most promising
cryptocurrencies out there, specially if Bitcoin remains vulnerable with
scalability, consensus deadlock and possible banking blockchains trying to
undermine it.

http://twitter.com/gubatron

**Comment by ManfredKarrer** [comment]
Re JSON/Protobuf:
As said I am not very biased and you have for sure more experience here.

Re vision:
There are some further reaching ideas, but I tried to keep myself on the ground and not think too far. 
- When Fiat accounts get integrated (OKPay offers APIs for that) you get possibility for a fully automated trade. Then many other financial operations become possible (stop loss, take profit, CFD,...). 
- With atomic crosschain exchange you can trade all cryptos trustlessly (no arbitrater needed)
- Decouple the arbitration system and make it more general purpose as a decentralized dispute resolution platform
- Extract P2P network as library and make it general purpose (if it turns out it works good enough)
- Extract the chat/mail system used for disputes as general purpose communication tool (like RicoChet) 
- Expand to a Market place like OpenBazaar

But to be honest, as soon I get enough funds out I want to fade out of Bitsquare to use my time on other stuff. I am more interested in stuff like Basic Income, Liquid/Delegated democracy platforms, finding ways how to fund common goods...

Re other cryptocurrencies:
I support altcoins already. At the moment just a selected list but basically all are possible which can be verified on a blockchain (CryptoNote coins unfortunately not - the arbitrator has no chance to solve a dispute as the tx is not linked to the addresses).

Btw: 
I have some concrete solution for a DAO for Bitsquare. Its pretty simple actually but I would need to write it down properly to share the details. 
With that DAO all partizipants will become trading fee receivers depending on the value of their contribution (like stake/shares). I could implement it probably in 1 or 2 weeks but as I am the only dev there was no real need so far for it....
Of course also as soon I am earning money I will look out for devs (paid job)... more work force is really needed....

**Comment by gubatron** [comment]
@aldenml I think you're going to like this project, Trading + P2P, the two things we can't stop talking about. Read the conversation above, I think you will find it somewhat of interest.

**Comment by gubatron** [comment]
@aldenml  and it's in java, none of that toy scripting language crap.

**Comment by ManfredKarrer** [comment]
@gubatron 
Thanks for promoting :-)

**Comment by ManfredKarrer** [comment]
@gubatron, @aldenml, @AdamISZ, @codeboost:
I forked the Bitsquare P2P network module out to an independent project.
https://github.com/BrightNetDAO/BrightNet

There are some people interested in a Tor based P2P network library, so that is open to anyone who wants to contribute to make the current Bitsquare version a general purpose P2P network. 
I just try to give an ignition for other people to work on that. I am too busy with Bitsquare to be able to contribute here much.
It is also open for a complete re-write or change of concept. 
If it turns out that it becomes a mature library I will use that in Bitsquare later as well. 

If you are interested, I can give you member/ownership access to the BrightNetDAO org.

**Pull request merged**
