### PR TITLE
Fix NPE when duplicate offer with deleted account

### LINKED ISSUE #6232: NPE when duplicating offer if the account does not exist.
### Description

Go to Portfolio -> History.  Click on the icon to duplicate one of your previous offers.  If the account of that offer is not available, a NPE error box will be displayed.

#### Version

1.9.1, probably earlier versions too.

### Expected behaviour

- If possible, clear the account selection which would make the user choose an account to enter the offer.

### Screenshots

image

    May-31 11:25:48.280 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.NullPointerException 
    May-31 11:25:48.293 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
    java.lang.NullPointerException
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferDataModel.isUsingHalCashAccount(MutableOfferDataModel.java:804)
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.setAmountToModel(MutableOfferViewModel.java:1176)
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.onFocusOutAmountTextField(MutableOfferViewModel.java:724)
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.triggerFocusOutOnAmountFields(MutableOfferViewModel.java:861)
	    at bisq.desktop.main.portfolio.duplicateoffer.DuplicateOfferViewModel.activate(DuplicateOfferViewModel.java:89)
	    at bisq.desktop.common.model.ActivatableWithDataModel._activate(ActivatableWithDataModel.java:29)
	    at bisq.desktop.common.view.ActivatableViewAndModel.lambda$prepareInitialize$0(ActivatableViewAndModel.java:37)

### PR DESCRIPTION
**Pull request by ghost**
Fixes #6232

Description:
When account doesn't exists anymore standard logic from [`initWithData`](https://github.com/bisq-network/bisq/blob/7ad2dd0ba6789bb7e4a7bf56a22b9b4f9a33d850/desktop/src/main/java/bisq/desktop/main/offer/bisq_v1/MutableOfferDataModel.java#L238-L261) is used

### CODE REVIEW

**Comment by ghost** [comment]
The fix is an improvement, however an NPE still happens if no account is available.

    Jun-01 08:33:21.197 [JavaFX Application Thread] WARN  b.d.m.p.d.DuplicateOfferDataModel: PaymentAccount not available. Should never get called as in offer view you should not be able to open a create offer view 
    Jun-01 08:33:21.209 [JavaFX Application Thread] WARN  b.c.p.price.PriceFeedService: We don't have a currency yet set. That should never happen 
    Jun-01 08:33:21.210 [JavaFX Application Thread] WARN  b.c.p.price.PriceFeedService: We don't have a currency yet set. That should never happen 
    Jun-01 08:33:21.217 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
    Jun-01 08:33:21.217 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= null 
    Jun-01 08:33:21.217 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.NullPointerException 
    Jun-01 08:33:21.218 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
    java.lang.NullPointerException
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.maybeShowMakeOfferToUnsignedAccountWarning(MutableOfferViewModel.java:1255)
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.onFocusOutMinAmountTextField(MutableOfferViewModel.java:790)
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.triggerFocusOutOnAmountFields(MutableOfferViewModel.java:862)
	    at bisq.desktop.main.portfolio.duplicateoffer.DuplicateOfferViewModel.activate(DuplicateOfferViewModel.java:89)
	    at bisq.desktop.common.model.ActivatableWithDataModel._activate(ActivatableWithDataModel.java:29)
	    at bisq.desktop.common.view.ActivatableViewAndModel.lambda$prepareInitialize$0(ActivatableViewAndModel.java:37)
	    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	    at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	    at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	    at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1060)
	    at javafx.scene.Node.invalidatedScenes(Node.java:1131)
	    at javafx.scene.Node.setScenes(Node.java:1169)
	    at javafx.scene.Parent$2.onChanged(Parent.java:372)

**Comment by ghost** [comment]
> The fix is an improvement, however an NPE still happens if no account is available.

@jmacxx I [fixed it](https://github.com/bisq-network/bisq/pull/6233/commits/5df700824f431e4b3b249dded6df18996001d014) by hiding "duplicate offer" button when no account exists

**Comment by ghost** [comment]
Still getting an NPE, I think there is a "hidden" account for BSQ swaps causing trouble.  Perhaps if that was excluded from the count everything would work as planned.

---

No altcoin accounts:

image

Portfolio history with the duplicate icon:

image

Count of non-fiat accounts is in fact 1.

    INFO  bisq.core.user.User: hasAnyNonFiatPaymentAccount count=1 



Log:

    Jun-01 21:25:58.731 [JavaFX Application Thread] WARN  b.d.m.p.d.DuplicateOfferDataModel: PaymentAccount not available. Should never get called as in offer view you should not be able to open a create offer view 
    Jun-01 21:25:58.790 [JavaFX Application Thread] WARN  b.c.p.price.PriceFeedService: We don't have a currency yet set. That should never happen 
    Jun-01 21:25:58.794 [JavaFX Application Thread] WARN  b.c.p.price.PriceFeedService: We don't have a currency yet set. That should never happen 
    Jun-01 21:25:58.840 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
    Jun-01 21:25:58.841 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= null 
    Jun-01 21:25:58.841 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.NullPointerException 
    Jun-01 21:25:58.843 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
    java.lang.NullPointerException
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.maybeShowMakeOfferToUnsignedAccountWarning(MutableOfferViewModel.java:1255)
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.onFocusOutMinAmountTextField(MutableOfferViewModel.java:790)
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.triggerFocusOutOnAmountFields(MutableOfferViewModel.java:862)
	    at bisq.desktop.main.portfolio.duplicateoffer.DuplicateOfferViewModel.activate(DuplicateOfferViewModel.java:89)
	    at bisq.desktop.common.model.ActivatableWithDataModel._activate(ActivatableWithDataModel.java:29)

**Comment by ghost** [comment]
I created [more advanced logic](https://github.com/bisq-network/bisq/blob/3c670084f0aabb45f0c27e49508df7d301c6cf2e/desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesView.java#L765-L780) for handling those edge case scenarios. Excluding BSQ Swap account wasn't enough, because it disallowed duplication of BSQ Swap offer when no altcoin account existed

**Review by ghost — APPROVED** [review]
ACK :sweat_smile:

**Review by ripcurlx — APPROVED** [review]
utACK - based on https://github.com/bisq-network/bisq/pull/6233#pullrequestreview-993468827

**Pull request merged**
