### PR TITLE
Improve text and icon colors for disabled offers

### PR DESCRIPTION
**Pull request by ripcurlx**
Before
Bildschirmfoto 2022-02-01 um 11 48 42
Bildschirmfoto 2022-02-01 um 11 48 35
After
Bildschirmfoto 2022-02-01 um 11 47 46
Bildschirmfoto 2022-02-01 um 11 47 39

### CODE REVIEW

**Comment by ripcurlx** [comment]
@jmacxx Could you please ACK those changes? Thanks!

**Review by ghost — APPROVED** [review]
ACK

**Review by ghost — APPROVED** [review]
utACK

**Review by bisq-github-admin-3 — APPROVED** [review]
ACK based on https://github.com/bisq-network/bisq/pull/6017

**Pull request merged**
