### PR TITLE
List [Bolivarcoin] (BOLI)

### PR DESCRIPTION
**Pull request by jestevez**
- Official project URL: https://github.com/BOLI-Project/BolivarCoin
- Official block explorer URL: https://chainz.cryptoid.info/boli/

### CODE REVIEW

**Comment by Giszmo** [comment]
The [git repo](https://github.com/BOLI-Project/BolivarCoin) claims the coin was started in 2015 yet there is only commits from 2019 (June to October). 22 by 2 authors. The first commit is titled "first BolivarCoin commit", so I suppose there is not some other repo that runs the coin since the claimed 2015. On the other hand, [CMC](https://coinmarketcap.com/currencies/bolivarcoin/) has price quotes as far back as 2015.

So there is [another repository](https://github.com/bolivarcoin/bolivarcoin) from 2015 with a total of 3 commits.

They also have an [Android wallet](https://play.google.com/store/apps/details?id=com.boli.wallet) with a very cringy "promotional" video.

**Comment by jestevez** [comment]
Thanks for the observation,

I contacted the developers and asked them to unify the github repositories and remove or improve the video from the Android wallet.

**Comment by BolivarcoinXT** [comment]
for more information about Bolivarcoin visit page bolis.info

**Comment by BolivarcoinXT** [comment]
> The [git repo](https://github.com/BOLI-Project/BolivarCoin) claims the coin was started in 2015 yet there is only commits from 2019 (June to October). 22 by 2 authors. The first commit is titled "first BolivarCoin commit", so I suppose there is not some other repo that runs the coin since the claimed 2015. On the other hand, [CMC](https://coinmarketcap.com/currencies/bolivarcoin/) has price quotes as far back as 2015.
> 
> So there is [another repository](https://github.com/bolivarcoin/bolivarcoin) from 2015 with a total of 3 commits.
> 
> They also have an [Android wallet](https://play.google.com/store/apps/details?id=com.boli.wallet) with a very cringy "promotional" video.

check block #1 on blockchain explorer if you need to verify that Bolivarcoin is been active since 2015

**Comment by BolivarcoinXT** [comment]
Let us know how can we help... send message here or visit our community groups, links on our page bolis.info

**Comment by jestevez** [comment]
The main repository has been aligned and the old repositories have been archived.

The Android video I requested to be deleted, I am waiting for an answer.

**Comment by BolivarcoinXT** [comment]
Video has been remove, wait 4 hours for play store to update 
 

Sent: Wednesday, December 11, 2019 at 6:40 AM

**Comment by jestevez** [comment]
Hi, we need to complete this pull request


> The [git repo](https://github.com/BOLI-Project/BolivarCoin) claims the coin was started in 2015 yet there is only commits from 2019 (June to October). 22 by 2 authors. The first commit is titled "first BolivarCoin commit", so I suppose there is not some other repo that runs the coin since the claimed 2015. On the other hand, [CMC](https://coinmarketcap.com/currencies/bolivarcoin/) has price quotes as far back as 2015.
> 
> So there is [another repository](https://github.com/bolivarcoin/bolivarcoin) from 2015 with a total of 3 commits.
> 
> They also have an [Android wallet](https://play.google.com/store/apps/details?id=com.boli.wallet) with a very cringy "promotional" video.

**Comment by ripcurlx** [comment]
JFYI: Asset listing is on hold right now because of bisq-network/proposals#153

**Pull request closed without merging**
