### PR TITLE
Replace "P2P network" with "Bisq network" in GUI

### PR DESCRIPTION
**Pull request by battleofwizards**
Rationale: it is not obvious whether "P2P network" in GUI refers to Bitcoin network, Tor network, traded altcoin network, or Bisq.

Screenshot from 2019-08-15 23-31-32

Screenshot from 2019-08-15 23-32-46

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Changes for the translation string need to be done in Transifex otherwise it would be overwritten by next update.

**Comment by battleofwizards** [comment]
Thanks @ManfredKarrer! I should have read the docs first.

I requested joining the bisq projects on Transifex.

**Comment by ManfredKarrer** [comment]
@battleofwizards If you add new entries it is ok to do it in the code as well as far I know (not the area I followed much). @y3v63n is the transifex admin and will know it...

**Comment by y3v63n** [comment]
@battleofwizards if you want to change English text, you need to make a PR. We can't do it in Transifex since it pulls the source from Github.

**Comment by battleofwizards** [comment]
Thanks @y3v63n!

I removed non-English changes from this PR. I hope it's fine to merge now.

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Pull request merged**
