### PR TITLE
Add onion address for @robkaandorp's btcnode

### PR DESCRIPTION
**Pull request by robkaandorp**
Network proposal https://github.com/bisq-network/proposals/issues/189

### CODE REVIEW

**Review by wiz — DISMISSED** [review]
ACK
```
% ./bitcoin-service-check.py 2pj2o2mrawj7yotg.onion 8333
OK - 623592 /Satoshi:0.19.1/ 2439.5ms|time=2439.5
```

**Comment by ripcurlx** [comment]
@robkaandorp Please sign your commit and I'm happy to merge your PR.

@wiz As we haven't defined it yet: Is a fixed IP and a DNS entry a requirement for BTC Core node operators?

**Comment by wiz** [comment]
This is totally fine, and currently @emzy is running a Tor-only Bitcoin node, since he doesn't have a static IP address for that node. My understanding of the Bisq code is that you can optionally omit either the Tor onion or the clearnet IP/hostname and it handles this fine.

As we scale Bisq larger and require more Bitcoin nodes, and as moore's law progresses, I can see a future where all Bisq contributors simply run a Raspberry Pi node at their house with a Tor onion only, so we don't need to pay monthly hosting costs for Bitcoin nodes. We can allocate some of the ops budget to one-time $100 purchases of raspberry pi setups for contributors, instead of spending $50 **per month** for hosting somewhere.

**Comment by ripcurlx** [comment]
Thanks @wiz for your comment. So please @robkaandorp just sign your commit as mentioned by the boring-cyborg and I'll merge this PR.



> Also make sure your commits are signed, and that you applied [Bisq's code style](https://github.com/bisq-network/style/issues) and [formatting](.editorconfig).

**Pull request closed without merging**
