### PR TITLE
Add yang

### PR DESCRIPTION
**Pull request by Yangtoshi**
Official project URL: https://www.yangbucks.com/ & https://github.com/orgs/yang-bucks

Valid contract address: https://etherscan.io/address/0x78fe9e298840a74cefd242bad511ca343c5b4d7b

On-chain transaction: https://etherscan.io/tx/0xe178dd514350dc847a54589d56431167bf073645832ef978e93230d66815b115

On-chain transaction #2:
https://etherscan.io/tx/0xa81c75a36d68a6c965258674b237a9edc371715a1ec02d179d19fdbec090e251

### CODE REVIEW

**Comment by Yangtoshi** [comment]
#3020

**Comment by blabno** [comment]
Do not try creating PRs by editing files online! One more attempt and you will be banned.

**Comment by Yangtoshi** [comment]
> Do not try creating PRs by editing files online! One more attempt and you will be banned.

apologies, i'm not the dev and didn't realize i did something wrong.

i'll have a dev handle this from here on out so i dont make any more mistakes.

**Comment by ripcurlx** [comment]
Closing because of inactivity since 20th of August. Feel free to reopen if comments from reviewer are taken into consideration.

**Comment by Yangtoshi** [comment]
i have deleted my mistake as per the comments from the reviewer and would like to reopen this request.

**Pull request closed without merging**
