### PR TITLE
List Horizen (ZEN)

### PR DESCRIPTION
**Pull request by tarrenj**
- Official project URL: https://horizen.global/
- Official block explorer URL: https://explorer.horizen.global/

Resubmitting https://github.com/bisq-network/bisq-assets/pull/114#event-1830750347 from the old bisq-assets` repo, which had positive comments from @cbeams and @manfredKarrer, but did not have a comment containing "ACK".

Tested with `./gradlew :assets:build`

### CODE REVIEW

**Comment by tarrenj** [comment]
Resubmitting https://github.com/bisq-network/bisq-assets/pull/114

**Review by blabno — CHANGES_REQUESTED** [review]
NACK. No PRs from master.

**Review by blabno — CHANGES_REQUESTED** [review]
NACK. No PRs from master.

**Comment by tarrenj** [comment]
ACK, will update now.

**Comment by tarrenj** [comment]
@blabno Resolved.

**Comment by blabno** [comment]
@tarrenj please create separate branch (name different then `master`) and create PR from there

**Comment by tarrenj** [comment]
ACK, should be back in front of a computer later today and will be able to knock this out.

**Comment by tarrenj** [comment]
> @tarrenj please create separate branch (name different then `master`) and create PR from there

Done: https://github.com/bisq-network/bisq/pull/1784

**Pull request closed without merging**
