### PR TITLE
Limit first Bisq trade to 0.25 BTC

### PR DESCRIPTION
**Pull request by ghost**
Implements [proposal 391](https://github.com/bisq-network/proposals/issues/391)

> I think a 0.25 BTC limit would be justified for a first time user who has not completed a trade yet.

More restrictive limits will still apply based on payment method.

It is intended to avoid that a new users who do not fully understand the process of a Bisq trade to cause an arbitration case with high amounts and therefore higher risks and costs for the DAO.

---

### Screenshots

post_trade_limit_take_offer

image

post_max_amount_warning
post_max_trade_limit

### CODE REVIEW

**Review by HenrikJannsen — APPROVED** [review]
utACK

**Comment by ripcurlx** [comment]
@pazza83 What's your take on this?

**Comment by ripcurlx** [comment]
> @pazza83 What's your take on this?

Sorry - missed your 👍 in the proposal - will start reviewing it now

**Comment by pazza83** [comment]
Hi @ripcurlx 

Looks good but I have made a follow up proposal to this. To try and expand it a little to be more than just one trade needed.
 
https://github.com/bisq-network/proposals/issues/396

**Comment by ghost** [comment]
Closing this PR as the scope is changing e.g. https://github.com/bisq-network/proposals/issues/396

**Pull request closed without merging**
