### PR TITLE
Replace NonMMappedSPVBlockStore by ClearableSPVBlockStore

### LINKED ISSUE #2402: Can not restore from seed on windows
Restoring from seed on windows does not work because bitcoinj access the blockchain file using a memory mapped file. There are issues on windows relinquishing control of memory mapped files.
See
- https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4715154
- http://www.mapdb.org/blog/mmap_files_alloc_and_jvm_crash/
- https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4724038
- https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6359560

There is a workardound to avoid this bug on bitcoinj, but that depends on some jdk8 specific stuff. Since bisq is run with jdk10, the workardound does not work.

### PR DESCRIPTION
**Pull request by oscarguindzberg**
NonMMappedSPVBlockStore approach is risky because stop using mmapped files means i/o performance loss.

ClearableSPVBlockStore fixes https://github.com/bisq-network/bisq/issues/2402 by:
- avoiding deleting the blockchain file but clearing its content instead.
- overriding close() to avoid invoking WindowsMMapHack.

### CODE REVIEW

**Comment by oscarguindzberg** [comment]
I tested the PR on windows and it works.

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Comment by ManfredKarrer** [comment]
I will merge but I am aware it requieres more testing. @ripcurlx @devinbileck Could you please test restore from seed words?

**Comment by devinbileck** [comment]
Restore from seed worked for me on mainnet using Windows 10.

**Pull request merged**
