### PR TITLE
List Krypton (ZOD)

### PR DESCRIPTION
**Pull request by kryptonchain**
- Official project URL: https://kryptonchain.org/
- Official block explorer URL: https://explorer.kryptonchain.org/

### CODE REVIEW

**Comment by kryptonchain** [comment]
Anything else we could provide to get this merged?
I saw a recent pull request from Monero for integrated address support, I was thinking to add that as well, but I could create a new pull request for that 🙂 (considering the time it takes to merge them)

**Comment by blabno** [comment]
This is privacy coin. Please describe how arbitration can be done. You should follow other privacy coin PRs like Monero, i.e. users should be warned that only transparent addresses can be used.

**Comment by kryptonchain** [comment]
Hi @blabno we only have one type of address 98 char address, but the receiver or sender addresses are not public.
Same as Turtlecoin (which I used as a base for my PR)
Arbitatration is done by checking for inputs and outputs for every transaction.

To check if the output belongs to the address you can use this tool:
https://explorer.kryptonchain.org/#check_txn

you will need a valid TX ID, your address private view key (created when you generate the address)
and the public address.

Imgur Image

Thank you

**Comment by kryptonchain** [comment]
Any update on this @blabno? Thank you

**Review by blabno — APPROVED** [review]
ACK

**Pull request merged**
