### PR TITLE
List Askcoin (ASK)

### PR DESCRIPTION
**Pull request by lichuan**
- Official project URL: http://www.askcoin.me
- Official block explorer URL: http://explorer.askcoin.me

### CODE REVIEW

**Review by blabno — COMMENTED** [review]
Code looks ok, but I was not able to see any transactions in the explorer to verify if arbitration will be possible.
Please provide link to a transaction in your block explorer.

**Comment by lichuan** [comment]
> Code looks ok, but I was not able to see any transactions in the explorer to verify if arbitration will be possible.
> Please provide link to a transaction in your block explorer.

Because askcion's explorer is a SPA (single page application), so there is only one url: explorer.askcoin.me, but you can visit account's detail page by input id in the search input box, for example, if you input 3, the account (account name: askcoin)'s page will come out, at the bottom of the page, there is a list of transactions related to the account.

**Comment by lichuan** [comment]
@blabno You can also refer to bitcointalk ANN url: https://bitcointalk.org/index.php?topic=5104959.0

**Comment by blabno** [comment]
@ripcurlx I am unable to tell if this explorer will allow arbitration. Could you verify it?

**Comment by lichuan** [comment]
@blabno Askcoin's explorer fully support arbitration, because the id of account is the same as the address of account, if you want to know someone's transactions, you just need to enter its id number to query its transactions

**Comment by ripcurlx** [comment]
@blabno Yes, I think it is fine for arbitration as the identifier in Bisq will be the account id and you'll be able to see the transaction referrer of the transaction within the blockexplorer.

**Pull request merged**
