### PR TITLE
Allow trader chat to continue after trade complete

### LINKED ISSUE #5734: Keep trader chat open after trade has finished
The trader chat gets automatically closed at trade completion and traders cannot open it again from closed trades.
I think it would be useful to allow at least the on going chats to continue until the users close it. 
Also to allow opening a trader chat from closed trades might be worth considering. Not 100% sure if its a good idea. Feedback welcome.

### PR DESCRIPTION
**Pull request by ghost**
Trader chat no longer gets automatically closed at trade completion, ~and traders can open it again from closed trades~.

[edit] no chat for `closed` trades, due to feedback received below.

Fixes #5734

### CODE REVIEW

**Comment by ripcurlx** [comment]
@pazza83 @chimp1984 This PR would make it possible to open a chat again also from closed trades. I think it would be sufficient to not auto-close the chat window when it is open after a trade is completed.

**Comment by ghost** [comment]
:+1:  I'm ok with removing the chat feature from closed trades, if that's what people want.

**Comment by chimp1984** [comment]
Great thanks @jmacxx that you implemented that so fast!
I have no strong opinion regarding re-opening.
Maybe the support guys can add their opinions.

**Comment by ghost** [comment]
Discussed with support team, they prefer no chat on closed trades, so I reverted that feature.  You'll still be able to chat until the chat window is closed.

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
