### PR TITLE
Add Arto Coin

### PR DESCRIPTION
**Pull request by artocash**
Ticker symbol (e.g. LTC): RTO
Official token name (e.g. Litecoin): Arto
Official block explorer URL: http://explorer.arto.cash/
Is it an Altcoin (dedicated blockchain) or a token (anything else) (e.g. Altcoin): Altcoin
Official token project URL: https://www.arto.cash/

_Information: Arto is a CryptoNote based coin._

### CODE REVIEW

**Comment by cbeams** [comment]
Sorry, @artocash, you've submitted this PR right on the heels of a repository split we performed yesterday. Our docs aren't up to date on this yet, but please re-submit your PR against https://github.com/bisq-network/bisq-core instead. Thanks.

**Comment by artocash** [comment]
Hello @cbeams, that's fine. But are you sure PR against https://github.com/bisq-network/bisq-core? can't find eg. CurrencyUtil.java on that repo. But I can find it in https://github.com/bisq-network/bisq-common. Thanks.

**Comment by artocash** [comment]
Well that's fine 😃 I already creating the PR. Thanks,

**Comment by cbeams** [comment]
I've reopened this PR for the aspects that do deal with code here in bisq-desktop.

I see that you've submitted bisq-network/bisq-core#1 for the code that lives in bisq-core, thanks.

You'll need to do the same for the bits that now live in bisq-common. Please go ahead with that now.

Obviously this arrangement is not ideal, and we'll work out a way to make it possible with a single PR in the future. In the meantime, thanks for working with us on this.

Also, @artocash, please check the box on all your PRs that reads "Allow maintainers to make additional changes". You should find this on the right menu of the PR toward the bottom. Doing this will cut down on back-and-forth.

**Comment by cbeams** [comment]
Also you'll need to change the base branch of this PR to point to `master`, not `0.6.7` (that branch will soon be deleted anyway. You can change the base branch by clicking the Edit button on the PR. You'll need to rework the contents of your PR branch and force push it.

**Comment by artocash** [comment]
Sorry, decided to delete the branch and reworking from master branch. It easier for me 😄 Thanks.

**Comment by artocash** [comment]
New [PR request](https://github.com/bisq-network/bisq-desktop/pull/1453). Thanks.

**Comment by cbeams** [comment]
UPDATE: Watch https://github.com/bisq-network/bisq-desktop/issues/1456. When it's closed, you'll be able to follow a new, simplified set of instructions to submit a pull request for $ARTO.

**Pull request closed without merging**
