### PR TITLE
Reduce bs formatter interface

### PR DESCRIPTION
**Pull request by bodymindarts**
Part 3 of my ongoing refactoring to remove BSFormatter.

This is the last refactoring that deals with method extraction. Next step will be to extract the CoinFormatter interface to deal with the polymorphism between BsFormatter and BsqFormatter.

Tracking issue: https://github.com/bisq-network/bisq/issues/3240

### CODE REVIEW

**Review by freimair — DISMISSED** [review]
Ack

**Comment by ripcurlx** [comment]
@bodymindarts I think because of the merge of the release branch your PR needs to be updated.

**Comment by bodymindarts** [comment]
Rebased vs master. Thanks for the hint @ripcurlx

**Comment by ripcurlx** [comment]
> Rebased vs master. Thanks for the hint @ripcurlx

@bodymindarts There are still (or again) conflicts with master.

**Review by freimair — DISMISSED** [review]
Ack

**Comment by ripcurlx** [comment]
@bodymindarts Based on our new GitHub configuration all your commits must be signed to be able to merge it. Please update also your old commits. Thanks!

**Comment by bodymindarts** [comment]
@ripcurlx re-uploaded with signed commits

**Review by freimair — APPROVED** [review]
utAck

**Pull request merged**
