### PR TITLE
Reflect new repository structure in issue links

### PR DESCRIPTION
**Pull request by ripcurlx**
Not a critical propblem as a redirect is in place. Reported by issue #1604

### CODE REVIEW

**Comment by cbeams** [comment]
@ManfredKarrer, was merging this as @bisq-github-admin-2 unintentional?

**Comment by ManfredKarrer** [comment]
Yes because I did not had merge rights anymore with my dev account. I merged already the other projects so it would have caused problems to leave desktop with the old version.

**Comment by ManfredKarrer** [comment]
That PR actually was  not required to merge quickly, so that was kind of unintentional.

**Comment by cbeams** [comment]
Manfred's inability to merge was caused by a rogue branch protection permissions problem in this repository's settings. Acting as @bisq-github-admin-1, I've changed that setting back to the default, which is that anyone with write permissions to the repository (i.e. @bisq-network/desktop-maintainers) can merge PRs. All good.

**Pull request merged**
