### PR TITLE
Fix the PriceNode lower bounds for MinFee

### LINKED ISSUE #5486: Minimum Fee behaving weirdly
### Description

I believe that there is something wrong with the fee estimation implemented in  #5235
I cant find what it is, but the final behaviour here is that it gets a value that is not coming from the mempool.space api (is it an average?) and it also has a 10sats/vb hardcoded minimum.
The image below shows that 21sats/vb, but the minimumFee was 1sat/vb (as far as I can tell from the code, it should use 2xminimumFee).
If I try 10sats/vb, it will accept it, but not less.

image

#### Version

1.6.4

### Steps to reproduce

Try to change the minumum fee.

### Expected behaviour

Should accept at least 2 x minimumFee, but stucks to 10 or a number that it takes from an unknown place.

### PR DESCRIPTION
**Pull request by ghost**
PriceNode caps the MinFee and the TxFee both to a minimum of 10.  The MinFee cap should be 2, which corresponds to the smallest allowable custom withdrawal fee.

Fixes #5486

### CODE REVIEW

**Comment by rafaelpac** [comment]
Nice.
But wouldnt it be better to avoid hardcoding the trading fee? What about using the HourFee for trading (and FastestFee for instant payment methods) and 2 x MinimunFee for withdraw?

**Comment by ghost** [comment]
@rafaelpac This is just enforcing established consensus rules, changing them would need approval from the DAO.

**Review by wiz — APPROVED** [review]
ACK - thanks for fixing this bug!

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
