### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Review by ripcurlx — APPROVED** [review]
utACK - comment changes are looking fine :+

**Comment by ripcurlx** [comment]
@rex4539 Please sign your commit, so I'm able to merge your PR. Thanks!

**Comment by rex4539** [comment]
Not sure what you mean. The commit was signed.

Anyway, closing. Too much "administration" going on. Not worth it :)

**Comment by ripcurlx** [comment]
> Not sure what you mean. The commit was signed.
> 
> Anyway, closing. Too much "administration" going on. Not worth it :)

Weird, now it is shown as signed, which wasn't before. If you re-open it i'll merge it.

**Pull request closed without merging**
