### PR TITLE
Changes "Verify result" to "Check signature"

### LINKED ISSUE #5208: Change Verify result button text in Dispute View
### Description

The"Verify result" button in the Dispute View is unclear and problematic. The button is intended for checking the signature of the mediator or arbitrator and the button text should reflect that. "Verify result" implies that pushing the button will confirm the result of the dispute. In my opinion the text for this button should be changed. I suggest "View signature", "Inspect signature" or "Check signature". 

#### Version

v1.5.6

### Steps to reproduce

* Open the Dispute View
* See the "Verify result" button
* Don't push it because it's too scary

### Expected behaviour

* Open the Dispute View
* See the "Check signature" button
* Push it with confidence

#### Additional info

/core/src/main/resources/i18n/displayString.properties
support.sigCheck.button=Verify result

### PR DESCRIPTION
**Pull request by JaredBoone**
Fixes #5208

This PR changes the button text in the DisputeView for support.sigCheck.button from "Verify result" to "Check signature"

### CODE REVIEW

**Review by wallclockbuilder — APPROVED** [review]
UtAck

**Review by ripcurlx — APPROVED** [review]
utACK

**Comment by ripcurlx** [comment]
@JaredBoone Your commit needs to be signed to be able to merge it into master. Thanks!

**Comment by JaredBoone** [comment]
@ripcurlx I had forgotten to add my public key to github. That's done, so I believe it should work now.

**Pull request merged**
