### PR TITLE
API XMR/BTC trading pair support (#6)

### PR DESCRIPTION
**Pull request by ghubstan**
New API features:

- Create XMR payment accts with API.
- Create XMR offers with API.
- Trade XMR using v1 protocol, not swapping.

Testing new API XMR support, docs:

- Created apitest cases for XMR support.
- Created XMR/BTC trade simulation script (regtest only).
- Updated api beta test guide for XMR support.

Based on PR https://github.com/bisq-network/bisq/pull/5876

### CODE REVIEW

**Comment by ripcurlx** [comment]
I just went through the scenarios of creating an XMR account and executed a successful trade. Here are my comments as an API user.

- `createcryptopaymentacct`: ☑️ 
I think we should add this to the documentation as we do it for `createpaymentacct` as well. ATM you need to look at simulation scripts to find out how to create altcoin accounts which might be the main use cases for API usage. Maybe we could even just re-use the `createpaymentacct` method with different parameters to make altcoin accounts a first class citizen.

- `createoffer`: ☑️
Is there a reason why we named the payment account id argument `--payment-account` and not `--payment-account-id`? I think it would be more consistent with the other API methods if we would support the argument with ...-id as well. WDYT? 

- `editoffer` ✅ 

### Trading process

Everything worked as expected I only recognized this time that using the `keepfunds` command is necessary to complete the trade (or isn't it?), but when just checking the `gettrade` command there is no change happening. So this might be confusing for API users. 

```
➜  bisq git:(6-api-xmr-trading) ✗ ./bisq-cli --password=mySecret gettrade --trade-id=yfxmel-4f5caead-1ceb-459e-8111-bc5b2f259e42-180
ID      My Role              Price in BTC for 1 XMR  Amount(XMR)  Tx Fee (BTC)  Maker Fee(BSQ)  Deposit Published  Deposit Confirmed  Buyer Cost(BTC)  XMR Sent  XMR Received  Payout Published  Withdrawn  XMR Buyer Address
yfxmel  XMR seller as maker              0.00395772         5.05    0.00002450            0.03  YES                YES                     0.02000000  YES       YES           YES               NO         46tM15KsogEW5MiVmBn7waPF8u8ZsB6aHjJk7BAv1wvMKfWhQ2h2so5BCJ9cRakfPt5BFo452oy3K8UK6L2u2v7aJ3Nf7P2
➜  bisq git:(6-api-xmr-trading) ✗ ./bisq-cli --password=mySecret --port=9998 keepfunds --trade-id=yfxmel-4f5caead-1ceb-459e-8111-bc5b2f259e42-180
funds from trade yfxmel-4f5caead-1ceb-459e-8111-bc5b2f259e42-180 saved in bisq wallet
➜  bisq git:(6-api-xmr-trading) ✗ ./bisq-cli --password=mySecret gettrade --trade-id=yfxmel-4f5caead-1ceb-459e-8111-bc5b2f259e42-180             
ID      My Role              Price in BTC for 1 XMR  Amount(XMR)  Tx Fee (BTC)  Maker Fee(BSQ)  Deposit Published  Deposit Confirmed  Buyer Cost(BTC)  XMR Sent  XMR Received  Payout Published  Withdrawn  XMR Buyer Address
yfxmel  XMR seller as maker              0.00395772         5.05    0.00002450            0.03  YES                YES                     0.02000000  YES       YES           YES               NO         46tM15KsogEW5MiVmBn7waPF8u8ZsB6aHjJk7BAv1wvMKfWhQ2h2so5BCJ9cRakfPt5BFo452oy3K8UK6L2u2v7aJ3Nf7P2
```

Maybe adding another column with trade state?

**Comment by ghubstan** [comment]
>> Is there a reason why we named the payment account id argument --payment-account and not --payment-account-id? 
>> I think it would be more consistent with the other API methods if we would support the argument with ...-id as well. WDYT?

At the time I thought abbreviating the param name was a good idea, but it was not.  I should make it consistent and change it to `--payment-account-id`.

**Comment by ghubstan** [comment]
>> Everything worked as expected I only recognized this time that using the keepfunds command is necessary to complete the
>> trade (or isn't it?), but when just checking the gettrade command there is no change happening. 
>> So this might be confusing for API users.

This is confusing and seemingly unnecessary to API users, but if it is not done, the completed trade will not be moved from the pending/open trades list (persistence file), to the closed trades list (persistence file).   I am almost certain there is a keep funds button click required as the last step in the UI / protocol.  (The alternative last step in the UI is to move-funds-to-external-wallet.)

The `keepfunds` cmd is consistent with the final step in the UI.  I think this needs some more study from both of us before I change it to say... automatically moving completed trade from open-trades list to closed-trades list in the "next to last" step of the protocol.

**Comment by ripcurlx** [comment]
> * `createcryptopaymentacct`: ☑️
>   I think we should add this to the documentation as we do it for `createpaymentacct` as well. ATM you need to look at simulation scripts to find out how to create altcoin accounts which might be the main use cases for API usage. Maybe we could even just re-use the `createpaymentacct` method with different parameters to make altcoin accounts a first class citizen.

@ghubstan Any thoughts on this as well?

**Comment by ghubstan** [comment]
> Any thoughts on this as well?

Not yet.  I hope to have some thought-time later today.

**Comment by ghubstan** [comment]
> > > Is there a reason why we named the payment account id argument --payment-account and not --payment-account-id?
> > > I think it would be more consistent with the other API methods if we would support the argument with ...-id as well. WDYT?
> 
> At the time I thought abbreviating the param name was a good idea, but it was not. I should make it consistent and change it to `--payment-account-id`.

@ripcurlx, do you agree a resolution of this issue deserves its own PR?

**Comment by ghubstan** [comment]
> > > Everything worked as expected I only recognized this time that using the keepfunds command is necessary to complete the
> > > trade (or isn't it?), but when just checking the gettrade command there is no change happening.
> > > So this might be confusing for API users.
> 
> This is confusing and seemingly unnecessary to API users, but if it is not done, the completed trade will not be moved from the pending/open trades list (persistence file), to the closed trades list (persistence file). I am almost certain there is a keep funds button click required as the last step in the UI / protocol. (The alternative last step in the UI is to move-funds-to-external-wallet.)
> 
> The `keepfunds` cmd is consistent with the final step in the UI. I think this needs some more study from both of us before I change it to say... automatically moving completed trade from open-trades list to closed-trades list in the "next to last" step of the protocol.

@ripcurlx, do you agree the resolution of this issue deserves its own PR?

**Comment by ghubstan** [comment]
> > * `createcryptopaymentacct`: ballot_box_with_check
> >   I think we should add this to the documentation as we do it for `createpaymentacct` as well. ATM you need to look at simulation scripts to find out how to create altcoin accounts which might be the main use cases for API usage. Maybe we could even just re-use the `createpaymentacct` method with different parameters to make altcoin accounts a first class citizen.
> 
> @ghubstan Any thoughts on this as well?

@ripcurlx, I agree this should have been added to the api docs long ago.

Do you agree a resolution of this issue deserves its own PR?

**Comment by ghubstan** [comment]
> Maybe adding another column with trade state?

I need to think about this for awhile...

I would like to make a "another column with trade state" adjustment in another PR that simply removes the `keepfunds` and `withdrawfunds`.

This suggestion would mean a diff from UI:  the closing out of a trade cannot be followed up in the API by the UI analog's `keepfunds` and `withdrawfunds` cmds.  Completion of a trade always automatically results in trade being moved to `closed-trades` file, and proceeds being moved (or left in) internal bisq wallet.   API users can always use the `sendbtc` and `sendbsq` cmds to move funds to external addresses.

What do you think of that?

**Comment by ripcurlx** [comment]
> > Maybe adding another column with trade state?
> 
> I need to think about this for awhile...
> 
> I would like to make a "another column with trade state" adjustment in another PR that simply removes the `keepfunds` and `withdrawfunds`.
> 
> This suggestion would mean a diff from UI: the closing out of a trade cannot be followed up in the API by the UI analog's `keepfunds` and `withdrawfunds` cmds. Completion of a trade always automatically results in trade being moved to `closed-trades` file, and proceeds being moved (or left in) internal bisq wallet. API users can always use the `sendbtc` and `sendbsq` cmds to move funds to external addresses.
> 
> What do you think of that?

Yes, I think that is what @jmacxx implemented here as well: https://github.com/bisq-network/bisq/pull/5870

**Review by ripcurlx — APPROVED** [review]
ACK - I agree to move the rest into separate PRs.

**Pull request merged**
