### PR TITLE
Remove analytics operator bond requirement

### PR DESCRIPTION
**Pull request by wiz**
As discussed in:
https://github.com/bisq-network/proposals/issues/115#issuecomment-529490565

### CODE REVIEW

**Review by chimp1984 — COMMENTED** [review]
NACK

Changing those values was never tested well in the DAO and its pretty complex to test.

**Comment by wiz** [comment]
@chimp1984 since the analytics operator role hasn't been released in any version of Bisq yet, it should be safe 😅

**Comment by ripcurlx** [comment]
> NACK
> 
> Changing those values was never tested well in the DAO and its pretty complex to test.

utACK - As long as it wasn't used nor released I think it should be quite safe to change.

**Review by ripcurlx — APPROVED** [review]
utACK

**Comment by chimp1984** [comment]
Please revert! It is risky to change that even if it was not used. Breaking DAO consensus can have severe effects and that change does not justify the risk.

**Comment by sqrrm** [comment]
I have to agree with @chimp1984 on this one. It seems like a very small benefit compared to the risk of breaking the DAO consensus.

**Comment by wiz** [comment]
@m52go yeah I spoke with the Chimp and he said that while the changes we made are probably fine, even if there's a 0.1% risk of breaking the DAO, we shouldn't do it without huge testing, which is a valid point, so we're going to revert the changes and remove the bond requirement for now.

**Pull request merged**
