### PR TITLE
Fix for #2106

### PR DESCRIPTION
**Pull request by niyid**
Added for new columns: Transaction Fee, Maker Fee, Buyer Deposit and Seller Deposit. More can be added on further evaluation against the requirements.

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Idoubt there is enough space. Can you post a screenshot?

**Comment by niyid** [comment]
> Idoubt there is enough space. Can you post a screenshot?

Sure. Find below. Also note that any further additions will be to the CSV export without adding to displayed columns on said screen.
Screenshot from 2019-07-31 16-57-30

**Comment by ManfredKarrer** [comment]
Thats not the standard size and no values visible. I am pretty shure there is not much available extra space for ne columns....

**Comment by niyid** [comment]
> Thats not the standard size and no values visible. I am pretty shure there is not much available extra space for ne columns....

OK. I will just remove the added columns on the screen while retaining them in the export. Thanks.

**Comment by niyid** [comment]
@ManfredKarrer 

Now there is a conflict: `desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesView.java` . Will you resolve or is it something I should do?

**Comment by niyid** [comment]
Please close this and use the PR below. Sorry for any inconvenience.

https://github.com/bisq-network/bisq/pull/3040

**Pull request closed without merging**
