### PR TITLE
Add popup while synchronizing at fee payment

### LINKED ISSUE #5522: Trade Step 1: If BSQ chosen for trade fees while "Synchronizing DAO", show correct warning popup
### Description

Some BSQ users are not aware that their BSQ wallet balance is virtually zero when Bisq is "Synchronizing DAO".

They may try to pay with BSQ for trade fees, but the UI tells them they have insufficient funds, which is incorrect.

#### Version

v1.6.4

### Steps to reproduce

Try to take or create a trade and choose to pay the fee with BSQ. Do this at a point when "Synchronizing DAO" is happening (shown in the bottom bar).

### Expected behaviour

When pressing Next, the user should get a warning popup saying:

> Your BSQ wallet is disabled while DAO is synchronizing and your BSQ balance may appear to be zero during this period. Please check the status bar and try again later when Synchronizing DAO is complete, or continue now with this trade and use BTC to pay the trade fees.

### Actual behaviour

When pressing Next, the user gets a warning popup saying "You need more BSQ to do this transaction", which is incorrect.

### Screenshots

Screenshot 2021-05-22 at 08 52 43

Screenshot 2021-05-22 at 08 53 02

### PR DESCRIPTION
**Pull request by sneznaj**
Add popup while synchronizing at fee payment

While synchronizing the wallet the amount of BSQ is zero.
The resulting popup at fee payment did not show this reason.

closes #5522

### CODE REVIEW

**Comment by ripcurlx** [comment]
@sneznaj Thanks for cleaning up the Git history. As lots of PRs got merged yesterday I can review your PR now in more detail. Could you please resolve the conflicts you see above and rebase your PR on master again `git pull --rebase origin master`. Thanks!

**Comment by alkum** [comment]
@sneznaj any update? A rebase on master should be straightforward.

**Comment by sneznaj** [comment]
> @sneznaj any update? A rebase on master should be straightforward.

Well, I didnt understand how to rebase on master here.

**Comment by alkum** [comment]
Did you try @ripcurlx 's suggestion above?

```
git pull --rebase origin master
```

**Comment by sneznaj** [comment]
ok i cd into the git repo and executed the command

**Pull request closed without merging**
