### PR TITLE
Upgrade JavaFX to v16

### PR DESCRIPTION
**Pull request by ripcurlx**
As we have now the possibility again to keep up with the latest bug fixes and updates I've upgraded JavaFX to v16.

It seems to be mainly a bug fix release. All details can be found here: https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-16.md

I did some smoke tests on Mainnet and everything seems to be fine.

### CODE REVIEW

**Comment by ripcurlx** [comment]
There seems to be something that needs to be looked into:
```
Mai 17, 2021 11:06:04 VORM. com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @51133c06'
```
This warning has now surfaced for the first time in JavaFX 16 as it implements https://bugs.openjdk.java.net/browse/JDK-8256362

**Comment by sqrrm** [comment]
This sounds good to me, it's not a fringe library so keeping it up to date makes sense to me.

**Comment by ripcurlx** [comment]
Using the javaFX plugin doesn't fix this issue, but it will as soon as this is fixed by the plugin itself (hopefully). See https://github.com/openjfx/javafx-gradle-plugin/issues/108

As this is an issue that exists already on master I think this PR is still good to be merged IMO. @sqrrm WDYT?

**Review by cd2357 — DISMISSED** [review]
ACK. Tested on macOS and Linux.

**Comment by cd2357** [comment]
Hmm packaging for linux fails for me with

```
> Task :desktop:packageInstallers
Executing command:
java -jar "/home/user/git/bisq/desktop/package/tools-1.0.jar" /home/user/git/bisq/desktop/build/libs/fatJar/desktop-1.6.4-SNAPSHOT-all.jar

Command output (stderr):
Exception in thread "main" java.io.IOException: Failed to rename /tmp/Bisq-stripped2587512738202276447.tmp to /home/user/git/bisq/desktop/build/libs/fatJar/desktop-1.6.4-SNAPSHOT-all.jar
at bisq.tools.Utils.renameFile(Utils.java:36)
at io.github.zlika.reproducible.StipZipFile.strip(StipZipFile.java:35)
at bisq.tools.DeterministicBuildTool.main(DeterministicBuildTool.java:24)
```

Can someone else please confirm? Just to check its not an issue with my local env.

**Comment by ripcurlx** [comment]
> Hmm packaging for linux fails for me with
> 
> ```
> > Task :desktop:packageInstallers
> Executing command:
> java -jar "/home/user/git/bisq/desktop/package/tools-1.0.jar" /home/user/git/bisq/desktop/build/libs/fatJar/desktop-1.6.4-SNAPSHOT-all.jar
> 
> Command output (stderr):
> Exception in thread "main" java.io.IOException: Failed to rename /tmp/Bisq-stripped2587512738202276447.tmp to /home/user/git/bisq/desktop/build/libs/fatJar/desktop-1.6.4-SNAPSHOT-all.jar
> at bisq.tools.Utils.renameFile(Utils.java:36)
> at io.github.zlika.reproducible.StipZipFile.strip(StipZipFile.java:35)
> at bisq.tools.DeterministicBuildTool.main(DeterministicBuildTool.java:24)
> ```
> 
> Can someone else please confirm? Just to check its not an issue with my local env.

Packaging on Ubuntu 20.04.2 worked just fine for me.

**Comment by ripcurlx** [comment]
Ok - as I wasn't able to create a universal deterministic JAR I'll revert my changes back to OS specific jars.

**Review by sqrrm — APPROVED** [review]
utACK

**Pull request merged**
