### PR TITLE
Add 

### PR DESCRIPTION
**Pull request by notstalin**

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
I don't know what this PR with 100s of changed files should be? I am not willing to spend time on that. Please hire an experienced Java developer and read the requirements. Its not hard and many other have done it correclty.

**Comment by ghost** [comment]
you are communicating with the wrong people here.
i would take a peak at your bouncing provider for your mx 

i certainly did not email you, ever-- could there be possibly another reason for our reception of this email correspondence regarding "bitsquare and moon coins being added" lol

cheers,
a friendly yet concerned internet user.
--
🔥 kind regards,
//artik// zyplok.com llc.


20. Jun 2017 12:47 by notifications@github.com:

**Comment by notstalin** [comment]
I´m trying to submit a pull request to list mooncoin on bitsquare and I put it in the wrong place. I am not a programmer and this website isn't made for someone like me. How do I submit the pull request?  

Best regards,

Simon Nicol

**Comment by ManfredKarrer** [comment]
A PR is nothing a non-progammer should/can do. Hire an experienced developer.

**Pull request closed without merging**
