### PR TITLE
List Conceal (CCX)

### PR DESCRIPTION
**Pull request by ghost**
Official project URL: https://conceal.network/
Official block explorer URL: https://explorer.conceal.network/
Additional: The Conceal CLI simple wallet provides a secret transaction key that enables 3rd party audits in case of a dispute similar to Monero. We are submitting separate pull requests for a pop-up explaining CCX trading requirements on Bisq.

### CODE REVIEW

**Comment by ghost** [comment]
There is only one place for PR for listing assets : https://github.com/bisq-network/bisq-assets
It's uneseful (and messing) to make it on other repos.
Please have a look as other people are doing.

**Comment by cbeams** [comment]
@HarryMacfinned, the description above explains why they have issued the extra PRs:

> The Conceal CLI simple wallet provides a secret transaction key that enables 3rd party audits in case of a dispute similar to Monero. We are submitting separate pull requests for a pop-up explaining CCX trading requirements on Bisq.

There is nothing wrong with this in principle. Just needs to be reviewed for correctness.

**Comment by ghost** [comment]
Here are the other two PR's:
https://github.com/bisq-network/bisq-assets/pull/88
https://github.com/bisq-network/bisq-core/pull/140

**Comment by lumenano** [comment]
Here are the other two PR's:
https://github.com/bisq-network/bisq-assets/pull/88
https://github.com/bisq-network/bisq-core/pull/140

**Comment by ghost** [comment]
The check failed, although it has since disappeared. It gave the following reason:
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'bisq-desktop'.
> Could not resolve all dependencies for configuration ':compile'.
   > Could not find network.bisq:bisq-core:-SNAPSHOT.
     Searched in the following locations:
         https://jcenter.bintray.com/network/bisq/bisq-core/-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/network/bisq/bisq-core/-SNAPSHOT/bisq-core--SNAPSHOT.pom
```
I want to mention that I'm getting the same kind of error when trying to install Bisq from the Arch Linux repository or when I directly build myself. 
I doubt the problem is with the code I submitted. It is only 5 lines and is a virtual copy of XMR code.

**Comment by ghost** [comment]
@cbeams wrote: 
> There is nothing wrong with this in principle. Just needs to be reviewed for correctness.

Ok, my bad. Reacting too fast. My apologies.

**Comment by ManfredKarrer** [comment]
I assume it requires like at Monero to run a full node which is fully synced. Can we (do we want to) add that burden on the arbitrators?

**Comment by ghost** [comment]
> I assume it requires like at Monero to run a full node which is fully synced. Can we (do we want to) add that burden on the arbitrators?

For the purpose of verifying a payment by an arbitrator, we have a special page here: https://explorer.conceal.network/txviewer/. This page displays otherwise private details of a transaction given three inputs: the recipient's address, the transaction hash and the transaction secret key. The transaction secret key can decrypt the private parts of the transaction and is available only to the sender unless the sender chooses to give it to a 3rd party.

The link to this page is given in the pop-up code we have submitted to you, so that Bisq users will be aware of the verification procedure before they send a payment.

The page itself makes an API call to one of our continuously operating nodes and so can view new transactions as soon as they are included in a block, without the need for a local node.

I will be happy to respond to any other concerns you may have.

**Comment by ManfredKarrer** [comment]
Ah thanks, that sounds good.

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Review by cbeams — APPROVED** [review]
utACK

**Comment by ghost** [comment]
Thank you Bisq team for approving our request for listing on your exchange. I assume it will take effect in the next release?

**Comment by cbeams** [comment]
Correct, and we'll probably release v0.7.2 within a month.

**Comment by krypt0x** [comment]
Conceal $CCX deserves to be listed on Bisq for free. We made an extra effort to have everything compliant and ready on time before the fee's controversy.  There is a track record of the work involved. It's not fair that Bisq halted our listing due to other projects' despair. Long hours of our work have been threw away. Please reevaluate this request. Thank you.

**Comment by HAMMERjah** [comment]
I'm not usually one for handouts, but this is accurate. CCX has gone beyond normal expectations and consistently shown good faith. Please consider this!

**Comment by cbeams** [comment]
Please see https://github.com/bisq-network/proposals/issues/35#issuecomment-425184121.

**Pull request merged**
