### PR TITLE
Language strings file cleanup; added missing, applied rename

### PR DESCRIPTION
**Pull request by cparke2**
The Bisq policy for displayStrings, as stated in the comments at the beginning of the primary (English) language properties file, is that all string keys should be present in **_all_** language files, even though fallthrough would otherwise result. In reviewing how well the language files actually comply with this rule, the following discrepancies were found and are fixed here:

1. **tradeFeedbackWindow.msg.part1/2/3** apparently was changed at some point in the past to **tradeFeedbackWindow.msg.feedback** and **tradeFeedbackWindow.msg.thanks**.  This change also involved removal of reference to a user survey in favor of redirecting users to a Bisq forums.  However, that change was never applied to any of the language files, which meant fallthrough has been happening and the translations were **_not_** displaying.

2. **filterWindow.addedSeedNodes** and **filterWindow.addedBtcNodes** were never added to language files. These and the other filterWindow strings are used by **desktop/src/main/java/bisq/desktop/main/overlays/windows/FilterWindow.java** file, although that window itself seems to be dead code at present (I cannot find it in the application or how it would be launched by the code). This is may be a separate issue for a different pull request at a later time, depending on whether FilterWindow is deemed obsolete or if it is actually a new feature still in development.

Prerequsite to PR https://github.com/bisq-network/bisq/pull/7268

### CODE REVIEW

**Comment by cparke2** [comment]
Tested Desktop UI using Russian language interface:
(previously, only the title bar was translated, since that key did not change)

**Before:**
Screenshot from 2024-09-21 22-01-56

**After:**
Screenshot from 2024-09-22 01-46-05

**Comment by cparke2** [comment]
Tested that new strings load properly using a small Java applet:
```
import bisq.core.locale.Res;
import java.io.PrintStream;
import static java.nio.charset.StandardCharsets.UTF_8;  

public class ResGetTest {
	public static void main(String[] args) {
	        final String key = args[0];
		Res.setup();
		PrintStream out = new PrintStream(System.out, true, UTF_8);
		out.println(Res.get(key));
	}
}
```

Output from all languages on string **tradeFeedbackWindow.msg.feedback**:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: cs_US
Rádi bychom od vás slyšeli o vašich zkušenostech. Pomůže nám to vylepšit software a vyhladit všechny nejasnosti.

Pokud máte nějaké dotazy nebo máte nějaké problémy, obraťte se prosím na ostatní uživatele a přispěvatele prostřednictvím fóra Bisq na:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: de_US
Wir würden gerne von Ihren Erfahrungen mit Bisq hören. Dies hilft uns die Software zu verbessern und etwaige Stolpersteine zu beseitigen.

Sollten Sie Fragen oder Probleme haben, kontaktieren Sie andere Nutzer und Mitwirkende im Bisq-Forum auf:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: es_US
Nos encantaría saber su opinión acerca de su experiencia. Nos ayudará a mejorar el software y refinar sus características.

Si tiene alguna pregunta o experimenta algún problema, por favor póngase en contacto con otros usuarios y colaboradores a través del foro Bisq en:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: fa_US
دوست داریم تجربه شما را بشنویم. این امر به ما کمک می کند تا نرم افزار را بهبود بخشیم و مشکلات را حل کنیم.

اگر سوالی دارید یا مشکلی را تجربه کرده‌اید، لطفا با سایر کاربران و شرکت کننده ها از طریق انجمن Bisq که در ذیل ارائه شده، به اشتراک بگذارید:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: fr_US
Nous aimerions avoir de vos commentaires sur votre expérience. Cela nous aidera à améliorer le logiciel et à aplanir les aspérités.

Si vous avez la moindre question, ou rencontrez un problème, veuillez s'il vous plaît vous mettre en relation avec les autres utilisateurs et contributeurs via le forum Bisq sur:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: it_US
Ci piacerebbe avere notizie sulla tua esperienza. Ci aiuterà a migliorare il software e a correggere eventuali errori.

In caso di domande o problemi, si prega di mettersi in contatto con altri utenti e collaboratori tramite il forum Bisq all'indirizzo:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: ja_US
私達はあなたの体験についての連絡をお待ちしております。 それは私達のソフトウェアを改良して、荒削りな部分を洗練させる手助けになります。

ご質問がある場合、または問題が発生した場合は、次のBisqフォーラムで他のユーザーや貢献者に連絡してください：

[main] INFO bisq.core.locale.GlobalSettings - Locale info: pl_US
Chcielibyśmy usłyszeć o Twoich wrażeniach. Pomoże to nam ulepszyć oprogramowanie i ulepszyć zabezpieczenia.

Jeśli masz jakiekolwiek pytania, lub doświadczyłeś problemów prosimy o kontakt z innymi użytkownikami i osobami które przyczyniają się do rozwoju Bisq na forum:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: en_US
We'd love to hear back from you about your experience. It'll help us to improve the software and to smooth out any rough edges.

If you'd like to provide feedback, if you have any questions, or experienced any problems, please get in touch with other users and contributors via the Bisq forum at:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: pt-br_US
Gostaríamos de saber como está sendo a sua experiência. Ela nos ajuda a corrigir e aperfeiçoar o software.

Se você tem dúvidas ou está tendo problemas, por favor entre em contato com outros usuários e contribuidores através do fórum Bisq em:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: pt_US
Adoraríamos ouvir sobre sua experiência. Isso nos ajudará a aperfeiçoar o software e a suavizar as arestas.

Se tiver alguma dúvida ou algum problema, entre em contacto com outros usuários e colaboradores através do fórum Bisq em:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: ru_US
Мы были бы рады услышать ваши отзывы. Они помогут нам улучшить приложение и исправить любые ошибки.

Если у вас возникли вопросы или сложности, свяжитесь с другими пользователями и разработчиками приложения на форуме Bisq:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: th_US
เรายินดีที่จะฟังความเห็นเกี่ยวกับประสบการณ์ของคุณ มันจะช่วยให้เราปรับปรุงซอฟต์แวร์และระบบดียิ่งขึ้น

หากคุณมีข้อสงสัยหรือประสบปัญหาใด ๆ โปรดติดต่อกับผู้ใช้และผู้สนับสนุนคนอื่น ๆ ผ่านทางฟอรัม Bisq ที่:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: vi_US
Chúng tôi rất vui lòng được nghe phản hồi của bạn. Điều đó sẽ giúp chúng tôi cải thiện phần mềm và hoàn thiện trải nghiệm người dùng.

nếu bạn có câu hỏi hay vấn đề, vui lòng liên hệ với người dùng khác và các nhàn đóng góp qua Bisq forum ở:

[main] INFO bisq.core.locale.GlobalSettings - Locale info: zh-hans_US
我们很想听听您的体验如何。这将帮助我们改进软件，优化体验不好的地方。

如果您有任何疑问或遇到任何问题，请通过 Bisq 论坛与其他用户和贡献者联系：

[main] INFO bisq.core.locale.GlobalSettings - Locale info: zh-hant_US
我們很想聽聽您的體驗如何。這將幫助我們改進軟件，優化體驗不好的地方。

如果您有任何疑問或遇到任何問題，請通過 Bisq 論壇與其他用户和貢獻者聯繫：

**Review by HenrikJannsen — APPROVED** [review]
utACK

Do you refer to " Please use in all language files the exact same order of the entries, that way a comparison is easier."?

This does not really mean that all language strings should be present in all language files. Not that familiar with Transifex workflow, but I assume its better to use the fallback. We discussed elsewhere already and can wait for response from @ripcurlx

**Comment by cparke2** [comment]
I could try to gut all the English displayStrings out of the language files, but as I said this certainly appears to have been the practice, and I'd be literally removing thousands of strings that I never added to do it!  Agree though it would make it easier for people when adding new strings, but I think it's way too late for that now.

I'm aware Bisq1 is in maintenance mode and most devs are working on new Bisq2 functionality behind the scenes, though not sure how I could contribute with most of the project planning and feature requests happening behind the scenes.

**Comment by HenrikJannsen** [comment]
> I could try to gut all the English displayStrings out of the language files, but as I said this certainly appears to have been the practice, and I'd be literally removing thousands of strings that I never added to do it! Agree though it would make it easier for people when adding new strings, but I think it's way too late for that now.

Ah ok. I was not aware that it was practice in Bisq 1 to add english strings. 

> 
> I'm aware Bisq1 is in maintenance mode and most devs are working on new Bisq2 functionality behind the scenes, though not sure how I could contribute with most of the project planning and feature requests happening behind the scenes.

Why do you think that? There is plenty of resources where one can see the things which are planned and in work:
https://github.com/bisq-network/proposals/issues/
https://github.com/bisq-network/bisq2/discussions
https://github.com/bisq-network/bisq2/issues

See also the high level bisq2 video at https://bisq.network/blog/bisq-2-now-in-beta

**Pull request merged**
