### PR TITLE
Improve popup text in case a local node is detected

### PR DESCRIPTION
**Pull request by chimp1984**
Improve popup text in case a local node is detected

### CODE REVIEW

**Comment by chimp1984** [comment]
@m52go Could you review?
```
popup.bitcoinLocalhostNode.msg=Bisq detected a locally running Bitcoin Core node (at localhost).\n\\n\
  Please ensure that following requirements are met when using a local Bitcoin Core node:\n\
  - The node need to be fully synced before you start Bisq\n\
  - The node need to have pruning disabled (option: 'prune=0')\n\
  - The node need to have bloom filters enabled (option: 'peerbloomfilters=1')
 ```

**Comment by chimp1984** [comment]
Before:
Screen Shot 2020-12-20 at 13 23 29

After:
Screen Shot 2020-12-20 at 13 27 57

**Comment by m52go** [comment]
Suggestion:

```
popup.bitcoinLocalhostNode.msg=Bisq detected a Bitcoin Core node running on this machine (at localhost).\n\n\
  Please ensure:\n\
  - the node is fully synced before starting Bisq\n\
  - pruning is disabled ('prune=0' in bitcoin.conf)\n\
  - bloom filters are enabled ('peerbloomfilters=1' in bitcoin.conf)
 ```

**Comment by chimp1984** [comment]
Thanks @m52go ! Much better!

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
