### PR TITLE
Add TOKC Altcoin

### PR DESCRIPTION
**Pull request by Sergstuddek**
- Ticker symbol (e.g. LTC): TOKC
- Official token name (e.g. Litecoin): Tokyo Coin
- Official block explorer URL: http://tokyoexplorer.ga
- Is it an Altcoin (dedicated blockchain) or a token (anything else) (e.g. Altcoin): Altcoin
- Official token project URL: http://tokyocoin.info

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Travis failed. Are u sure it compiles and unit tests are ok? We just added a new requirement that if PR dont compile or tests fail the PR will get blocked for 2 weeks to avoid that devs are reviewing PR which do not match min. requirements.

**Comment by Sergstuddek** [comment]
This is my fail, i will fix it

**Comment by Sergstuddek** [comment]
As I think everything is alright, when will be next issue?

**Comment by mrosseel** [comment]
utACK

**Comment by Sergstuddek** [comment]
What?

**Comment by mrosseel** [comment]
utACK (untested ACK) - Reviewed and agree with the code changes but haven't actually tested them.

**Comment by cbeams** [comment]
See https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#peer-review for details.

**Comment by Sergstuddek** [comment]
Ok. Thanks for info

**Review by ManfredKarrer — CHANGES_REQUESTED** [review]
Unit test failed:

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertFalse(Assert.java:39)
	at junit.framework.Assert.assertFalse(Assert.java:47)
	at junit.framework.TestCase.assertFalse(TestCase.java:219)
	at io.bisq.gui.util.validation.AltCoinAddressValidatorTest.testTOKC(AltCoinAddressValidatorTest.java:579)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Please be aware that  your PR is now blocked for 2 weeks. Running the unit test is the min. requirement to avoid that we burn our dev resources!

**Comment by ManfredKarrer** [comment]
Blocked until Feb. 14th. because of failing Unit test.

**Comment by mrosseel** [comment]
@cbeams we could save Manfred and the contributors some more time by enabling the unit tests for CI builds, this is the cmd line output of travis:

```142.67s$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V```

**Comment by cbeams** [comment]
> @cbeams we could save Manfred and the contributors some more time by enabling the unit tests for CI builds:

Agreed. I actually thought I had done exactly this when enabling building pull requests in Travis CI recently. What I didn't realize is that we had tests explicitly disabled in `.travis.yml`.

I've just re-enabled them in ed0148bfee59c091972ca5da0626ce5bec6d1405.

> This is the cmd line output of travis
> `142.67s$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`

Actually, that's Travis CI's standard command for doing dependency management prior to actually building the project. See https://docs.travis-ci.com/user/languages/java/#Maven-Dependency-Management.

We were skipping tests because we had customized the Travis CI `script` command in our `.travis.yml`. That's fixed now.

@ManfredKarrer, this means that we should be able to reliably see whether Altcoin pull requests are valid right away, both in that they compile and that all tests pass.

Of course, what this change doesn't prevent is the case in which an Altcoin pull requests doesn't add any tests at all. To deal with that, we'd need to introduce code coverage and set a minimum threshold that can't be broken. This would tell us when someone adds code (for an Altcoin), but doesn't add tests covering that code. In any case, this should be a step in the right direction, and the best thing about it is that Altcoin PR submitters should be able to see the failure right away, too, and fix it, hopefully before the PR wastes any of your time at all.

**Pull request closed without merging**
