### PR TITLE
Rebrand Neos to Donu

### PR DESCRIPTION
**Pull request by ksynb**
Project Information:

* Official project URL: https://www.donu.io
* Official block explorer URL: https://chainz.cryptoid.info/donu/
* Official Github Source: https://github.com/donito-inc/donu-core

### CODE REVIEW

**Comment by blabno** [comment]
NEOS has been submitted in this PR https://github.com/bisq-network/bisq/pull/1657 by @BoubonicNugz. 

@BoubonicNugz could you confirm this is legit re-branding?

**Comment by blabno** [comment]
The code looks ok, although I'm not sure how it will influence existing offers.
Wouldn't it be safer to delist NEOS and add Donu as a new asset?

**Comment by buzztiaan** [comment]
the address formats are the same and all users know it moved, but i can see your motivation yeah
there's no open offers at the moment

**Comment by BoubonicNugz** [comment]
ACK'd

This is a legit re-branding.  @ksynb is the lead developer of the project.

**Comment by blabno** [comment]
@ManfredKarrer @ripcurlx Do you think it's safe to accept this re-brand with regards to potential existing offers?

**Comment by sqrrm** [comment]
Regarding rebranding, I think we might want to discuss a bit and have some kind of template on how to handle that. Might be best to just add it as a new asset for any rebranding.

**Comment by ksynb** [comment]
> Regarding rebranding, I think we might want to discuss a bit and have some kind of template on how to handle that. Might be best to just add it as a new asset for any rebranding.

That would be reasonable. I know folks in the community would appreciate it being back up and available for trade. With the current PR containing required details, is it possible for inclusion in the next update or would you prefer a new PR is created with the intent specified as initial inclusion?

**Review by blabno — APPROVED** [review]
Since we've got a lot of other topics queued for next few dev calls and taking into consideration that the developer who initially create PR to list this asset with previous name I'm giving this ACK.

**Pull request merged**
