### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by cedricwalter**
added French translations, work in progress

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Thanks! Please use the development branch for further PR, the DAO branch is not used anymore, but I will merge it down.... Also check out our transifex page, might be more comfortable...
https://www.transifex.com/bitsquare

**Comment by ManfredKarrer** [comment]
@riclas @cedricwalter 
I added it to the Dev branch in_dev folder as it is not complete yet. I am not sure if the base file was up to date. Better use transifex to have it well organized.

**Comment by jonathancross** [comment]
Happy to see you here @cedricwalter !

**Comment by cedricwalter** [comment]
@jonathancross you are also everywhere on internet ;-)

**Comment by cedricwalter** [comment]
@ManfredKarrer BTW the trial has expired at https://www.transifex.com/bitsquare it says that an admin need to select a plan now.

**Comment by riclas** [comment]
Please disregard that message everyone :)

**Pull request merged**
