### PR TITLE
Replacing JUnit4 with JUnit5 Jupiter

### PR DESCRIPTION
**Pull request by napoly**
Removing JUnit 4 dependencies and upgrading Hamcrest.

### CODE REVIEW

**Review by alvasw — APPROVED** [review]
ACK

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Comment by alejandrogarcia83** [comment]
Congrats to your first merged PR in Bisq!

**Comment by napoly** [comment]
thank you !!!

**Pull request merged**
