### PR TITLE
Update tor-browser to v11.0.15 / tor-binary to v0.4.7.8

### PR DESCRIPTION
**Pull request by ripcurlx**
While running `./gradlew --write-verification-metadata sha256` I recognized that there had been lots of line-breaks added on master compared to what I see when running it locally. @chimp1984 Did you do any manual changes in the file or run the command from your local gradle installation?

### CODE REVIEW

**Comment by ripcurlx** [comment]
I think this is some auto-formatting that is done by IntelliJ before commit. I'll force push my changes again without the autoformatting after file generation.

**Comment by ripcurlx** [comment]
@chimp1984 I think it is good to commit the un-formatted changes otherwise it is really hard to see the changes locally.

**Review by chimp1984 — APPROVED** [review]
utACK

**Review by bisq-github-admin-3 — APPROVED** [review]
utACK - based on https://github.com/bisq-network/bisq/pull/6280#pullrequestreview-1027351142

**Pull request merged**
