### PR TITLE
Seems to be you had renamed the CryptoNote Class..

### PR DESCRIPTION
**Pull request by ghost**
..when we first created our PR we didn't expect that.

### CODE REVIEW

**Comment by ripcurlx** [comment]
@qwertycoin-org Do you ever run the code locally? This will fail as well String != long

**Comment by qwertycoin-org** [comment]
@ripcurlx yes
Bisq changed the Classname from CryptonoteAddressValidator
to CryptoNoteAddressValidator after we had first created our PR.

**Comment by ripcurlx** [comment]
> @ripcurlx yes
> Bisq changed the Classname from CryptonoteAddressValidator
> to CryptoNoteAddressValidator after we had first created our PR.

I see - please adapt your PR to the changes.

**Comment by qwertycoin-org** [comment]
@ripcurlx is fixed here: https://github.com/bisq-network/bisq/pull/2562 in a fresh PR.

**Pull request closed without merging**
