### PR TITLE
List Webchain (WEB)

### PR DESCRIPTION
**Pull request by khaledalam**
- Official project URL: https://webchain.network
- Official block explorer URL: https://explorer.webchain.network

### CODE REVIEW

**Comment by pahanzt** [comment]
@ManfredKarrer hi, on behalf of Webchain team, I'd like to clarify, what's failing here exactly? @khaledalam (responsible developer) couldn't identify a problem. Please give a tip and tag him with an answer.

**Comment by ManfredKarrer** [comment]
Ignore that, thats an issue on the build sytem and download at oracle...

**Comment by pahanzt** [comment]
@ManfredKarrer thanks for response. is pull request going to be merged or are we still missing something?

**Comment by pahanzt** [comment]
@ManfredKarrer hello, could you please help with our case? 17 days since our last request.

**Comment by ManfredKarrer** [comment]
Assets are not my responsibility. We are short on dev resources and asset listing is not on the high priority list. See discussions with delisting inactive coins. > 90% of the coins are never traded anyway so we ahve to question if its worth for us to put so much effort on it.

**Comment by cbeams** [comment]
@blabno reviews these PRs as he has time, but there are no guarantees. This PR does not follow instructions as it has multiple commits. Please re-read the instructions. Please also fix the merge error that now exists.

**Comment by blabno** [comment]
@pahanzt please rebase against master and resolve conflicts.

**Comment by khaledalam** [comment]
@blabno solved it.

**Comment by juice99** [comment]
@blabno @cbeams any news about merging it?

**Comment by khaledalam** [comment]
> @pahanzt please rebase against master and resolve conflicts.

@cbeams i rebased for the second time, it's ready now please check it.

**Comment by khaledalam** [comment]
@cbeams @pahanzt  ??

**Comment by khaledalam** [comment]
@blabno  @cbeams  ??

**Comment by blabno** [comment]
You did not rebased but merged instead. You have to rebase. Your PR must be composed of just one commit.

**Comment by khaledalam** [comment]
@blabno done here: #2154
sorry about not following PR instructions, please check it as fast as possible since this PR hangs for +2 months. thanks in advanced

**Comment by khaledalam** [comment]
@blabno @cbeams @ManfredKarrer  all instructions followed here: #2176 , thanks for explanation

**Comment by blabno** [comment]
unknown repository

**Comment by ripcurlx** [comment]
Closing because of duplicate. https://github.com/bisq-network/bisq/pull/2176

**Pull request closed without merging**
