### PR TITLE
Tor 0.4.2.6

### PR DESCRIPTION
**Pull request by freimair**
Part of https://github.com/bisq-network/projects/issues/23

Contains:
- Upgrade Tor to a version that defaults to HSv3.
- Upgrade jtorctl to handle HSv3 properly.
- Upgrade netlayer so it uses the new jtorctl and tor.

Note:
- the previous versions of the libraries added timeouts checks to further dial in on the Tor issues we encounter. These changes are included here as well. However, that did not went so well for Windows and Bisq reverted the update.
- for testing, I created a `libs` directory holding snapshots of the `jtorctl` and `netlayer` binaries. Once we are somewhat certain that they work, I am going to release them properly and remove the libs dir.

### CODE REVIEW

**Comment by devinbileck** [comment]
I tested this on a Windows 10 VM which has encountered Tor startup issues in the past and it worked successfully, for which it took 86 seconds to start Tor. Note that my testing only verified application startup and connecting to the Tor network.

**Comment by ripcurlx** [comment]
@freimair There is no need to add the [Do not merge!] if you have it as a `Draft` PR, as no one can merge it in that case. As @devinbileck already started testing it on Windows, shall we test it on all supported OSes as well (I could take over macOS)?

**Comment by freimair** [comment]
> no need to add the [Do not merge!]

better safe than sorry (and you guys merged something recently that has not been fully tested...)

> already started testing it on Windows,

I asked him to do the quick check to see if the issue he had last update is still there. And I will talk to him tomorrow about how to set up the testing framework.

**Comment by freimair** [comment]
After testing
- major platforms report green light (linux, macos, windows)
- testing has been performed with v2 seednodes and v3 seednodes
- ripcurlx even tested "upgrading" an existing client to v3 (by deleting the hs files)

all in all, no failures have been reported [detailed test results](https://bisq.ontestpad.com/project/1/folder/f60/)

Thus, I released all binaries of the netlayer stack properly now and I ask you guys to do some smoke tests just to make sure I did not mess up the dependency references.

**Review by ripcurlx — APPROVED** [review]
ACK

After running in-depth tests on macOS (see testpad) I ran with the current state a couple of smoke tests again (v2 address and afterwards upgrade to v3). So far looking good!

**Pull request merged**
