### PR TITLE
Reduce number of decimals shown for monetary fiat prices to 2

### LINKED ISSUE #3449: Fiat amount is rounded but two decimal places are displayed
[How to Reproduce]
1. Start Alice's desktop
2. Create buy offer
3. See rounded fiat amount with two decimal places

[Expected Results]
Rounded fiat amount should be displayed without two decimal places in UI.

[Actual Results]
Rounded fiat amount is displayed with two decimal places in UI.

RoundedDecimals
Figure 1.  USD cents are rounded to 0 but displayed

BubbleTextIndicatingRounding png
Figure 2.   Bubble text about security is displayed but hard to read in dark mode (See [3440](https://github.com/bisq-network/bisq/issues/3440) ) 

This issue was discovered during v1.2.0 [testing](https://bisq.ontestpad.com/script/111#78/5) .

### PR DESCRIPTION
**Pull request by ghost**
Fixes #3449

Reduce number of decimals shown from 4 to 2 for fiat monetary values.

### CODE REVIEW

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK

Thanks for your first PR, but you fixed the wrong precision.
Bildschirmfoto 2020-02-04 um 10 58 25
The amount should be rounded, having no decimals for fiat.

Please add to your PR also how you test your change. Thanks!

**Comment by ghost** [comment]
Thanks @ripcurlx for the review, I've pushed an update so decimals are removed for displayed fiat volume amounts.

I've updated the appropriate tests and ran the `bisq:desktop test` task. I also did sanity checks with a local build. Let me know if I missed something.

**Review by ripcurlx — APPROVED** [review]
ACK

I tested it locally on Regtest and it works as expected.
I did find an existing bug while testing which was fixed in https://github.com/bisq-network/bisq/pull/3926/commits/3438535836e1dba4e80151adaa13797053f34a21.
**Before**
Bildschirmfoto 2020-02-05 um 17 42 20
**After**
Bildschirmfoto 2020-02-05 um 17 44 06

The bug only occurred when switching between fiat and altcoin payment accounts in the create offer dialog.

**Comment by ripcurlx** [comment]
@milesap **Congrats to your first merged PR!**

Just a heads up that we changed recently our process on what kind of contribution is up for compensation and which is not.
To make it clear for development contributions the `is:priority` label is added to a PR if it is up for compensation. Please see our recent [Bisq Q1 2020 Update](https://youtu.be/oImSdIAsywA) for more details.

**Pull request merged**
