### PR TITLE
Update data stores for v1.8.3

### PR DESCRIPTION
**Pull request by ripcurlx**
Full node in dark mode and light node in light mode.

Bildschirmfoto 2022-02-24 um 20 50 12
Bildschirmfoto 2022-02-24 um 20 50 14
Bildschirmfoto 2022-02-24 um 20 50 21
Bildschirmfoto 2022-02-24 um 20 50 25
Bildschirmfoto 2022-02-24 um 20 50 32
Bildschirmfoto 2022-02-24 um 20 50 40

### CODE REVIEW

**Comment by ripcurlx** [comment]
@sqrrm Could you please ACK this one? Thanks!

**Comment by ripcurlx** [comment]
@jmacxx Just in case sqrrm is not available right now, it would be great if you could review those data store changes as well. Thanks!

**Review by ghost — APPROVED** [review]
ACK light node
utACK full node

**Comment by ripcurlx** [comment]
> ACK light node utACK full node

Thanks @jmacxx ! I've just updated them again (to improve UX for new users) as @sqrrm promised to review them tonight.

**Comment by ripcurlx** [comment]
Bildschirmfoto 2022-02-28 um 17 06 11
Bildschirmfoto 2022-02-28 um 17 06 23
Bildschirmfoto 2022-02-28 um 17 06 30

I didn't have any conflicts with seednodes.

**Pull request merged**
