### PR TITLE
List QMCoin

### PR DESCRIPTION
**Pull request by project-qmc**
- Official project URL: https://github.com/project-qmc/QMC
- Official block explorer URL: http://136.243.26.230/

### CODE REVIEW

**Comment by project-qmc** [comment]
Was trying to figure an rough ETA for possible listing but noticed no releases have been made recently (and also a note about reaching consensus regarding listing fees - which was settled as still no fee I think?) ... So my question is, how does it work now days?

**Review by blabno — APPROVED** [review]
ACK

**Comment by project-qmc** [comment]
Thanks, I don't suppose there is any new release ETA, is there? seeing as the last one was in August and the one before that was in July?

I've got a feeling that a lot of coins get listed after a very long wait and therefor they end up without volume (as they seek alternatives) - plus it is possible their devs forget to check for a new release after a month. We'll make sure this doesn't happen with QMC - but even a rough ETA would be nice !

**Comment by ghost** [comment]
Next release is _planned_ for mid-end october.

**Comment by project-qmc** [comment]
Awesome, looking forward to it.
Thanks again!

**Comment by project-qmc** [comment]
@HarryMacfinned Any idea for a new ETA? :)

**Comment by ghost** [comment]
There are some issues with the last java version to use.
And since v0.9.0 will have many novelties, it will require strong testing.
We'll probably have to wait at least one more week I guess.

**Comment by project-qmc** [comment]
Sounds good. Not much of a java guy myself but do know a bit of everything - so if you guys ever need a helping hand just ping ;)

**Comment by project-qmc** [comment]
Soooo this isn't in the new release ?

**Comment by ghost** [comment]
I guess new assets listing will be done with v0.9.0.
And there are delays.

**Comment by ripcurlx** [comment]
@project-qmc 0.8.1 was just about temporarily fixing a startup issue. Release 0.9.0 is in its final development phase and it will need in-depth testing as we nearly touched every class and introduced lots of new stuff. So fingers crossed that we'll start testing soon.

**Pull request merged**
