### PR TITLE
List FourtyTwo (FRTY)

### PR DESCRIPTION
**Pull request by System96**
Official project URL: [https://coin42.co] 
Official block explorer URL: [http://explorer.coin42.co]

### CODE REVIEW

**Review by blabno — CHANGES_REQUESTED** [review]
NACK no PRs from master and block explorer is not reachable

**Comment by ManfredKarrer** [comment]
Open again once you have a stable block explorer.

**Comment by System96** [comment]
Domains are fixed now as well as the Block explorer

**Comment by blabno** [comment]
Please describe how arbitrator can verify if transaction did happened and see transaction details.

**Pull request closed without merging**
