### PR TITLE
Upate bitcoinj to commit dcf8af0 - Bloom filter fix

### PR DESCRIPTION
**Pull request by oscarguindzberg**
Fixes https://github.com/bitcoinj/bitcoinj/issues/2070
Maybe fixes https://github.com/bisq-network/bisq/issues/4870

This PR should be merged to hotfix/v1.5.1 and then to master.

### CODE REVIEW

**Comment by chimp1984** [comment]
I left a comment on the bitcoinj commit. Once that is resolved I can utACK that PR.

**Comment by oscarguindzberg** [comment]
Thanks for spotting the bitcoinj bug. I just fixed it.
I added a new commit in bitcoinj to fix it.
I changed the bitcoinj commit version in this PR to dcf8af0.

**Review by chimp1984 — COMMENTED** [review]
utACK

**Review by sqrrm — APPROVED** [review]
utACK

**Pull request merged**
