### PR TITLE
Update Dark Theme to V2 with new CSS and images by Pedro

### PR DESCRIPTION
**Pull request by wiz**
* Increase overall darkness
* Clean up tables and increase background contrasts
* Add background color to disabled buttons
* Remove large padding on read only fields to fix Create Offer scroll
* Darken color of dark theme grey speech bubble
* Remove negative padding from toggle switches
* Add background to password field
* Closes #4121

### CODE REVIEW

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - Tested a trade on Regtest and found this issue (see amount fields):

Bildschirmfoto 2020-06-25 um 13 38 43

**Comment by m52go** [comment]
The red field background seems to stop abruptly. Is this intentional? It looks to me like it should fill the whole field:

Screenshot from 2020-06-26 12-55-08

There is missing padding on the bottom of the screen for funding a trade (see light mode on the right for comparison):

Screenshot from 2020-06-26 12-57-06

It seems there's extra padding on this screen for taking an offer (can scroll, but there is no need to scroll):

Screenshot from 2020-06-26 12-58-08

The grey used for the bubble body is different from the grey for the bubble tip. Also (to my eyes) the blue looks out-of-place:

Screenshot from 2020-06-26 13-00-34

**Comment by pedromvpg** [comment]
Corrected all of this except the invalid fields on Create Order.

Impossible to do without changing something in the java code. 
The outer element needs to be able to detect that the element inside of it is invalid.

Group 11


Also made other small adjustments like making the theme generally darker and revised a bit of the colors on the header (they had some kind of leftover blueish gray).

Group 10

Adjustments here
https://github.com/pedromvpg/bisq/tree/dark-theme-v2

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - slider for fee is not positioned correctly

Bildschirmfoto 2020-07-03 um 21 22 26

**Comment by wiz** [comment]
@ripcurlx AFAIK that issue was already fixed, can you double check you are running the correct commit?

**Comment by m52go** [comment]
Running 82baa86b163ff23dfa7f45493b04b1b2ab557bfb...I'm seeing it correctly positioned.

dark

**Comment by ripcurlx** [comment]
Probably my bad. I checked it out clean once again and now it seems to be correct.

**Review by ripcurlx — APPROVED** [review]

**Pull request merged**
