### PR TITLE
Fix initialization ordering issue

### LINKED ISSUE #5210: Buyer opens mediation while seller is offline - NullPointerException
### Description

When buyer opens a mediation while seller is offline, a Null Pointer Exception is launched when the seller returns online after the app has been launched.

#### Version

1.5.7 (Ongoing testing)

### Steps to reproduce

1. Alice has published a buy offer
2. Bob has taken the buy offer
3. Alice requests support when Bob is offline
4. Bob returns online and the exception is launched

This has been reproduced in several tests that I have done.

#### OS

Windows 10

#### Log

```
java.lang.NullPointerException
	at bisq.core.trade.protocol.ProcessModel.getBtcWalletService(ProcessModel.java:326)
	at bisq.core.trade.Trade.getDelayedPayoutTx(Trade.java:681)
	at bisq.core.support.dispute.DisputeManager.onPeerOpenedDisputeMessage(DisputeManager.java:385)
	at bisq.core.support.dispute.mediation.MediationManager.onSupportMessage(MediationManager.java:113)
	at bisq.core.support.SupportManager.lambda$applyMessages$7(SupportManager.java:321)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.core.support.SupportManager.applyMessages(SupportManager.java:316)
	at bisq.core.support.SupportManager.tryApplyMessages(SupportManager.java:128)
	at bisq.core.support.SupportManager.lambda$new$1(SupportManager.java:79)
	at bisq.network.p2p.mailbox.MailboxMessageService.lambda$processMyMailboxItem$14(MailboxMessageService.java:474)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.mailbox.MailboxMessageService.processMyMailboxItem(MailboxMessageService.java:474)
	at bisq.network.p2p.mailbox.MailboxMessageService.handleMailboxItem(MailboxMessageService.java:464)
	at bisq.network.p2p.mailbox.MailboxMessageService.processSingleMailboxEntry(MailboxMessageService.java:386)
	at bisq.network.p2p.mailbox.MailboxMessageService.onAdded(MailboxMessageService.java:354)
	at bisq.network.p2p.mailbox.MailboxMessageService.addHashMapChangedListenerAndApply(MailboxMessageService.java:379)
	at bisq.network.p2p.mailbox.MailboxMessageService.onBootstrapped(MailboxMessageService.java:226)
	at bisq.network.p2p.P2PService.applyIsBootstrapped(P2PService.java:340)
	at bisq.network.p2p.P2PService.onUpdatedDataReceived(P2PService.java:313)
	at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:346)
	at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:204)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$6(NetworkNode.java:392)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:392)
	at bisq.network.p2p.network.Connection.lambda$onMessage$9(Connection.java:436)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.network.Connection.lambda$onMessage$10(Connection.java:436)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

#### Fix developer

If you valid this issue and think that a new dev like me could be able to find and develop a fix, I would like to have a chance to do that. If instead this is urgent, you are free to choose someone more experienced than me :)

### PR DESCRIPTION
**Pull request by ghost**
Fixes #5210 

TradeManager must be inited before MailboxMessageService.  Fixes two NPE scenarios described in #5210 

### Scenario 1.  Start up with a Mailbox message queued for delivery to DisputeManager

- This relates to the first call stack posted in #5210.
- The mailbox message service is initialized and propagates the message synchronously up to DisputeManager
- DisputeManager queries the Trade associated with the Dispute.  
- We get an NPE while attempting to access `Trade -> processModel -> provider` as the TradeManager has not yet been initialized via `initPersistedTrades`.
- The solution is to bootstrap the MailboxMessageService last so that any messages it dispatches are received by initialized services.

### Scenario 2.  Start up with a password protected wallet.

- Same pre-conditions as before, + have password protection set on Bob's wallet.
- After entering the password we get the [second NPE](https://github.com/bisq-network/bisq/issues/5210#issuecomment-783579294) described.
- The call stack shows that the initialization route located at `DomainInitialisation::initDomainServices()` is used.  It needs to call `tradeManager.onAllServicesInitialized()` before `arbitrationManager / mediationManager / refundManager` are started.

### CODE REVIEW

**Comment by ripcurlx** [comment]
@chimp1984 Could you please have a quick look at these changes, just to be sure we are not missing any hidden sideffect that the original order should have prevented. Thanks!

**Comment by ripcurlx** [comment]
I also experienced non-reproducable issues with MailboxMessages in the TraderChat. They are stuck in `Message saved in receiver's mailbox` although it seems in the log they were loaded during startup by the other peer. Unfortunately when I started debugging I wasn't able to reproduce the issue again. Looks also a little bit like a race condition. I'm looking into it in more detail right now.

**Comment by chimp1984** [comment]
I don't think we should fix it that way. The idea was to have the lower level domain completed before we initiialize the higher level domains. I will have a look for an alternative fix.

**Review by chimp1984 — DISMISSED** [review]
ACK

I tested just that use case and it fixes the problem.

The underlying problem is that the order how listeners are registered and the domains are initialized is not sufficiently clearly organized.
SupportManager registers its listener in the constructor, others in onAllServicesInitialized.

Listener are moslty held in HashSets, so the order of execution is not related to the order how they get added, which is semantically correct as listeners should not rely on order of execution, but as we see the domains would require more precise order.

It would require a larger refactoring to get those processes better defined.
I think the suggested fix carries probably low risk but all main use cases specially those involving mailbox messages should be tested well.

The decryptedMailboxMessageWithPubKeys and decryptedDirectMessageWithPubKeys in SupportManager are remaining TODOs from the past mailbox message refactoring efforts. We hold already the data in the MailboxMessageService and should rather use that as our data owner, instead of the way how we listen and keep track of the mailboxMessages in SupportManager. That would be more in line with other use cases and more clear. But all changes in that area carry quite some risk and complexity...

**Comment by ghost** [comment]
Further to @ripcurlx comment about trader chat messages, there was an issue where trader chat messages were not propagated to the GUI upon startup if a password protected wallet was used.  TraderChatManager was not processing mailbox messages when initialized via `onAllServicesInitialized`.  Added https://github.com/bisq-network/bisq/pull/5219/commits/d3b62b1a588a81c62c0728c00d2ce8512a7ae22b to fix.  The issue also happens in v1.5.5.

**Review by ripcurlx — APPROVED** [review]
ACK - tested quite a bit with mailbox messages during trading, chat and mediation and everything worked so far for me. I wasn't able to re-produce my chat mailbox issues with this PR until now. I'll keep an eye for this while continuing release testing, but I think this is save to be merged.

**Pull request merged**
