### PR TITLE
Attempt self-ping 3 times before reporting error with connectivity.

### PR DESCRIPTION
**Pull request by ghost**
Since https://github.com/bisq-network/bisq/pull/6147 was released in v1.9.1, there have been a few reports of false alarm about incoming connectivity.  One [here](https://github.com/bisq-network/bisq/pull/6147#issuecomment-1123826820) from @liisachan and a couple others from support channels via @w0000000t.  It appears that self-ping via Tor is not 100% [reliable](https://github.com/bisq-network/bisq/issues/1172).

With this PR we'll make three ping attempts, with several minutes random delay between them.  After three successive failed attempts we'll issue the inbound connectivity warning.

[In regards to the suggestion of putting a green/red indicator in the footer, I'm still considering that for a future PR].

### CODE REVIEW

**Review by ripcurlx — APPROVED** [review]
utACK

**Comment by Liisachan** [comment]
I'm not good at Java, but shouldn't `if (++failedSelfPings >= 3)` be `if (failedSelfPings++ >= 3)` ?
As it is now, it seems that in the 1st try 1>=3 is evaluated, false; in the 2nd try 2>=3 is evaluated, false; in the 3rd try, 3 >= 3 is evaluated, true. Thus self-ping will be tried only up to 2 times, not 3 times.

**Comment by Liisachan** [comment]
Then again, this is evaluated only `if (stringResult.contains("failed"))`, so it's okay? Feels a bit inelegant, though.

**Comment by ghost** [comment]
Agree that postfix increment is generally a bit easier on the eyes.  Prefix increment is necessary when used in an `if` statement.  

It runs through this number of pings (3) if they keep failing:

- send ping
- result comes back: failed
- is 1 >= 3 ? no, try again after a delay.
- send ping
- result comes back: failed
- is 2 >= 3 ? no, try again after a delay.
- send ping
- result comes back: failed
- is 3 >= 3 ? yes, warn user.

**Comment by Liisachan** [comment]
Okay, thanks :)

I'd like to ask something else, just in case... A generic Tor connection issue (not just incoming connection issue) is probably much more common. Now `checkTorFirewall` & `firewallIssueHandler` could be called after `startupTimeout` due to random delays up to about `STARTUP_TIMEOUT_MINUTES * 2`.
Is a delayed (redundant) error message from `firewallIssueHandler` automatically suppressed in case the user already gets the error message from `startupTimeout`? When Tor is not working well in the first place, if another popup says 'It appears this machine blocks incoming Tor connections', then the user might misunderstand the nature of the problem.

**Comment by ghost** [comment]
This morning at start up Bisq popped up the message that incoming connections are blocked.  

<details>
<summary>Log</summary>

    Jun-16 07:14:43.140 [TorControlParser] INFO  o.b.netlayer.tor.Tor: Hidden Service a2e...id.onion has been announced to the Tor network. 
    Jun-16 07:14:43.155 [Thread-12] INFO  b.n.p2p.network.TorNetworkNode: 
    ################################################################
    Tor hidden service published after 3443 ms. Socket=HiddenServiceSocket[addr=a2e...id.onion,port=9999]
    ################################################################ 

    Jun-16 07:14:49.008 [TorControlParser] INFO  o.b.netlayer.tor.Tor: Hidden Service a2e...id.onion has been announced to the Tor network. 

    Jun-16 07:15:17.467 [JavaFX Application Thread] INFO  b.c.a.PrivateNotificationManager: Send Ping to peer a2e...id.onion:9999, nonce=-403294440 
    Jun-16 07:15:17.469 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Processing GetDataResponse took 18228 ms 
    Jun-16 07:15:17.469 [NetworkNode:SendMessage-to-a2e...id.onion:9999] WARN  b.n.p2p.network.NetworkNode: We are sending a message to ourselves 

    Jun-16 07:18:30.683 [JavaFX Application Thread] INFO  b.c.a.PrivateNotificationManager: Send Ping to peer a2e...id.onion:9999, nonce=-1040399647 
    Jun-16 07:18:30.683 [NetworkNode:SendMessage-to-a2e...id.onion:9999] WARN  b.n.p2p.network.NetworkNode: We are sending a message to ourselves 
    Jun-16 07:18:51.391 [JavaFX Application Thread] INFO  b.c.a.PrivateNotificationManager: Sending ping to a2e.......id failed. That is expected if the peer is offline.
	    ping=Ping(nonce=-1040399647, lastRoundTripTime=0).
	    Exception=Cannot connect to hidden service 
    Jun-16 07:18:51.391 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: Sending ping to a2e.......id failed. That is expected if the peer is offline.
	    ping=Ping(nonce=-1040399647, lastRoundTripTime=0).
	    Exception=Cannot connect to hidden service 

    Jun-16 07:19:28.589 [JavaFX Application Thread] INFO  b.n.p.network.ConnectionState: We have changed the peerType from INITIAL_DATA_EXCHANGE to PEER as we have received all expected initial data responses at connection with peer Optional[sn5emzyvxuildv34n6jewfp2zeota4aq63fsl5yyilnvksezr3htveqd.onion:8000]/ad01a0b3-99c0-47d5-bc2d-29dcbbb5757d. 

    Jun-16 07:21:51.406 [JavaFX Application Thread] INFO  b.c.a.PrivateNotificationManager: Send Ping to peer a2e...id.onion:9999, nonce=1528031193 
    Jun-16 07:21:51.407 [NetworkNode:SendMessage-to-a2e...id.onion:9999] WARN  b.n.p2p.network.NetworkNode: We are sending a message to ourselves 
    Jun-16 07:22:08.139 [JavaFX Application Thread] INFO  b.c.a.PrivateNotificationManager: Sending ping to a2e.......id failed. That is expected if the peer is offline.
	    ping=Ping(nonce=1528031193, lastRoundTripTime=0).
	    Exception=Cannot connect to hidden service 
    Jun-16 07:22:08.140 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: Sending ping to a2e.......id failed. That is expected if the peer is offline.
	    ping=Ping(nonce=1528031193, lastRoundTripTime=0).
	    Exception=Cannot connect to hidden service 
	
</details>

Checked the Settings -> Network Info screen and all connections are outgoing, none incoming.  Posted an offer and attempted to take it from another Bisq client.  Result shown to the taker was "`You cannot take that offer because the maker is offline.`"  Still no incoming connections.  Bisq remains in this state, I waited 30 minutes with no change, still unable to receive incoming connections.

Closed and restarted Bisq, everything was fine.  Incoming connections work ok.

---

This indicates two things:

- The self-ping test is working correctly.  It warned of a situation where my offers cannot be taken.
- Bisq (or Tor) can start up in a state where it cannot accept any incoming connections.

**Comment by w0000000t** [comment]
Would there be a way for Bisq to "get new identity" like with tor browser or Orbot, in a way that is automatically triggered when self ping fails?

**Pull request merged**
