### PR TITLE
Small improvements/fixes

### PR DESCRIPTION
**Pull request by ManfredKarrer**

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
No idea why Travis build fails, my local build works (incl. tests). Cannot open Travis page...

**Review by ripcurlx — CHANGES_REQUESTED** [review]
bisq.core.payment.validation.AltCoinAddressValidatorTest > test FAILED

**Comment by ManfredKarrer** [comment]
Ah thanks. Hm... somehow my test run succeeded before, but now they failed as well... Fixed with latest commits.

**Review by ripcurlx — APPROVED** [review]

**Comment by ripcurlx** [comment]
utACK

**Pull request merged**
