### PR TITLE
Adopt economyFee recommendation from mempool rate provider.

### PR DESCRIPTION
**Pull request by ghost**
From https://github.com/bisq-network/proposals/issues/343#issuecomment-1147472088

image

image

    Jun-06 10:46:25.182 [Timer-17] INFO  b.p.m.p.MempoolFeeRateProvider$Fourth: Retrieved estimated mining fee of 10 sat/vB and economyFee of 1 sat/vB from mempool.bisq.services 
    Jun-06 10:46:25.182 [Timer-17] INFO  b.p.m.p.MempoolFeeRateProvider$Fourth: refresh took 247 ms. 
    Jun-06 10:46:25.390 [Timer-18] INFO  b.p.m.p.MempoolFeeRateProvider$First: Retrieved estimated mining fee of 10 sat/vB and economyFee of 2 sat/vB from mempool.space 
    Jun-06 10:46:25.390 [Timer-18] INFO  b.p.m.p.MempoolFeeRateProvider$First: refresh took 454 ms. 
    Jun-06 10:46:25.653 [Timer-20] INFO  b.p.m.p.MempoolFeeRateProvider$Second: Retrieved estimated mining fee of 10 sat/vB and economyFee of 1 sat/vB from mempool.emzy.de 
    Jun-06 10:46:25.653 [Timer-20] INFO  b.p.m.p.MempoolFeeRateProvider$Second: refresh took 717 ms. 
    Jun-06 10:46:25.662 [Timer-19] INFO  b.p.m.p.MempoolFeeRateProvider$Third: Retrieved estimated mining fee of 10 sat/vB and economyFee of 2 sat/vB from mempool.ninja 
    Jun-06 10:46:25.662 [Timer-19] INFO  b.p.m.p.MempoolFeeRateProvider$Third: refresh took 726 ms.

### CODE REVIEW

**Comment by wiz** [comment]
@jmacxx thanks for making this PR so quickly. however, are we sure that all the bugs in bisq's fee calculation have been fixed so that the 1 sat/vByte fee withdrawal doesn't cause rounding errors down to 0.999 sat/vByte as it did a few years ago - will need to test this inside bisq :)

**Comment by wiz** [comment]
another thing is that we will need to ship mempool v2.4 and have emzy and devin upgrade their mempool instances before we can merge this PR

**Comment by wiz** [comment]
here is the original 1 sat/vByte issue for context, I believe it was fixed when SegWit was added into Bitcoin but we need to test https://github.com/bisq-network/bisq/issues/3306

**Comment by wiz** [comment]
ok @emzy @devinbileck can you please upgrade to mempool v2.4.0 so we can proceed with testing this PR 
https://github.com/mempool/mempool/releases/tag/v2.4.0

**Comment by Emzy** [comment]
> ok @Emzy @devinbileck can you please upgrade to mempool v2.4.0 so we can proceed with testing this PR https://github.com/mempool/mempool/releases/tag/v2.4.0

Done.

**Comment by devinbileck** [comment]
mempool.bisq.services has been upgraded to 2.4.0

**Comment by wiz** [comment]
ok so out of all the mempool nodes in https://github.com/bisq-network/bisq/blob/master/pricenode/src/main/resources/application.properties
we can now see that `economyFee` is provided by:
https://mempool.space/api/v1/fees/recommended
https://mempool.emzy.de/api/v1/fees/recommended
https://mempool.ninja/api/v1/fees/recommended
https://mempool.bisq.services/api/v1/fees/recommended

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
