### PR TITLE
Improve warning message regarding insufficient BSQ

### LINKED ISSUE #4439: WARNING ABOUT 5.46 BSQ FLOOR
### Description

Since 1.3.7, PR #4383 added a 5.46 BSQ floor amount to prevent dust errors. The problem though is the user isn't  educated about that, it only shows a insufficient BSQ warning, which worries those that have otherwise enough BSQ.
Please, just add a explanation about the floor amount when the user tries to spend it.

#### Version

1.3.7

### Steps to reproduce

Trying to spend BSQs when you have less than 5.46 

### Expected behaviour

Warning explaining you are not allowed to spend that coins.

### Actual behaviour

Just "insufficient funds" warning

### PR DESCRIPTION
**Pull request by ghost**
Improve the warning message to explain why BSQ balances close to 5.46 are not sufficient to be used for trade fees, due to dust limits in the Bitcoin protocol.

Fixes #4439

image

### CODE REVIEW

**Comment by ghost** [comment]
Close / Open to try the Travis build again.  For some unknown reason it has been failing.

**Comment by ripcurlx** [comment]
@m52go Could you please proof read this and I'm happy to merge it.

**Comment by m52go** [comment]
ACK - looks like the same text I suggested in https://github.com/bisq-network/bisq/issues/4439#issuecomment-681242910.

**Review by ripcurlx — APPROVED** [review]
utACK based on https://github.com/bisq-network/bisq/pull/4440#issuecomment-682820567

**Pull request merged**
