### PR TITLE
List AureusNummusGold (ANG)

### PR DESCRIPTION
**Pull request by AureusNummusGold**
Official project URL: https://an.gold
Official block explorer URL: https://etherscan.io/token/0x130914E1B240a7F4c5D460B7d3a2Fd3846b576fa

### CODE REVIEW

**Comment by oleksandr-skoryi** [comment]
Does anybody know, why travis still checking something?

**Comment by AureusNummusGold** [comment]
Travis stuck, recreate pull request 
https://github.com/bisq-network/bisq/pull/4191

**Comment by merlyn22** [comment]
Please list Aureus Nummus Gold ANG 🙏

**Comment by merlyn22** [comment]
Please list Aureus Nummus Gold ANG 🙏

**Pull request closed without merging**
