### PR TITLE
List Genix (GENIX)

### PR DESCRIPTION
**Pull request by farsider350**
List Genix (GENIX)
Author: farsider350 farsider350@protonmail.com
Date: Thu April 11 22:00 GMT+1000

List Genix (GENIX)

Official project URL: https://genix.cx
Official block explorer URL: http://explorer.genix.cx

### CODE REVIEW

**Review by blabno — CHANGES_REQUESTED** [review]
NACK apply Bisq codestyle

**Comment by farsider350** [comment]
Not sure I understand. This is exactly the same way I've done the PRs in the past.
Codestyle? I've checked a lot of PRs since you requested this without finding any sort of differences to this one.

**Comment by blabno** [comment]
Codestyle is here: https://github.com/bisq-network/bisq/tree/master/.idea/codeStyles

**Comment by ripcurlx** [comment]
@farsider350 Closing PR because of inactivity. Feel free to re-open when PR requirements are fulfilled.

**Pull request closed without merging**
