### PR TITLE
List Help The Homeless Coin (HTH)

### PR DESCRIPTION
**Pull request by MichaelHDesigns**
Author: Michael Howlett <devilking6105@gmail.com>
Date:   Thurs Nov 15 19:04:34 2018 -0800

    List Help The Homeless Coin (HTH)

### CODE REVIEW

**Comment by MichaelHDesigns** [comment]
Author: Michael Howlett devilking6105@gmail.com
Date: Thurs Nov 15 19:04:34 2018 -0800

List Help The Homeless Coin (HTH)

**Comment by blabno** [comment]
Resolve conflicts. Keep it in a single commit.

**Comment by CaveSpectre11** [comment]
NACK - bisq.asset.Asset out of synch with a Nov 8th commit

**Comment by ManfredKarrer** [comment]
Close because of inactivity.

**Pull request closed without merging**
