### PR TITLE
Validate offer <-> payment-acct in createoffer

### PR DESCRIPTION
**Pull request by ghubstan**
This change prohibits creation of new offers with incompatible payment accounts with the api.

- `PaymentAccountUtil` 
  Renamed isAnyTakerPaymentAccountValidForOffer -> isAnyPaymentAccountValidForOffer.
  Renamed isTakerPaymentAccountValidForOffer -> isPaymentAccountValidForOffer.
  Deleted commented code.

- `PaymentAccounts`: Adjusted to PaymentAccountUtil method name changes.

- `OfferFilter`: Adjusted to PaymentAccountUtil method name changes.

- `OfferBookViewModelTest`: Adjusted to PaymentAccountUtil method name changes.

- Added `CoreOffersService#verifyPaymentAccountIsValidForOffer`

- `ValidateCreateOfferTest`, `OfferTest`: Added test cases.

PR https://github.com/bisq-network/bisq/pull/5274 should be reviewed & merged before this one.

### CODE REVIEW

**Comment by ghubstan** [comment]
Issue https://github.com/bisq-network/bisq/issues/5281 should be resolved.

**Review by sqrrm — DISMISSED** [review]
utACK

**Review by sqrrm — APPROVED** [review]
utACK

**Comment by ghubstan** [comment]
Closes https://github.com/bisq-network/bisq/issues/5281

**Pull request merged**
