### PR TITLE
List Traid (TRAID)

### PR DESCRIPTION
**Pull request by TraidPlatform**
- Official project URL: https://github.com/TraidPlatform/traidcoin
- Official block explorer URL: https://explorer.traid.tv/

### CODE REVIEW

**Comment by TraidPlatform** [comment]
Closed and  reopened to trigger CI.

**Comment by blabno** [comment]
@TraidPlatform please rebase against master and resolve conflicts.

**Comment by TraidPlatform** [comment]
@blabno done, thanks.

**Review by blabno — CHANGES_REQUESTED** [review]
NACK

Squash and rebase against master.
What does that mean https://icobench.com/ico/traid, are you involved in ICO?

**Comment by ManfredKarrer** [comment]
Traid is an ICO coin. Bisq does not list ICO coins.

**Pull request closed without merging**
