### PR TITLE
List Neos (NEOS)

### PR DESCRIPTION
**Pull request by BoubonicNugz**
- Re-Submit
- Previous PR: https://github.com/bisq-network/bisq-assets/pull/117

Project Information:
- Official project URL: https://www.neos.sh
- Official block explorer URL: https://chainz.cryptoid.info/neos/
- Official Github Source:  https://github.com/neoscoin/neos-core/

### CODE REVIEW

**Review by blabno — APPROVED** [review]
ACK

**Comment by blabno** [comment]
@BoubonicNugz please edit your comment and add project url and block explorer

**Comment by ManfredKarrer** [comment]
NACK. Will wait until the project url and block explorer are added

**Comment by BoubonicNugz** [comment]
Updated with project information!

**Comment by buzztiaan** [comment]
is there need for a new pull request to rename the tickersymbol? nothing else changed

**Pull request merged**
