### PR TITLE
Add chart series for total trade fees

### PR DESCRIPTION
**Pull request by chimp1984**
Implements https://github.com/bisq-network/bisq/issues/6203

### CODE REVIEW

**Comment by chimp1984** [comment]
@xyzmaker123 @jmacxx Anyone time for a review?

**Comment by ghost** [comment]
@chimp1984 Sure, I'm gonna review it within 30-60 minutes.

**Review by ghost — APPROVED** [review]
ACK
- tested if chart works in a few edge case scenarios
- roughly reviewed code changes
- I didn't fully analysed data validity

NOTE: Codacy fails

**Comment by ripcurlx** [comment]
> ACK
> 
> * tested if chart works in a few edge case scenarios
> * roughly reviewed code changes
> * I didn't fully analysed data validity
> 
> NOTE: Codacy fails

Ignored this specific remark, as the whole file doesn't apply it ATM.

**Comment by bisq-github-admin-3** [comment]
Merging as Codacy is not accepting the exclusion of a rule.

**Pull request merged**
