### PR TITLE
Use LegacyAddress instead of Address for BSQ

### PR DESCRIPTION
**Pull request by oscarguindzberg**
Use LegacyAddress for BSQ related code to make sure we don't accept a segwit address for BSQ by accident.

### CODE REVIEW

**Review by chimp1984 — DISMISSED** [review]
utACK

**Review by sqrrm — DISMISSED** [review]

**Comment by sqrrm** [comment]
@oscarguindzberg Could you sign the commit? I'm unable to merge otherwise.

**Comment by oscarguindzberg** [comment]
> @oscarguindzberg Could you sign the commit? I'm unable to merge otherwise.

@sqrrm sorry I forgot to sign. I just signed it.

**Review by sqrrm — APPROVED** [review]
utACK

**Pull request merged**
