### PR TITLE
Rename "Move funds to Bisq wallet" -> "Keep funds in Bisq wallet" to …

### PR DESCRIPTION
**Pull request by ghost**
Just renaming a text according to the proposal from the issue.

Fixies: #4255

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Just change the text that is displayed to the user.  No need to change the code tag.  One line, one file change and no horrendous ripple effects.

**Comment by ghost** [comment]
@jmacxx I understand your point, but I think the consistency is good and it helps to better communicate via the code. I also acknowledge it is a small thing, but still, the consistency of the code with the way how its meant for the user helps to communicate the reason why its there.

**Comment by sqrrm** [comment]
@petrhejna No need to change the specific language files, only displayStrings.properties needs to be changed. The other ones are handled by the translation team and pulled at release time.

I agree with @jmacxx here, better not change the code tag.

**Comment by ghost** [comment]
Closing in favor of https://github.com/bisq-network/bisq/pull/4313

**Pull request closed without merging**
