### PR TITLE
List WrkzCoin (WRKZ)

### PR DESCRIPTION
**Pull request by wrkzdev**
* Official project URL: https://www.wrkz.work/
* Official block explorer URL: https://myexplorer.wrkz.work/

### CODE REVIEW

**Comment by blabno** [comment]
@wrkzdev please rebase against master and resolve conflicts.

**Review by blabno — CHANGES_REQUESTED** [review]
NACK no PRs from master

**Comment by wrkzdev** [comment]
@blabno Please let me know if I need to make a separated PR or is it OK?

**Comment by blabno** [comment]
Do not merge master. Rebase and squash into single commit.

**Pull request closed without merging**
