### PR TITLE
Add coin VARIUS

### PR DESCRIPTION
**Pull request by zero24x**
Official project URL: http://variuscoin.com & https://github.com/zero24x/varius/
Official block explorer: https://www.coinexplorer.net/varius

Link to random transaction (1): https://www.coinexplorer.net/VARIUS/transaction/0fe1710c6253bce272be19de08609aabf026a739bfd9d7572a0615b472e19d02
Link to random transaction (2): https://www.coinexplorer.net/VARIUS/transaction/26dcdc87ea75a366b6a43701d61e5e9b1ddf0b5a4c73245663513432100c8278

### CODE REVIEW

**Review by blabno — COMMENTED** [review]
Code looks good, but the website is done in some website builder. Missing whitepaper. Daily volume 4$.

**Comment by zero24x** [comment]
@blabno : please accept us, yes, we are a smaller project with a builder website

we already invested developer time to make the pullrequest here and we can advertise in our discord so it helps BISQ exchange to get more known!

also we thought BISQ is one of the exchanges where even smaller project can list without paying thousands of dollars! 

thanks a lot, and good project you have here!

@freimair @ManfredKarrer @wiz  **please your input on this topic also, thanks**

**Review by blabno — APPROVED** [review]
ACK for code, the rest is to be decided by maintainers.

**Comment by ripcurlx** [comment]
> ACK for code, the rest is to be decided by maintainers.

If it fulfills our requirements I don't think we should invest more time in vetting. With the DAO non-traded coins will be automatically removed anyways.

**Comment by zero24x** [comment]
thanks @ripcurlx a lot for adding us, great!

**Pull request merged**
