### PR TITLE
List AureusNummusGold (ANG)

### PR DESCRIPTION
**Pull request by AureusNummusGold**
Official project URL: https://an.gold
Official block explorer URL: https://etherscan.io/token/0x130914E1B240a7F4c5D460B7d3a2Fd3846b576fa

### CODE REVIEW

**Comment by huey735** [comment]
Asset listing was put on hold - https://github.com/bisq-network/proposals/issues/166

**Review by torralba27 — COMMENTED** [review]
This project needs to be listed. Its the best time for this kind of crytocurrency that is backed by real asset.

**Comment by torralba27** [comment]
List the project on Bisq, it's the perfect time.

**Comment by whiz1234** [comment]
This is one of the very few projects with good Team and backed by Gold. It needs to be listed on here, so a lot of people can see it's potential and benefit from the project.

**Review by whiz1234 — APPROVED** [review]

**Comment by divana0022** [comment]
Listing in exchange

**Comment by kitkit19** [comment]
Very good project time to list.

**Comment by kashyf** [comment]
This project has the potential to strengthen the line between traditional gold and crypto markets. We will be back again to the gold standard days, with digital asset which is backing physical gold.

**Comment by Amit123456789-mithi** [comment]
Nice project 👉💯👌🙏🙏

**Comment by Cindy-CM** [comment]
Check the project guys, huge effort and great team behind this. One of the promising project this year. I got interested with Aureus because it is a digital currency and asset which is backed up by physical gold. Check their website to learn more guys.

**Comment by harry57** [comment]
Really amazing Project and they are performed really best and payment as a gold will bring huge audience here

**Comment by Emon321** [comment]
Good project

**Comment by Hazel-O** [comment]
Great project guys, it is worth sharing, can't wait to list ANG on exchanges for me to buy more. 

Keep up the good work guys. .

**Comment by dessyhodin97** [comment]
This project Aureus Nummus Gold is a great project which deserves a listing on your exchange 👍. Hope it gets listed

**Comment by siner9586** [comment]
> Official project URL: https://an.gold
> Official block explorer URL: https://etherscan.io/token/0x130914E1B240a7F4c5D460B7d3a2Fd3846b576fa

Nice

**Comment by zoe0408** [comment]
> Official project URL: https://an.gold
> Official block explorer URL: https://etherscan.io/token/0x130914E1B240a7F4c5D460B7d3a2Fd3846b576fa

This project needs to be in the list 😇 I support it's listing..

**Comment by naitzirhczero** [comment]
Great project backed by a dynamic team.

**Comment by manumpak1995** [comment]
AureusNummusGold, very good Project, time to list now, $ANG

**Comment by ismailjaan8565** [comment]
AureusNummusGold, very good Project, time to list now, $ANG

**Review by torralba27 — COMMENTED** [review]
Aureus Nummus Gold or ANG token have FINCEN and FINTRAC approval and registration. No outside investors, all in-house self-funded so I believe it is the best time to list this in Bisq.

**Comment by AureusN** [comment]
> Asset listing was put on hold - [bisq-network/proposals#166](https://github.com/bisq-network/proposals/issues/166)

Good morning, this is Jacob from the Aureus Nummus founder team. On behalf of the Aureus Nummus Gold community I humbly request a  positive review from the Bisq community in order to get the ANG token up and trading. Our committment, 1 BTC or the equivalent in fiat for successful listing and 150,000 USD dedicated to market making, as we of course recognize the need for turnover and volume once the trading starts. Please email to jtf@an.gold or visit www.an.gold.
Thank you.
Jacob J. DeMedici, Ph.D.
Quantum Computing Labs Corp

**Comment by AureusN** [comment]
> Official project URL: https://an.gold
> Official block explorer URL: https://etherscan.io/token/0x130914E1B240a7F4c5D460B7d3a2Fd3846b576fa

Good morning, this is Jacob from the Aureus Nummus founder team. On behalf of the Aureus Nummus Gold community I humbly request a positive review from the Bisq community in order to get the ANG token up and trading. Our committment, 1 BTC or the equivalent in fiat for successful listing and 150,000 USD dedicated to market making, as we of course recognize the need for turnover and volume once the trading starts. Please email to jtf@an.gold or visit www.an.gold.
Thank you.
Jacob J. DeMedici, Ph.D.
Quantum Computing Labs Corp

**Review by wiz — COMMENTED** [review]
Bisq has a no scam policy and this project's website looks to me like an obvious premine scam, offering "tokens redeemable for gold" with a website featuring yachts and typical scammy content. The sockpuppet accounts that signed up on GitHub just to voice their support in the comments above also do not inspire confidence about the ethics of the project.

Some quick Google searches and reading their BCT forum thread seems to indicate there is zero activity for this "project" except for doing token airdrops, which if their claim about the tokens being redeemable for gold is true, why would they give away free gold?

My favorite part however, is the @whiz1234 account that signed up on GitHub on May 23 just to "approve" this PR - nice try lol.

NACK

**Comment by AureusN** [comment]
> Bisq has a no scam policy and this project's website looks to me like an obvious premine scam, offering "tokens redeemable for gold" with a website featuring yachts and typical scammy content. The sockpuppet accounts that signed up on GitHub just to voice their support in the comments above also do not inspire confidence about the ethics of the project.
> 
> Some quick Google searches and reading their BCT forum thread seems to indicate there is zero activity for this "project" except for doing token airdrops, which if their claim about the tokens being redeemable for gold is true, why would they give away free gold?
> 
> My favorite part however, is the @whiz1234 account that signed up on GitHub on May 23 just to "approve" this PR - nice try lol.
> 
> NACK


QUITE THE HATE REVIEW ISN'T IT MY DEAR?

ALLEGING FRAUD WITHOUT ANY EVIDENCE WHATSOEVER IS REALLY AMAZING. IF YOU WOULDN'T HIDE BEHIND AN ANONYMOUS OUR LEGAL COUNSEL WOULD GIVE YOU AN OPPORTUNITY TO PROVE YOUR SLANDERING IN COURT WHERE YOU WOULD HAVE TO EITHER PUT UP OR SHUT UP AND BEAR THE CONSEQUENCES FOR YOUR USELESS HATE COMMENTS.

THE STANDARD OF EVIDENCE IS NOT ZERO.  IF YOU WANT TO ALLGE SOMETHING PLEASE DO SO WITH THE AUTHORITIES.

WE ARE A FINTRAC AND FINCEN REGISTERED COMPANY BASED IN ONSHORE JURISDICTIONS WITH VERIFIABLE PUBLIC CORPORATE BOOKS AND WE DO TAKE OUR BUSINESS VERY SERIOUSLY.

WE ARE A NEW COMPANY AND NEW TO THE MARKET AS STATED VERY CLEARLY ON OUR WEBSITE AND WHAT EVERYONE DOES IN OUR POSITION IS BUILDING A BASIC AUDIENCE BEFORE LOOKING FOR SUITABLE EXCHANGES.

APPROACHING EXCHANGES WITH ZERO AUDIENCE ISNT APPRECIATED AND NOW WITH A BASI AUDIENCE IT ISNT APPRECIATED EITHER.

PEOPLE LIKE YOU DO A DISSERVICE TO EXCHANGES AS BISQ BECAUSE YOU SHOW TO THE WHOLE WORLD THAT LISTING CANDIDATES ARE TROLLED AND NOT THOROUGHLY EVALUATED BASED ON FACTS. 

RPOVE THAT YOUR STANDARDS ARE HIGHER THAN THE USUAL INTERNET TROLLS. SHOW YOUR FACE, YOUR REAL NAME AND YOUR ADDRESS AND WE SHALL MEET IN COURT.

YOUR ANTICS PUT ALSO BISQ AT LEGAL RISK BECAUSE I CAN ASSURE YOU THAT IN OUR WOLRD WE RESPOND WITH LEGAL ACTION TO SLANDERING.

**Comment by csjones** [comment]
> > Bisq has a no scam policy and this project's website looks to me like an obvious premine scam, offering "tokens redeemable for gold" with a website featuring yachts and typical scammy content. The sockpuppet accounts that signed up on GitHub just to voice their support in the comments above also do not inspire confidence about the ethics of the project.
> 
> > 
> 
> > Some quick Google searches and reading their BCT forum thread seems to indicate there is zero activity for this "project" except for doing token airdrops, which if their claim about the tokens being redeemable for gold is true, why would they give away free gold?
> 
> > 
> 
> > My favorite part however, is the @whiz1234 account that signed up on GitHub on May 23 just to "approve" this PR - nice try lol.
> 
> > 
> 
> > NACK
> 
> 
> 
> 
> 
> QUITE THE HATE REVIEW ISN'T IT MY DEAR?
> 
> 
> 
> ALLEGING FRAUD WITHOUT ANY EVIDENCE WHATSOEVER IS REALLY AMAZING. IF YOU WOULDN'T HIDE BEHIND AN ANONYMOUS OUR LEGAL COUNSEL WOULD GIVE YOU AN OPPORTUNITY TO PROVE YOUR SLANDERING IN COURT WHERE YOU WOULD HAVE TO EITHER PUT UP OR SHUT UP AND BEAR THE CONSEQUENCES FOR YOUR USELESS HATE COMMENTS.
> 
> 
> 
> THE STANDARD OF EVIDENCE IS NOT ZERO.  IF YOU WANT TO ALLGE SOMETHING PLEASE DO SO WITH THE AUTHORITIES.
> 
> 
> 
> WE ARE A FINTRAC AND FINCEN REGISTERED COMPANY BASED IN ONSHORE JURISDICTIONS WITH VERIFIABLE PUBLIC CORPORATE BOOKS AND WE DO TAKE OUR BUSINESS VERY SERIOUSLY.
> 
> 
> 
> WE ARE A NEW COMPANY AND NEW TO THE MARKET AS STATED VERY CLEARLY ON OUR WEBSITE AND WHAT EVERYONE DOES IN OUR POSITION IS BUILDING A BASIC AUDIENCE BEFORE LOOKING FOR SUITABLE EXCHANGES.
> 
> 
> 
> APPROACHING EXCHANGES WITH ZERO AUDIENCE ISNT APPRECIATED AND NOW WITH A BASI AUDIENCE IT ISNT APPRECIATED EITHER.
> 
> 
> 
> PEOPLE LIKE YOU DO A DISSERVICE TO EXCHANGES AS BISQ BECAUSE YOU SHOW TO THE WHOLE WORLD THAT LISTING CANDIDATES ARE TROLLED AND NOT THOROUGHLY EVALUATED BASED ON FACTS. 
> 
> 
> 
> RPOVE THAT YOUR STANDARDS ARE HIGHER THAN THE USUAL INTERNET TROLLS. SHOW YOUR FACE, YOUR REAL NAME AND YOUR ADDRESS AND WE SHALL MEET IN COURT.
> 
> 
> 
> YOUR ANTICS PUT ALSO BISQ AT LEGAL RISK BECAUSE I CAN ASSURE YOU THAT IN OUR WOLRD WE RESPOND WITH LEGAL ACTION TO SLANDERING.
> 
> 

If there was any doubt before, a caps lock response confirms this is definitely a scam.

**Pull request closed without merging**
