### PR TITLE
Refactor detectMultipleHolderNames for efficient use of RAM.

### LINKED ISSUE #7006: Mediation ticket opening failed due to OOM at detectMultipleHolderNames
An `OutOfMemory` exception happened here, when converting a map to string.

https://github.com/bisq-network/bisq/blob/4d4c9e3186a858e6295d6c938f28ba56109b3f36/core/src/main/java/bisq/core/support/dispute/agent/MultipleHolderNameDetection.java#L148-L149

```
    ERROR b.c.s.CommonSetup: OutOfMemoryError occurred. We shut down. java.lang.OutOfMemoryError: Java heap space
	    at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	    at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	    at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
	    at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
	    at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	    at java.base/java.util.AbstractMap.toString(AbstractMap.java:556)
	    at bisq.core.support.dispute.agent.MultipleHolderNameDetection.detectMultipleHolderNames(MultipleHolderNameDetection.java:149)
	    at bisq.core.support.dispute.agent.MultipleHolderNameDetection.lambda$new$1(MultipleHolderNameDetection.java:138)
	    at bisq.core.support.dispute.agent.MultipleHolderNameDetection$$Lambda$1691/0x0000000100a02040.onChanged(Unknown Source)
	    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
	    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:211)
	    at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:162)
	    at java.base/java.util.AbstractList.add(AbstractList.java:111)
	    at bisq.common.proto.persistable.PersistableList.add(PersistableList.java:51)
	    at bisq.core.support.dispute.DisputeManager.onOpenNewDisputeMessage(DisputeManager.java:407)
	    at bisq.core.support.dispute.mediation.MediationManager.onSupportMessage(MediationManager.java:119)
```	

---

### Possible mitigations:

- Trap the exception so as not to mess up the opening of a mediation ticket pair.
- Refactor the method to be less memory intensive.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #7006 (Out Of Memory Exception thrown)

Purpose of the method is to (a) maintain a list of flagged disputes, and (b) notify listeners if new items were added.
Using `toString()` on a large map of String to List<Dispute> caused an OOM exception.
For (b) notifying listeners it is only the change in flagged dispute count that is relevant (so the UI can display an alert icon). The same effect can be obtained by counting identified records.

<details>
<summary>Verification</summary>

User opens a dispute using a payment account that has a different holder name than in a previous dispute.  Mediator clicks on the alert icon.

image

</details>

### CODE REVIEW

**Review by alvasw — COMMENTED** [review]
Concept ACK

Good catch! The `toString()` comparison is indeed bad.

I saw that you're using a `AtomicLong`s to count the item. Does this imply that `detectMultipleHolderNames()` is called from multiple threads? If that's the case `suspiciousDisputesByTraderMap` shouldn't be a `HashMap`.

Otherwise the following change is simpler and faster:
```diff
diff --git a/core/src/main/java/bisq/core/support/dispute/agent/MultipleHolderNameDetection.java b/core/src/main/java/bisq/core/support/dispute/agent/MultipleHolderNameDetection.java
index 1be96332ef..09c722eed5 100644
--- a/core/src/main/java/bisq/core/support/dispute/agent/MultipleHolderNameDetection.java
+++ b/core/src/main/java/bisq/core/support/dispute/agent/MultipleHolderNameDetection.java
@@ -146,7 +146,10 @@ public class MultipleHolderNameDetection {
     ///////////////////////////////////////////////////////////////////////////////////////////
 
     public void detectMultipleHolderNames() {
-        String previous = suspiciousDisputesByTraderMap.toString();
+        int previous = suspiciousDisputesByTraderMap.values().stream()
+                .mapToInt(List::size)
+                .sum();
+
         getAllDisputesByTraderMap().forEach((key, value) -> {
             Set<String> userNames = value.stream()
                     .map(dispute -> {
@@ -161,8 +164,12 @@ public class MultipleHolderNameDetection {
                 suspiciousDisputesByTraderMap.put(key, value);
             }
         });
-        String updated = suspiciousDisputesByTraderMap.toString();
-        if (!previous.equals(updated)) {
+
+        int updated = suspiciousDisputesByTraderMap.values().stream()
+                .mapToInt(List::size)
+                .sum();
+
+        if (previous != updated) {
             listeners.forEach(Listener::onSuspiciousDisputeDetected);
         }
     }
```

**Comment by ghost** [comment]
Review change to use `int` applied.

**Review by alvasw — APPROVED** [review]
utACK

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
