### PR TITLE
Update dependency verification for changes in pricenode

### PR DESCRIPTION
**Pull request by ripcurlx**

### CODE REVIEW

**Comment by ripcurlx** [comment]
I checked the dependencies added and they are all related to the changes in the pricenode module using the latest `org.knowm.xchange` library.

@jmacxx Could you please double check if something seems problematic in the dependencies added?

@cbeams Do you have an idea why the dependency verification failed visually in the build, but the build succeed anyways?

```
./gradlew build

> Configure project :
Project :common => no module-info.java found
Project :p2p => no module-info.java found
Project :core => no module-info.java found
Project :desktop => no module-info.java found
Project :monitor => no module-info.java found
Pricenode: Skipping spot provider tests
Dependency verification failed for configuration ':daonode:runtimeClasspath'
2 artifacts failed verification:
  - protobuf-java-util-3.19.1.jar (com.google.protobuf:protobuf-java-util:3.19.1) from repository MavenRepo
  - protobuf-java-util-3.19.1.pom (com.google.protobuf:protobuf-java-util:3.19.1) from repository MavenRepo
If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/7.3.3/userguide/dependency_verification.html#sec:troubleshooting-verification

Open this report for more details: file:///Users/christoph/Documents/Workspaces.nosync/Java/mono-repo/bisq/build/reports/dependency-verification/at-1654759887396/dependency-verification-report.html

> Task :proto:extractIncludeProto UP-TO-DATE
> Task :proto:extractProto UP-TO-DATE
> Task :proto:generateProto UP-TO-DATE
> Task :proto:compileJava UP-TO-DATE
> Task :proto:processResources UP-TO-DATE
> Task :proto:classes UP-TO-DATE
> Task :proto:jar UP-TO-DATE
> Task :cli:compileJava UP-TO-DATE
> Task :cli:processResources UP-TO-DATE
> Task :cli:classes UP-TO-DATE
> Task :cli:jar UP-TO-DATE
> Task :common:compileJava UP-TO-DATE
> Task :common:processResources NO-SOURCE
> Task :common:classes UP-TO-DATE
> Task :common:jar UP-TO-DATE
> Task :assets:compileJava UP-TO-DATE
> Task :assets:processResources UP-TO-DATE
> Task :assets:classes UP-TO-DATE
> Task :assets:jar UP-TO-DATE
> Task :p2p:compileJava UP-TO-DATE
> Task :p2p:processResources UP-TO-DATE
> Task :p2p:classes UP-TO-DATE
> Task :p2p:jar UP-TO-DATE
> Task :core:compileJava UP-TO-DATE
> Task :core:processResources UP-TO-DATE
> Task :core:classes UP-TO-DATE
> Task :core:jar UP-TO-DATE
> Task :daemon:compileJava UP-TO-DATE
> Task :daemon:processResources UP-TO-DATE
> Task :daemon:classes UP-TO-DATE
> Task :daemon:jar UP-TO-DATE
> Task :desktop:compileJava UP-TO-DATE
> Task :desktop:processResources UP-TO-DATE
> Task :desktop:classes UP-TO-DATE
> Task :desktop:jar UP-TO-DATE
> Task :seednode:compileJava UP-TO-DATE
> Task :seednode:processResources UP-TO-DATE
> Task :seednode:classes UP-TO-DATE
> Task :seednode:jar UP-TO-DATE
> Task :apitest:compileJava UP-TO-DATE
> Task :apitest:processResources UP-TO-DATE
> Task :apitest:classes UP-TO-DATE
> Task :apitest:jar UP-TO-DATE
> Task :apitest:startScripts UP-TO-DATE
> Task :apitest:distTar UP-TO-DATE
> Task :apitest:distZip SKIPPED
> Task :apitest:assemble UP-TO-DATE
> Task :apitest:compileTestJava UP-TO-DATE
> Task :apitest:processTestResources UP-TO-DATE
> Task :apitest:testClasses UP-TO-DATE
> Task :apitest:test SKIPPED
> Task :apitest:check UP-TO-DATE
> Task :apitest:installDist UP-TO-DATE
> Task :apitest:build UP-TO-DATE
> Task :assets:assemble UP-TO-DATE
> Task :assets:compileTestJava UP-TO-DATE
> Task :assets:processTestResources NO-SOURCE
> Task :assets:testClasses UP-TO-DATE
> Task :assets:test UP-TO-DATE
> Task :assets:check UP-TO-DATE
> Task :assets:build UP-TO-DATE
> Task :cli:startScripts UP-TO-DATE
> Task :cli:distTar UP-TO-DATE
> Task :cli:distZip SKIPPED
> Task :cli:assemble UP-TO-DATE
> Task :cli:compileTestJava UP-TO-DATE
> Task :cli:processTestResources NO-SOURCE
> Task :cli:testClasses UP-TO-DATE
> Task :cli:test UP-TO-DATE
> Task :cli:check UP-TO-DATE
> Task :cli:installDist UP-TO-DATE
> Task :cli:build UP-TO-DATE
> Task :common:assemble UP-TO-DATE
> Task :common:compileTestJava UP-TO-DATE
> Task :common:processTestResources NO-SOURCE
> Task :common:testClasses UP-TO-DATE
> Task :common:test UP-TO-DATE
> Task :common:check UP-TO-DATE
> Task :common:build UP-TO-DATE
> Task :core:assemble UP-TO-DATE
> Task :core:compileTestJava UP-TO-DATE
> Task :core:processTestResources UP-TO-DATE
> Task :core:testClasses UP-TO-DATE
> Task :core:test UP-TO-DATE
> Task :core:check UP-TO-DATE
> Task :core:build UP-TO-DATE
> Task :daemon:startScripts UP-TO-DATE
> Task :daemon:distTar UP-TO-DATE
> Task :daemon:distZip SKIPPED
> Task :daemon:assemble UP-TO-DATE
> Task :daemon:compileTestJava UP-TO-DATE
> Task :daemon:processTestResources NO-SOURCE
> Task :daemon:testClasses UP-TO-DATE
> Task :daemon:test UP-TO-DATE
> Task :daemon:check UP-TO-DATE
> Task :daemon:installDist UP-TO-DATE
> Task :daemon:build UP-TO-DATE
> Task :daonode:compileJava UP-TO-DATE
> Task :daonode:processResources UP-TO-DATE
> Task :daonode:classes UP-TO-DATE
> Task :daonode:jar UP-TO-DATE
> Task :daonode:startScripts UP-TO-DATE
> Task :daonode:distTar UP-TO-DATE
> Task :daonode:distZip SKIPPED
> Task :daonode:shadowJar UP-TO-DATE
> Task :daonode:startShadowScripts UP-TO-DATE
> Task :daonode:shadowDistTar UP-TO-DATE
> Task :daonode:shadowDistZip UP-TO-DATE
> Task :daonode:assemble UP-TO-DATE
> Task :daonode:compileTestJava NO-SOURCE
> Task :daonode:processTestResources UP-TO-DATE
> Task :daonode:testClasses UP-TO-DATE
> Task :daonode:test NO-SOURCE
> Task :daonode:check UP-TO-DATE
> Task :daonode:installDist UP-TO-DATE
> Task :daonode:build UP-TO-DATE
> Task :desktop:startScripts UP-TO-DATE
> Task :desktop:distTar UP-TO-DATE
> Task :desktop:distZip SKIPPED
> Task :desktop:shadowJar UP-TO-DATE
> Task :desktop:startShadowScripts UP-TO-DATE
> Task :desktop:shadowDistTar UP-TO-DATE
> Task :desktop:shadowDistZip UP-TO-DATE
> Task :desktop:assemble UP-TO-DATE
> Task :desktop:compileTestJava UP-TO-DATE
> Task :desktop:processTestResources UP-TO-DATE
> Task :desktop:testClasses UP-TO-DATE
> Task :desktop:test UP-TO-DATE
> Task :desktop:check UP-TO-DATE
> Task :desktop:installDist UP-TO-DATE
> Task :desktop:build UP-TO-DATE
> Task :inventory:compileJava UP-TO-DATE
> Task :inventory:processResources UP-TO-DATE
> Task :inventory:classes UP-TO-DATE
> Task :inventory:jar UP-TO-DATE
> Task :inventory:startScripts UP-TO-DATE
> Task :inventory:distTar UP-TO-DATE
> Task :inventory:distZip SKIPPED
> Task :inventory:shadowJar UP-TO-DATE
> Task :inventory:startShadowScripts UP-TO-DATE
> Task :inventory:shadowDistTar UP-TO-DATE
> Task :inventory:shadowDistZip UP-TO-DATE
> Task :inventory:assemble UP-TO-DATE
> Task :inventory:compileTestJava NO-SOURCE
> Task :inventory:processTestResources NO-SOURCE
> Task :inventory:testClasses UP-TO-DATE
> Task :inventory:test NO-SOURCE
> Task :inventory:check UP-TO-DATE
> Task :inventory:installDist UP-TO-DATE
> Task :inventory:build UP-TO-DATE
> Task :monitor:compileJava UP-TO-DATE
> Task :monitor:processResources UP-TO-DATE
> Task :monitor:classes UP-TO-DATE
> Task :monitor:jar UP-TO-DATE
> Task :monitor:startScripts UP-TO-DATE
> Task :monitor:distTar UP-TO-DATE
> Task :monitor:distZip SKIPPED
> Task :monitor:assemble UP-TO-DATE
> Task :monitor:compileTestJava UP-TO-DATE
> Task :monitor:processTestResources NO-SOURCE
> Task :monitor:testClasses UP-TO-DATE
> Task :monitor:test UP-TO-DATE
> Task :monitor:check UP-TO-DATE
> Task :monitor:installDist UP-TO-DATE
> Task :monitor:build UP-TO-DATE
> Task :p2p:assemble UP-TO-DATE
> Task :p2p:compileTestJava UP-TO-DATE
> Task :p2p:processTestResources UP-TO-DATE
> Task :p2p:testClasses UP-TO-DATE
> Task :p2p:test UP-TO-DATE
> Task :p2p:check UP-TO-DATE
> Task :p2p:build UP-TO-DATE

> Task :pricenode:compileJava UP-TO-DATE
Dependency verification failed for configuration ':pricenode:detachedConfiguration36'
40 artifacts failed verification:
  - protobuf-java-util-3.19.1.jar (com.google.protobuf:protobuf-java-util:3.19.1) from repository MavenRepo
  - protobuf-java-util-3.19.1.pom (com.google.protobuf:protobuf-java-util:3.19.1) from repository MavenRepo
  - cache-api-1.1.1.pom (javax.cache:cache-api:1.1.1) from repository MavenRepo
  - jakarta.ws.rs-api-2.1.6.pom (jakarta.ws.rs:jakarta.ws.rs-api:2.1.6) from repository MavenRepo
  - java-jwt-3.18.3.pom (com.auth0:java-jwt:3.18.3) from repository MavenRepo
  - rescu-2.1.0.pom (com.github.mmazi:rescu:2.1.0) from repository MavenRepo
  - resilience4j-all-1.7.0.pom (io.github.resilience4j:resilience4j-all:1.7.0) from repository MavenRepo
  - resilience4j-bulkhead-1.7.0.pom (io.github.resilience4j:resilience4j-bulkhead:1.7.0) from repository MavenRepo
  - resilience4j-cache-1.7.0.pom (io.github.resilience4j:resilience4j-cache:1.7.0) from repository MavenRepo
  - resilience4j-circuitbreaker-1.7.0.pom (io.github.resilience4j:resilience4j-circuitbreaker:1.7.0) from repository MavenRepo
  - resilience4j-core-1.7.0.pom (io.github.resilience4j:resilience4j-core:1.7.0) from repository MavenRepo
  - resilience4j-ratelimiter-1.7.0.pom (io.github.resilience4j:resilience4j-ratelimiter:1.7.0) from repository MavenRepo
  - resilience4j-retry-1.7.0.pom (io.github.resilience4j:resilience4j-retry:1.7.0) from repository MavenRepo
  - resilience4j-timelimiter-1.7.0.pom (io.github.resilience4j:resilience4j-timelimiter:1.7.0) from repository MavenRepo
  - vavr-0.10.2.pom (io.vavr:vavr:0.10.2) from repository MavenRepo
  - vavr-match-0.10.2.pom (io.vavr:vavr-match:0.10.2) from repository MavenRepo
  - vavr-parent-0.10.2.pom (io.vavr:vavr-parent:0.10.2) from repository MavenRepo
  - xchange-binance-5.0.13.pom (org.knowm.xchange:xchange-binance:5.0.13) from repository MavenRepo
  - xchange-bitbay-5.0.13.pom (org.knowm.xchange:xchange-bitbay:5.0.13) from repository MavenRepo
  - xchange-bitfinex-5.0.13.pom (org.knowm.xchange:xchange-bitfinex:5.0.13) from repository MavenRepo
  - xchange-bitflyer-5.0.13.pom (org.knowm.xchange:xchange-bitflyer:5.0.13) from repository MavenRepo
  - xchange-bitstamp-5.0.13.pom (org.knowm.xchange:xchange-bitstamp:5.0.13) from repository MavenRepo
  - xchange-btcmarkets-5.0.13.pom (org.knowm.xchange:xchange-btcmarkets:5.0.13) from repository MavenRepo
  - xchange-cexio-5.0.13.pom (org.knowm.xchange:xchange-cexio:5.0.13) from repository MavenRepo
  - xchange-coinbasepro-5.0.13.pom (org.knowm.xchange:xchange-coinbasepro:5.0.13) from repository MavenRepo
  - xchange-coinmarketcap-5.0.13.pom (org.knowm.xchange:xchange-coinmarketcap:5.0.13) from repository MavenRepo
  - xchange-coinmate-5.0.13.pom (org.knowm.xchange:xchange-coinmate:5.0.13) from repository MavenRepo
  - xchange-coinone-5.0.13.pom (org.knowm.xchange:xchange-coinone:5.0.13) from repository MavenRepo
  - xchange-core-5.0.13.pom (org.knowm.xchange:xchange-core:5.0.13) from repository MavenRepo
  - xchange-exmo-5.0.13.pom (org.knowm.xchange:xchange-exmo:5.0.13) from repository MavenRepo
  - xchange-hitbtc-5.0.13.pom (org.knowm.xchange:xchange-hitbtc:5.0.13) from repository MavenRepo
  - xchange-huobi-5.0.13.pom (org.knowm.xchange:xchange-huobi:5.0.13) from repository MavenRepo
  - xchange-independentreserve-5.0.13.pom (org.knowm.xchange:xchange-independentreserve:5.0.13) from repository MavenRepo
  - xchange-kraken-5.0.13.pom (org.knowm.xchange:xchange-kraken:5.0.13) from repository MavenRepo
  - xchange-luno-5.0.13.pom (org.knowm.xchange:xchange-luno:5.0.13) from repository MavenRepo
  - xchange-mercadobitcoin-5.0.13.pom (org.knowm.xchange:xchange-mercadobitcoin:5.0.13) from repository MavenRepo
  - xchange-parent-5.0.13.pom (org.knowm.xchange:xchange-parent:5.0.13) from repository MavenRepo
  - xchange-paribu-5.0.13.pom (org.knowm.xchange:xchange-paribu:5.0.13) from repository MavenRepo
  - xchange-poloniex-5.0.13.pom (org.knowm.xchange:xchange-poloniex:5.0.13) from repository MavenRepo
  - xchange-quoine-5.0.13.pom (org.knowm.xchange:xchange-quoine:5.0.13) from repository MavenRepo
If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/7.3.3/userguide/dependency_verification.html#sec:troubleshooting-verification

Open this report for more details: file:///Users/christoph/Documents/Workspaces.nosync/Java/mono-repo/bisq/build/reports/dependency-verification/at-1654759887396/dependency-verification-report.html
Dependency verification failed for configuration ':pricenode:compileClasspath'
76 artifacts failed verification:
  - protobuf-java-util-3.19.1.jar (com.google.protobuf:protobuf-java-util:3.19.1) from repository MavenRepo
  - protobuf-java-util-3.19.1.pom (com.google.protobuf:protobuf-java-util:3.19.1) from repository MavenRepo
  - cache-api-1.1.1.pom (javax.cache:cache-api:1.1.1) from repository MavenRepo
  - jakarta.ws.rs-api-2.1.6.pom (jakarta.ws.rs:jakarta.ws.rs-api:2.1.6) from repository MavenRepo
  - java-jwt-3.18.3.pom (com.auth0:java-jwt:3.18.3) from repository MavenRepo
  - rescu-2.1.0.pom (com.github.mmazi:rescu:2.1.0) from repository MavenRepo
  - resilience4j-all-1.7.0.pom (io.github.resilience4j:resilience4j-all:1.7.0) from repository MavenRepo
  - resilience4j-bulkhead-1.7.0.pom (io.github.resilience4j:resilience4j-bulkhead:1.7.0) from repository MavenRepo
  - resilience4j-cache-1.7.0.pom (io.github.resilience4j:resilience4j-cache:1.7.0) from repository MavenRepo
  - resilience4j-circuitbreaker-1.7.0.pom (io.github.resilience4j:resilience4j-circuitbreaker:1.7.0) from repository MavenRepo
  - resilience4j-core-1.7.0.pom (io.github.resilience4j:resilience4j-core:1.7.0) from repository MavenRepo
  - resilience4j-ratelimiter-1.7.0.pom (io.github.resilience4j:resilience4j-ratelimiter:1.7.0) from repository MavenRepo
  - resilience4j-retry-1.7.0.pom (io.github.resilience4j:resilience4j-retry:1.7.0) from repository MavenRepo
  - resilience4j-timelimiter-1.7.0.pom (io.github.resilience4j:resilience4j-timelimiter:1.7.0) from repository MavenRepo
  - vavr-0.10.2.pom (io.vavr:vavr:0.10.2) from repository MavenRepo
  - vavr-match-0.10.2.pom (io.vavr:vavr-match:0.10.2) from repository MavenRepo
  - vavr-parent-0.10.2.pom (io.vavr:vavr-parent:0.10.2) from repository MavenRepo
  - xchange-binance-5.0.13.pom (org.knowm.xchange:xchange-binance:5.0.13) from repository MavenRepo
  - xchange-bitbay-5.0.13.pom (org.knowm.xchange:xchange-bitbay:5.0.13) from repository MavenRepo
  - xchange-bitfinex-5.0.13.pom (org.knowm.xchange:xchange-bitfinex:5.0.13) from repository MavenRepo
  - xchange-bitflyer-5.0.13.pom (org.knowm.xchange:xchange-bitflyer:5.0.13) from repository MavenRepo
  - xchange-bitstamp-5.0.13.pom (org.knowm.xchange:xchange-bitstamp:5.0.13) from repository MavenRepo
  - xchange-btcmarkets-5.0.13.pom (org.knowm.xchange:xchange-btcmarkets:5.0.13) from repository MavenRepo
  - xchange-cexio-5.0.13.pom (org.knowm.xchange:xchange-cexio:5.0.13) from repository MavenRepo
  - xchange-coinbasepro-5.0.13.pom (org.knowm.xchange:xchange-coinbasepro:5.0.13) from repository MavenRepo
  - xchange-coinmarketcap-5.0.13.pom (org.knowm.xchange:xchange-coinmarketcap:5.0.13) from repository MavenRepo
  - xchange-coinmate-5.0.13.pom (org.knowm.xchange:xchange-coinmate:5.0.13) from repository MavenRepo
  - xchange-coinone-5.0.13.pom (org.knowm.xchange:xchange-coinone:5.0.13) from repository MavenRepo
  - xchange-core-5.0.13.pom (org.knowm.xchange:xchange-core:5.0.13) from repository MavenRepo
  - xchange-exmo-5.0.13.pom (org.knowm.xchange:xchange-exmo:5.0.13) from repository MavenRepo
  - xchange-hitbtc-5.0.13.pom (org.knowm.xchange:xchange-hitbtc:5.0.13) from repository MavenRepo
  - xchange-huobi-5.0.13.pom (org.knowm.xchange:xchange-huobi:5.0.13) from repository MavenRepo
  - xchange-independentreserve-5.0.13.pom (org.knowm.xchange:xchange-independentreserve:5.0.13) from repository MavenRepo
  - xchange-kraken-5.0.13.pom (org.knowm.xchange:xchange-kraken:5.0.13) from repository MavenRepo
  - xchange-luno-5.0.13.pom (org.knowm.xchange:xchange-luno:5.0.13) from repository MavenRepo
  - xchange-mercadobitcoin-5.0.13.pom (org.knowm.xchange:xchange-mercadobitcoin:5.0.13) from repository MavenRepo
  - xchange-parent-5.0.13.pom (org.knowm.xchange:xchange-parent:5.0.13) from repository MavenRepo
  - xchange-paribu-5.0.13.pom (org.knowm.xchange:xchange-paribu:5.0.13) from repository MavenRepo
  - xchange-poloniex-5.0.13.pom (org.knowm.xchange:xchange-poloniex:5.0.13) from repository MavenRepo
  - xchange-quoine-5.0.13.pom (org.knowm.xchange:xchange-quoine:5.0.13) from repository MavenRepo
  - cache-api-1.1.1.jar (javax.cache:cache-api:1.1.1) from repository MavenRepo
  - jakarta.ws.rs-api-2.1.6.jar (jakarta.ws.rs:jakarta.ws.rs-api:2.1.6) from repository MavenRepo
  - java-jwt-3.18.3.jar (com.auth0:java-jwt:3.18.3) from repository MavenRepo
  - rescu-2.1.0.jar (com.github.mmazi:rescu:2.1.0) from repository MavenRepo
  - resilience4j-all-1.7.0.jar (io.github.resilience4j:resilience4j-all:1.7.0) from repository MavenRepo
  - resilience4j-bulkhead-1.7.0.jar (io.github.resilience4j:resilience4j-bulkhead:1.7.0) from repository MavenRepo
  - resilience4j-cache-1.7.0.jar (io.github.resilience4j:resilience4j-cache:1.7.0) from repository MavenRepo
  - resilience4j-circuitbreaker-1.7.0.jar (io.github.resilience4j:resilience4j-circuitbreaker:1.7.0) from repository MavenRepo
  - resilience4j-core-1.7.0.jar (io.github.resilience4j:resilience4j-core:1.7.0) from repository MavenRepo
  - resilience4j-ratelimiter-1.7.0.jar (io.github.resilience4j:resilience4j-ratelimiter:1.7.0) from repository MavenRepo
  - resilience4j-retry-1.7.0.jar (io.github.resilience4j:resilience4j-retry:1.7.0) from repository MavenRepo
  - resilience4j-timelimiter-1.7.0.jar (io.github.resilience4j:resilience4j-timelimiter:1.7.0) from repository MavenRepo
  - vavr-0.10.2.jar (io.vavr:vavr:0.10.2) from repository MavenRepo
  - vavr-match-0.10.2.jar (io.vavr:vavr-match:0.10.2) from repository MavenRepo
  - xchange-binance-5.0.13.jar (org.knowm.xchange:xchange-binance:5.0.13) from repository MavenRepo
  - xchange-bitbay-5.0.13.jar (org.knowm.xchange:xchange-bitbay:5.0.13) from repository MavenRepo
  - xchange-bitfinex-5.0.13.jar (org.knowm.xchange:xchange-bitfinex:5.0.13) from repository MavenRepo
  - xchange-bitflyer-5.0.13.jar (org.knowm.xchange:xchange-bitflyer:5.0.13) from repository MavenRepo
  - xchange-bitstamp-5.0.13.jar (org.knowm.xchange:xchange-bitstamp:5.0.13) from repository MavenRepo
  - xchange-btcmarkets-5.0.13.jar (org.knowm.xchange:xchange-btcmarkets:5.0.13) from repository MavenRepo
  - xchange-cexio-5.0.13.jar (org.knowm.xchange:xchange-cexio:5.0.13) from repository MavenRepo
  - xchange-coinbasepro-5.0.13.jar (org.knowm.xchange:xchange-coinbasepro:5.0.13) from repository MavenRepo
  - xchange-coinmarketcap-5.0.13.jar (org.knowm.xchange:xchange-coinmarketcap:5.0.13) from repository MavenRepo
  - xchange-coinmate-5.0.13.jar (org.knowm.xchange:xchange-coinmate:5.0.13) from repository MavenRepo
  - xchange-coinone-5.0.13.jar (org.knowm.xchange:xchange-coinone:5.0.13) from repository MavenRepo
  - xchange-core-5.0.13.jar (org.knowm.xchange:xchange-core:5.0.13) from repository MavenRepo
  - xchange-exmo-5.0.13.jar (org.knowm.xchange:xchange-exmo:5.0.13) from repository MavenRepo
  - xchange-hitbtc-5.0.13.jar (org.knowm.xchange:xchange-hitbtc:5.0.13) from repository MavenRepo
  - xchange-huobi-5.0.13.jar (org.knowm.xchange:xchange-huobi:5.0.13) from repository MavenRepo
  - xchange-independentreserve-5.0.13.jar (org.knowm.xchange:xchange-independentreserve:5.0.13) from repository MavenRepo
  - xchange-kraken-5.0.13.jar (org.knowm.xchange:xchange-kraken:5.0.13) from repository MavenRepo
  - xchange-luno-5.0.13.jar (org.knowm.xchange:xchange-luno:5.0.13) from repository MavenRepo
  - xchange-mercadobitcoin-5.0.13.jar (org.knowm.xchange:xchange-mercadobitcoin:5.0.13) from repository MavenRepo
  - xchange-paribu-5.0.13.jar (org.knowm.xchange:xchange-paribu:5.0.13) from repository MavenRepo
  - xchange-poloniex-5.0.13.jar (org.knowm.xchange:xchange-poloniex:5.0.13) from repository MavenRepo
  - xchange-quoine-5.0.13.jar (org.knowm.xchange:xchange-quoine:5.0.13) from repository MavenRepo
If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/7.3.3/userguide/dependency_verification.html#sec:troubleshooting-verification

Open this report for more details: file:///Users/christoph/Documents/Workspaces.nosync/Java/mono-repo/bisq/build/reports/dependency-verification/at-1654759887396/dependency-verification-report.html

> Task :pricenode:processResources UP-TO-DATE
> Task :pricenode:classes UP-TO-DATE
> Task :pricenode:bootJarMainClassName UP-TO-DATE
> Task :pricenode:bootJar UP-TO-DATE
> Task :pricenode:bootStartScripts UP-TO-DATE
> Task :pricenode:bootDistTar UP-TO-DATE
> Task :pricenode:bootDistZip UP-TO-DATE
> Task :pricenode:jar UP-TO-DATE
> Task :pricenode:startScripts UP-TO-DATE
> Task :pricenode:distTar UP-TO-DATE
> Task :pricenode:distZip SKIPPED
> Task :pricenode:assemble UP-TO-DATE
> Task :pricenode:compileTestJava UP-TO-DATE
> Task :pricenode:processTestResources NO-SOURCE
> Task :pricenode:testClasses UP-TO-DATE
> Task :pricenode:test UP-TO-DATE
> Task :pricenode:check UP-TO-DATE
> Task :pricenode:installDist UP-TO-DATE
> Task :pricenode:build UP-TO-DATE
> Task :proto:assemble UP-TO-DATE
> Task :proto:extractIncludeTestProto UP-TO-DATE
> Task :proto:extractTestProto UP-TO-DATE
> Task :proto:generateTestProto NO-SOURCE
> Task :proto:compileTestJava NO-SOURCE
> Task :proto:processTestResources NO-SOURCE
> Task :proto:testClasses UP-TO-DATE
> Task :proto:test NO-SOURCE
> Task :proto:check UP-TO-DATE
> Task :proto:build UP-TO-DATE
> Task :relay:compileJava UP-TO-DATE
> Task :relay:processResources UP-TO-DATE
> Task :relay:classes UP-TO-DATE
> Task :relay:jar UP-TO-DATE
> Task :relay:startScripts UP-TO-DATE
> Task :relay:distTar UP-TO-DATE
> Task :relay:distZip SKIPPED
> Task :relay:assemble UP-TO-DATE
> Task :relay:compileTestJava NO-SOURCE
> Task :relay:processTestResources NO-SOURCE
> Task :relay:testClasses UP-TO-DATE
> Task :relay:test NO-SOURCE
> Task :relay:check UP-TO-DATE
> Task :relay:installDist UP-TO-DATE
> Task :relay:build UP-TO-DATE
> Task :seednode:startScripts UP-TO-DATE
> Task :seednode:distTar UP-TO-DATE
> Task :seednode:distZip SKIPPED
> Task :seednode:shadowJar UP-TO-DATE
> Task :seednode:startShadowScripts UP-TO-DATE
> Task :seednode:shadowDistTar UP-TO-DATE
> Task :seednode:shadowDistZip UP-TO-DATE
> Task :seednode:assemble UP-TO-DATE
> Task :seednode:compileTestJava UP-TO-DATE
> Task :seednode:processTestResources NO-SOURCE
> Task :seednode:testClasses UP-TO-DATE
> Task :seednode:test UP-TO-DATE
> Task :seednode:check UP-TO-DATE
> Task :seednode:installDist UP-TO-DATE
> Task :seednode:build UP-TO-DATE
> Task :statsnode:compileJava UP-TO-DATE
> Task :statsnode:processResources UP-TO-DATE
> Task :statsnode:classes UP-TO-DATE
> Task :statsnode:jar UP-TO-DATE
> Task :statsnode:startScripts UP-TO-DATE
> Task :statsnode:distTar UP-TO-DATE
> Task :statsnode:distZip SKIPPED
> Task :statsnode:assemble UP-TO-DATE
> Task :statsnode:compileTestJava NO-SOURCE
> Task :statsnode:processTestResources NO-SOURCE
> Task :statsnode:testClasses UP-TO-DATE
> Task :statsnode:test NO-SOURCE
> Task :statsnode:check UP-TO-DATE
> Task :statsnode:installDist UP-TO-DATE
> Task :statsnode:build UP-TO-DATE

BUILD SUCCESSFUL in 3s
132 actionable tasks: 132 up-to-date
```

**Comment by cbeams** [comment]
I only have a moment to respond so haven't looked at this deeply, but in short, no, I don't know why the build didn't fail. I just reviewed https://docs.gradle.org/current/userguide/dependency_verification.html, and there is an explicit `--write-verification-metadata` switch you need to add when updating the file, but so far as I recall, verification failures should fail the build by default (and I believe have done so in the past).

**Comment by ripcurlx** [comment]
> I only have a moment to respond so haven't looked at this deeply, but in short, no, I don't know why the build didn't fail. I just reviewed https://docs.gradle.org/current/userguide/dependency_verification.html, and there is an explicit `--write-verification-metadata` switch you need to add when updating the file, but so far as I recall, verification failures should fail the build by default (and I believe have done so in the past).

Yes, that is what I've done to update the verification file and yes I do remember it failed in the past (we had one checksum change once). I haven't done anything intentional that could have changed the build.

**Review by ghost — APPROVED** [review]
ACK

**Review by bisq-github-admin-3 — APPROVED** [review]
utACK - based on https://github.com/bisq-network/bisq/pull/6242#pullrequestreview-1001200537

**Pull request merged**
