### PR TITLE
Restore QR code scanner feature for mobile notification pairing

### PR DESCRIPTION
**Pull request by devinbileck**
This restores the functionality that was removed in b5beea58. This implementation utilizes the JavaCV library rather than the webcam-capture library for reasons discussed in #4940.

I have tested this on both Linux (Ubuntu 23.10) and macOS (Sonoma 14.4).

### CODE REVIEW

**Review by alejandrogarcia83 — CHANGES_REQUESTED** [review]
NACK

The CI build fails on macOS (see https://github.com/bisq-network/bisq/actions/runs/8447335400/attempts/1#summary-23137520876),

**Comment by devinbileck** [comment]
@alejandrogarcia83 I am not sure why that failed. It does not provide much detail.
I re-ran it on my fork and it passed: https://github.com/devinbileck/bisq/actions/runs/8447335253
Would you be able to re-run it, since I dont seem to have the ability to, in order to see if it was just a transient failure?

**Review by alvasw — APPROVED** [review]
utACK

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
