### PR TITLE
Seednode accounting option is by command line, overrides UserPreferences.

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/bisq-network/bisq/pull/6644#discussion_r1247984869

Seednodes cannot use the UserPreference setting to enable/disable accounting.
They use the flag `--isBmFullNode=true`

### CODE REVIEW

**Comment by ghost** [comment]
Ping @HenrikJannsen

**Review by alvasw — APPROVED** [review]
utACK

**Comment by alvasw** [comment]
@alejandrogarcia83 @gabernard This bug affects the upgraded seednodes.

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
