### PR TITLE
Fix gradle build files, update docs

### PR DESCRIPTION
**Pull request by ManfredKarrer**

### CODE REVIEW

**Review by ripcurlx — APPROVED** [review]
utACK

**Comment by cbeams** [comment]
It's a little strange to see this merged before #1660, but assuming that happens soon, I guess it's no big deal. People may not actually be able to build against JDK 10 if they follow the updated instructions in the README. Hopefully that just doesn't happen in the meantime.

**Comment by ManfredKarrer** [comment]
@cbeams #1660 is already merged

**Comment by cbeams** [comment]
Hah, so it has. I was looking at a stale browser tab. 🤦‍♂️ Thanks.

**Pull request merged**
