### PR TITLE
List Hatch (HATCH)

### PR DESCRIPTION
**Pull request by hatchpay**
* Official project URL: https://hatch.ga
* Official block explorer URL: https://explorer2.hatch.ga

### CODE REVIEW

**Review by blabno — APPROVED** [review]
ACK

**Comment by hatchpay** [comment]
Please tell me what your comment ACK means?

**Comment by ghost** [comment]
see : https://github.com/bitcoin/bitcoin/issues/6100#issuecomment-98471846

**Comment by hatchpay** [comment]
> see : [bitcoin/bitcoin#6100 (comment)](https://github.com/bitcoin/bitcoin/issues/6100#issuecomment-98471846)

Thank you.

**Comment by hatchpay** [comment]
> ACK

Thank you for your comment. Will you add a HATCH to the exchange?

**Comment by ripcurlx** [comment]
@hatchpay Rebased and merged conflict because of other altcoin PRs that were merged.

**Pull request merged**
