### PR TITLE
Increase "Proposals of current cycle" table size to fit the window

### LINKED ISSUE #3229: [UI] Increase "Proposals of current cycle" table size to fit the window
daotable

### PR DESCRIPTION
**Pull request by niyid**
fixes #3229

### CODE REVIEW

**Review by freimair — CHANGES_REQUESTED** [review]
thanks for your contribution, however, I just fired your branch up and I am seeing no difference to before. 

Screenshot from 2019-11-01 09-10-08

maybe this can be done similarly to the fixed done in https://github.com/bisq-network/bisq/pull/3077

**Comment by niyid** [comment]
OK. I will take a look. Thanks.

**Comment by niyid** [comment]
The list-view previously left a lot of space outside of the scroll panel. Now the space is well utilized and will extend further with more items in the list-view. The difference is as shown below:

Screenshot from 2019-11-01 14-35-22

**Comment by niyid** [comment]
@freimair 

Please check the screenshot I got on applying the PR below:

Screenshot from 2019-11-07 23-56-04

Compare to the screenshot without applying the PR below:

Screenshot from 2019-11-08 00-00-35

**Comment by freimair** [comment]
just checked again, nothing changed on my side. please be aware that I am on Linux Gnome Shell here. Maybe @devinbileck (windows) and @ripcurlx (macos) can have a look too?

**Comment by niyid** [comment]
@freimair 

Hi. Can we clear this up on Slack? I have sent you a few messages.

@ripcurlx @devinbileck 
I will appreciate if further tests can be conducted on other systems. BTW I am on Fedora 22.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
@niyid Your fix improves on first sight the height of the open proposals, but as soon as the blind voting is on it hides an important part behind off screen.
Bildschirmfoto 2019-11-12 um 13 19 58
Bildschirmfoto 2019-11-12 um 13 20 03

Master in Blind vote phase:
Bildschirmfoto 2019-11-12 um 13 31 22

The right way to fix this would be to adapt the `double initialProposalTableViewHeight = 180;` and `tableView.setPrefHeight(100);` based on the proposal phase, as atm it resizes only correctly in the Blind vote phase.

**Comment by niyid** [comment]
Thanks for the feedback. I will adopt your suggestion.

Regards.

**Comment by niyid** [comment]
> Thanks for the feedback. I will adopt your suggestion. Regards.
> […](#)

@ripcurlx 

Since this fix only appears to work in the BLIND_VOTE phase, I could make the height as is for the rest and resize to double in the BLIND_VOTE phase. Does that work?

```
        double initialProposalTableViewHeight = 180;
    	if(DaoPhase.Phase.BLIND_VOTE.equals(currentPhase)) {
    		initialProposalTableViewHeight = 360;
    	}        
```

```
        tableView.setPrefHeight(100);
    	if(DaoPhase.Phase.BLIND_VOTE.equals(currentPhase)) {
            tableView.setPrefHeight(200);
    	}

```

**Comment by ripcurlx** [comment]
> Since this fix only appears to work in the BLIND_VOTE phase, I could make the height as is for the rest and resize to double in the BLIND_VOTE phase. Does that work?

Did it work for you when you tried it out?

**Comment by niyid** [comment]
I had not; I merely sought your expert advice on the matter. :-)

**Comment by niyid** [comment]
> > Since this fix only appears to work in the BLIND_VOTE phase, I could make the height as is for the rest and resize to double in the BLIND_VOTE phase. Does that work?
> 
> Did it work for you when you tried it out?

Can you please point me to any resources on testing the GUI on the TESTNET?

I found this: https://github.com/bisq-network/proposals/issues/74 but I need specifics on how to pass data to target views - mock test.

**Comment by julianknutsen** [comment]
@niyid Check out https://github.com/bisq-network/bisq/blob/master/Makefile that was recently added to master to help the onboarding of `localnet` Bisq clusters that are useful for testing/debugging.

We don't currently have a testing framework for unit testing, but it isn't too complicated to bring up a `localnet` and move it through the proposal phases to verify the behavior.

**Comment by niyid** [comment]
Thanks a lot Julian.

**Pull request closed without merging**
