### PR TITLE
Replace a @wiz v2 seednode with a new v3 seednode

### PR DESCRIPTION
**Pull request by wiz**
This commit replaces v2 seednode `jhgcy2won7xnslrb` with a new v3 seednode `wizseedscybbttk4bmb2lzvbuk2jtect37lcpva4l3twktmkzemwbead` 

Screen Shot 2020-04-02 at 21 46 25

### CODE REVIEW

**Comment by freimair** [comment]
part of https://github.com/bisq-network/projects/issues/23

**Comment by wiz** [comment]
For the avoidance of doubt, the `jhgcy2won7xnslrb` will remain operating for 6 months, at which point we can filter it out from the network after enough people have upgraded

**Review by freimair — APPROVED** [review]
tried it, works

### Testing setup
- clean working dir
- v2 node from master branch
- got initial data
- got >30 peers
- got DAO data

**Review by ripcurlx — APPROVED** [review]
utACK - based on https://github.com/bisq-network/bisq/pull/4113#pullrequestreview-386443818

**Pull request merged**
