### PR TITLE
Update my gpg key

### PR DESCRIPTION
**Pull request by ManfredKarrer**
- old one was expired.

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Don't know why Travis fails:

3.41s$ git clone --depth=50 https://github.com/bisq-network/bisq.git bisq-network/bisq
Cloning into 'bisq-network/bisq'...
remote: Enumerating objects: 9688, done.
remote: Counting objects: 100% (9688/9688), done.
remote: Compressing objects: 100% (3884/3884), done.
remote: Total 9688 (delta 5125), reused 8605 (delta 4560), pack-reused 0
Receiving objects: 100% (9688/9688), 20.50 MiB | 22.35 MiB/s, done.
Resolving deltas: 100% (5125/5125), done.
$ cd bisq-network/bisq
4.09s$ git fetch origin +refs/pull/1902/merge:
fatal: Couldn't find remote ref refs/pull/1902/merge
The command "eval git fetch origin +refs/pull/1902/merge: " failed. Retrying, 2 of 3.

**Comment by devinbileck** [comment]
The error you list above was for a different PR (#1902), which I am guessing failed because it was merged while the build on Travis was still in progress. As for the failure for this PR, I am at a loss.

**Comment by devinbileck** [comment]
Seems it was a random failure. I restarted the build and it passed :)

**Comment by ManfredKarrer** [comment]
Ah thanks!

**Pull request closed without merging**
