### PR TITLE
List Helium (HLM)

### PR DESCRIPTION
**Pull request by TeelaBrown**
- Official project URL: https://heliumchain.org
- Official block explorer URL: https://www.heliumchain.info

### CODE REVIEW

**Comment by TeelaBrown** [comment]
To clarify: Helium was distributed as an airdrop to Spreadcoin holders and did not have an ICO/pre-sale.

**Review by blabno — COMMENTED** [review]
Code looks ok, but I was not able to determine if arbitration is possible as I could not find any regular transactions in recent blocks.
Please provide link to a regular transaction (non block rewared) in your block explorer.

**Comment by TeelaBrown** [comment]
Thank you for reviewing. This is a regular tx in the blockexplorer:

https://www.heliumchain.info/#/tx/d18706af05e9576de8e5bac4c68df0c0c2ac263dc19342cdbbf64945c7fc2f36

**Review by blabno — APPROVED** [review]
ACK

**Pull request merged**
