### PR TITLE
List LuKa (LUK)

### PR DESCRIPTION
**Pull request by egyware**
- Official project URL: https://www.cryptoluka.cl/
- Official block explorer URL: https://explorer.cryptoluka.cl/

### CODE REVIEW

**Comment by blabno** [comment]
I can't see any blocks in that block explorer.

**Review by blabno — CHANGES_REQUESTED** [review]
NACK no PRs from master

**Comment by cryptoluka** [comment]
@blabno the explorer is running. Please check again... is running everyday because some applications depends of it.

**Comment by blabno** [comment]
@cryptoluka Please rebase against master and resolve conflicts.

**Pull request closed without merging**
