### PR TITLE
Late vote reveal handling

### PR DESCRIPTION
**Pull request by sqrrm**
Vote reveal has to be published to complete the vote process even after the reveal phase. To indicate votes I added an indication that votes were not counted in result
image

Also added text to show failed votes in proposaldisplay
image

### CODE REVIEW

**Review by devinbileck — CHANGES_REQUESTED** [review]
I am encountering a display issue with this new indicator. When initially clicking on a prior voting cycle for which I successfully published the vote reveal, it is showing this new icon indicating it wasn't counted:
image

And clicking on it to bring up the details shows my vote was not included:
image

But viewing the individual votes shows each vote:
image

But when clicking on the current cycle and back to the prior cycle resolves it:
image

**Comment by sqrrm** [comment]
@devinbileck Good find. It was the vote inclusion check that was wrong. Now fixed.

**Comment by devinbileck** [comment]
That fixed it.

However, I am now noticing if I had ignored a proposal and my vote is not included, the ignored proposal is not shown in the results for the prior cycle, but the ones that I attempted to vote upon do show up.

As seen in this screenshot, Bob (bottom) made all the proposals and remained online and published his vote reveal tx, while Alice (top) went offline after the blind vote. Alice ignored the BTC maker fee proposal and it is not shown for her.
image

I haven't yet determined if this is related to this change or not.

**Comment by devinbileck** [comment]
My above mentioned issue is not related to this change. I tested on master and had the same behaviour. In fact after restarting Bob's client, the ignored proposals no longer showed up. Not sure if related but I seem to have a conflict with my DAO state as it is not in sync with my seed. Not sure why at this point.

**Comment by sqrrm** [comment]
It's pretty strange to lose a proposal, once received the client should save it. If you can reproduce that issue it would be good to take a look at. Might cause some issue during voting if it splits the votes.

**Comment by devinbileck** [comment]
Agreed. I will see if I can reproduce it.

**Review by devinbileck — APPROVED** [review]
ACK

**Pull request merged**
