### PR TITLE
Edit BSQ swap offer

### LINKED ISSUE #6075: [1.8.3] Edit BSQ swap offer in offer book goes to nowhere
As it is not possible to edit a BSQ swap offer clicking on edit offer on a BSQ swap offer will take the user to my open offers and not as expected to an edit offer screen.

#### Version

1.8.2+

### Steps to reproduce

- Create BSQ swap offer
- Click on edit offer in offer book

### Expected behaviour

There shouldn't be an edit button for BSQ swap offers

### Actual behaviour

Edit offer button takes users to my open offers

### Screenshots

Bildschirmfoto 2022-02-24 um 10 43 56
Bildschirmfoto 2022-02-24 um 10 45 07

### PR DESCRIPTION
**Pull request by ghost**
Fixes #6075
Made it possible to edit price.

### Screenshots:
bsq-swap-edit-offer

---

bsq-swap-edit-offer-2

### CODE REVIEW

**Comment by ripcurlx** [comment]
@xyzmaker123 As no fees are being paid for BSQ offers I think to edit a BSQ offer it causes less code changes if you just remove the old one and open a new create offer view with pre-populated fields similar as it is done when cloning an BSQ offer. But please wait with this until #6135 is merged as lot of code that you would touch is going to be changed.

**Comment by xyzmaker123** [comment]
> just remove the old one and open a new create offer

I have mixed feelings about this approach:
- it would be not possible to cancel edit offer
- not consistent UI behavior in comparison with other offers edition

Of course my opinion is subjective and not disinterested :)

---


> But please wait with this until https://github.com/bisq-network/bisq/pull/6135 is merged

I have no other choice anyway :)

**Comment by ghost** [comment]
@ripcurlx I rebased into master and resolved conflicts

> just remove the old one and open a new create offer

I think it's not good approach:
- it would be not possible to cancel edit offer
- not consistent UI behavior in comparison with other offers edition

**Comment by ripcurlx** [comment]
As I don't remember anymore if there was a reason (besides that there are no fees paid, so no loss when deleting an offer) I'd like to have @chimp1984 opinion on this as well.

**Comment by chimp1984** [comment]
I do not remember any reason preventing that, but as you said as canceling an offer is without costs it was easier to cancel and re-create. I don't have time atm to review the changes. Its non trivial changes so should be reviewed with care.

**Comment by ghubstan** [comment]
I do recall @sqrrm saying he never intended to make swap offers editable because cancelling them is free.

If they become editable in UI, I will eventually need to make them editable in the API -- that is also a non-trivial change on both the CLI and server (daemon) side.

**Pull request closed without merging**
