### PR TITLE
Refactor dao parser

### PR DESCRIPTION
**Pull request by sqrrm**
Moved PR from https://github.com/bisq-network/bisq-core/pull/175

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
I assume that is WIP as discussed, right? If so, could you add WIP in the title?

**Comment by ManfredKarrer** [comment]
@sqrrm Could up resolve the conflicts?

**Comment by sqrrm** [comment]
Conflicts resolved

**Review by ManfredKarrer — APPROVED** [review]
ACK

I am still not 100% sure about where to put the locktime, but we can keep that atm...

**Pull request merged**
