### PR TITLE
Revert "Move bisq-* scripts from root directory to scripts directory"

### PR DESCRIPTION
**Pull request by alejandrogarcia83**
Reverts bisq-network/bisq#6760

### CODE REVIEW

**Comment by alejandrogarcia83** [comment]
Reqested by @alvasw (https://github.com/bisq-network/bisq/pull/6760#issuecomment-1632180917).

**Review by alvasw — APPROVED** [review]
utACK

**Comment by alejandrogarcia83** [comment]
@gabernard I cannot merge my own PRs.

**Review by gabernard — APPROVED** [review]
utACK

**Pull request merged**
