### PR TITLE
inject clock for usage in isDateInTolerance

### PR DESCRIPTION
**Pull request by christophsturm**

### CODE REVIEW

**Comment by mrosseel** [comment]
Clock doesn't seem to be used yet, are those commits coming?

**Comment by christophsturm** [comment]
i have a different PR that adds unit tests for the `SignedWitness` class. once this is merged i will use the clock for more unit testing. I just wanted to do the clock injection in a separate pr to make prs small and easy to review and not block a bigger pr if someone has an objection.

**Comment by sqrrm** [comment]
For these kinds of PRs it would be good to have an explanation of why they're needed. It's not obvious why this one is needed without the follow up conversation.

**Review by sqrrm — APPROVED** [review]
utACK

**Comment by christophsturm** [comment]
> For these kinds of PRs it would be good to have an explanation of why they're needed. It's not obvious why this one is needed without the follow up conversation.

ok.

**Pull request merged**
