### PR TITLE
Editable account names

### LINKED ISSUE #6009: Make account names editable for all account types
### Description

Recently @xyzmaker123 made [SEPA account names editable](https://github.com/bisq-network/bisq/pull/5930)

This was a great usability addition.

It would be good if this was extended to ALL account types (National Currency and Altcoins).

The account name is only saved and shared locally so it does not effect any trades in progress.

#### Version

1.8.2

### Steps to reproduce

If you have a SEPA or SEPA Instant account you can change the name.

You cannot change the name for any other account type Altcoin or National Currency Account

### Expected behaviour

ALL payment account type names to be editable.

### Actual behaviour

Only SEPA and SEPA Instant payment account type names are editable.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #6009

### CODE REVIEW

**Comment by ripcurlx** [comment]
@xyzmaker123 Could you please go through all changed files for unused imports. I stopped my review after finding some in AdvanceCashForm and AmazonGiftCardForm. Not sure why Codacy didn't catch them as `UnusedImports` is configured 🤔  Actually I found that we have disabled most of the checks at hand. I'll re-enable them and disable them if they are not appropriate for our use cases.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - see https://github.com/bisq-network/bisq/pull/6014#issuecomment-1033620725

**Comment by xyzmaker123** [comment]
@ripcurlx I fixed issue with unused imports. Build failed now, I don't think it's related with my changes.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK

1. Click on existing payment account
2. Change the account name
3. Click on a different payment account in list

Expected result:
Account name is reset to old name

Actual result:
Changed account name is shown in list and when selected again. It is only properly reset if you switch away e.g. to a different tab.

**Review by ripcurlx — APPROVED** [review]
ACK - Tested it on Regtest

**Comment by w0000000t** [comment]
Still erroring for me.
Go to Account > National currency accounts, click on a CBM account (or faster payments), as soon as I change the text in the name field a nullpointer exception happens.
Works no problem with Zelle Revolut and Sepa.
Excerpt from the log:

```
[JavaFX Application Thread] INFO  b.core.provider.fee.FeeService: BTC tx fee: txFeePerVbyte=10 minFeePerVbyte=2 
[JavaFX Application Thread] INFO  b.d.c.c.control.PopOver: hide:200.0 ms 
 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
[JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= null 
[JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.NullPointerException 
[JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.desktop.components.paymentmethods.FasterPaymentsForm.updateAllInputsValid(FasterPaymentsForm.java:137)
	at bisq.desktop.components.paymentmethods.PaymentMethodForm.lambda$addAccountNameTextFieldWithAutoFillToggleButton$1(PaymentMethodForm.java:136)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1459)
	at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1463)
	at javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(TextInputControl.java:1402)
	at javafx.scene.control.TextInputControl.lambda$new$0(TextInputControl.java:146)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.scene.control.TextField$TextFieldContent.insert(TextField.java:91)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:1264)
	at javafx.scene.control.TextInputControl.updateContent(TextInputControl.java:572)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:564)
	at javafx.scene.control.skin.TextFieldSkin.replaceText(TextFieldSkin.java:450)
	at com.sun.javafx.scene.control.behavior.TextFieldBehavior.replaceText(TextFieldBehavior.java:179)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.defaultKeyTyped(TextInputControlBehavior.java:402)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(TextInputControlBehavior.java:332)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:4064)
	at javafx.scene.Scene.processKeyEvent(Scene.java:2123)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2591)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
	at com.sun.glass.ui.View.notifyKey(View.java:971)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
java.lang.NullPointerException
	at bisq.desktop.components.paymentmethods.FasterPaymentsForm.updateAllInputsValid(FasterPaymentsForm.java:137)
	at bisq.desktop.components.paymentmethods.PaymentMethodForm.lambda$addAccountNameTextFieldWithAutoFillToggleButton$1(PaymentMethodForm.java:136)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1459)
	at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1463)
	at javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(TextInputControl.java:1402)
	at javafx.scene.control.TextInputControl.lambda$new$0(TextInputControl.java:146)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.scene.control.TextField$TextFieldContent.insert(TextField.java:91)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:1264)
	at javafx.scene.control.TextInputControl.updateContent(TextInputControl.java:572)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:564)
	at javafx.scene.control.skin.TextFieldSkin.replaceText(TextFieldSkin.java:450)
	at com.sun.javafx.scene.control.behavior.TextFieldBehavior.replaceText(TextFieldBehavior.java:179)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.defaultKeyTyped(TextInputControlBehavior.java:402)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(TextInputControlBehavior.java:332)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:4064)
	at javafx.scene.Scene.processKeyEvent(Scene.java:2123)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2591)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
	at com.sun.glass.ui.View.notifyKey(View.java:971)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Pull request merged**
