### PR TITLE
List LBRY Credits (LBC)

### PR DESCRIPTION
**Pull request by BrannonKing**
- Official project URL: https://lbry.com
- Official block explorer URL: https://explorer.lbry.com/

Feel free to ask any questions.

### CODE REVIEW

**Comment by ykris45** [comment]
https://github.com/bisq-network/bisq/issues/2629 @BrannonKing i reference my issues about Listing LBRY Credits in your PR

**Comment by kodxana** [comment]
Just can't wait to see LBC readable on bisq :)

**Comment by ripcurlx** [comment]
@BrannonKing Please resolve the conflict with Asset (probably because of another merged asset PR)

**Comment by BrannonKing** [comment]
@ripcurlx , I just rebased it.

**Comment by ripcurlx** [comment]
@blabno Could you give it a quick look if it is ready for v1.2.3? Thanks!

**Review by blabno — APPROVED** [review]
ACK

**Pull request merged**
