### PR TITLE
Use bitcoinj 0.15.8 (commit 5312aa3)

### PR DESCRIPTION
**Pull request by oscarguindzberg**
Fixes broadcast confirmation when connected to 1 bitcoin node

### CODE REVIEW

**Comment by oscarguindzberg** [comment]
Moved to WIP. Waiting to see the progress of https://github.com/bitcoinj/bitcoinj/pull/2054

**Comment by oscarguindzberg** [comment]
Pushed more code to bitcoinj:
- Revert fix to broadcast confirmation when connected to 1 bitcoin node by enabling listener.
- Add fix to broadcast confirmation when connected to 1 bitcoin node by setting the future immediately after tx broadcast.
- Disable dropPeersAfterBroadcast feature because it is considered risky.

**Comment by oscarguindzberg** [comment]
Removed WIP tag. This is ready to be merged in IMHO.

**Review by chimp1984 — COMMENTED** [review]
utACK

**Review by sqrrm — DISMISSED** [review]

**Comment by sqrrm** [comment]
@oscarguindzberg commit not signed

**Comment by oscarguindzberg** [comment]
@sqrrm sorry, I just signed the commit

**Review by sqrrm — APPROVED** [review]

**Pull request merged**
