### PR TITLE
WIP show strange guice behavior

### PR DESCRIPTION
**Pull request by christophsturm**
Can anybody explain this? why does bisq.seednode.GuiceSetupTest work even when the OfferBook registration is commented out?

@ManfredKarrer @ripcurlx @sqrrm @freimair

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
If you don't define a binding Guice creates a new instance each time when a dependey is injected. So thats why it is important to set bindings, specially if only 1 instance must exist. But best practice to define all bindings.

**Comment by christophsturm** [comment]
so in the context of bisq with its different guice modules per app this means that a component that is on the classpath but not in the module of that app will still be available but possibly with the wrong lifecycle (not singleton)

**Comment by ManfredKarrer** [comment]
yes.

**Comment by christophsturm** [comment]
so it would be better to use the `@Singleton` annotation on our own classes instead of binding them as `Singleton.class` in the module. then its always correct. binding is mostly for classes that you don't have control over.

**Pull request closed without merging**
