### PR TITLE
[WIP] Add initial version of release process

### PR DESCRIPTION
**Pull request by ripcurlx**

### CODE REVIEW

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Comment by ManfredKarrer** [comment]
@ripcurlx Oops sorry, saw too late that it was WIP...

**Comment by devinbileck** [comment]
I am starting to try out the new draft pull request feature in GitHub which prevents it from being merged until ready :)

**Comment by ripcurlx** [comment]
> I am starting to try out the new draft pull request feature in GitHub which prevents it from being merged until ready :)

Good point - I'll do it as a draft PR in the future 😄

**Pull request merged**
