### PR TITLE
List multiple stable coins

### PR DESCRIPTION
**Pull request by ripcurlx**
~- Tether (ERC-20 based token)~
  ~- Official project URL: https://tether.to/~
  ~- Official block explorer URL: https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7~ 
- DAI (ERC-20 based token)
    - Official project URL: https://makerdao.com/en
   - Official block explorer URL: https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359
- TrueUSD (ERC-20 based token) 
   - Official project URL: https://www.trusttoken.com/trueusd/
   - Official block explorer URL: https://etherscan.io/token/0x0000000000085d4780B73119b644AE5ecd22b376
- USD Coin (ERC-20 based token)
   - Official project URL: https://www.centre.io/usdc
   - Official block explorer URL: https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

Fixes https://github.com/bisq-network/bisq/issues/2369.

### CODE REVIEW

**Review by blabno — APPROVED** [review]
ACK

**Comment by ManfredKarrer** [comment]
@ripcurlx Is tether a Erc20Token? I thought its on OMNI....

**Review by ManfredKarrer — COMMENTED** [review]
Is tether a Erc20Token? I thought its on OMNI....

**Comment by ripcurlx** [comment]
> Is tether a Erc20Token? I thought its on OMNI....

@ManfredKarrer There are two implementations: OMNI and ERC-20. As mentioned in #2369 I'm not sure if it would cause confusion if we support both address types.

**Comment by ripcurlx** [comment]
I removed Tether for now because of the duplicate implementation with Omni and ERC-20.

**Comment by aejontargaryen** [comment]
https://www.youtube.com/watch?v=5KXHgh2rTTw?t=783

**Pull request merged**
