### PR TITLE
V1.1.6 for seednodes

### PR DESCRIPTION
**Pull request by ripcurlx**
Update seednode branch with release v1.1.6

### CODE REVIEW

**Comment by wiz** [comment]
Instead of reviewing this PR, how about we abandon the `seednode_temporaryfix` branch, and just make a new branch off the v1.1.6 release branch, with these 2 commits cherry-picked:

aa82dae66 Fix automatic 24 hour restart 
1d7a06333 Shutdown seed nodes every 24h

**Comment by wiz** [comment]
Actually, I just checked and it's the same end-result, so it doesn't matter. ACK 😁

**Comment by wiz** [comment]
Now running this branch on jhgcy2won7xnslrb.onion and seems :+1:

**Review by chimp1984 — APPROVED** [review]
utACK

**Pull request merged**
