### PR TITLE
Improvements for edit offer

### PR DESCRIPTION
**Pull request by ripcurlx**
Dependent on https://github.com/bisq-network/bisq-core/pull/102

### CODE REVIEW

**Review by ManfredKarrer — CHANGES_REQUESTED** [review]
Looks good as far I tested. Only small thing is that the title in the box "Set amount and price" is not correct anymore as we don't allow editing amount.

**Comment by ripcurlx** [comment]
@ManfredKarrer please merge bisq-network/bisq-core#102 for new translations

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Comment by ManfredKarrer** [comment]
Actually it was tested, just last commit was untested....

**Pull request merged**
