### PR TITLE
Extract btc to segwit addresses

### PR DESCRIPTION
**Pull request by oscarguindzberg**
Allow users to extract their BTC funds to external segwit addresses.
Users can't use segwit addresses to receive funds yet.
Please, don't merge until https://github.com/bisq-network/bisq/pull/4504 is merged.

### CODE REVIEW

**Review by chimp1984 — DISMISSED** [review]
utACK

**Review by chimp1984 — DISMISSED** [review]
utACK

**Comment by chimp1984** [comment]
@oscarguindzberg the WIP prefix can be removed, right?

**Review by wiz — DISMISSED** [review]
ACK - tested OK
Screen Shot 2020-09-22 at 0 19 54

**Comment by oscarguindzberg** [comment]
- Signed my commits. 
- Removed WIP.
- This PR is ready to be merged.

**Review by chimp1984 — COMMENTED** [review]
utACK

**Review by ripcurlx — APPROVED** [review]
utACK based on https://github.com/bisq-network/bisq/pull/4509#pullrequestreview-492824870

**Pull request merged**
