### PR TITLE
Fixes for issues 2944 and 2955

### PR DESCRIPTION
**Pull request by niyid**
1. Issue 2944 is a fix for a bug where the low and high statistics are flipped when the currency is a cryptocurrency.
2. Issue 2955 required adding a median computation as part of the statistics. This is a fairly straightforward feature add.

### CODE REVIEW

**Review by sqrrm — CHANGES_REQUESTED** [review]
I think your IDE might be messing up the files you touch. Both the formatting and some characters. Please take care to setup your environment correctly. There is a guide to get the formatting right. The issue with the characters I don't know about.

The actual fix might be correct but it's very hard to review among the mess.

**Comment by niyid** [comment]
> I think your IDE might be messing up the files you touch. Both the formatting and some characters. Please take care to setup your environment correctly. There is a guide to get the formatting right. The issue with the characters I don't know about.
> 
> The actual fix might be correct but it's very hard to review among the mess.

OK. I will reformat and check in. Is there any way I can see what you have? My compare says they are the same with my local.

**Comment by sqrrm** [comment]
Take a look under files changed tab here in the PR, https://github.com/bisq-network/bisq/pull/2972/files

If you have no diff locally your system must be changing stuff on its own. What OS are you on?

**Comment by niyid** [comment]
> Take a look under files changed tab here in the PR, https://github.com/bisq-network/bisq/pull/2972/files
> 
> If you have no diff locally your system must be changing stuff on its own. What OS are you on?

Do you refer to the contents of `displayStrings.properties`? I noticed that even on my local since I first pulled. I am using Fedora 22.

**Comment by niyid** [comment]
> > Take a look under files changed tab here in the PR, https://github.com/bisq-network/bisq/pull/2972/files
> > If you have no diff locally your system must be changing stuff on its own. What OS are you on?
> 
> Do you refer to the contents of `displayStrings.properties`? I noticed that even on my local since I first pulled. I am using Fedora 22.

OK. I see the Eclipse IDE formatting has put spaces in certain areas throwing the diff computation off.

**Comment by sqrrm** [comment]
Both displayStrings.properties and TradesChartsViewModelTest.java in which you seem to have put TradesChartsViewModel, and formatted with 8 space tabs, should be 4 spaces.

**Comment by niyid** [comment]
Apologies on the mistakes. I forked again and recommitted. Once again sorry for any inconvenience.

**Pull request closed without merging**
