### PR TITLE
Sort existing gradle-witness.gradle

### PR DESCRIPTION
**Pull request by blabno**
This should make comparison in future much easier.

### CODE REVIEW

**Comment by freimair** [comment]
I would love to see that in action! Thanks for showing that up!

However, I suggest we implement https://github.com/signalapp/gradle-witness/issues/34 ourselves, as the original seems to be unmaintained for quite some time and we have our own fork anyhow.

As for the implementation part, I already did https://github.com/bisq-network/gradle-witness/pull/2.

For going forward, I suggest we get the implementation merged, and then add the resulting gradle-witness.jar in this PR and be done with it.

**Comment by blabno** [comment]
@freimair I think your fix is better. But this PR also does sort the current contents of the file so it's a good start.

**Comment by freimair** [comment]
@blabno, Chris has merged the changes in the gradle-witness repo. Would you build the new gradle-witness.jar and include the binary in this PR so we can get this merged?

**Review by ripcurlx — DISMISSED** [review]
NACK - Could you please address https://github.com/bisq-network/bisq/pull/3585#issuecomment-554433803?

**Comment by blabno** [comment]
@ripcurlx @freimair new included.

**Review by freimair — APPROVED** [review]
Ack. gradle-witness.jar checksum matches, library checksums did not change.

**Pull request merged**
