### PR TITLE
Add and rename Portfolio History columns meaningfully

### LINKED ISSUE #3338: Add and rename Portfolio History columns meaningfully
* Rename "Transaction Fee" column to "Taker trading fee"
* Rename "Maker Fee" column to "Maker trading fee"
* Add maker or taker position of the local trader to "Offer type" column
* Add mining fees columns, named "Maker mining fee" and "Taker mining fee"

How the table looks currently

exportedhistory

Related to https://github.com/bisq-network/bisq/issues/2106

@sqrrm @niyid @wiz

### PR DESCRIPTION
**Pull request by niyid**
Fixes #3338

### CODE REVIEW

**Review by freimair — CHANGES_REQUESTED** [review]
I would love to see this contribution in our Bisq. However,

- please check the formatting
- please do not commit import-rearrangements

**Comment by niyid** [comment]
> I would love to see this contribution in our Bisq. However,
> 
> * please check the formatting
> * please do not commit import-rearrangements

@freimair 
Sorry about that. I have reverted to preexisting import arrangement and formatting.

Fixes #3338

**Comment by ripcurlx** [comment]
@niyid Please sign all your commits.

**Comment by niyid** [comment]
Recreated as #3785

**Pull request closed without merging**
