### PR TITLE
Update data stores for v1.9.6

### PR DESCRIPTION
**Pull request by ripcurlx**
Light node in light mode and full node in dark mode

Bildschirmfoto 2022-10-20 um 12 14 29
Bildschirmfoto 2022-10-20 um 12 14 35
Bildschirmfoto 2022-10-20 um 12 14 41
Bildschirmfoto 2022-10-20 um 12 14 45
Bildschirmfoto 2022-10-20 um 12 14 51
Bildschirmfoto 2022-10-20 um 12 14 56

### CODE REVIEW

**Comment by ripcurlx** [comment]
@jmacxx Could you please ACK this PR? Thanks!

**Comment by ghost** [comment]
@ripcurlx I am encountering a problem.  When I start a fresh Bisq it gets into a loop with the seednode, repeatedly downloading the same block of accountagewitness data.  (The code gives up after 10 attempts in order to not be an infinite loop).  The log shows that the received accountagewitness data is not put into the excluded keyset of subsequent download attempts which is why it repeats downloading the same data.

On my existing Bisq upgraded to this patch, it has the same problem:  receives 4559 accountagewitness but only adds 14 to the excluded set and receives the same 4559 records 10 times over before giving up.

https://github.com/bisq-network/bisq/pull/6340 is the relevant PR but **it works fine prior to the data store update**.  I've been running with that PR for over a month with updated seednodes and no issues.

Reverting back to v1.9.6 prior to this PR and it is OK -- see the two sets of logs below for comparison.




**Test case:**

- setup seednode v1.9.6 and bisq client v1.9.6 (two jmacxx seednodes are setup on v1.9.6).
- start bisq client with an empty data directory pointing to the seednode(s).
- bisq client should download any updates to tradestatistics and accountagewitness data.

&nbsp;

<details>
<summary>Log of fail case (this PR & fresh data directory):</summary>


    #################################################################
    Connected to node: jmacxxto7g7welbgcjwfpquzqaehmvp5bf6mqlz5nciho2sc6v7hbyid.onion:8000
    Received 8357 instances from a PreliminaryGetDataRequest
    BsqSwapOfferPayload: 35 / 54.281 kB
    RefundAgent: 1 / 1.427 kB
    Filter: 1 / 9.155 kB
    MailboxStoragePayload: 134 / 448.582 kB
    Mediator: 2 / 2.856 kB
    Alert: 2 / 2.505 kB
    AccountAgeWitness: 4569 / 138.319 kB
    OfferPayload: 606 / 1.088 MB
    SignedWitness: 7 / 6.691 kB
    TradeStatistics3: 3000 / 177.913 kB
    ################################################################# 
    Oct-20 09:21:52.405 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 14439 entries from SignedWitnessStorageService to the excluded key set of our request 
    Oct-20 09:21:52.405 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 2045 entries from AccountAgeWitnessStorageService to the excluded key set of our request 
    Oct-20 09:21:52.405 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 0 entries from TradeStatistics2StorageService to the excluded key set of our request 
    Oct-20 09:21:52.405 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 453 entries from TradeStatistics3StorageService to the excluded key set of our request 
    Oct-20 09:21:52.405 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 1024 entries from ProposalStorageService to the excluded key set of our request 
    Oct-20 09:21:52.406 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 544 entries from BlindVoteStorageService to the excluded key set of our request 
    Oct-20 09:21:52.410 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000.  
    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 5005 instances from a GetUpdatedDataRequest
    BsqSwapOfferPayload: 1 / 1.544 kB
    MailboxStoragePayload: 1 / 3.049 kB
    AccountAgeWitness: 4559 / 138.017 kB
    OfferPayload: 3 / 5.489 kB
    TradeStatistics3: 441 / 26.133 kB
    ################################################################# 
    Oct-20 09:22:31.484 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 5 protectedStorageEntries took 0 ms. 
    Oct-20 09:22:31.489 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 5000 persistableNetworkPayloads took 5 ms. 
    Oct-20 09:22:31.489 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataManager: DataResponse did not contain all data, so we repeat request until we got all data 
    Oct-20 09:22:31.490 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Processing GetDataResponse took 10 ms 
    Oct-20 09:22:33.603 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 14439 entries from SignedWitnessStorageService to the excluded key set of our request 
    Oct-20 09:22:33.603 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 2045 entries from AccountAgeWitnessStorageService to the excluded key set of our request 
    Oct-20 09:22:33.603 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 0 entries from TradeStatistics2StorageService to the excluded key set of our request 
    Oct-20 09:22:33.603 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 453 entries from TradeStatistics3StorageService to the excluded key set of our request 
    Oct-20 09:22:33.604 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 1024 entries from ProposalStorageService to the excluded key set of our request 
    Oct-20 09:22:33.604 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 544 entries from BlindVoteStorageService to the excluded key set of our request 
    Oct-20 09:22:33.607 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000.  
    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 5003 instances from a GetUpdatedDataRequest
    MailboxStoragePayload: 3 / 9.148 kB
    AccountAgeWitness: 4559 / 138.017 kB
    TradeStatistics3: 441 / 26.133 kB
    ################################################################# 
    Oct-20 09:22:50.452 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 3 protectedStorageEntries took 0 ms. 
    Oct-20 09:22:50.455 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 5000 persistableNetworkPayloads took 3 ms. 
    Oct-20 09:22:50.455 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataManager: DataResponse did not contain all data, so we repeat request until we got all data 
    Oct-20 09:22:50.455 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Processing GetDataResponse took 4 ms 
    Oct-20 09:22:50.472 [JavaFX Application Thread] INFO  b.c.d.m.n.RequestStateHashesHandler: We received from peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000 a GetDaoStateHashesResponse with 90 stateHashes 
    Oct-20 09:22:50.473 [JavaFX Application Thread] INFO  b.c.d.m.n.RequestStateHashesHandler: We received from peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000 a GetProposalStateHashesResponse with 5 stateHashes 
    Oct-20 09:22:50.492 [JavaFX Application Thread] INFO  b.c.d.m.n.RequestStateHashesHandler: We received from peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000 a GetBlindVoteStateHashesResponse with 5 stateHashes 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 14439 entries from SignedWitnessStorageService to the excluded key set of our request 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 2045 entries from AccountAgeWitnessStorageService to the excluded key set of our request 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 0 entries from TradeStatistics2StorageService to the excluded key set of our request 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 453 entries from TradeStatistics3StorageService to the excluded key set of our request 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 1024 entries from ProposalStorageService to the excluded key set of our request 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 544 entries from BlindVoteStorageService to the excluded key set of our request 
    Oct-20 09:22:52.467 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000.  
    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 5000 instances from a GetUpdatedDataRequest
    AccountAgeWitness: 4559 / 138.017 kB
    TradeStatistics3: 441 / 26.133 kB
    ################################################################# 
    Oct-20 09:22:50.452 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 3 protectedStorageEntries took 0 ms. 
    Oct-20 09:22:50.455 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 5000 persistableNetworkPayloads took 3 ms. 
    Oct-20 09:22:50.455 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataManager: DataResponse did not contain all data, so we repeat request until we got all data 
    Oct-20 09:22:50.455 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Processing GetDataResponse took 4 ms 
    Oct-20 09:22:50.472 [JavaFX Application Thread] INFO  b.c.d.m.n.RequestStateHashesHandler: We received from peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000 a GetDaoStateHashesResponse with 90 stateHashes 
    Oct-20 09:22:50.473 [JavaFX Application Thread] INFO  b.c.d.m.n.RequestStateHashesHandler: We received from peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000 a GetProposalStateHashesResponse with 5 stateHashes 
    Oct-20 09:22:50.492 [JavaFX Application Thread] INFO  b.c.d.m.n.RequestStateHashesHandler: We received from peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000 a GetBlindVoteStateHashesResponse with 5 stateHashes 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 14439 entries from SignedWitnessStorageService to the excluded key set of our request 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 2045 entries from AccountAgeWitnessStorageService to the excluded key set of our request 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 0 entries from TradeStatistics2StorageService to the excluded key set of our request 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 453 entries from TradeStatistics3StorageService to the excluded key set of our request 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 1024 entries from ProposalStorageService to the excluded key set of our request 
    Oct-20 09:22:52.464 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 544 entries from BlindVoteStorageService to the excluded key set of our request 
    Oct-20 09:22:52.467 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000.  
    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 5000 instances from a GetUpdatedDataRequest
    AccountAgeWitness: 4559 / 138.017 kB
    TradeStatistics3: 441 / 26.133 kB
    ################################################################# 
    Oct-20 09:23:07.489 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 0 protectedStorageEntries took 0 ms. 
    Oct-20 09:23:07.493 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 5000 persistableNetworkPayloads took 4 ms. 
    Oct-20 09:23:07.493 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataManager: DataResponse did not contain all data, so we repeat request until we got all data 

    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 5000 instances from a GetUpdatedDataRequest
    AccountAgeWitness: 4559 / 138.017 kB
    TradeStatistics3: 441 / 26.133 kB
    ################################################################# 
    Oct-20 09:23:16.138 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 0 protectedStorageEntries took 0 ms. 
    Oct-20 09:23:16.142 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 5000 persistableNetworkPayloads took 4 ms. 
    Oct-20 09:23:16.142 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataManager: DataResponse did not contain all data, so we repeat request until we got all data 

    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 5000 instances from a GetUpdatedDataRequest
    AccountAgeWitness: 4559 / 138.017 kB
    TradeStatistics3: 441 / 26.133 kB
    ################################################################# 
    Oct-20 09:23:23.142 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 0 protectedStorageEntries took 0 ms. 
    Oct-20 09:23:23.146 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 5000 persistableNetworkPayloads took 4 ms. 
    Oct-20 09:23:23.146 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataManager: DataResponse still did not contained all data but we requested already 10 times and stop now. 


</details>



<details>
<summary>Log of success case (v1.9.6 prior to this PR & fresh data directory) :</summary>

    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 6827 instances from a PreliminaryGetDataRequest
    BsqSwapOfferPayload: 36 / 55.824 kB
    BlindVotePayload: 141 / 605.591 kB
    RefundAgent: 1 / 1.427 kB
    Filter: 1 / 9.155 kB
    TempProposalPayload: 42 / 46.674 kB
    MailboxStoragePayload: 1130 / 3.837 MB
    ProposalPayload: 285 / 57.338 kB
    Mediator: 2 / 2.856 kB
    Alert: 2 / 2.505 kB
    AccountAgeWitness: 4055 / 122.759 kB
    OfferPayload: 613 / 1.101 MB
    SignedWitness: 519 / 496.253 kB
    ################################################################# 
    Oct-20 10:15:56.574 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Processing GetDataResponse took 3129 ms 
    Oct-20 10:15:56.576 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 14373 entries from SignedWitnessStorageService to the excluded key set of our request 
    Oct-20 10:15:56.577 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 4055 entries from AccountAgeWitnessStorageService to the excluded key set of our request 
    Oct-20 10:15:56.577 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 0 entries from TradeStatistics2StorageService to the excluded key set of our request 
    Oct-20 10:15:56.577 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 0 entries from TradeStatistics3StorageService to the excluded key set of our request 
    Oct-20 10:15:56.577 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 986 entries from ProposalStorageService to the excluded key set of our request 
    Oct-20 10:15:56.577 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 533 entries from BlindVoteStorageService to the excluded key set of our request 
    Oct-20 10:15:56.581 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000.  
    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 3637 instances from a GetUpdatedDataRequest
    BlindVotePayload: 11 / 54.66 kB
    MailboxStoragePayload: 1 / 2.924 kB
    ProposalPayload: 38 / 7.681 kB
    AccountAgeWitness: 521 / 15.772 kB
    SignedWitness: 66 / 63.105 kB
    TradeStatistics3: 3000 / 177.903 kB
    ################################################################# 
    Oct-20 10:16:09.678 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 3636 persistableNetworkPayloads took 1308 ms. 
    Oct-20 10:16:09.744 [JavaFX Application Thread] INFO  b.c.t.s.TradeStatisticsManager: maybeRepublishTradeStatistics took 64 ms. Number of tradeStatistics: 167903. Number of own trades: 0 
    Oct-20 10:16:09.748 [JavaFX Application Thread] INFO  b.c.d.n.l.n.RequestBlocksHandler: We request blocks from peer jmacx3kp7iku7eod6s4sasvxtdknakbsw2l2us5tyrk3q2634i222zid.onion:8000 from block height 750541. 
    Oct-20 10:16:09.765 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataManager: DataResponse did not contain all data, so we repeat request until we got all data 
    Oct-20 10:16:09.765 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Processing GetDataResponse took 1407 ms 
    Oct-20 10:16:09.795 [JavaFX Application Thread] INFO  b.c.d.n.l.n.RequestBlocksHandler: Sending of GetBlocksRequest message to peer jmacx3kp7iku7eod6s4sasvxtdknakbsw2l2us5tyrk3q2634i222zid.onion:8000 succeeded. 
    Oct-20 10:16:10.898 [processMailboxEntry-46] INFO  b.n.p.m.MailboxMessageService: Batch processing of 1131 mailbox entries took 1136 ms 
    Oct-20 10:16:11.785 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 14439 entries from SignedWitnessStorageService to the excluded key set of our request 
    Oct-20 10:16:11.786 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 4576 entries from AccountAgeWitnessStorageService to the excluded key set of our request 
    Oct-20 10:16:11.786 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 0 entries from TradeStatistics2StorageService to the excluded key set of our request 
    Oct-20 10:16:11.786 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 3000 entries from TradeStatistics3StorageService to the excluded key set of our request 
    Oct-20 10:16:11.786 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 1024 entries from ProposalStorageService to the excluded key set of our request 
    Oct-20 10:16:11.786 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 544 entries from BlindVoteStorageService to the excluded key set of our request 
    Oct-20 10:16:11.790 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000.  
    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 3000 instances from a GetUpdatedDataRequest
    TradeStatistics3: 3000 / 177.627 kB
    ################################################################# 
    Oct-20 10:16:19.467 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 0 protectedStorageEntries took 0 ms. 
    Oct-20 10:16:19.469 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 3000 persistableNetworkPayloads took 2 ms. 
    Oct-20 10:16:19.469 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataManager: DataResponse did not contain all data, so we repeat request until we got all data 
    Oct-20 10:16:19.469 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Processing GetDataResponse took 4 ms 
    Oct-20 10:16:21.476 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 14439 entries from SignedWitnessStorageService to the excluded key set of our request 
    Oct-20 10:16:21.477 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 4576 entries from AccountAgeWitnessStorageService to the excluded key set of our request 
    Oct-20 10:16:21.477 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 0 entries from TradeStatistics2StorageService to the excluded key set of our request 
    Oct-20 10:16:21.478 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 6000 entries from TradeStatistics3StorageService to the excluded key set of our request 
    Oct-20 10:16:21.478 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 1024 entries from ProposalStorageService to the excluded key set of our request 
    Oct-20 10:16:21.478 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 544 entries from BlindVoteStorageService to the excluded key set of our request 
    Oct-20 10:16:21.484 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000.  
    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 3000 instances from a GetUpdatedDataRequest
    TradeStatistics3: 3000 / 177.525 kB
    ################################################################# 
    Oct-20 10:16:32.508 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 0 protectedStorageEntries took 0 ms. 
    Oct-20 10:16:32.512 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 3000 persistableNetworkPayloads took 4 ms. 
    Oct-20 10:16:32.512 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataManager: DataResponse did not contain all data, so we repeat request until we got all data 
    Oct-20 10:16:32.512 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Processing GetDataResponse took 7 ms 

    Oct-20 10:16:33.595 [JavaFX Application Thread] INFO  b.n.p2p.peers.PeerManager: We have 3 connections open. Our limit is 12 
    Oct-20 10:16:34.520 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 14439 entries from SignedWitnessStorageService to the excluded key set of our request 
    Oct-20 10:16:34.522 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 4576 entries from AccountAgeWitnessStorageService to the excluded key set of our request 
    Oct-20 10:16:34.522 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 0 entries from TradeStatistics2StorageService to the excluded key set of our request 
    Oct-20 10:16:34.528 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 9000 entries from TradeStatistics3StorageService to the excluded key set of our request 
    Oct-20 10:16:34.529 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 1024 entries from ProposalStorageService to the excluded key set of our request 
    Oct-20 10:16:34.529 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: We added 544 entries from BlindVoteStorageService to the excluded key set of our request 
    Oct-20 10:16:34.540 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000.  
    #################################################################
    Connected to node: jmacx22rplg5ckci3s6xvxuuerycwve72wsote4o7suvryd435z3glid.onion:8000
    Received 751 instances from a GetUpdatedDataRequest
    TradeStatistics3: 751 / 41.749 kB
    ################################################################# 
    Oct-20 10:16:41.362 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 0 protectedStorageEntries took 0 ms. 
    Oct-20 10:16:41.362 [JavaFX Application Thread] INFO  b.n.p2p.storage.P2PDataStorage: Processing 751 persistableNetworkPayloads took 0 ms. 
    Oct-20 10:16:41.362 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataManager: DataResponse contained all data 

</details>

**Comment by ghost** [comment]
@ripcurlx after updating my seednodes to this patch, the clients running this patch work correctly.

**Review by ghost — APPROVED** [review]
ACK

**Review by bisq-github-admin-3 — APPROVED** [review]
utACK - based on https://github.com/bisq-network/bisq/pull/6385#pullrequestreview-1150204580

**Pull request merged**
