### PR TITLE
List RSK Smart Bitcoin (R-BTC)

### PR DESCRIPTION
**Pull request by harrigan**
### Asset name
 
RSK Smart Bitcoin

### Ticker
 
R-BTC

### Website
 
https://www.rsk.co/

### Block explorer
 
https://explorer.rsk.co/

### Additional technical requirements
 
There are no additional technical requirements.

### CODE REVIEW

**Comment by harrigan** [comment]
For background, this pull request is part of an entry to the [Sovryn Hackathon](https://gitcoin.co/issue/SovrynBTC/sovrython-2021-bounties/17/100025825) to provide a gateway in and out of the RSK sidechain. At the moment, the only way to exchange BTC for R-BTC is via centralised exchanges and relays, or via the decentralised but slow and technical RSK Powpeg. Bisq would provide a useful alternative.

**Review by chimp1984 — DISMISSED** [review]
utACK

**Review by ripcurlx — DISMISSED** [review]
utACK

**Comment by ripcurlx** [comment]
@harrigan There is a minor tab issue codacy is complaining about: https://app.codacy.com/gh/bisq-network/bisq/pullRequest?prid=7725154

**Review by ripcurlx — APPROVED** [review]
ACK

**Pull request merged**
