### PR TITLE
Cleanup gradle config

### PR DESCRIPTION
**Pull request by devinbileck**
I made a few changes at an attempt to cleanup and reorganize some of the gradle config.

- Remove duplicate openjfx dependencies in common/build.gradle.
- Use latest Gradle (4.10.2).
- Move desktop/gradle files to root gradle folder. Rather than having a gradle folder underneath the desktop folder, put its content in the root gradle folder to reduce duplication and have a single location for gradle content.
- Define some of the common buildscript dependencies in the root build.gradle so as
to reduce duplication and easier maintenance (i.e. updating version numbers). Gradle build files within sub folders should be able to apply these plugins without also having to define them as a dependency first. **I am not sure if this is a desired change. Feedback appreciated!**

### CODE REVIEW

**Comment by ripcurlx** [comment]
As gradle is not my expertise I think it would be best if @cbeams reviews these changes.

**Comment by devinbileck** [comment]
Also, is `desktop/settings.gradle` necessary? Should it be removed?

**Comment by ManfredKarrer** [comment]
I am also not competent to review those changes.

@cbeams Could you have a look if you find time?

**Comment by cbeams** [comment]
Closing as superseded by #1862, as it just made more sense for me to start from scratch there. Thanks, @devinbileck for getting this ball rolling. Please do have a look at that PR and let me know there if you have any questions or other stuff you'd like to follow up on.

**Pull request closed without merging**
