### PR TITLE
Use bitcoinj with connection handling audit fixes + Transaction.unCache() set confidence to null

### PR DESCRIPTION
**Pull request by oscarguindzberg**

### CODE REVIEW

**Comment by oscarguindzberg** [comment]
Not really "WIP", I assume we are using "WIP" for "Don't merge noncritical changes until further notice".

**Comment by ManfredKarrer** [comment]
Yes its just a signal that not ready to merge. U can use the draft mode (dropdown when creating a PR) then it cannot be merged.

**Comment by ManfredKarrer** [comment]
FYI we will delay all not DAO related PR after DAO launch.

**Comment by oscarguindzberg** [comment]
Including latest bisq's bitcoinj commit "Transaction.unCache() set confidence to null"

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Pull request merged**
