### PR TITLE
Removing undefined 'jdkfixFile' var from 'srcfiles' param

### PR DESCRIPTION
**Pull request by jonathancross**
Looks like this was overlooked in https://github.com/bitsquare/bitsquare/commit/f076a840f59b1db9d28a4a767eff4695da4598c0

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Hi Jonathan! Thanks for the PR, but it seems you have been on an outdated version. The current master and dev branch don't have that anymore. 0.5.2 is the latest version. Maybe with the DAO merge something got screwed up...

**Comment by jonathancross** [comment]
Hmmm.. confusing history, looks like you fixed this just 1 minute after commenting (10:57 PM) in pr  https://github.com/bitsquare/bitsquare/commit/55e4685244deceee7244540a84c7aa40bd358a09

Anyhow, happy its fixed  :-)

**Comment by ManfredKarrer** [comment]
Yes that i fixed after your PR. But there have been other things in there which have not been in the branches...

**Comment by jonathancross** [comment]
Hmmm, okay, I'll wipe out my fork and start fresh before making any additional PRs.

**Pull request closed without merging**
