### PR TITLE
List Pinkcoin (PINK)

### PR DESCRIPTION
**Pull request by aistrych**
- Official project URL: https://getstarted.with.pink/
- 1st official block explorer URL: https://chainz.cryptoid.info/pink/
- 2st official block explorer URL: https://www.coinexplorer.net/PINK

### CODE REVIEW

**Review by blabno — CHANGES_REQUESTED** [review]
NACK couldn't get any info from the web page

**Comment by aistrych** [comment]
@blabno Sorry, our website is being upgraded right now but will be available shorty. I will let you know as soon as it's ready.

**Comment by ManfredKarrer** [comment]
Open again once ready....

**Comment by aistrych** [comment]
@blabno @ManfredKarrer Ok, it's ready. You can check it (BTW: I can't reopen it - no such button).

**Review by blabno — COMMENTED** [review]
ACK

**Pull request merged**
