### PR TITLE
BsqWalletV2Test: Add invalid and dust send tests

### PR DESCRIPTION
**Pull request by alvasw**
The tests try to send 0 BSQ and the current dust amount in BSQ.

### CODE REVIEW

**Comment by alejandrogarcia83** [comment]
Hi @alvasw,
please resolve the merge conflict. Thank you!

**Review by alejandrogarcia83 — DISMISSED** [review]
utACK

**Comment by alvasw** [comment]
Rebased.

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
