### PR TITLE
Arbitration Request - Message Popup

### PR DESCRIPTION
**Pull request by niyid**
Issue #3328

### CODE REVIEW

**Comment by ripcurlx** [comment]
Please resolve the conflict with master.

**Review by freimair — CHANGES_REQUESTED** [review]
it seems by merging master you reverted some of your changes. Please use a `git rebase --onto master from to` and a force push to update your PR.

**Comment by ripcurlx** [comment]
Please resolve the build conflict.

**Comment by niyid** [comment]
Sure. Will do.

**Pull request closed without merging**
