### PR TITLE
List MirQuiX (MQX)

### PR DESCRIPTION
**Pull request by ghost**
- Official project URL: https://www.mirquix.org
- Official block explorer URL: https://explorer.mirquix.org

N.B. Explorer is currently being migrated from old chain, https://explorer.mirq.org

### CODE REVIEW

**Comment by blabno** [comment]
Squash commits into a single one and provide link to a transaction in explorer proving that we can conduct arbitration.

**Comment by WG91** [comment]
> Squash commits into a single one and provide link to a transaction in explorer proving that we can conduct arbitration.

Link to transaction :https://explorer.mirquix.org/tx/116ccfa064e7b6fdeec69937683fd9e435b9e05a19a798dce370482b697493f7

**Comment by ghost** [comment]
> Squash commits into a single one and provide link to a transaction in explorer proving that we can conduct arbitration.

Squashed into one line.

Link to random transaction: https://explorer.mirquix.org/tx/116ccfa064e7b6fdeec69937683fd9e435b9e05a19a798dce370482b697493f7

**Review by blabno — APPROVED** [review]
ACK

**Pull request merged**
