### PR TITLE
Add csv export to bsq tx view

### PR DESCRIPTION
**Pull request by chimp1984**

### CODE REVIEW

**Comment by pazza83** [comment]
Hi @chimp1984 

Thanks for this it is a good addition.

I was meaning to add a request to include a 'copy' button on this screen DAO > BSQ Wallet > Transactions

It would be good to include a 'copy' button on the columns:

Transaction ID
Information

Lots of times i end up having to open the link and then copying from there. would be good if users could just copy the above in the app.

**Comment by ripcurlx** [comment]
@chimp1984 Could you please remove the unused `reportColumns` variable https://app.codacy.com/gh/bisq-network/bisq/pullRequest?prid=6748977 Thanks!

**Review by ripcurlx — DISMISSED** [review]
utACK except the little change request by Codacy

**Comment by chimp1984** [comment]
> utACK except the little change request by Codacy

Done.

**Comment by pazza83** [comment]
@chimp1984 

Does this is include the request add a request to include a 'copy' button on this screen DAO > BSQ Wallet > Transactions?

If not happy to make a new Git Hub issue for it.

It is only a small change but would be helpful.

**Comment by chimp1984** [comment]
> @chimp1984
> 
> Does this is include the request add a request to include a 'copy' button on this screen DAO > BSQ Wallet > Transactions?
> 
> If not happy to make a new Git Hub issue for it.
> 
> It is only a small change but would be helpful.


No thats not included. Maybe you can make a issue with checkboxes of all the open suggestions. So we have that all in one place.

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
