### PR TITLE
List Mogwaicoin (MOG)

### PR DESCRIPTION
**Pull request by darkfriend77**
Please add **Mogwaicoin (MOG)** to **BISQ**
**Date:** Mon Dec 17 22:45 GMT+1000

Official project URL: https://www.mogwaicoin.org/
Official block explorer URL: http://explorer.mogwaicoin.org/

Github: https://github.com/mogwaicoin

Thanks,
Cedric (mogwai@mogwaicoin.org)

### CODE REVIEW

**Comment by ripcurlx** [comment]
@darkfriend77 It is not mentioned in the asset listing doc yet, but your commit must be signed as well to make it through our GitHub merge requirements: https://help.github.com/en/github/authenticating-to-github/signing-commits.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - commit must be signed

**Comment by darkfriend77** [comment]
Okay, I signed the commit.

**Comment by darkfriend77** [comment]
@ripcurlx can you please reconsider the signed pull request, :-) regards Cedric

**Comment by darkfriend77** [comment]
@ripcurlx @ManfredKarrer 
I've read about the https://github.com/bisq-network/proposals/issues/153 listing issue, there is a  comment about listing technical or conceptual interesting coins, I think Mogwaicoin with the Game "The World of Mogwais" on top is a conceptual new and really interesting thing please consider the listing... or coin has been growing since we have been able to show of the mobile version and have started with the asian community, which is much more tied to the background of the story. Please check https://www.coingecko.com/de/munze/mogwai,

Regards 
Cedric

The framework of the game is already live and playable, however we are working on the mobile implementation where we have an alpha running, here a small pitch of what it is ...

**The World of Mogwai is a Blockchain based Game** 
where you interact with Mogwais. Its concept is based on popular role playing games and will include some features as found in trading card games. The story about "The World of Mogwais" is based on a cultural background in Asia and of the western fictional interpretation in the film "Gremlins". However, the story and the interpretation we are following is not limited to these universes. It involves creative ideas and fictional realities without any relation to culture or religious backgrounds.
**Burning Concept**
The technical implementation of burning Mogwaicoins ($MOG) is processed by making a transaction to a mirror address. A mirror address is qualified by its public key not being in the range of valid private keys governed by the secp256k1 ECDSA standard used by Mogwaicoin. This will lead into a transaction where the sent coins will stay on the receiving address forever, because there isn't a valid private key to access the funds on the mirror address.
Another feature of the mirror address is that it has a unique relation to a public key and its public address. Ownership of the mirror address can be proven by exposing a signed message containing the public key and being signed by its public address.
The Concept of burning coins implements a unique deflationary factor. And is used as the only way of interacting with The World of Mogwais.
**Interaction Concept**
Each mirror address is a so-called link into the world of mogwais, with an initial transaction to this mirror address you are activating the bonding process. The creation process for the mogwai consists of different factors including static and randomized factors like mirror address, blockhash, block height and so on. Interaction validation occurs by validating sent coins coming from the linked address at least partially.

**Pull request closed without merging**
