### PR TITLE
Support handling of removed assets.

### PR DESCRIPTION
**Pull request by ManfredKarrer**
- cross check the isCryptoCurrency method if the symbol matches any
fiat currency and of both not match consider it still a CC. In case of
a removed asset it was returning false before which caused an issue in
the trade currency pair showing both sides as BTC.
- Show N/A for name in case the asset is not available.

The code mostly operates with the ticker symbol which gets stored in
the offer, so even an asset is removed traders who have that asset in
their account list can trade without problems.
Tested create offer, take offer and executing a trade.

### CODE REVIEW

**Review by ripcurlx — APPROVED** [review]
utACK

**Review by cbeams — APPROVED** [review]
utACK

**Comment by ManfredKarrer** [comment]
Fixing tests and add some changes...

**Comment by ManfredKarrer** [comment]
As the additional changes have been non trivial I leave it for another ACK.

**Comment by ripcurlx** [comment]
utACK

**Pull request merged**
