### PR TITLE
Remove emzy bsq explorer

### PR DESCRIPTION
**Pull request by HenrikJannsen**

### CODE REVIEW

**Review by alejandrogarcia83 — DISMISSED** [review]
utACK

**Review by alejandrogarcia83 — DISMISSED** [review]
utACK

**Comment by alejandrogarcia83** [comment]
I can't merge this PR due to merge conflicts. Please resolve them. Thank you!

**Comment by HenrikJannsen** [comment]
If we remove `new BlockChainExplorer("mempool.bisq.services (@devinbileck)", "https://mempool.bisq.services/bisq/tx/", "https://mempool.bisq.services/bisq/address/")` we don't have any BSQ explorer as the one from emzy got removed as well.

@devinbileck Is it ok to leave that BSQ exlorer until we have added a new one?

**Comment by HenrikJannsen** [comment]
Rebased

**Comment by devinbileck** [comment]
> If we remove `new BlockChainExplorer("mempool.bisq.services (@devinbileck)", "https://mempool.bisq.services/bisq/tx/", "https://mempool.bisq.services/bisq/address/")` we don't have any BSQ explorer as the one from emzy got removed as well.
> 
> @devinbileck Is it ok to leave that BSQ exlorer until we have added a new one?

Yes, that is fine to leave it running for now.

**Comment by runbtc** [comment]
You can add my BSQ explorer. It is not available via clearnet, but is available via onion service.
http://runbtcxzz4v2haszypwbrn2baqdo7tlwt6dw7g27cwwaootd4gktwayd.onion/

**Comment by HenrikJannsen** [comment]
Still relevant

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
