### PR TITLE
Bump gradle wrapper to version 5.6.4

### PR DESCRIPTION
**Pull request by sam-sla**
Current version 4.10.2 is over one year old and newer versions of gradle seem to improve build times, from close to 3min to just over 2min on my Linux machine.
Gradle 5 and above requires Java 8, and that requirement is met since the build instructions mention Java 10 and 11.

Original PR https://github.com/bisq-network/bisq/pull/3422 closed due to build problems.

### CODE REVIEW

**Comment by sam-sla** [comment]
@ripcurlx I think the same happened here... Is gradle 5.6.4 causing problems with TravisCI?

**Comment by ripcurlx** [comment]
> @ripcurlx I think the same happened here... Is gradle 5.6.4 causing problems with TravisCI?

Yes, your PR got Abuse detected again. Maybe your account got flagged by Travis? Let me quickly open a branch myself and cherry-pick your commits to make sure it is not because of the Gradle update.

**Comment by ripcurlx** [comment]
I guess you need to contact support@travis-ci.com to get your account unflagged again.

**Comment by ripcurlx** [comment]
Closing as superseded by #3627

**Comment by sam-sla** [comment]
> I guess you need to contact [support@travis-ci.com](mailto:support@travis-ci.com) to get your account unflagged again.

Thanks, I've contacted them :crossed_fingers:

**Pull request closed without merging**
