### PR TITLE
List Horizen (ZEN)

### PR DESCRIPTION
**Pull request by tarrenj**
* Official project URL: https://horizen.global/
* Official block explorer URL: https://explorer.horizen.global/

Continuation of https://github.com/bisq-network/bisq/pull/1651

Resubmitting bisq-network/bisq-assets#114 from the old bisq-assets` repo, which had positive comments from @cbeams and @ManfredKarrer, but did not have a comment containing "ACK".

Tested with ./gradlew :assets:build

### CODE REVIEW

**Comment by tarrenj** [comment]
Closing until I can fix the Travis CI error.

**Comment by devinbileck** [comment]
@tarrenj The CI build failure is a result of JDK10 no longer available for download from Oracle. All the CI builds are failing due to this. See https://github.com/bisq-network/bisq/issues/1787.

**Comment by tarrenj** [comment]
@devinbileck Ahh, thanks for the info! Reopening this PR. I'll keep an eye on it and close it again if there's any updates required on my end when the JDK version's bumped.

**Comment by blabno** [comment]
@pahanzt please rebase against master and resolve conflicts.

**Comment by tarrenj** [comment]
I'm guessing these failures are because of a bad merge and not broken CI like last time? I'll look further into this and resolve in the coming week.

**Comment by ManfredKarrer** [comment]
Plese rebase on master again. The PR should only have 1 single commit as defined in the instructions.

**Pull request closed without merging**
