### PR TITLE
Temporarily disable wiz's monero explorer node

### PR DESCRIPTION
**Pull request by wiz**
Will re-enable later after making a new monero node on a different server

### CODE REVIEW

**Review by ripcurlx — APPROVED** [review]
utACK

**Comment by ghost** [comment]
There's a filter for that in 1.5.0 https://github.com/bisq-network/bisq/pull/4736

**Comment by wiz** [comment]
@jmacxx must have missed the memo, oh well, will re-add it later

**Comment by wiz** [comment]
@jmacxx I didn't get the memo about that, oh well, I will just re-add it later

**Pull request merged**
