### PR TITLE
Clarify wording on buy/sell offerbook button

### PR DESCRIPTION
**Pull request by ghost**
Implements a request from a matrix user:

**davterra_**
This has probably come up before.....i just connected to this chat.....but having spent a career in trading, I find the wording on the "sell" buttons to be very confusing. When you sell, you don't "take" an "offer". I humbly suggest changing the wording on the red sell buttons to "Sell to this buyer"  and on the green buy buttons to "Buy from this seller". From a trading standpoint, they should say "Hit Bid" & "Take Offer" but I realize could be equally confusing to someone with no trading experience. My suggested wording seems to be clearer for anyone/everyone. Thanks for reading.

---

buy

sell

### CODE REVIEW

**Comment by ghost** [comment]
What about just "Buy" / "Sell"?

**Comment by pazza83** [comment]
I have sent davterra_ a DM in Matrix. Would be good to get them to chime in

**Comment by ghost** [comment]
I ran with this change on my main Bisq for quite some time and it was better.  With `BUY FROM THIS SELLER` the UI felt clearer & more intuitive than the old `TAKE OFFER`.  Just my 2c.

**Comment by ripcurlx** [comment]
@chimp1984 @m52go @UX-P Any thoughts on this? IMO those changes look fine, but I want more contributors to weigh in on this.

**Comment by chimp1984** [comment]
I think button text should not be that long, specially not in repeated rows and the dual usage of buy/sell in the text is also a bit strange.

**Comment by UX-P** [comment]
Hi @ripcurlx, I do agree that although the message is clear, the button text is too long.

@chimp1984 I know there was an initial reason for ‘the ‘Take offer’ wording. With the new top-level navigational change, does this reasoning still apply? Otherwise, a ‘Buy’ and 'Sell' button as @xyzmaker123 suggested is the more conventional option. Below is an example of trading platforms implementing this wording in a similar context.

Example in Local Bitcoin 
Screenshot 2022-08-24 at 19 50 19


Example in Local Monero
Screenshot 2022-08-24 at 19 38 49

**Comment by ghost** [comment]
I have reworded the buttons to "BUY" and "SELL" per https://github.com/bisq-network/bisq/pull/6296#issuecomment-1226052634

**Comment by ripcurlx** [comment]
> I have reworded the buttons to "BUY" and "SELL" per [#6296 (comment)](https://github.com/bisq-network/bisq/pull/6296#issuecomment-1226052634)

I'm also for changing it to "BUY" and "SELL" 👍 

@jmacxx Could you please rebase and force push so it can be merged? Thanks!

**Comment by ghost** [comment]
Rebased as requested.

**Review by ripcurlx — DISMISSED** [review]
ACK

**Comment by ripcurlx** [comment]
@jmacxx It seems to be your commit hasn't been properly signed.

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
