### PR TITLE
Add payment method: moneygram

### PR DESCRIPTION
**Pull request by blabno**
Fixes: https://github.com/bisq-network/bisq-desktop/issues/1050

### CODE REVIEW

**Comment by blabno** [comment]
Need to wait for https://github.com/bisq-network/bisq-common/pull/21 to be merged and then retrigger the build.

**Comment by ripcurlx** [comment]
@blabno Did you check allow edits by maintainer? I'd like to push a little change regarding duplicate colons.

**Comment by blabno** [comment]
Yes I did.

**Comment by ripcurlx** [comment]
Weird. I tried it with https url and git@github.com url and both return the same permission error:
```
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/blabno/exchange.git
 ! [remote rejected]     blabno-feature/money-gram-payment-method -> blabno-feature/money-gram-payment-method (permission denied)
error: failed to push some refs to 'https://github.com/blabno/exchange.git'
```

**Comment by blabno** [comment]
I've unchecked and checked again.

**Comment by ripcurlx** [comment]
In the confirmation it says the receipt has to show full name, city, country and amount, but in the fields to copy there is only city displayed. Are all fields required?
bildschirmfoto 2018-04-27 um 16 50 37

**Comment by ripcurlx** [comment]
I guess we have to wait for an answer by @alfsbs to your [comment](https://github.com/bisq-network/bisq-desktop/issues/1050#issuecomment-384974838) if country and city is needed for the buyer to do the transfer.

**Comment by ripcurlx** [comment]
Besides the issue with country/city ACK

**Comment by alfsbs** [comment]
Regarding the confirmation, as manfred said, it is called Athorisation # not MTCN, and the required fields are country, state and name:
“When using MoneyGram the BTC buyer has to send the Authorisation # and a photo of the receipt by email to the BTC seller. The receipt must clearly show the seller’s full name, country, state and the amount. The buyer will get displayed the seller’s email in the trade process.”

**Comment by blabno** [comment]
@alfsbs is `state` always required? In the code, I found lot's of places with conditional logic based on country code, i.e.:
```
if (BankUtil.isStateRequired(payload.getCountryCode()))
```

**Comment by alfsbs** [comment]
@blabno state is not always required, but when it is its mandatory. Would you need me to confirm for which countries it is mandatory?

**Comment by blabno** [comment]
@alfsbs I think we can rely on BankUtil for now.
@ManfredKarrer  could you merge 
https://github.com/bisq-network/bisq-common/pull/21 ? We could then retrigger builds in core and desktop and close this PR.

**Comment by ManfredKarrer** [comment]
NACK. It still does not support multiple currencies.

**Comment by blabno** [comment]
Revolut, OkPay and Uphold support 23 currencies. Should we support the same currencies as well in this case @alfsbs?

**Comment by alfsbs** [comment]
@blabno Moneygram supports 47 [currencies](https://money.moneygram.com.au/information/currencies-and-countries), but it does not support QAR, RON, so we can implement it for the 21 other currencies.

**Comment by ripcurlx** [comment]
@alfsbs @blabno What is the current state of this PR? Do you still wait for answers from our side? Just want to slowly prepare everything that should be included in the next release.

**Comment by alfsbs** [comment]
We are waiting for the merge. @ManfredKarrer do you think you could merge it?

**Comment by ManfredKarrer** [comment]
I think it is not completed. Missing the 47 currencies.

**Comment by alfsbs** [comment]
@ManfredKarrer, do you think we can implement it for the 21 commented currencies please confirm so @blabno blabno can finalize the PR. Thanks

**Comment by ManfredKarrer** [comment]
I would prefer to get all currencies in, otherwise that will likely stick like it is for longer time. But if nobody implements it and if the current implementation is complete beside that I am ok to go with that as well.

**Comment by ripcurlx** [comment]
ACK: Tested it locally and besides a translation issue in core everything worked so far.

**Pull request merged**
