### PR TITLE
Update tor-browser to v11.5.2 / tor-binary to v0.4.7.10

### PR DESCRIPTION
**Pull request by ripcurlx**

### CODE REVIEW

**Comment by ripcurlx** [comment]
Tested it on macOS 12.6 without any problems. @devinbileck Could you please give it a shot on Windows and @jmacxx on Linux? Thanks!

**Review by ghost — APPROVED** [review]
ACK (Linux)

**Review by cd2357 — COMMENTED** [review]
utACK

**Comment by ripcurlx** [comment]
@devinbileck ☝️

**Comment by devinbileck** [comment]
@ripcurlx sorry, I was finally able to rid myself of Windows ;)
I currently don't even have a Windows VM.

**Comment by ripcurlx** [comment]
> @ripcurlx sorry, I was finally able to rid myself of Windows ;) I currently don't even have a Windows VM.

Good to hear 😄  - I'll try it on a VM then.

**Comment by ripcurlx** [comment]
Worked for me on Windows as well.

**Review by bisq-github-admin-3 — APPROVED** [review]
utACK - based on individual reviews

**Pull request merged**
