### PR TITLE
Generate RPM package

### PR DESCRIPTION
**Pull request by devinbileck**
An RPM package is now generated as part of the Linux packaging script.
The packaging script can be run on any Debian or Redhat based
system and will generate both a deb and rpm package.

Resolves https://github.com/bisq-network/bisq/issues/401

### CODE REVIEW

**Comment by devinbileck** [comment]
This is pending on https://github.com/bisq-network/bisq/pull/2190 to be approved and merged.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
@devinbileck Now as the linux build scripts are merged, could you please resolve the conflict and I'll merge the PR.

**Comment by devinbileck** [comment]
@ripcurlx please take a look now.

**Comment by ripcurlx** [comment]
@devinbileck Can you please resolve the conflicts and I'm happy to review and merge. 😄

**Review by ripcurlx — APPROVED** [review]

**Comment by ripcurlx** [comment]
@devinbileck I've merged the last part which was necessary because of another approved PR.

**Pull request merged**
