### PR TITLE
Fix/improve clickable areas of toggle buttons

### LINKED ISSUE #6263: Enable Offers toggle-button activated when not clicking it
### Description

Enable/Disable Offers toggle-button activated if clicked outside of it, to the right.

#### Version

v1.9.2 (`master` branch)

1)  Go to PORTFOLIO -> MY OPEN OFFERS
2)  Click wide to right of the `Enabled` toggle-button (not in the toggle-button area).
3)  Offers are disabled/enabled if clicking outside of the toggle-button area (all the way to the edge of the window).

### Expected behaviour

Offers are not enabled or disabled if not clicking inside the toggle-button.

### Actual behaviour

Offers are  enabled or disabled if clicking way to the right of the toggle-button.

Not a big deal, but confused me before I understood why all my offers were disabled.

### Screenshots

Offers-Enable-Disable-Button

#### Device or machine

Ubuntu 20.04.4 LTS

### PR DESCRIPTION
**Pull request by Android-X13**
Fixes #6263

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
utACK

**Comment by ghost** [comment]
@Android-X13 looks great.  May I request an additional thing?
Could you fix the clickable area of toggle buttons in DAO -> Facts & Figures -> Bsq Supply screen?  There its possible to click on a toggle button and it toggles the one below.

image

**Comment by Android-X13** [comment]
Hi @jmacxx,
The author of the relevant code resorted to a hack in order to decrease the height of the switches and the vertical gap between them:

switch hack

The switches work best in their default height although the gaps increase quite enough which isn't what was wanted.
Unless there's a better way to shrink the toggle's height symmetrically instead of doing hacks, my only solution to this would be to decrease the overlapping between them. But this would mean that their vertical gaps would increase a bit. And the clickable area still won't be ideal (but it will be better than now).
If you still want this, should I push it in this branch?

**Comment by ghost** [comment]
> the clickable area still won't be ideal (but it will be better than now).

Yes, I think an improvement would be worth it.  To my mind it is similar enough to include in this branch.  Thanks.

**Comment by Android-X13** [comment]
Before:

Before

After:

After

The clickabe area is better now and the vertical distance between the switches isn't increased (too) much.
It could be better but the gaps would also grow more.. I think the compromise between height and clickable areas is acceptable now

**Comment by Android-X13** [comment]
Kindly disregard my ramblings in the last comment above. The vertical gaps between toggles in BSQ SUPPLY do increase like shown, but their clickable area is ideal now.

Also, somehow I managed to screw up this PR. Really sorry about that. I'm new to git...

**Review by ghost — APPROVED** [review]
ACK

**Review by ripcurlx — APPROVED** [review]
utACK - based on https://github.com/bisq-network/bisq/pull/6307#pullrequestreview-1072180475

**Pull request merged**
