### PR TITLE
WIP Updated netlayer, jtorctl and tor-binary

### PR DESCRIPTION
**Pull request by freimair**
# Changes
- the latest tor binary
- a fresh jtorctl release (which should at least give some more information in #2398
- a fresh netlayer release (which might bring us forward in #1943)

# Before merging
We need a tester for each platform. I did my linux part and it works nicely.

Missing tests: 
- [x] Windows
- [x] OSX

The testing effort needed is simply building bisq and starting it up. If that works (or at least no other than it did before), the branch can be merged.

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
@freimair If a PR is not ready for merge/review please mark them with prefix WIP and use the draft feature (new in GH - when you create the PR you can select it as draft)

**Comment by freimair** [comment]
@ManfredKarrer the PR is ready for merging and review. That is exaclty the point. I cannot test on OSX neither can I test on Windows. The reviewing process is meant to make it unlikely that a merge does break master. So please review and make it unlikely that the merge is going to break master by testing on OSX for example.
Since we still do not have integration testing on different platforms, we have to do it that way...

**Comment by devinbileck** [comment]
I gave this a test on my primary Windows machine and it ran without issue. However, on my Windows VM I still encounter the auth cookie issue. But this time the behavior is slightly different. It is raising an IOException wrapped in a TorCtlException. So instead of performing onSetupFailed, it is performing restartTor.
image

**Comment by freimair** [comment]
ah yes, and although the [Tor spec](https://github.com/torproject/torspec/blob/master/control-spec.txt#L1700) says that with this new version the default HS addresses are of the new format, a short chat with a tor dev resulted in https://trac.torproject.org/projects/tor/ticket/29669. so no worries. we are still with the old address format

**Comment by ManfredKarrer** [comment]
@freimair Did a quick test and all looks ok on OSX

**Review by ManfredKarrer — APPROVED** [review]
ACK

**Pull request merged**
