### PR TITLE
Update strings to reflect Bisq is exchange network

### PR DESCRIPTION
**Pull request by devinbileck**
Motivated by changes done to the website, as described in
https://github.com/bisq-network/bisq-website/pull/280

### CODE REVIEW

**Review by RiccardoMasutti — DISMISSED** [review]

**Comment by freimair** [comment]
is "The exchange" a marketing statement?

@m52go @ManfredKarrer @ripcurlx @sqrrm

**Comment by m52go** [comment]
I'm not sure where/how "the exchange" wording originated, but like I said in [this comment](https://github.com/bisq-network/bisq-website/pull/280#issue-336867176), it's pretentious and unusual.

Debian - _a_ free operating system (OS) for your computer ([link](https://www.debian.org/))
Qubes -  _a_ reasonably secure operating system ([link](https://www.qubes-os.org/))
Bitcoin - _an_ experimental digital currency ([link](https://github.com/bitcoin/bitcoin))

I'll wait to merge the website changes until this gets more consensus since it's a relatively meaningful change (i.e., definition of the project).

**Comment by devinbileck** [comment]
Initially I felt "The" was a valid statement. But after @m52go pointed it out, I have to agree as I am all for humility.

**Comment by ripcurlx** [comment]
On hold until consensus is found in bisq-network/bisq-website#280

**Review by RiccardoMasutti — APPROVED** [review]

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
