### PR TITLE
Update data stores for v1.5.0

### PR DESCRIPTION
**Pull request by ripcurlx**
Light node in light mode and full node in dark mode

Bildschirmfoto 2020-11-13 um 12 00 02
Bildschirmfoto 2020-11-13 um 11 59 57
Bildschirmfoto 2020-11-13 um 11 59 52
Bildschirmfoto 2020-11-13 um 11 59 48
Bildschirmfoto 2020-11-13 um 11 59 43
Bildschirmfoto 2020-11-13 um 11 59 40

### CODE REVIEW

**Comment by ripcurlx** [comment]
@chimp1984 Could you please have a look at the trade statistics 3 data store? Thanks!

**Comment by sqrrm** [comment]
I wonder about the TradeStatistics3Store. It's different size to what I get when I run from my own old instance. I thought they should be the same (apart from new trades within the last couple of minutes after my restart).

The other stores look good.

**Comment by chimp1984** [comment]
Git lfs download takes ages... Will test once its downloaded. I have a local file which is about 20 kb larger, but might be the missing prune...

**Comment by chimp1984** [comment]
I have roughly the same file size with a fresh app. So TradeStatistics3Store_1.5.0 looks good to me.

**Review by chimp1984 — APPROVED** [review]
utACK

**Review by sqrrm — APPROVED** [review]
ACK

**Pull request merged**
