### PR TITLE
List BitDaric (DARX)

### PR DESCRIPTION
**Pull request by bitdaric**
- Official website: https://www.bitdaric.live/
- Official block explorer: https://explorer.bitdaric.live/

Changed code as comments (previous pull closed here https://github.com/bisq-network/bisq/pull/1965)

### CODE REVIEW

**Review by blabno — APPROVED** [review]
ACK

**Comment by blabno** [comment]
Please resolve conflicts (keep it as 1 commit)

**Comment by blabno** [comment]
@bitdaric squash those commits into a single one

**Comment by bitdaric** [comment]
@blabno   https://github.com/bisq-network/bisq/pull/2309

**Pull request closed without merging**
