### PR TITLE
Adjust numbers alignment

### LINKED ISSUE #3991: Fix numbers alignment in GUI
### Description

Not a bug per-se, but really not up to standards and expectations.

Numbers have to be aligned by comma. Only so can one easily assess the number and its relation to the numbers next to it. Especially when it comes to finances.

Given I am a heavy trader and I see that a software does not even manage to display monetary numbers professionally, i would not even bother using the software + if someone asks me, I would immediately tell them so.

### Expected behaviour

Screenshot from 2020-02-19 13-16-27_fixed

### Actual behaviour

Screenshot from 2020-02-19 13-16-27

There are other places in the GUI where the same thing happens.
Seems like an easy fix though.

### PR DESCRIPTION
**Pull request by freimair**
Fixes #3991

This PR fixes the most visible number alignment issues. Omitted the stuff in [Funds] and in other places, because there would be more to it than just pushing around css classes.

Here are some impressions:
Screenshot from 2020-04-14 20-31-40
Screenshot from 2020-04-14 20-31-27
Screenshot from 2020-04-14 20-31-13

### CODE REVIEW

**Comment by ripcurlx** [comment]
The problem I see with that is that @pedromvpg wanted to have the columns aligned in the same way except for the last one. To make this possible I implemented a solution that works with monospace fonts. As this was dropped because of font style issues, the alignment doesn't work properly anymore.

**Comment by freimair** [comment]
just to check if I understood correctly:

- you ditched Monospace font because of aesthetic reasons (so no alignment anymore)
- we do not want aligned comma points because of @pedromvpg and column alignment

I understand that @pedromvpg design (with monospace) had the numbers aligned by comma. So he did design it that way didn't he? Only after ditching the monospace font, the numbers became misaligned.

Given the great work @pedromvpg did with designing the UI, I somehow doubt that he would consider having number not aligned by its comma as aesthetic. Especially in an application where the numbers are its heart and soul.

**Comment by freimair** [comment]
still relevant

**Comment by cd2357** [comment]
ACK

I tested it and and indeed, numbers are much more readable when they're right-aligned.

Looks like a simple and elegant solution (using CSS classes), I'd say if other ongoing UI work "conflicts" with this, it would be trivial to just rebase and merge, or somehow integrate it if necessary.

So I'd say this PR it's worth merging.

**Comment by freimair** [comment]
I still think this is relevant. @ripcurlx would you assign @pedromvpg for review or merge it right away?

**Comment by ripcurlx** [comment]
> I still think this is relevant. @ripcurlx would you assign @pedromvpg for review or merge it right away?

Unfortunately I'm not able to assign him as reviewer. Will ping him on keybase.

**Comment by cd2357** [comment]
Still relevant (even now, 6 months after PR was created).

Can someone with a better understanding of this shortly indicate what is holding it back? Is it:

a) this PR is fine, but needs final approval from @pedromvpg 
b) this PR is fine, just needs to resolve conflicts with the latest master (since its not clear if / when @pedromvpg will have time to review)
c) this PR needs some adjustments first (see comments above re: last column)
d) this PR has to wait, cause other UI changes are coming soon (new design?) and merging this would complicate the upcomnig UI efforts
e) smth else

**Comment by pedromvpg** [comment]
Hey, 

I won't be able to compile until later tonight.
Can you post a before and after screenshot to compare the changes?

Thanks

**Comment by ripcurlx** [comment]
> Hey,
> 
> I won't be able to compile until later tonight.
> Can you post a before and after screenshot to compare the changes?
> 
> Thanks

Hi @pedromvpg! Please see https://github.com/bisq-network/bisq/pull/4171#issue-403347877 . @freimair basically changed the alignment for all number columns to right-align instead of left-align.

**Comment by pedromvpg** [comment]
I think keeping all of the columns left aligned and the last column centered if its a column with check boxes would be the easiest to read.

I'm of the preference of keeping the 'Amount' column alignment consistent with the rest more than keeping the commas aligned.

image

image

**Comment by pedromvpg** [comment]
@freimair 
My priority is to keep the overall presentation clean. By aligning the comas, mostly on the amount column, you think would increase the ease of legibility of the numerals without hurting the legibility of the overall table?

In my view it helps in the specifics but it really makes the table look messy.

**Comment by cd2357** [comment]
> I'm of the preference of keeping the 'Amount' column alignment consistent with the rest more than keeping the commas aligned.

I agree with @freimair on this, right-aligning for numeric values makes them more readable because of the comma alignment. [Bitfinex](https://www.bitfinex.com/trading) and [Kraken](https://trade.kraken.com/charts) dashboards right-align them as well.

The [material design guidelines](https://material.io/components/data-tables) also default to text as left-aligned, numbers as right-aligned.

> ..the last column centered if its a column with check boxes..

Here I agree with @pedromvpg , checkbox columns look better when center-aligned.

Also text columns should probably stay left-aligned, as @pedromvpg suggested (for consistency with the rest of the UI). This PR, in the current form, also changes this (for example, Offer ID becomes right-aligned, even though its not a numeric value).

---

From what I can tell, the main point of this PR was the numeric alignment. So to simplify the decision, let's just concentrate on this one aspect (and leave all else unchanged, like text left-aligned, checkboxes center-aligned).

It seems there are strong pros and cons for left and right aligning numbers.

Maybe @m52go could run a user survey on twitter, and ask them to vote between

A) left-aligned number columns

Screenshot 2020-10-07 at 12 24 00

B) right-aligned number columns

Screenshot 2020-10-07 at 12 22 22

Or maybe there's another, better way to get user feedback?

Would this make sense?

**Comment by m52go** [comment]
It's not clear to me what's best here so I'd personally lean toward whatever Pedro recommends but...might not hurt to ask users too.

https://twitter.com/bisq_network/status/1313859755975176193

**Comment by m52go** [comment]
Well it seems the pro designers favor left-align (Pedro and [this guy](https://twitter.com/skyler_westby/status/1313867412454825989)) while everyone else favors right-align.

**Pull request closed without merging**
