### PR TITLE
Add reset buttons for BM accounting

### PR DESCRIPTION
**Pull request by HenrikJannsen**
Adds button in Settings/DAO to enable full BM accounting mode and reset data to scratch (back to 2020) or resync from latest resource file data.

### CODE REVIEW

**Review by alvasw — APPROVED** [review]
ACK

**Review by alejandrogarcia83 — DISMISSED** [review]
utACK

**Comment by alejandrogarcia83** [comment]
@HenrikJannsen Your branch has a merge conflict with master. Please resolve the conflict.

**Comment by HenrikJannsen** [comment]
Rebased on current main branch.

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
