### PR TITLE
Update currency filtering logic

### LINKED ISSUE #5300: Currency filtering is inconsistent
### Description

Currency filter (selection drop-down menu) is not working consistently. For instance, there are offers for Zcash and for Doge. I can filter only for Zcash, not for Doge. LBC coin was previously not selectable too, but after an LBC altcoin account was 

created. Either I should be able to filter after I have created the specific altcoin account, or I should be able to filter by all altcoins no matter which accounts I have. I assume, the ladder should apply.

#### Version

1.5.9

### Steps to reproduce

Use the drop-down menu to filter for an altcoin. Some you can filter (in my case for instance Zcash), some you cannot (in my case for instance DOGE). 

### Expected behaviour

Currency filter should be consistent, either with after having created that altcoin account, or filtering through all altcoins no matter which altcoin accounts you have

### Actual behaviour

Not possible to filter for certain altcoins.

#### Device or machine

Windows 64 bit

### PR DESCRIPTION
**Pull request by ghost**
Fixes #5300

### CODE REVIEW

**Comment by alkum** [comment]
ACK.

All currencies are enabled by default only for new installations, but that's fine.

**Comment by ripcurlx** [comment]
For this change I'd like to get more consensus as it will show for the initial dropdown a list with only one market that has actual offers. (AUD has some Mainnet offers)
Bildschirmfoto 2022-02-28 um 13 09 41

I agree that this pre-selection is not such a big thing anymore since we have the search possibility in the combobox we haven't had in the past. Personally I'd be fine with this change if we also change the sorting in the comboxbox from sorting by name to the currency code (first column value) which is more intuitive IMO.

@chimp1984 @m52go @UX-P @leo816

**Comment by m52go** [comment]
Is there any way to sort currencies by trading activity? Maybe not real-time but even updated manually would work since the overall trends don't change very much.

**Comment by pazza83** [comment]
> Is there any way to sort currencies by trading activity? Maybe not real-time but even updated manually would work since the overall trends don't change very much.

It is done in a similar way as proposed; number of current offers, in Market > Offer Book

This seems to work well. Could this be implemented for users going via Buy / Sell ?


Market - offer book

**Comment by m52go** [comment]
Interesting. Mine appear to be sorted alphabetically in spite of having the sort-by-number-of-offers option ticked on in settings. But I do remember my drop-down looking like yours at some point in the past...so I'm not sure what's going on.

**Comment by pazza83** [comment]
@m52go 

I think the option is in Setting > Preferences

Sort market lists with no. of offers / trades

**Comment by m52go** [comment]
Yes, as I said, that option is ticked on but not working for some reason...seems like a bug.

**Comment by chimp1984** [comment]
NACK

I think to spam the whole list with a multitude of currencies never traded is decreasing usability.
The related issue also do not suggest that solution but only complains inconsistency.

I think a better solution would be to show main currencies as we have, but use for the filter predicate the whole list of all currencies so that If I search for a currency which is not in the default list (or user defined list) it still is found.

**Comment by ghost** [comment]
> The related issue also do not suggest that solution but only complains inconsistency.

That solution was suggested by @pazza83 [in discussion](https://github.com/bisq-network/bisq/issues/5300#issuecomment-1034748685) on issue, however I also [wasn't sure](https://github.com/bisq-network/bisq/issues/5300#issuecomment-1034806517) if it's the best one.

> I think a better solution would be to show main currencies as we have, but use for the filter predicate the whole list of all currencies so that If I search for a currency which is not in the default list (or user defined list) it still is found.

I like it, I'll check how difficult it is to implement it that way.

**Comment by ghost** [comment]
I pushed solution suggested by @chimp1984 :
- when user type single letter default/user defined list is used for search
- when user type two or more letters list of all currencies is used for search

**Review by leo816 — DISMISSED** [review]

**Comment by chimp1984** [comment]
> I pushed solution suggested by @chimp1984 :
> 
>     * when user type single letter default/user defined list is used for search
> 
>     * when user type two or more letters list of all currencies is used for search

I think that is confusing.
Just show the user defined list when opening the dropdown and apply the search to all currencies.

**Comment by chimp1984** [comment]
NACK

**Comment by ghost** [comment]
> Just show the user defined list when opening the dropdown and apply the search to all currencies.

[Fixed](https://github.com/bisq-network/bisq/pull/6041/commits/5b4599253b2d7b686154e86a3aacafa16ac0c992)

**Review by ripcurlx — APPROVED** [review]
ACK - Tested it on Mainnet

All suggested changes in comments have been implemented.

**Pull request merged**
