### PR TITLE
List Denarius (D)

### PR DESCRIPTION
**Pull request by metaspartan**
List Denarius (D)

Official project URL: https://denarius.io
Official block explorer URL: https://chainz.cryptoid.info/d/ or https://coinexplorer.net/D

### CODE REVIEW

**Comment by ripcurlx** [comment]
@blabno Could you give this a look if it should make it into v1.2.4?

**Review by blabno — APPROVED** [review]
ACK

**Review by ripcurlx — APPROVED** [review]
utACK - because of https://github.com/bisq-network/bisq/pull/3650#pullrequestreview-323020019

**Comment by ripcurlx** [comment]
@carsenk Please sign your commit to get merged. https://help.github.com/en/github/authenticating-to-github/signing-commits

**Comment by metaspartan** [comment]
> @carsenk Please sign your commit to get merged. https://help.github.com/en/github/authenticating-to-github/signing-commits

Should be good now. https://github.com/bisq-network/bisq/pull/3650/commits/81b032b9bc55770226a3a2ff23ff3255ce512da3

**Comment by metaspartan** [comment]
Any update on adding this?

**Comment by freimair** [comment]
your commit are still not signed. A signed commit should have a greenish [verified] box next to the commit hash. Have you uploaded your key to github?

**Comment by ripcurlx** [comment]
@carsenk Your commits are not signed and it should be only one commit as described in the `how to list an asset` documentation.

**Comment by metaspartan** [comment]
> @carsenk Your commits are not signed and it should be only one commit as described in the `how to list an asset` documentation.

Sorry not sure why it wasn't signing, now it is: https://puu.sh/EMxyL/3f7d0528e8.png

**Comment by buzzkillb** [comment]
Any estimate on when Denarius will be added?

**Comment by ripcurlx** [comment]
> Any estimate on when Denarius will be added?

As soon as it fulfills the requirements. It still has more than one single commit.

**Comment by metaspartan** [comment]
@ripcurlx You are seriously going to make me recommit this as one commit? You are the one whom made me submit more than one commit..........

**Comment by julianknutsen** [comment]
> @ripcurlx You are seriously going to make me recommit this as one commit? You are the one whom made me submit more than one commit..........

Rebase and force push would have taken less time than this comment took to write and would have fulfilled the request made by the reviewers.

[Step 5](https://docs.bisq.network/exchange/howto/list-asset.html#step-5-create-a-well-formed-git-commit) of `how to list an asset` explicitly states the squash requirements. If you don't follow them, expect this to be rejected.

As the lead developer of Denarius, you should be familiar with the need for signed commits as well as standardizing processes to reduce waste. We use both here at Bisq to minimize the work required by reviewers and maintainers for new assets. This PR has now wasted both unnecessarily.

@ripcurlx @freimair This is a great example of why we should just [close ](https://docs.bisq.network/exchange/howto/list-asset.html#pull-requests-that-do-not-conform-to-the-requirements-above-will-be-rejected) these types of PRs as `invalid` from the beginning. Projects and developers who want their asset listed should be expected to follow the very simple steps. If they can develop and maintain an actual cryptocurrency project, they can learn how to make a valid PR.

**Comment by metaspartan** [comment]
@julianknutsen I followed the steps in their entirety when I submitted this PR. It was one commit, 3 files changed, all transparent. Also just to bring it to your attention, in that list it does NOT say you are required to sign the commits. I typically have my commits signed and something happened within my setup when I pushed this PR to where they weren't, does not make any less of a valid commit. You are super disrespectful and not understanding.....

["Step 5"](https://docs.bisq.network/exchange/howto/list-asset.html#step-5-create-a-well-formed-git-commit) There is **absolutely no where** in that document that the commit must be signed.

I am glad this is public, so everyone can see how you treat other contributors to the project. You going on a rant is entirely unnecessary and entirely unprofessional. I will do you a favor and close it for you. 

I will submit a new PR, fully signed commit for @ripcurlx and others. 

As for @julianknutsen you should learn some respect and how to treat people. You are clearly lacking there.

**Pull request closed without merging**
