### PR TITLE
Add bsq.sqrrm.net BSQ explorer operated by @sqrrm

### PR DESCRIPTION
**Pull request by wiz**

### CODE REVIEW

**Review by sqrrm — DISMISSED** [review]
ACK

**Comment by sqrrm** [comment]
@wiz I think we better put all the remaining explorer updates in the PR. Just easier with conflicts and cherry picking for the release.

**Comment by wiz** [comment]
@sqrrm ah yeah the commas 😓 okay I resolved the merge conflict

**Review by sqrrm — APPROVED** [review]
utACK

**Pull request merged**
