### PR TITLE
Update data stores and dates for v1.1.6

### PR DESCRIPTION
**Pull request by ripcurlx**
I've updated the data stores for our release on Monday.
Full node hashes of data stores used in this PR
Bildschirmfoto 2019-09-13 um 14 43 18
Are matching the ones received in a lite node
Bildschirmfoto 2019-09-13 um 14 43 10
Assuming that we'll release on Monday (16th of Sept), I've set the update requirement three days later (19th of Sept) and the activation of the mediation system ten days later (26th of Sept).

I've also removed code that was added only for testing purposes.

### CODE REVIEW

**Review by sqrrm — COMMENTED** [review]
utACK on code changes, need to test the data stores later

**Comment by chimp1984** [comment]
@ripcurlx Could you also post screenshots of the proposal and blind vote hashes? 
DaoState hash is same as on my local apps.

**Review by chimp1984 — APPROVED** [review]
utACK

**Comment by chimp1984** [comment]
Rocket getting ready to start ;-)

**Comment by ripcurlx** [comment]
@chimp1984 These are all current states of my full node
Bildschirmfoto 2019-09-13 um 18 52 06
Bildschirmfoto 2019-09-13 um 18 52 13
Bildschirmfoto 2019-09-13 um 18 52 18

**Comment by wiz** [comment]
Verified DAO state
594700 -> 34a024c8
Verified Proposals state
594217 -> c2a8471e
Verified Blind votes state
594677 -> 7d27e889

**Comment by chimp1984** [comment]
Confirm also all 3 hashes.

**Review by sqrrm — APPROVED** [review]
ACK

**Pull request merged**
