### PR TITLE
Re-enable all tests

### PR DESCRIPTION
**Pull request by alvasw**
Relates to https://github.com/bisq-network/bisq/pull/6619.

### CODE REVIEW

**Comment by alejandrogarcia83** [comment]
Please rebase you PR to resolve the merge conflicts.

**Comment by alejandrogarcia83** [comment]
Please rebase your PR to resolve the merge conflicts.

**Comment by alvasw** [comment]
Done

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
