### PR TITLE
Community tab

### LINKED ISSUE #4904: Promote Keybase as a support channel within Bisq GUI
# Promote Keybase as a support channel within Bisq GUI

As far as I am aware Bisq uses Keybase as it's primary support channel.  Keybase, however, Keybase is hardly mentioned in the Bisq client. I do not recall meeting a new trader on Bisq yet that is aware of Keybase.

From a personal perspective the time between me making my first trade and installing Keybase was 5 months. I was using Bisq daily in this time, so I think lots of new users might leave before then even become aware of Keybase, and by extension the community and support resources Bisq provides.

Reflecting on this, I would have preferred the client to persuade me to access Keybase sooner. It is very helpful, especially for new users. Things that are helpful to new users will likely make new users feel part of a community and stick around for longer and complete more trades. 

## Problem

The below problems decrease user experience and engagement of Bisq users, especially amongst new users:

- Bisq users are not always aware then can contact support via Keybase
- Bisq client does not reference Keybase anywhere within the client
- Bisq traders that are aware of Keybase have to break trade protocol to send user a link to Keybase.
- Bisq trader unware of Keybase may be suspicious of such a link
- Keybase is a great resource. Not enough new users are funned though to Keybase 
- Similar to the above Bisq client does not direct users to https://github.com/bisq-network/support
- Similar to the above Bisq client does not have a simple contact/community section. Bisq is a P2P network. It should encourage community. It misses out by not doing so.

**Example of problem:**

The image below is a recent conversion. It was a New Bisq user experiencing difficulties during a trade. The trader was unaware of Keybase. In an effort to be helpful the trader breaks protocol (do not send urls), putting their security deposit at risk to send the buyer a link to Keybase :roll_eyes:

This is a common chat. More common in the last 2 weeks since the issues around confirmations not being registered within the client.

b5

## Desired outcome

The below would all be good outcomes.

- Improved user experience and increased engagement of Bisq users.
- New users to be more sticky and become life long Bisq users
- All traders to be aware of where to access support, resources, and community information
- Experienced traders not to feel awkward in breaking protocol to send someone to the Bisq team on Keybase

## Solutions (screenshots showing actual behavior and expected behavior)

Here are examples of current screenshots taken from the current client v1.5.0. I have made recommendations for some simple solutions that can be implemented to move closer to the desired outcomes.

#### Trade process being need help section outdated

b6

The help section should point people to keybase. People going to community page will likely get sent onwards anyway.

---

#### Trader chat - no information about Keybase displayed

b4

Display information about Keybase being a support channel. 

> Need help? Why don't you chat with one of our friendly support agents on Keybase in the bisq team support channel. Download it here https://keybase.io/team/bisq 

---

#### Example of pop up new users see - no mention of Keybase

b3

Mention Keybase (text as above)

---

#### Popup new users see when they visit the Support section - no mention of Keybase

b2

Mention Keybase (text as above)

---

#### Setting page - No mention of Keybase

b1

Link to https://keybase.io/team/bisq

---

#### Alerts - No mention of Keybase

error2

Mention Keybase (text as above)

---

#### Error in trade information screen  - No mention of Keybase

 error 3

Mention Keybase (text as above)

---

#### Warning - Mentions keybse

error

Add link to https://keybase.io/team/bisq

---

#### Bisq Client menu bar - No community section

b7

Add community section links to things like:

community

## Additional info

Keybase is a good resource for bisq users. I would like to see more people using it, or at least decrese the percentage of new users that come to Bisq try it out and leave without ever knowing that Bisq had options for support.

Please see my tangentially related proposal to [Use Keybase to increase accessibility to Bisq for new traders with no funds for security deposit, trading and mining fees](https://github.com/bisq-network/proposals/issues/283)

### PR DESCRIPTION
**Pull request by ghost**
Fixes #4904

### CODE REVIEW

**Comment by ripcurlx** [comment]
@xyzmaker123 Thanks for your PR. Just a couple of remarks on the UI Code. Please try to use the AutoTooltip... components instead of the JFX.. default ones. So it will automatic truncate and provide a tooltip if a translation won't fit into the boundaries. The other thing is we try to not use FXML syntax whenever possible as it is bad for performance. So we normally just have a main container as an entry point and instantiate all other UI components manually. And yes, there are still some legacy FXML UIs (network..) out there which would need some dev love. :wink:

**Comment by ghost** [comment]
@ripcurlx Thank you for your comments - I updated pull request in accordance with them.

**Comment by ripcurlx** [comment]
@xyzmaker123 All your new views are missing the license header.

**Comment by ripcurlx** [comment]
> @xyzmaker123 All your new views are missing the license header.

Not all  - just the *View.java ones

**Comment by ripcurlx** [comment]
I think the biggest issue this has is that it will truncate the menu bar even for English in the default width of 1200. To make this work for an initial startup we need to adapt `Layout.INITIAL_WINDOW_WIDTH` to `1240`. This probably shouldn't be a big deal for most screens IMO.

Bildschirmfoto 2021-09-27 um 10 29 06

Bildschirmfoto 2021-09-27 um 10 46 50

**Review by ripcurlx — APPROVED** [review]
ACK - Please review my comments, but I fixed the issues myself already.

**Comment by ghost** [comment]
Thanks @ripcurlx for final fixes. Yeah - I'll try to be more careful about license header in future.

**Comment by chimp1984** [comment]
Added an issue: https://github.com/bisq-network/bisq/issues/5732

**Pull request merged**
