### PR TITLE
Add pay from BSQ wallet button

### PR DESCRIPTION
**Pull request by chimp1984**
Add button to buyers trade step 2 view in case of a BSQ trade to fill in the amount and address to the BSQ send view.

### CODE REVIEW

**Comment by chimp1984** [comment]
Screenshot 2021-03-15 at 17 45 49
Screenshot 2021-03-15 at 17 45 54

**Comment by ripcurlx** [comment]
To me `Pay from BSQ wallet` sounds like it would automatically pay the BSQ from the BSQ wallet. Maybe it should be labeled `Go to BSQ wallet`?

**Comment by wallclockbuilder** [comment]
Maybe a tooltip? Right next to the button.
[ PAY FROM BSQ WALLET ] ( i ) Fills out the address and amount. You have to press send to pay.

**Review by ripcurlx — APPROVED** [review]
utACK - I missed that it pre-populates the input fields to send the BSQ, so it is not a simple go to wallet button. After thinking about it I think it is fine doing it like this, as even if a user thinks this will automatically send the BSQ will see that she is re-directed to the wallet for confirmation.

**Comment by ripcurlx** [comment]
> Maybe a tooltip? Right next to the button.
> [ PAY FROM BSQ WALLET ] ( i ) Fills out the address and amount. You have to press send to pay.

Yes, maybe an info could improve this, but I don't think it is a showstopper for this PR.

**Pull request merged**
