### PR TITLE
Correct input validation of Norwegian bank account numbers.

### PR DESCRIPTION
**Pull request by sturles**
Warning: Java is not my first language.  You probably want to review the code, which is adapted from here: https://no.wikipedia.org/wiki/MOD11#Implementasjoner_i_forskjellige_programmeringspr.C3.A5k

It checks the format and validates the input of Norwegian bank account numbers by generating and checking the checksum (last digit).  I have tested it with various valid and invalid numbers, and it works.  

The account number can be used to generate an IBAN number as well, but I haven't come to that yet.  IBAN number will have the format NOxx<accountnumber>, where NO is the country code for Norway and xx is a new checksum generated as described here: https://en.wikipedia.org/wiki/International_Bank_Account_Number#Generating_IBAN_check_digits6

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Thanks will check in the next days.

**Comment by ManfredKarrer** [comment]
Could you do the PR at development branch? If too much hassle I will add the changes myself in dev branch, but in master I don't want to merge as people are using that when building from source.

**Comment by sturles** [comment]
Trying, but github insists on mixing commits which aren't mine with my PR. :-/

**Comment by ManfredKarrer** [comment]
I committed some to the dev branch, you need to use the dev branch, then merge your commits from master to dev. Seems you merged dev to master and created form master the PR. Master is only used for releases.

**Comment by sturles** [comment]
I have tried to checkout Development, merge my changes, push to github and make a new pull request, but github still wants to include some Italian translation stuff which I know nothing about in the pull request.

**Comment by ManfredKarrer** [comment]
I think that Italian was form a PR to master a bit ago. Did u have updated master before?
Anyway if you like I can just copy over the changes.

**Comment by sturles** [comment]
Just copy over the changes.

**Comment by ManfredKarrer** [comment]
Oki... Thanks for your contribution! Will copy it over soon (in the middle of a bigger work atm...).

**Comment by ManfredKarrer** [comment]
Hi @sturles:
I committed your code now: 
https://github.com/bitsquare/bitsquare/commit/e14d70b9d924974ea89131d07fe10762c19f7ca5

**Pull request closed without merging**
