### PR TITLE
Implement simple password-based gRPC authentication

### PR DESCRIPTION
**Pull request by ghubstan**
A 2nd attempt at gRPC authentication after finding out in #4129 that TLS + Macaroons is too much overhead for ~:cli~ our purposes at this point (edit: @cbeams).  Most of the changes not related to refactoring :cli are listed below.

 * Renamed CliCommand to RpcCommand, differentiating it from cmd
   string token(s)

 * Added new CliConfig, based on :common Config

 * Injected Config into CoreApi to make bisq.properties and cmd line
   args available to server

 * Added cleartext username:password BisqCallCredentials to :cli, and
   an AuthenticationInterceptor to :core (server)

 * Moved :daemon resources folder to expected location under src/main

 * Duplicated CompositeOptionSet, ConfigException and BisqException
   in :cli because they are not visible from :common.  (TODO refactor?)
   CompositeOptionSet will be used to let command line parameters
   override params set in config file.

 * Removed outdated references to :cli in a couple of comments in
   :common Config

 * gRPC parameters & command names are lowercase to mimic bitcoind/rpc

TODO:  Decide what rpc auth param names to use, to differentiate them from bitcoind rpc user/password param names.  Until that decision is made, the existing bitcoind rpcUser/rpcPassword param names are used for gRPC authentication.  As you know, you can define rpcUser/rpcPassword creds in bisq.properties and/or pass rpc login creds on command line:

    ./bisq-daemon --rpcUser=somebody --rpcPassword=password  getversion

### CODE REVIEW

**Comment by ghubstan** [comment]
TODO change rpcuser/rpcpassword params to grpcuser/grpcpassword, as per the request made by @cbeams to me in keybase

**Comment by cbeams** [comment]
Thanks, @ghubstan. Please hold off on further changes for the moment, I have a number of review commits incoming.

**Comment by cbeams** [comment]
@ghubstan, you'll need to check the 'allow edits from maintainers' checkbox on this PR. Until then, I'm unable to push my review commits. See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork. Thanks.

**Comment by ghubstan** [comment]
>  you'll need to check the 'allow edits from maintainers' checkbox on this PR. Until then, I'm unable to push my review commits. 

@cbeams,  'allow edits from maintainers' was checked when I logged in a few minutes ago:
allow-edits

I wonder if the problem (or bug) has anything to do with this PR being created as a draft.  I _think_ the last time you pushed commits to one of my PRs, it had not yet been changed to a draft.

**Comment by ghubstan** [comment]
@cbeams , I clicked "ready for review" to temporarily change this from a draft to a normal pull request to see if that will allow you to push changes.

**Comment by cbeams** [comment]
@ghubstan the inability to push was an issue on my side with my local `.git/hooks`. I've solved it for the time being and pushed up my current set of commits. You'll see the last few are still in a WIP state, so please don't build anything on top of this just yet.

It's worth looking through each of the commits, in some of them I've explained exactly why changes were made.

Overall, though, the idea is to radically simplify things. One of the main purposes of the cli is to serve as a reference client for working with Bisq's rpc api, and as such it should be dead simple to understand. It's probably a bit _too_ simple now, I would do some additional refactoring to reduce certain redundant code, but I wouldn't go very far here. The implementation will certainly need to get more sophisticated as we go implementing all the endpoints, but we can do that on an as-needed basis.

Hope this helps / makes sense. Let me know if you have questions / feedback. It might be a little bit before I get back to this, Monday possibly.

By the way, here's how you can invoke `bisq-cli` now:

    ./bisq-cli -auth=mytoken getversion

Where `mytoken` was provided on the bisqd side as:

    ./bisq-daemon --apiToken=mytoken

The `apiToken` naming will change further, it's still WIP, but as you can see, rpcuser / rpcpassword are out of the picture now (and can return to their existing use for talking to bitcoind).

**Comment by cbeams** [comment]
And you can / should change this PR back to a draft now. Thanks.

**Comment by ghubstan** [comment]
@cbeams, Thanks for the feedback, notes on style conventions and new commits.   Glad this work can gain some momentum now...  The only remark I have is that the reason I broke main into RpcCommand, CliConfig & CommandParser was to avoid the main class from getting very large (a personal itch), but of course I want to follow the conventions.

**Comment by cbeams** [comment]
@ghubstan, I've cleaned up the WIP commits and pushed several additional ones.

Please have a look at the implementation now and properly review it from your side. All possible error cases should be handled gracefully now. Please see if you can break it in any way, make sure everything makes sense, is intuitive, etc. Thanks.

Note that you'll need to start the daemon with `--apiPassword=xyz` and you'll need to match that on the cli client with `--password=xyz`.

**Comment by ghubstan** [comment]
@cbeams, Your changes make sense to me.  I know you don't want me to add a bunch of JUnit tests, so I am building a linux 'expect' test script to save me time.    So far, the eight test cases are passing.

I pushed two commits.  I intend to push some wallet encrypt/decrypt methods Sunday or Monday, along with error handling for getbalance, which returns "Error: UNKNOWN" when the wallet is not yet avaiable or decrypted.

**Review by cbeams — CHANGES_REQUESTED** [review]
I am unable to reproduce the failure you're talking about. Neither `./bisq-cli --password="foo bar" getversion` nor `./gradlew :cli:run --args='--password="foo bar" getversion'` causes any issue for me, i.e. the double quotes are handled properly by JOptSimple, and it appears to me that the code you've added is unnecessary. What is the repro case for you?

**Comment by cbeams** [comment]
>  I know you don't want me to add a bunch of JUnit tests, so I am building a linux 'expect' test script to save me time. So far, the eight test cases are passing.

Just for the record, I have nothing against (and usually everything for) unit tests, but this is a special situation where it's awkward to work with them and not (yet, at least) worth the trouble. I'll be interested to see the `expect` scripts. I've also heard good things about https://github.com/sstephenson/bats as a bash-based testing system; it might be worth a look.

> I intend to push some wallet encrypt/decrypt methods Sunday or Monday, along with error handling for getbalance, which returns "Error: UNKNOWN" when the wallet is not yet avaiable or decrypted.

Perfect. I was actually going to ask you to do this next. In particular, handling the `Error: UNKNOWN` case.

How about this as a set of next steps?

 1. Handle the `Error: UNKNOWN` case in a first-class way, such that the user understands through an error message that they cannot perform the operation they're trying to (e.g. `getbalance`) because the wallet is encrypted and has not been unlocked.
 2. Implement a `setwalletpassword` method that, given a single argument, attempts to encrypt a previously unencrypted wallet using the argument as the wallet password. The method will fail with an appropriate error message if the wallet password has already been set. Given two arguments, the method will attempt to change the wallet password from its old value (1st argument) to a new value (2nd argument). In this way, the `setwalletpassword` method is like combining Bitcoin Core's https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/encryptwallet/ and https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/walletpassphrasechange/ methods into one.
 3. Implement `unlockwallet <passphrase> <timeout>` similar to the way https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/walletpassphrase/ works, and
 4. Implement `lockwallet` similar to the way https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/walletlock/ works.

And each of these would have expect/bats-based tests.

I was going to say that we should not implement a `removewalletpassword` method as a counterpart to `setwalletpassword <newpassword>`, because it's a potential security risk and there isn't a clear real-world use case for it (note that Bitcoin Core has no such method either), but, on thinking about it, perhaps we should implement it if only for the practical use case of automated testing. Ideally, we would spin up a new Bisq node on each run through the automated tests, using a new temporary data dir, (e.g. with `--appDataDir=$(mktemp -d)`), such that the wallet is always new and un-encrypted at the beginning of each run, but the downside of doing this is that it's time-consuming to spin up the node. When in a tight development loop, one would usually want to spin up a test node or complete localnet environment (see the Makefile in the root of the repo), and then be able to run the cli test suite against it very quickly as incremental code changes are being made. So I'm open to implementing a `removewalletpassword` method based on this rationale.

I just wanted to quickly type all of this up here as a comment here to get your feedback, but assuming we want to go this route, we should probably model the items above as their own issue(s). Perhaps you could transcribe this to a new issue, and make each of the above checkboxes. You can then put together a PR that will close that new issue when merged.

Another candidate next task is to implement a cookie-based alternative to explicitly providing `--apiPassword` to the daemon and `--password` to the cli when both are being run on the same machine. This would work very similarly to the way bitcoind generates a `${datadir}/.cookie` file that bitcoin-cli is aware of (see https://bitcoin.stackexchange.com/questions/46782/rpc-cookie-authentication for details if you're not familar). Doing this is actually more secure when running on the same machine because the passwords don't show up in plaintext in process lists, shell history, etc, and can be access-controlled using normal file permissions. Implementing this would mean making the cli aware of the default Bisq data directory location, and this would need to be done in a way that fully duplicates what's already in :core, keeping in mind that the :cli project is all about being a reference client, not about reusing code that other client / bot implementors could not easily reuse themselves. Again, this can and should be written up as its own issue. We can get together a project board to start managing these in a priority-ordered fashion, etc. I can help with that once we have a few issues vying for our attention.

**Comment by cbeams** [comment]
And regarding merging this PR, please address my review feedback, and I think we'll be good to go or close to it.

Note that I have some additional commits that build on the commits here to refactor things on the server side (`BisqGrpcServer` and co). Those commits are out of scope for this PR and I'll submit them separately once we've merged this, but I'm mentioning it now just in case you start to do anything on the daemon side, as we'd surely run into merge conflicts. If you're curious about these changes in the meantime, you can see the `refactor-rpc-server` branch in my fork.

**Comment by cbeams** [comment]
Note that I updated the title of this issue and made a minor edit to the description to better reflect what's actually going on here.

**Comment by ghubstan** [comment]
> [I am unable to reproduce the failure you're talking about.... i.e. the double quotes are handled properly by JOptSimple, and it appears to me that the code you've added is unnecessary. What is the repro case for you?]

You're right, I couldn't reproduce the problem either on the command line.  The problem was my tcl/expect script, which has weird double quote syntax requirements.  I reverted that change and fixed my test script.

**Comment by cbeams** [comment]
@ghubstan, are the test scripts suitable to be committed as well? So long as they don't have hard-coded paths or other system-specific stuff, it would be great to see these and use them myself.

**Comment by cbeams** [comment]
(It's fine if they're *nix-only)

**Comment by ghubstan** [comment]
> @ghubstan, are the test scripts suitable to be committed as well?

@cbeams, for now, I'll back up the test script here:
https://github.com/ghubstan/doodads/blob/master/expect-scripts/cli-test.sh

Just copy the bash script to the root project dir, run :daemon & test script:
    `$ ./bisq-daemon --apiPassword=xyz`
    `$ ./cli-test.sh`
(:cli's wallet should be unencrypted and empty)

I pretty sure 'expect' is available for OSX, but I'm not sure if there are syntax diffs.

**Comment by ghubstan** [comment]
> I've also heard good things about https://github.com/sstephenson/bats as a bash-based testing system; it might be worth a look.

It only took a minute of looking at bats to decide I would like to use that instead of tcl based expect.  Looks a lot easier to use, and it can also be installed from apt pkg mgr.  I'll switch over after I add the wallet endpoints.

**Comment by ghubstan** [comment]
> 2\. Implement a `setwalletpassword` method that, given a single argument, attempts to encrypt a previously unencrypted wallet using the argument as the wallet password. The method will fail with an appropriate error message if the wallet password has already been set. Given two arguments, the method will attempt to change the wallet password from its old value (1st argument) to a new value (2nd argument). In this way, the `setwalletpassword` method is like combining Bitcoin Core's https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/encryptwallet/ and https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/walletpassphrasechange/ methods into one.

This brings up the question of method names.  In another branch, I created protos (and impls):

```
service EncryptWallet {
    rpc EncryptWallet (EncryptWalletRequest) returns (EncryptWalletReply) {
    }
}

message EncryptWalletRequest {
    string passphrase = 1;
}

message EncryptWalletReply {
    bool success = 1;
    string error_message = 2; // optional error message
}

service WalletPassphraseChange {
    rpc WalletPassphraseChange (WalletPassphraseChangeRequest) returns (WalletPassphraseChangeReply) {
    }
}

message WalletPassphraseChangeRequest {
    string old_passphrase = 1;
    string new_passphrase = 2;
}

message WalletPassphraseChangeReply {
    bool success = 1;
    string error_message = 2; // optional error message
}
```

They do not combine the two methods into one `setwalletpassword` as you wish, but they are named and work exactly like the eponymously named bitcoind methods.

I would implement the `setwalletpassword` method from this proto:
```
service SetWalletPassword {
    rpc SetWalletPassword (SetWalletPasswordRequest) returns (SetWalletPasswordReply) {
    }
}

message SetWalletPasswordRequest {
    string passphrase = 1;
    string new_passphrase = 2;
}

message SetWalletPasswordReply {
    bool success = 1;
    string error_message = 2; // optional error message
}
```
However you want this done is OK with me, and I think `setwalletpassword` would be consistent with text in the UI.  But I want to bring up the point that if the cli is for developers, and many of those developers are familiar with bitcoin-cli, wouldn't it be nice if we stuck to bitcoin-cli's method and parameter names where appropriate?  If we did, many new users would intuitively know how to use bisq-cli without even having to look at --help.

If you don't want to use existing bitcoind method names (that's OK), I would just like to be informed of what you wanted before I went off to add a bunch of new endpoints.    Beyond that, I am just looking at this from the perspective of someone who has been using bitcoin-cli a lot lately (unfortunately, not wheelin' and deelin' BTC).

**Comment by ghubstan** [comment]
I've reviewed all your comments today (26-APR). The last remark I have is that I do want to add a `removewalletpassword` method for automated testing reasons.

**Comment by cbeams** [comment]
Good questions, thanks. I'd like the overall model and feel of bisq-cli to match that of bitcoin-cli, but not slavishly so. As we progress, we'll probably find many reasons to diverge in ways big and small. In this particular case, I find the wallet encryption-related bitcoind rpc method names and design to be somewhat haphazard, i.e. not particularly coherent or intuitive. It's good to be informed by what bitcoind has done, so as not to naively reinvent things, but having been so informed, I'm happy to take a fresh cut at our own equivalents while we have a relatively blank design slate. And note that we should deviate in any case from the 'passphrase' term they use to the 'password' phrase we have used throughout Bisq's history and UI.

> wouldn't it be nice if we stuck to bitcoin-cli's method and parameter names where appropriate? If we did, many new users would intuitively know how to use bisq-cli without even having to look at --help.

Users will need to refer to --help output or other documentation frequently when using the Bisq rpc api and cli whether or not the methods in question closely match their bitcoind analogs. The overlap in these particular methods exists only because Bisq and Bitcoin Core share a common 'wallet' subdomain; as we get deeper into designing methods specific to Bisq's trading domain, our two APIs will differ greatly. More important than parity with bitcoind's api design is that our own api design is internally consistent, following a set of design principles that allow users to intuit and predict what functionality they need is likely to be called, and where that functionality does not yet exist, to afford contributors the ability to name and design things correctly out of the gate according to those principles and conventions.

**Comment by cbeams** [comment]
@ghubstan, you'll see I've added a number of additional commits, including adding your expect-based test suite. Please give everything a look and give a thumbs-up from your side and we'll get this committed. It's an ACK from my side.

**Review by cbeams — DISMISSED** [review]

**Review by cbeams — APPROVED** [review]
ACK (again) from my side after a couple additional commits.

**Review by cbeams — DISMISSED** [review]

**Comment by ghubstan** [comment]
ACK

**Review by cbeams — DISMISSED** [review]
ACK. @bisq-network/bisq-maintainers, can we get this merged asap? I have additional changes that build on these commits, and I'd like to get them available to @ghubstan in a separate PR.

We might want to discuss allowing me to merge these gRPC-related PRs after peer review with @ghubstan. I'm not sure if it's worth the wait to have one of you go through them as well. I've debated doing this work together in my own fork to speed stuff up, but I like the idea of keeping it all here in the main repo, and doing everything incrementally in small PRs. Just not sure if the normal review process will keep up with that. Thoughts?

**Comment by ghubstan** [comment]
@cbeams, Commit ac87c23 replaces the expect test cases with bats test cases.  Just letting you know asap because I'm trying to squeeze this change in before the merge.

**Comment by ghubstan** [comment]
The redundant "Review required" happened because of a commit (ac87c23) I reverted (ce17200).
The test.sh migration from expect to bats will go into a new PR.

**Comment by cbeams** [comment]
I just removed the bats commit and its reversion and force pushed the branch back to its original state when I gave my final ACK.

**Review by cbeams — APPROVED** [review]
ACK

**Comment by sqrrm** [comment]
I'm good with @cbeams merging this work

**Pull request merged**
