### PR TITLE
Remove references to keybase and switch to Matrix

### PR DESCRIPTION
**Pull request by w0000000t**
Except `dao.bond.bondedRoleType.ROCKET_CHAT_ADMIN` which refers to an
unused role, every other instance of `keybase` has been contextually
updated to Matrix (bisq.chat); functions to display moderator name
and profile address on keybase have been updated to work with Matrix
usernames and urls.

Fixes #replaceWithIssueNr, fixes #replaceWithIssueNr

Your PR description here.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Good initiative!  A couple of comments:

- you should only commit changes to the main`displayStrings.properties`; the translated ones are updated automatically by transifex
- **pazza** in class `DisputeAgentLookupMap` should be changed to **pazza83**

**Comment by w0000000t** [comment]
> Good initiative! A couple of comments:
> 
> * you should only commit changes to the main`displayStrings.properties`; the translated ones are updated automatically by transifex
> * **pazza** in class `DisputeAgentLookupMap` should be changed to **pazza83**

thanks for the comments!
I suspected as much regarding the translations... did them anyway as, if updated automatically, they are overwritten anyway... regarding pazza I already changed it to pazza83 in the code, or is there another reference to their username elsewhere? Cannot find it by searching in Idea

**Comment by ghost** [comment]
ok I missed that you already got that pazza83 name change.  :+1:   
p.s. Its usually the case that @ripcurlx asks  for the translated files not to be included.

**Comment by w0000000t** [comment]
Ouch, I do hope he doesn't ask me to adjust it, because I definitely can, but then I couldn't for the life of me squash the commits together even if he was so incredibly kind to show me in my previous PR

**Comment by ghost** [comment]
1. [copy back the original versions of the translated resources]
2. `git status` to double-check what files you'll be modifying
3. `git add *`
4. `git commit -m"fix"`
5. `git rebase -i HEAD~2`
6. [in editor that pops up, change the second commit command from `pick` to `fixup`]
7. `git commit --amend -S`
8. `git push --force origin`
9. have a :beer:

**Comment by w0000000t** [comment]
Saving this nice writeup for later use! Nice little abstract, thanks!

**Comment by w0000000t** [comment]
I think I've done it @jmacxx ! Had to mess with the access token thingamajig but it appears to have worked!

**Review by ripcurlx — DISMISSED** [review]
utACK - Code changes are looking fine 👍

**Comment by ripcurlx** [comment]
@w0000000t But your account is not properly signed 😅

**Comment by w0000000t** [comment]
> @w0000000t But your account is not properly signed 😅

...I know what happened.
This PR was signed with my previous email, and I have since then removed that emaill from github in favor of a new one, which I managed to get to sign correctly. I thought the signed status of this PR would have stayed, but it didn't apparently as I was royally wrong.
Dang, I'll try and amend it using my new working signature, more practice for me 😅

**Comment by w0000000t** [comment]
@ripcurlx please confirm I didn't make a complete mess, it appears signed now and I should have squashed all commits now, maybe?

**Review by ripcurlx — APPROVED** [review]
utACK - Changes are looking fine 👍

**Pull request merged**
