### PR TITLE
rename XDR ticker (conflict with ISO 4217)

### PR DESCRIPTION
**Pull request by vlad-khramov**
See #2503

### CODE REVIEW

**Review by blabno — COMMENTED** [review]
Shouldn't tickers be uppercase?

**Comment by vlad-khramov** [comment]
I have not found this restriction in https://docs.bisq.network/exchange/howto/list-asset.html
and there is at least one coin with not uppercase ticker
https://github.com/bisq-network/bisq/blob/master/assets/src/main/java/bisq/asset/coins/QMCoin.java

Should I make it uppercased?

**Comment by ManfredKarrer** [comment]
I think we don't have a strict requirement for that but I would say lets keep it uppercase. Uppercase is the standard.

**Comment by vlad-khramov** [comment]
Can I use digit in the beginning of ticker ("1XDR")?
Creators of blockchain want bXDR or 1XDR (reason - XDR is highlighted) since simple XDR is prohibited

**Comment by blabno** [comment]
Man, ticker is a ticker. There is a name where you can play a bit.

**Review by blabno — APPROVED** [review]
ACK

**Pull request merged**
