### PR TITLE
Tweak seednode bitcoin.conf, remove timeout, separate testnet block

### PR DESCRIPTION
**Pull request by wiz**
The `timeout` line of our bitcoin.conf occasionally causes it to get stuck, should remove it from all nodes.
Also separate testnet into its own block

### CODE REVIEW

**Comment by wiz** [comment]
@emzy this should address the issue you had recently

**Comment by Emzy** [comment]
> @Emzy this should address the issue you had recently
This was the error in the log:
```
ProcessNewBlock: AcceptBlock FAILED (prev-blk-not-found (code 0))
ERROR: AcceptBlockHeader: prev block not found
```

**Comment by wiz** [comment]
@emzy there is some more relevant log message around that, but basically one of your peers failed to send you a block in time, and because of the long `timeout=30000` setting it got stuck and held up your node for a long time. I never meant to commit that line into our configuration, it was a mistake so this PR just removes the timeout, and next time you have a peer with poor connection it will use the default timeout value

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
