### PR TITLE
Generate more than 1 block(regtest)

### PR DESCRIPTION
**Pull request by wallclockbuilder**
Instead of running `make block` 24 times, you can now run `make blocks n=24`.

### CODE REVIEW

**Review by ripcurlx — DISMISSED** [review]
ACK - Works as expected

**Comment by ripcurlx** [comment]
@wallclockbuilder You need to sign your commit and I'm happy to merge this  PR

**Comment by wallclockbuilder** [comment]
Commit signed.

**Review by ripcurlx — APPROVED** [review]
ACK

**Pull request merged**
