### PR TITLE
Renaming: Use transaction virtual size

### PR DESCRIPTION
**Pull request by oscarguindzberg**
This is a follow up of https://github.com/bisq-network/bisq/pull/4710
Since segwit was implemented we use "bitcoin transaction virtual size" instead of "bitcoin transaction size" in the code.
I did not want to do all the renaming of methods and variable names in https://github.com/bisq-network/bisq/pull/4710 to reduce merging hell.
So, I am doing it now.
Don't get overwhelmed by the number of changes... this is just a renaming PR.

Please, merge https://github.com/bisq-network/bisq/pull/4754 before merging this PR.

### CODE REVIEW

**Review by chimp1984 — APPROVED** [review]
Superficial utACK

**Comment by chimp1984** [comment]
@oscarguindzberg Have you checked the translation strings if there is any need for an update as well?

**Comment by oscarguindzberg** [comment]
@chimp1984 I just fixed displayStrings.properties.
I assumed translators will notice the changes and translate into other languages.
Should I do the translations myself?

**Comment by chimp1984** [comment]
> @chimp1984 I just fixed displayStrings.properties.
> I assumed translators will notice the changes and translate into other languages.
> Should I do the translations myself?


Yes translater do the other languages. No need to waste your valuable dev time on translations

**Pull request merged**
