### PR TITLE
Fix tooltip issues

### PR DESCRIPTION
**Pull request by ripcurlx**
This should fix all issues, except the extended height in transactions rows mentioned in https://github.com/bisq-network/exchange/issues/1253

### CODE REVIEW

**Comment by cbeams** [comment]
@ripcurlx, this PR is `In Progress` but unassigned. Are you in fact still working on it? If so, please assign to yourself. If it's waiting for Manfred to take action, then I'd recommend putting it in `Priorities` (if that's indeed true), and assigning him as a reviewer.

**Comment by ripcurlx** [comment]
From my side everything should be fixed so far. I'll do a you suggested.

**Comment by cbeams** [comment]
Slated for `v0.6.5`. This change lives only on `Development` at the moment, but we'll get that branch merged into `master` (and hopefully removed altogether) by the time we ship `v0.6.5` (if not much sooner).

**Comment by ManfredKarrer** [comment]
I don't plan to merge it with 0.6.5 as it would require much more testing effort. Once merged into master all devs use it and we have longer time for testing until the next release.

**Pull request merged**
