### PR TITLE
Use bitcoinj 0.15.8.bisq.13 (commit dcf8af0)

### PR DESCRIPTION
**Pull request by oscarguindzberg**
Fixes https://github.com/bisq-network/bisq/issues/4870

### CODE REVIEW

**Comment by oscarguindzberg** [comment]
bitcoinj commits that were added:
https://github.com/bisq-network/bitcoinj/commit/902679fdcfa98ba3fdf6ec20b2a1c6fce78bacdb
https://github.com/bisq-network/bitcoinj/commit/1a786a2d1aaf18a19f11032bde9a6b6382b1a18c
https://github.com/bisq-network/bitcoinj/commit/bc8d2e791aa073856d83cbac16d4e8f3f7b7f71a

**Review by chimp1984 — APPROVED** [review]
utACK

I reviewed the BitcoinJ changes but I am not familiar with the details of the BloomFilter implementation.

**Comment by chimp1984** [comment]
@ripcurlx Can you cherry pick that to master as well?

**Comment by ripcurlx** [comment]
> @ripcurlx Can you cherry pick that to master as well?

I can create a PR for it - sure

**Comment by ripcurlx** [comment]
> @ripcurlx Can you cherry pick that to master as well?

https://github.com/bisq-network/bisq/pull/4964

**Pull request merged**
