### PR TITLE
Account management usability improvements

### PR DESCRIPTION
**Pull request by ghost**
Implements some requests from #4837 :

- Widen payment account dropdown in create & edit offer screens
- Sort payment account dropdown by name in create & edit offer screens
- Sort account listview by name in manage fiat accounts screen
- Sort account listview by name in manage altcoin accounts screen
- Bug fix: do not adjust BTC amount in edit offer screen

There was a bug where editing an existing offer could have its payment account changed to one with more restrictive limits and the offer would still be allowed (although not take-able). It should not be allowed to be saved in this case.  This change takes proper heed of the `allowAmountUpdate` flag which is false for offer edits.  
e.g. edit an F2F buy for 0.25, change to Zelle unsigned, the offer will prevent saving.  
Ref: https://github.com/bisq-network/bisq/issues/4837#issuecomment-734647423

### CODE REVIEW

**Comment by pazza83** [comment]
Thanks @jmacxx that was super quick  👍

**Comment by ripcurlx** [comment]
@jmacxx It looks like existing tests are failing. Could you please have a look why and adapt it if it is a false positive? Thanks!

**Comment by ghost** [comment]
Sorry I had got into a bad habit of building with `-x test`.  Fixed the issue in https://github.com/bisq-network/bisq/pull/4863/commits/0af139c666d5d243f12f27cd8ba58c735354b1c8

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
