### PR TITLE
Feature enabling log file upload to mediators

### LINKED ISSUE #5906: Make it easier for users to provide logs to mediators and support agents
### Description

When traders experience a bug mediators and support staff will often request copies of the users logs to diagnose the issue. For trade bugs it is often the case that both buyers and sellers logs are required to understand what went wrong.

Currently it is can be difficult for users to provide logs, especially if they are less technical, or just not experienced providing them before. 

As it can be difficult for users to provide logs the request for logs can often be quite tedious for users, and, therefore, is often ignored. This makes diagnosing issues harder. 

Some of the things that make it difficult are:

- Logs are found mixed in with the Bisq root data directory
- Different operating systems have the Bisq root data directory in different default locations
- The size of log files mean they cannot be sent as attachments in mediator chat in Bisq
- Lack of wiki detailing how to provide logs files.

#### Version

1.7.5

### Proposed behaviour

1. Change the location of logs in the data directory to `Bisq\Logs` This will mean all logs are in one place and easily distinguishable as logs files.
2. Maybe change formatting of log files rename to bisq-log-1, bisq-log-2, etc this would make it easier for users to identity logs an not over look bisq.log being a log file.
3. Decrease the size of the logs so they can be sent within mediator chat messages OR Increase the size of the files that can be sent in mediator chat messages to allow for the sending of logs
4. Add a shortcut to Bisq App > setting > About to automatically open Bisq log files folder eg `'Ctrl + l' or 'alt + l' or 'cmd + l'` opens Data directory log folder in user's operating system. This would make it easier for support agents to request log files.
5. Add a button on mediation chat to `Attach log file` this would make it easy for mediators to request logs (subject to no.3 being achievable). 
6. Create a wiki page detailing how users can provide logs and include link to other relevant wiki pages.

### PR DESCRIPTION
**Pull request by ghost**
Closes #5906
@pazza83 asked for the process of submitting log files to be made easier.  The solution presented here is basically a click and send option to transmit appropriate log files to a dispute's Mediator.

- From dispute chat there is a button `Send Log Files`.
- A popup is shown explaining the procedure with a progress bar.
- User presses `Send`.
- Logs which reference the tradeId are packaged in a zip file.
- The zip file is sent to the Mediator.
- User is notified that the upload is complete, or if there was an error.
- A message in dispute chat alerts the Mediator that log files have been received.

---

### Screenshots:

image

image

**Mediator notification:**

image

**Mediator's received logs:**

image

---

**Implementation notes:**

- Log files (even compressed) are larger than the max network packet size, so the file is transmitted in a series of blocks, each ack'd by the receiver and assembled into the received zip file.
- The zip file is named with the tradeId, the trader's role and a datestamp.  This makes it easier to organize received files.
- Within the zip, logs are created under a subdirectory named with the tradeId and trader's role; again this is to make it easier to organize the logs when support personnel extract them from the zip.

**Testing notes:**

- In regtest, there are mediator and trader sessions.  Start a trade, open a dispute, go to dispute chat and press [send logs].
- Tested in Tor/mainnet environment by modifying the code to send logs to an alternate onion address.
- The zip file handling code may have unforseen issues on different platforms.  I have yet to verify in Windows or MacOS.
- [edit]:  Tested on Windows -> https://github.com/bisq-network/bisq/pull/5953/commits/3ea15438820747db88a3a4ef1bdce2a1edda5faf

### CODE REVIEW

**Comment by pazza83** [comment]
Hi @jmacxx looks great. I think this will be really useful.

Please can you send a screenshot of the initial dispute screen for the user where the button `Send Log Files` is present.

Please can you let me know:

- Will this also be present on arbitrator chat (this was not requested but I think it would be useful)
- Will this send all log files of the user? If so do you have an idea of the time it would take for a user with lots of log files?
- When the Send Log screen gets to 100% is there anything to indicate it is complete eg a popup etc?

**Comment by ghost** [comment]
> send a screenshot of the initial dispute screen for the user where the button `Send Log Files` is present.

image





>  Will this also be present on arbitrator chat (this was not requested but I think it would be useful)

Not at the moment, but if this feature is successful it should be easy enough to enable for the arbitrator.  I need to think about that a bit..



> Will this send all log files of the user? If so do you have an idea of the time it would take for a user with lots of log files?

Log files referencing the tradeId will be added to the zip archive and sent.  Tests on Tor have been in the order of a 1.5 minutes for 6 log files (zip size 7Mb).  Most disputes are likely to only include a couple of log files and that takes about 30 seconds.

> When the Send Log screen gets to 100% is there anything to indicate it is complete eg a popup etc?

Yes, see screenshot ->

image

**Comment by ripcurlx** [comment]
@jmacxx I just tried to send my log files on macOS on Regtest with following exception:
```
Jän.-11 12:22:59.135 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Jän.-11 12:22:59.136 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= Illegal character in opaque part at index 48: jar:file:////Users/christoph/Library/Application Support/bisq-BTC_REGTEST_Alice_dao/0699932_BUYER_MAKER_20220111_122258.zip 
Jän.-11 12:22:59.136 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.IllegalArgumentException 
Jän.-11 12:22:59.144 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
java.lang.IllegalArgumentException: Illegal character in opaque part at index 48: jar:file:////Users/christoph/Library/Application Support/bisq-BTC_REGTEST_Alice_dao/0699932_BUYER_MAKER_20220111_122258.zip
	at java.base/java.net.URI.create(URI.java:906)
	at bisq.core.support.dispute.mediation.FileTransferSender.createZipFileToSend(FileTransferSender.java:69)
	at bisq.desktop.main.overlays.windows.SendLogFilesWindow.lambda$addContent$1(SendLogFilesWindow.java:163)
	at bisq.common.reactfx.FxTimer.lambda$restart$0(FxTimer.java:93)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
```

**Comment by ripcurlx** [comment]
I've also did some minor clean-ups and color improvements as the blue border color for mediation/arbitration chats always hurts my eye.

Bildschirmfoto 2022-01-11 um 12 38 07
Bildschirmfoto 2022-01-11 um 12 38 12
Bildschirmfoto 2022-01-11 um 12 38 18
Bildschirmfoto 2022-01-11 um 12 38 25
Bildschirmfoto 2022-01-11 um 12 38 30
Bildschirmfoto 2022-01-11 um 12 38 38

**Comment by ripcurlx** [comment]
> java.lang.IllegalArgumentException: Illegal character in opaque part at i

I guess it is the path issue again we had for the block file loading already.

**Comment by ghost** [comment]
`at index 48` --  it is complaining about the space in the file path, solution will likely be to enclose the path with single quotes.  I'll try it out and report back.

**Comment by ghost** [comment]
Fixed by replacing any space with `%20` in the file path.

**Review by ripcurlx — APPROVED** [review]
ACK - Tested it on Regtest with macOS Moneterey

**Comment by bisq-github-admin-3** [comment]
I'm still merging this PR although as Codacy has permission issues (again)

**Pull request merged**
