### PR TITLE
Add KingCoin

### PR DESCRIPTION
**Pull request by minerlab**
hi bisq team, please add KingCoin in your platform
Name: KingCoin
Ticker: KING
Algorithm: X11    
bitcointalk: https://bitcointalk.org/index.php?topic=2273043.0
explorer1: http://lpool.name/explorer/KING
explorer2: https://thecryptopool.com/explorer/KING
explorer3: https://cryptohub.online/blocks_hist/KING/
example address: LQuwqu9VyiHvbskFvXExeykhgo3NpUWZm2
site: http://www.kingcoin.eu
telegram: https://t.me/joinchat/CyIjuQ4v1-o9LxDa9Bi2SQ
twitter: https://twitter.com/_King_Coin
reddit: r/Kingcoindev
If your answer is positive I will add bisq to the site as an official exchange.
thanks.

[AltCoinAddressValidator.txt](https://github.com/bisq-network/exchange/files/1441391/AltCoinAddressValidator.txt)
[AltCoinAddressValidatorTest.txt](https://github.com/bisq-network/exchange/files/1441393/AltCoinAddressValidatorTest.txt)
[CurrencyUtil.txt](https://github.com/bisq-network/exchange/files/1441394/CurrencyUtil.txt)

### CODE REVIEW

**Comment by mrosseel** [comment]
please make your pull request against Development. If you do a PR against master you include all changes made to Development not yet merged to master, and your changes get lost in the sea of other changes.

**Comment by ManfredKarrer** [comment]
Yes, please re-do the PR to the development branch. it should contain only your changes. I will close that one.

**Comment by minerlab** [comment]
Ok sorry, the rest is fine?


Il giorno ven 3 nov 2017 alle 17:06 Manfred Karrer <notifications@github.com>
ha scritto:

**Comment by mrosseel** [comment]
not going to dig through 250 changed files to find your 
changes, sry :). Just do another PR against Development and we'll check your changes, thx !

**Comment by ManfredKarrer** [comment]
I have not looked into it as its too much work with so much merged commits...

**Pull request closed without merging**
