### PR TITLE
Add logo to README

### PR DESCRIPTION
**Pull request by MarnixCroes**
This makes the README look better, imo

### CODE REVIEW

**Comment by pazza83** [comment]
Do you mean the .exe file? If so I agree.

**Comment by ripcurlx** [comment]
I just recognized that we also need to remove the Travis build icon and replace it with the Github Actions svg.
I think `[Actions Status]`
should do the trick. Could you please add this to your PR as well?

**Comment by MarnixCroes** [comment]
> Do you mean the .exe file? If so I agree.

@pazza83 
which one?

**Review by ripcurlx — APPROVED** [review]
ACK - tested it locally

Bildschirmfoto 2022-04-13 um 10 58 16

**Pull request merged**
