### PR TITLE
Update data stores for v1.3.3

### PR DESCRIPTION
**Pull request by ripcurlx**
Full node in dark mode and light node in light mode.
Tested it with a light node using the resync functionality, a light node that hasn't been synced for a while and a full node that hasn't been synced before the incident.

Bildschirmfoto 2020-04-29 um 15 53 09
Bildschirmfoto 2020-04-29 um 15 53 13
Bildschirmfoto 2020-04-29 um 15 53 17
Bildschirmfoto 2020-04-29 um 15 53 21
Bildschirmfoto 2020-04-29 um 15 53 24
Bildschirmfoto 2020-04-29 um 15 53 28

### CODE REVIEW

**Review by wiz — DISMISSED** [review]
ACK

**Review by cbeams — CHANGES_REQUESTED** [review]
NACK. Can you merge #4114 before merging this? That will ensure the data stores get into LFS.

**Comment by cbeams** [comment]
(understood if this is urgent to the degree that you do not want to merge #4114 first)

**Comment by ripcurlx** [comment]
> (understood if this is urgent to the degree that you do not want to merge #4114 first)

I'm fine doing it as I cherry-pick the data store changes anyways on top of v1.3.2

**Review by cbeams — APPROVED** [review]
ACK. Built everything and brought up a localnet environment, no errors.

**Pull request merged**
