### PR TITLE
make all scripts executable

### LINKED ISSUE #5873: Executable flag needed for scripts
### Description

All .sh files in directory ```scripts/``` need the executable (+x) flag

#### Version

master

### Steps to reproduce

Install script for a seednode fails because it cant execute ```scripts/install_java_linux.sh```

### Expected behaviour

```
# ./install_seednode_debian.sh
...
[*] Installing Bitcoin into OS
[*] Installing Bitcoin configuration
[*] Generating Bitcoin RPC credentials      
[*] Installing Bitcoin init scripts
[*] Creating Bisq user with Tor access
[*] Creating Bisq homedir
[*] Moving Bisq repo
[*] Installing OpenJDK 11.0.2 from Bisq repo 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  178M  100  178M    0     0  97.4M      0  0:00:01  0:00:01 --:--:-- 97.3M
Java has been installed in /usr/lib/jvm/openjdk-11.0.2
...
```

### Actual behaviour

```
# ./install_seednode_debian.sh
....
[*] Installing Bitcoin into OS
[*] Installing Bitcoin configuration
[*] Generating Bitcoin RPC credentials
[*] Installing Bitcoin init scripts
[*] Creating Bisq user with Tor access
[*] Creating Bisq homedir
[*] Moving Bisq repo
[*] Installing OpenJDK 11.0.2 from Bisq repo
-bash: /bisq/bisq/scripts/install_java_linux.sh: Permission denied
```

### PR DESCRIPTION
**Pull request by Emzy**
Fixes #5873

make all scripts executable

### CODE REVIEW

**Review by ghubstan — COMMENTED** [review]
`install_java.sh` really is an empty file.  Can it be deleted from the project?

**Comment by ghubstan** [comment]
`utACK`

Here are the scripts' perms in my clone of the branch:

	-rwxrwxr-x 1 6.8K  create_dao_genesis.sh*
	-rwxrwxr-x 1 2.4K  install_java.bat*
	-rwxrwxr-x 1 3.9K  install_java_linux.sh*
	-rwxrwxr-x 1 1.7K  install_java_macos.sh*
	-rwxrwxr-x 1    0  install_java.sh*

I don't know if it matters, but I would have set them to `-rwxrw-r--`.

**Comment by Emzy** [comment]
> `utACK`
> 
> Here are the scripts' perms in my clone of the branch:
> 
> ```
> -rwxrwxr-x 1 6.8K  create_dao_genesis.sh*
> -rwxrwxr-x 1 2.4K  install_java.bat*
> -rwxrwxr-x 1 3.9K  install_java_linux.sh*
> -rwxrwxr-x 1 1.7K  install_java_macos.sh*
> -rwxrwxr-x 1    0  install_java.sh*
> ```
> 
> I don't know if it matters, but I would have set them to `-rwxrw-r--`.

There is no harm it it.
Also I think `-rwxrwxr-x` is needed. 
The checkout will be made by a normal user, but you will install Java as root. I think at least the seednode install script is doing it that way.

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
