### PR TITLE
List DixiCoin (DXC)

### PR DESCRIPTION
**Pull request by Dixicoin-DXC**
Author: Michael Howlett <devilking6105@Gmail.com>
Date: Mon Nov 5 07:30:00 2018-0800  //

List Dixi(DXC)

- Official project URL: [https://dixicoin.net]
- Official block explorer URL: [https://dixi.live]

### CODE REVIEW

**Comment by blabno** [comment]
@Dixicoin-DXC please rebase against master and resolve conflicts.

**Review by blabno — CHANGES_REQUESTED** [review]
NACK no PRs from master

**Comment by ManfredKarrer** [comment]
Close as no response from dev. Also we have a code freeze for new release soon.

**Comment by Dixicoin-DXC** [comment]
@ManfredKarrer sorry didnt see please tell me what you need

**Pull request closed without merging**
