### PR TITLE
Wise: fix account summary and add copy icon to form.

### LINKED ISSUE #6983: Wise: Seller doesn't see the buyer's holder name
PR #6964 was merged into master before it was ready. This issue tracks one of the issues.

### Seller doesn't see the buyer's holder name
1. Create new Wise accounts with an e-mail address and a holder name on Alice's and Bob's Bisq instances.  
2. Start a trade between Alice and Bob  
3. Press the payment started button on the buyer's side  
4. The seller doesn't see the holder name of the buyer 
seller_holder_missing

### LINKED ISSUE #6984: Wise: Holder name is missing on both traders trade details popup
PR https://github.com/bisq-network/bisq/pull/6964 was merged into master before it was ready. This issue tracks one of the issues.

### Holder name is missing on both traders trade details popup
trade_details_everything_missing

### LINKED ISSUE #6985: Wise: Copy button missing (next to the holder name text field)
PR https://github.com/bisq-network/bisq/pull/6964 was merged into master before it was ready. This issue tracks one of the issues.

### Copy button missing (next to the holder name text field)
copy_button_missing

### PR DESCRIPTION
**Pull request by ghost**
Fix review issues raised by @alvasw.  Closes #6983 Closes #6984  Closes #6985

- corrects the account summary string to include holder name.
- adds a copy icon to form field to match the others.

---

wise-1

wise-2

wise-3

### CODE REVIEW

**Comment by ghost** [comment]
Copy icon added to Pix account form also:

pixfix

**Review by alvasw — CHANGES_REQUESTED** [review]
Nit

Hi @yonson2023,
I tested this PR again and it's doesn't include the code review changes, you applied to your previous MoneyBeam PR. Please apply those here too.

**Comment by ghost** [comment]
Done.

**Review by alvasw — APPROVED** [review]
ACK  

Perfect! Thank you so much!  

#### Test Setup  
- Created Pix and Wise accounts on v1.9.14 on Alice's and Bob's Bisq instance  
- Created Pix and Wise accounts on this PR on Alice's and Bob's Bisq instance  

#### Trades (For Pix and Wise)
- Between old accounts  
  - Checked trade details screen  
  - Tested copy button  
- Between new accounts  
  - Checked trade details screen  
  - Tested copy button  
- Between old and new accounts
  - Checked trade details screen  
  - Tested copy button

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Comment by alejandrogarcia83** [comment]
@yonson2023 Thank you for opening this PR. I can't merge your PR before your commits are signed. For more information see: https://github.com/bisq-network/bisq/blob/master/CONTRIBUTING.md#sign-your-commits-with-gpg

**Comment by ghost** [comment]
Done.

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
