### PR TITLE
Add DAO launch popup

### LINKED ISSUE #2632: DAO announcement popup
We should have a nice DAO announcement popup to give all our users about an overview about the DAO.
@m52go Could you provide some text?
@pedromvpg Could you help with some design?

### PR DESCRIPTION
**Pull request by ripcurlx**
Fixes #2632.

### CODE REVIEW

**Comment by m52go** [comment]
Text suggestions:

```
popup.dao.launch.headline=The complete vision, realized

popup.dao.launch.trading=Trade BSQ (colored bitcoin) to participate in Bisq governance. You can buy and sell BSQ just like any other asset on Bisq.
```

For the cheaper fees string, my reworded version is a bit longer. I like it better, but if it's too long to fit in the space we have, we can just use the alternative.

```
//suggestion (maybe better, but too long?)
popup.dao.launch.cheaperFees=You pay Bisq contributors when you buy BSQ from them. You also get a 90% discount on trading fees by paying with BSQ.\nSave money & support the project by using BSQ!

//alternative (shorter)
popup.dao.launch.cheaperFees=Get a 90% discount on trading fees when you use BSQ. Save money and support the project at the same time!
```

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Comment by ripcurlx** [comment]
Updated it for trading
Bildschirmfoto 2019-04-10 um 16 27 22

For cheaper fees I needed to use the shorter variant:
Bildschirmfoto 2019-04-10 um 16 27 32
Bildschirmfoto 2019-04-10 um 16 30 03

**Comment by m52go** [comment]
Yeah I figured it would be too long. All good!

**Comment by ManfredKarrer** [comment]
The version on top feels a bit strange to me. It does not fell to be part of the headline but then why its there....

**Comment by ripcurlx** [comment]
> The version on top feels a bit strange to me. It does not fell to be part of the headline but then why its there....

The version on top will be 1.0.0 in the release. It should emphasize the version 1.0. I just used the current version atm, so it also works if we decide in the end to go live with 1.0.1. But maybe it should just says static "Bisq v1.0" as in Pedro's design suggested.

Like that:
Bildschirmfoto 2019-04-10 um 16 43 23

**Comment by ManfredKarrer** [comment]
Screen Shot 2019-04-10 at 09 43 38
Screen Shot 2019-04-10 at 09 43 35

The green colors in the screenshots are a bit different as the app gree.

**Comment by ripcurlx** [comment]
> Screen Shot 2019-04-10 at 09 43 38
> 
> Screen Shot 2019-04-10 at 09 43 35
> 
> The green colors in the screenshots are a bit different as the app gree.

Hmm, true. I did screenshot it from the app, but I guess something went wrong during the export. I'll re-check the source files.

**Comment by ManfredKarrer** [comment]
For my taste the distance between text and screenshot is a bit too high in relation to other distances.
Maybe the arrows would be a bit closer as well.
I think if we use the version we should use it hard coded with 1.0 as if we need to push an update soon it will be weird (1.0.1 etc). But maybe we shoudl include it more in the headline. Like:
"Bisq 1.0 - The ...."

**Comment by ManfredKarrer** [comment]
Did you export to jpeg? I think we can keep it png then they are exact.

**Comment by ManfredKarrer** [comment]
Do you think a sliding animation (left -> right) for the slides is lots of work? The hard cuts are a bit too hard IMO.
Alos maybe the background can be more darkened?

**Comment by ripcurlx** [comment]
> Did you export to jpeg? I think we can keep it png then they are exact.

I used png's already - I think it is the fade out that causes the issue in the "cheaper fees" screenshot.

**Comment by ripcurlx** [comment]
I adapted the layout a little bit and changed the last screenshot (it was an optical effect when fading or overlaying with a gradient to white)
Bildschirmfoto 2019-04-10 um 17 35 41
Bildschirmfoto 2019-04-10 um 17 35 36

**Comment by ripcurlx** [comment]
> Do you think a sliding animation (left -> right) for the slides is lots of work? The hard cuts are a bit too hard IMO.
> Alos maybe the background can be more darkened?

I'm not sure if I'm able to finish it today (I'm off soon). Let's see if I can squeeze in some transition animations.

**Comment by ManfredKarrer** [comment]
Should link go to DAO webpage or to docs? I think docs might fit better to learn more as DAO webpage is super high level

**Comment by ManfredKarrer** [comment]
We can merge that and add the animation tomorrow...

**Comment by ripcurlx** [comment]
> Should link go to DAO webpage or to docs? I think docs might fit better to learn more as DAO webpage is super high level

You mean this link: https://docs.bisq.network/dao-user-reference.html?

**Pull request merged**
