### PR TITLE
Define more version variables, fix style problems

### PR DESCRIPTION
**Pull request by ghubstan**
Define fontawesomefx version variables.

Fix testCompile org.mockito:mockito-core syntax.

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
@christophsturm Can you review that?

**Comment by mrosseel** [comment]
utACK

**Comment by battleofwizards** [comment]
Nice little cleanup. Could you please rebase to a single, clean commit? Otherwise ACK (tested).

**Comment by ghubstan** [comment]
> Nice little cleanup. Could you please rebase to a single, clean commit? Otherwise ACK (tested).
@battleofwizards ,

This PR is a continuation of [3052](https://github.com/bisq-network/bisq/pull/3052), created before I found out PR merges must come from topic branches, _not_ master forks.  After I made commits for that PR and waited for approval / merge, other commits were made on this file and I chased those, manually merging them to my master fork's build.gradle.

This Son of PR 3052 is also based on changes on that same master fork -- again, chasing others' commits to this file and doing the last bit of tidying up before re-forking and doing all work in topic branches from now on ;-/

I don't know how to rebase / squash commits on my master fork into a single commit.  I've never done it, and don't want to make a mess.

Do you think I should close this PR and create a new PR for merging from a _topic branch_ created from a new master fork?  Its build.gradle file will have one commit and no diffs from the one you just tested.  But if I do need to merge & tidy up others' commits while my new PR is still open, I will be able to squash those commits in the topic branch.

**Comment by battleofwizards** [comment]
> Do you think I should close this PR and create a new PR for merging from a topic branch created from a new master fork?

Yes, this is the easiest way if you don't want to rebase and force push your master. Also, it would free your master to branch out for another contributions.

As a side note, one safe way to learn rebasing is to create a new branch from the one you intended to clean. You can then experiment freely. Nothing bad will happen to your original branch. Also, you can always copy your project over.

**Comment by christophsturm** [comment]
we could also enable squash merging in the github settings.

**Comment by christophsturm** [comment]
lgtm

**Comment by ghubstan** [comment]
Closing this PR, recreating fork, topic branch "tidy-build-file" and replacement PR.

**Pull request closed without merging**
