### PR TITLE
Current work to date

### PR DESCRIPTION
**Pull request by haiqu**
Includes English language improvements, layout changes for 1024x768 monitors, new files for i18n and addition of three (or four?) new currencies. I have also nearly finished the second price feed from CMC but wanted to get this change in before the next release.

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
I fear that PR is too heavy to merge directly. I will check out your fork and split it into small pieces. I would recommend to use custom branches for each feature and make PR before it gets too heavy, so it is easier for me to merge.

**Comment by ManfredKarrer** [comment]
I added most text and layout changes to the dev branch. For the price feed stuff I need a bit more time...

**Review by ManfredKarrer — COMMENTED** [review]
I added the changes to dev.

**Review by ManfredKarrer — COMMENTED** [review]
Fixed it in dev branch.

**Comment by haiqu** [comment]
I don't blame you. The first commit to my fork included a heap of binaries, and I didn't know how to reverse it so I did an `mvn clean` and made a second commit almost immediately. But if you did a straight merge probably all that crap would end up in the master branch, which we don't want.

I'm getting better at this now though. :)

**Comment by haiqu** [comment]
Manfred, if you're finished merging into dev can you close this pull request. Otherwise all my new pushes end up on the bottom of the list.

**Comment by ManfredKarrer** [comment]
Yes I merged all layout and wording stuff in. (hope i did not miss anything)

**Pull request closed without merging**
