### PR TITLE
Integrate new netlayer library

### PR DESCRIPTION
**Pull request by mrosseel**
This is the first part of the integration of the new netlayer lib. (see issue #971)
These are the 3 parts:
- integrate netlayer, adapt TorNetworkNode
- add bridges UI
- clean up

Note: feel free to ignore this pull request, it's just open in case someone wants to test the new library.

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Just tested but localhost mode does not work. The relevant code in LocalhostNetworkNode is commented out.
With the tor version Bitcoin nodes are not discovered.
There are also a few data which seems not set: "hiddenservicedir_changeme", streamID ("Foo) -  I assume that should be a random string.
Please clean up also unused code, and make sure there are no complaints from code inspection (nullable problems,...)

**Comment by mrosseel** [comment]
I clearly stated that cleanup was not yet done.
Do you have any idea why the seednodes do work and the bitcoin nodes not?

**Comment by ManfredKarrer** [comment]
Ah, sorry did not read the comment above... No idea yet but can look into it.

**Comment by ManfredKarrer** [comment]
Merged into https://github.com/bisq-network/exchange/tree/netlayer

**Pull request closed without merging**
