### PR TITLE
Remove 3 wiz seed nodes

### PR DESCRIPTION
**Pull request by wiz**
I'm busy with mempool.space these days, so I'm going to resign as a Bisq seed node operator. I'll let @chimp1984 decide when to merge this PR, but after it's merged I'll leave my 3 seed nodes running for a few months to let everyone upgrade, and after that shut them down.

### CODE REVIEW

**Review by chimp1984 — APPROVED** [review]
utACK

**Comment by chimp1984** [comment]
@ripcurlx Please wait with merge until the seeds of the new operators are ready.

**Comment by Emzy** [comment]
utACK
/pull/6331 are the new seeds

**Review by ripcurlx — APPROVED** [review]
utACK - based on replacement in https://github.com/bisq-network/bisq/pull/6331

**Pull request merged**
