### PR TITLE
List Blur (BLUR)

### PR DESCRIPTION
**Pull request by ghost**
**Edit(10/13):** This PR includes modifications to the standard Cryptonote address validator.  The validator, with these changes, will now be able to support one and two-character prefixes for standard cryptonote addresses & subaddresses.

This is a resubmission of a previous PR located at: bisq-network/bisq-assets/pull/58
That submission had been ACKed by @blabno

**Official project URL:** https://blur.cash
**Official block explorer URL:** http://explorer.blur.cash

*Additional: The Blur CLI/GUI wallets issue a transaction private key, similar to Monero. Using a transaction private key, the transaction's hash, and a recipient address, arbitrators can verify transactions using the Blur Network Transaction Viewer (https://blur.cash/#tx-viewer).*

Two additional pull requests were submitted for a pop-up explaining the requirements to trade BLUR on Bisq. That code has already been merged.

For reference, those merged PRs can be found here:
bisq-network/bisq/pull/1617
bisq-network/bisq-core/pull/142

### CODE REVIEW

**Comment by blur-network** [comment]
Originally, this PR was re-submitted with modifications to include the recently merged CryptonoteAddressValidator. But, those are failing for Blur addresses.  However, they work properly on https://xmr.llcoins.net/addresstests.html.  

I'm looking into what the issue is, and will submit a separate PR if it is due to the checksum, with a solution.

**Comment by Technohacker** [comment]
@blur-network Could I get the original class definition as well, so that I could try fixing the Base58 regex validation?

**Comment by blur-network** [comment]
@Technohacker Definitely. Will send over as soon as I get back at a workstation.

The error seemed to be the result of public BLUR addresses being 97 characters (despite only a two-character prefix). The code appears to expect a 96 character string instead. 

Prefix is ‘bL’ (0x1e4d in hex, 7757 decimal) which I believe results in ‘c3dc’ encoded but I’m not at a computer to ensure the accuracy of the last bit.

**Comment by blur-network** [comment]
@Technohacker You can find the commit from that previous PR here: https://github.com/bisq-network/bisq/commit/331be554ddc81a690afa991c03fdeddb04f00e1

Sorry for the delay on reply.  Please do let me know if there's an error in my code that I'm just not catching, there... But the build fails on Line 31 of BlurTest.java

**Comment by Technohacker** [comment]
@blur-network Thanks! I'll see what I can do :)

**Comment by blur-network** [comment]
@blabno @ManfredKarrer Please let me know if there is anything holding back the merge process, or what I can do to speed it along.  Would like to ensure that trading of BLUR makes it into the next release, if possible.  The regex validation in this PR is functional. Once the CryptonoteAddressValidator code is complete, I can modify the Blur Address Tests to use that for validation instead.

**Comment by blur-network** [comment]
@Technohacker that offer to help, extends to you too.  Wouldn't mind helping out with the validation code.  Also wouldn't want to start working on it without knowing where your efforts are at, so as not to repeat work that is already completed.

**Comment by Technohacker** [comment]
@blur-network Unfortunately I was stuck with other work so I couldn't get anything done :sweat_smile: 
Any mode of communication we can keep? :D

**Comment by blur-network** [comment]
@Technohacker Discord is my go-to. I’ve also got telegram..

**Comment by blur-network** [comment]
Changes have been force-pushed to also validate Two-character prefixes (Blur, Aeon, etc... ) on public addresses & subaddresses, using CryptonoteAddressValidator

**Comment by blur-network** [comment]
I presume this will need ACKed again @blabno

**Review by blabno — APPROVED** [review]
ACK

**Pull request merged**
