### PR TITLE
Bump gradle wrapper to version 5.6.4

### PR DESCRIPTION
**Pull request by sam-sla**
Current version 4.10.2 is over one year old and newer versions of gradle seem to improve build times, from close to 3min to just over 2min on my machine.
Gradle 5 and above requires Java 8, and that requirement is met since the build instructions mention Java 10 and 11.

### CODE REVIEW

**Comment by ripcurlx** [comment]
@sam-sla Based on the Wrapper JAR Checksum is it correct that you updated the gradle-wrapper.jar version from v4.9 to v4.10.2? Why not directly to v5.6.2? I'm no pro Gradle user so there might be a reason for it. Would it be possible to add also the [checksum verification](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification) for the downloaded Gradle version to this PR?

**Comment by ripcurlx** [comment]
I personally use Gradle v5.6.2 for some time already and never had any issues building Bisq so far.
@devinbileck Could you give it a run on Windows as well?
@wiz Could you give it a run on Linux as well?

**Comment by sam-sla** [comment]
I did this on Linux, forgot to mention :)

As as I remember I just ran the gradle wrapper task to 5.6.2 (and actually there's a 5.6.4 now that we should use). I don't remember going from 4.9 to 4.10.2, as it is 4.10.2 in the repo already.
I am no pro gradle user either :P Will look into the checksum verification, thanks for the feedback!

**Comment by ripcurlx** [comment]
I haven't touched the gradle stuff so far, but found out when checking the hashes with the official gradle wrapper hashes that we have the wrapper file v4.9 on master and that it was updated to v4.10.2 in this PR. Maybe that is how it should be if it is upgraded step by step, but I'm just not sure if there is a real benefit having the wrapper file v4.10.2 if we download in the configuration 5.6.2.

**Comment by sam-sla** [comment]
So I've re-done this to be sure. Fetched latest from the upstream repo and updated my fork; reset this branch and updated the wrapper directly to 5.6.4 (and executed it once which actually triggered more changes to the wrapper jar and the scripts!) then ran the checksum verification like you suggested and everything seems to match. I think it should be good now :+1:

**Comment by ripcurlx** [comment]
@sam-sla Does gradle/wrapper/gradle-wrapper.jar.sha256 has any effect during the gradle download process? Or is this just the output of your manually checksum check of the wrapper jar? What I meant with verifying https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification, was the checksum of the downloaded distribution by the gradle-wrapper.jar as the gradle-wrapper.jar itself will be manually verified by us when we merge it into master anyways.

**Comment by sam-sla** [comment]
> @sam-sla Does gradle/wrapper/gradle-wrapper.jar.sha256 has any effect during the gradle download process? Or is this just the output of your manually checksum check of the wrapper jar? What I meant with verifying https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification, was the checksum of the downloaded distribution by the gradle-wrapper.jar as the gradle-wrapper.jar itself will be manually verified by us when we merge it into master anyways.

Yes it was just the "output" of the verification, that sha was pulled from their page for the current version of the jar :) I thought you wanted it in so it could be verified at any point with `sha256sum --check gradle-wrapper.jar.sha256`, shall I remove it then?

**Comment by ripcurlx** [comment]
> I thought you wanted it in so it could be verified at any point with `sha256sum --check gradle-wrapper.jar.sha256`, shall I remove it then?

Yes please, I thought this is somehow loaded by the wrapper itself for verification.

**Comment by ripcurlx** [comment]
Can you please add `distributionSha256Sum=1f3067073041bc44554d0efe5d402a33bc3d3c93cc39ab684f308586d732a80d` to the gradle-wrapper.properties file? This will cause a downloaded distribution to fail if it doesn't match the hash.
```
 bisq git:(sam/bump-gradle-wrapper) ✗ ./gradlew
Downloading https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
.........................................................................................
Verification of Gradle distribution failed!

Your Gradle distribution may have been tampered with.
Confirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.

 Distribution Url: https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
Download Location: /Users/christoph/.gradle/wrapper/dists/gradle-5.6.4-bin/bxirm19lnfz6nurbatndyydux/gradle-5.6.4-bin.zip
Expected checksum: '1f3067073041bc44554d0efe5d402a33bc3d3c93cc39ab684f308586d732a80dxxx'
  Actual checksum: '1f3067073041bc44554d0efe5d402a33bc3d3c93cc39ab684f308586d732a80d'
```

**Comment by sam-sla** [comment]
> Can you please add `distributionSha256Sum=1f3067073041bc44554d0efe5d402a33bc3d3c93cc39ab684f308586d732a80d` to the gradle-wrapper.properties file? This will cause a downloaded distribution to fail if it doesn't match the hash.
> 
> ```
>  bisq git:(sam/bump-gradle-wrapper) ✗ ./gradlew
> Downloading https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
> .........................................................................................
> Verification of Gradle distribution failed!
> 
> Your Gradle distribution may have been tampered with.
> Confirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.
> 
>  Distribution Url: https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
> Download Location: /Users/christoph/.gradle/wrapper/dists/gradle-5.6.4-bin/bxirm19lnfz6nurbatndyydux/gradle-5.6.4-bin.zip
> Expected checksum: '1f3067073041bc44554d0efe5d402a33bc3d3c93cc39ab684f308586d732a80dxxx'
>   Actual checksum: '1f3067073041bc44554d0efe5d402a33bc3d3c93cc39ab684f308586d732a80d'
> ```
That looks great, always learning :) Will do it later today :+1:

**Comment by sam-sla** [comment]
Done now, and I noticed I had modified the distribution type from "all" to "bin" by mistake, so I fixed that one now too (the sha is different from the one you tested).
I also tested the sha verification when it downloads the wrapper zip :+1:

**Review by devinbileck — APPROVED** [review]
ACK
Build was successful on Windows.
Checksums are consistent with https://gradle.org/release-checksums/.

**Review by ripcurlx — APPROVED** [review]
ACK

**Comment by ripcurlx** [comment]
@sam-sla Travis detected an abuse on this branch and I'm not able to trigger a manual build for this. Could you close this PR and make a new one with same content referencing this PR? Thanks!

**Comment by sam-sla** [comment]
Closing in favor of https://github.com/bisq-network/bisq/pull/3615

**Pull request closed without merging**
