### PR TITLE
List Greenblockcoin (GBK)

### PR DESCRIPTION
**Pull request by greenblockcoin**
Official project URL: https://greenblockcoin.io

Official block explorer URL: https://etherscan.io/token/0x9c417A6B1D2E38e4D1EFe7b981F2B80Bb77cB16B

This is a resubmission. 
Original pull request: https://github.com/bisq-network/bisq-assets/pull/106
Not sure if it was ACKed

### CODE REVIEW

**Comment by greenblockcoin** [comment]
sorry, I don't understand why I get "build failed" when using ./gradlew :assets:build. What am I doing wrong?

**Comment by cbeams** [comment]
> sorry, I don't understand why I get "build failed" when using ./gradlew :assets:build. What am I doing wrong?

I've fixed this for you, see the latest commit.

**Review by cbeams — APPROVED** [review]
ACK.

**Comment by greenblockcoin** [comment]
Oh! That's why
Thank You

**Comment by greenblockcoin** [comment]
Hi guys, I don't mean to be pushy but I just wanted to know approximately how long is it going to take for us to be listed on bisq?
Thank you again

**Comment by devinbileck** [comment]
Since this has been merged, it will be included in the next release which is planned for mid-end October.

**Comment by greenblockcoin** [comment]
great. thank you

**Comment by greenblockcoin** [comment]
hello everyone. We tried to find our token after the new release on bisq but we couldn't find it. Is there something we did wrong? or do we need to wait again for the next release?
looking forward for your reply.
thank you

**Comment by ghost** [comment]
Bisq is still on v0.8.0.
There are some delays, and we need to wait a bit for v0.9.0.

**Comment by ManfredKarrer** [comment]
Was removed following proposal https://github.com/bisq-network/proposals/issues/58

**Pull request merged**
