### PR TITLE
Proposed fix for Issue 1186: Resize "Offers to buy/sell with X" list to Bisq's vertical window size.

### PR DESCRIPTION
**Pull request by ghubstan**

### CODE REVIEW

**Comment by cbeams** [comment]
Please rebase this branch such that the only commits are your own, and that the "Merge remote-tracking branch" commits are eliminated, thanks.

**Comment by ghubstan** [comment]
Failed to fix commit history problem in my issue branch.   Rebased my fork's master branch and recreating issue branch from that, then will recreate this PR.

**Comment by cbeams** [comment]
No need to close and recreate PRs. Just rework your branch and `git push —force` it to this PR’s branch in your fork of the repo. That updates everything here in-place.

Try that, and we should be able to reopen this PR.

**Comment by ghubstan** [comment]
Sorry, I've already deleted that branch, created a new one and submitted the new PR.  

I had never needed to know how to use rebase before, hence the screw-up.  But I now know how to make sure my master fork's commit history is clean and in sync with your remote master before creating an issue branch for future PRs.

**Comment by cbeams** [comment]
No worries, thanks!

**Pull request closed without merging**
