### PR TITLE
Fix emergency payout

### LINKED ISSUE #4854: Emergency Multisig payout tool - java.lang.NullPointerException
### Description

I get a non-descriptive error when trying to use the Emergency Multisig payout tool with the `depositTxLegacy` box checked.

#### Version

Bisqv1.5.0

### Steps to reproduce

1. Start 2 bisq 1.4.2 nodes in regtest
2. On one node create an offer, on the other node take it
3. Migrate both nodes to 1.5.0
4. Use the emergency payout tool to spend the deposit tx.
You will get the exception described above.

### Screenshots

Screenshot from 2020-11-26 18-16-50

#### Device or machine

Pop!_os 18.04 LTS

#### Additional info

```
Nov-26 18:16:39.317 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Nov-26 18:16:39.317 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= null 
Nov-26 18:16:39.317 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.NullPointerException 
Nov-26 18:16:39.319 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
java.lang.NullPointerException
	at org.bitcoinj.core.TransactionInput.bitcoinSerializeToStream(TransactionInput.java:174)
	at org.bitcoinj.core.Message.bitcoinSerialize(Message.java:266)
	at org.bitcoinj.core.Transaction.bitcoinSerializeToStream(Transaction.java:1480)
	at org.bitcoinj.core.Transaction.bitcoinSerializeToStream(Transaction.java:1461)
	at org.bitcoinj.core.Message.unsafeBitcoinSerialize(Message.java:224)
	at org.bitcoinj.core.Message.bitcoinSerialize(Message.java:183)
	at org.bitcoinj.core.Transaction.hashForSignature(Transaction.java:1218)
	at org.bitcoinj.core.Transaction.hashForSignature(Transaction.java:1202)
	at bisq.core.btc.wallet.TradeWalletService.emergencySignAndPublishPayoutTxFrom2of2MultiSig(TradeWalletService.java:1129)
	at bisq.desktop.main.overlays.windows.ManualPayoutTxWindow.lambda$addContent$2(ManualPayoutTxWindow.java:167)
	at java.base/java.util.Optional.ifPresent(Optional.java:172)
	at bisq.desktop.main.overlays.windows.ManualPayoutTxWindow.lambda$addButtons$3(ManualPayoutTxWindow.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8865)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3876)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3604)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2613)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
 
java.lang.NullPointerException
	at org.bitcoinj.core.TransactionInput.bitcoinSerializeToStream(TransactionInput.java:174)
	at org.bitcoinj.core.Message.bitcoinSerialize(Message.java:266)
	at org.bitcoinj.core.Transaction.bitcoinSerializeToStream(Transaction.java:1480)
	at org.bitcoinj.core.Transaction.bitcoinSerializeToStream(Transaction.java:1461)
	at org.bitcoinj.core.Message.unsafeBitcoinSerialize(Message.java:224)
	at org.bitcoinj.core.Message.bitcoinSerialize(Message.java:183)
	at org.bitcoinj.core.Transaction.hashForSignature(Transaction.java:1218)
	at org.bitcoinj.core.Transaction.hashForSignature(Transaction.java:1202)
	at bisq.core.btc.wallet.TradeWalletService.emergencySignAndPublishPayoutTxFrom2of2MultiSig(TradeWalletService.java:1129)
	at bisq.desktop.main.overlays.windows.ManualPayoutTxWindow.lambda$addContent$2(ManualPayoutTxWindow.java:167)
	at java.base/java.util.Optional.ifPresent(Optional.java:172)
	at bisq.desktop.main.overlays.windows.ManualPayoutTxWindow.lambda$addButtons$3(ManualPayoutTxWindow.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8865)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3876)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3604)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2613)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

### PR DESCRIPTION
**Pull request by oscarguindzberg**
Fixes #4854

### CODE REVIEW

**Comment by ghubstan** [comment]
utACK

**Comment by ghost** [comment]
NACK?  Test failed for segwit although passed for legacy.  Perhaps @huey735 could double check the segwit scenario.  If necessary I can add more information tomorrow.  
p.s. I was testing this due to working on #4061.

**Comment by oscarguindzberg** [comment]
@jmacxx thanks for testing this.
I tested with segwit on regtest and it worked.
Do you have a list of steps I could follow to reproduce the bug?

**Comment by ghost** [comment]
### Segwit test

- Run Alice & Bob as clean new **v1.50+patch.4859** Bisq regtest instances - let them sync up and fund them with BTC
- Bob creates an offer to sell 0.01 BTC
- Alice takes the offer
- 1 confirmation
- Alice initiates fiat payment
- Mediator initiates Emergency Multisig payout tool
- Fills in the fields: [depositTxid], 0.016, 0.006, 0.00001234, [buyer payout address], [seller payout address ], [buyer prvkey], [seller prvkey], [buyer pubkey], [seller pubkey], [legacy **NOT** CHECKED]
- click `Sign and publish transaction`
- Transaction **DOES NOT** appear in Funds, Transactions screen neither Alice nor Bob
- Transactions screen does not update when subsequent blocks come in.
- Trade never sees published payout.


### Legacy test

- Run Alice & Bob as clean new **v1.39** Bisq regtest instances - let them sync up and fund them with BTC
- Bob creates an offer to sell 0.01 BTC
- Alice takes the offer
- 1 confirmation
- Alice initiates fiat payment
- Mediator initiates Emergency Multisig payout tool
- Fills in the fields: [depositTxid], 0.016, 0.006, 0.00001234, [buyer payout address], [seller payout address], [buyer prvkey], [seller prvkey], [buyer pubkey], [seller pubkey], [legacy CHECKED]
- click `Sign and publish transaction`
- Transaction appears in Funds, Transactions screen on both Alice and Bob
- 1 confirmation, transactions screen shows the appropriate confirmation progress icons

**Comment by oscarguindzberg** [comment]
@jmacxx do you have the logs of the mediator at the time you click "Sign and publish transaction" for the segwit use case? do you have bitcoin regtest logs?

**Comment by oscarguindzberg** [comment]
@jmacxx are you using default security deposits? If you do, the expected payouts are 0.0115 and 0.0015

**Comment by ghost** [comment]
Yes default security deposit is 0.006 for a 0.01 trade.  Its the minimum security deposit.  Payouts are 0.006 for seller and 0.016 for buyer.  Here's what appears in the mediator's log (regtest).  The transaction does not show up in the blockchain.

        Nov-30 13:09:58.017 [JavaFX Application Thread] INFO  b.c.btc.wallet.WalletService: 
        payoutTx:
        Transaction{95e2218d447731be5a9da8e6cb8baf19a357c6dd009c0fd99989a67a6bd1c22f, wtxid 9adae4e46eacd21e698dbe34a53b468acbb76d57a7f4b15579d424951c11f580
        weight: 673 wu, 169 virtual bytes, 334 bytes
        purpose: UNKNOWN
           in   <empty>  0.02201234 BTC (2201234)
                witness:EMPTY 30440220641962b4ba8140c8eec8340e6df93f754211dcec64811aa9945c38fc980d22fe02207f0588d13272b8afc17b110e1f13bb5ff7850e5c1890085774da47c516e3e5ef01 3045022100ffe944ff7562cdb369f1b044dfabf4bca84ad5b2be90dcb64eafd1decc2828d5022047c3b2ce5b664ee3cf293d7e50db70f0e39dce462672e8e86868956bcd0ce2c601 522102f77470b7d2cb72796d5d1d4b74bf05720e6227a44aa209d765cd61d0a5fb1838210242a4bc03819c2bb8cdc2d8ed31ef34cb8ae64a1348e3eeb8f7e998acb6a44f7352ae
                unconnected  outpoint:6f306ee571b8feeb7ed2b96b8affb27a393083a4ae3d1d311b543acfbe1e3dc5:0
           out  0[] PUSHDATA(20)[5226d2b975a4e87b4d1bbb9a43bcb3a01c8380ba] (00145226d2b975a4e87b4d1bbb9a43bcb3a01c8380ba)  0.016 BTC (1600000)
                P2WPKH addr:bcrt1q2gnd9wt45n58kngmhwdy809n5qwg8q96enen2q
           out  0[] PUSHDATA(20)[1b3e28d844ce3e7b495abc56609be4c199683fe9] (00141b3e28d844ce3e7b495abc56609be4c199683fe9)  0.006 BTC (600000)
                P2WPKH addr:bcrt1qrvlz3kzyecl8kj26h3txpxlycxvks0lfre7eq2
           fee  0.00001833 BTC/wu, 0.00007301 BTC/vkB, 0.00003694 BTC/kB  0.00001234 BTC
        } 
        Nov-30 13:09:58.018 [JavaFX Application Thread] INFO  o.b.core.TransactionBroadcast: Waiting for 1 peers required for broadcast, we have 1 ... 
        Nov-30 13:09:58.019 [JavaFX Application Thread] INFO  o.b.core.TransactionBroadcast: broadcastTransaction: We have 1 peers, adding 95e2218d447731be5a9da8e6cb8baf19a357c6dd009c0fd99989a67a6bd1c22f to the memory pool 
        Nov-30 13:09:58.019 [JavaFX Application Thread] INFO  o.b.core.TransactionBroadcast: Sending to 1 peers, will wait for 0, sending to: Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.19.0.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2020-11-30 13:08:44, height=4535} 
        Nov-30 13:09:58.022 [JavaFX Application Thread] ERROR b.d.m.o.w.ManualPayoutTxWindow: onSuccess

**Comment by ghost** [comment]
Ok got it to work... had to make the Tx fee equal to the amount left over in the UTXO it is spending... in this example it had to be 0.00003388.  Strange that it still worked in legacy tx though.  Anyway, sorry for bothering you.

**Comment by oscarguindzberg** [comment]
> Yes default security deposit is 0.006 for a 0.01 trade

you are right about that.

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
