### PR TITLE
fix a generics warning and some idea autofixes

### PR DESCRIPTION
**Pull request by christophsturm**

### CODE REVIEW

**Comment by christophsturm** [comment]
I just noticed that the diff is much bigger than it should be, probably because i have "rearrange code" checked in my idea git dialog. is rearrange code not something that should be use?

**Comment by ManfredKarrer** [comment]
> is rearrange code not something that should be use?

We never used it. I tried it out sometimes but I was not happy with its decisions....

Organize Imports is mandatory to be used and defined in the projects IDEA settings.

**Comment by christophsturm** [comment]
ok i will keep rearrange code off from now on.

**Comment by sqrrm** [comment]
@christophsturm I should probably have merged the PRs in order, now there is a conflict. Looks reasonable.

**Comment by christophsturm** [comment]
I'll just redo this PR without rearrange code.

**Pull request closed without merging**
