### PR TITLE
Changes required for GRIN re-listing

### PR DESCRIPTION
**Pull request by ghost**
- Changes GRIN altcoin account validation to use [SlatepackAddress](https://github.com/mimblewimble/grin-rfcs/blob/master/text/0015-slatepack.md#slatepackaddress) format.
- Update tests accordingly.
- Update the account creation popup text accordingly (see screenshots).
- See also: https://bisq.wiki/Trading_GRIN

https://github.com/bisq-network/proposals/issues/350
https://github.com/bisq-network/growth/issues/205#issuecomment-962480146

### Account creation

image

### Account creation

image

### Account creation popup

grin_account_popup

### Trade, start payment

grin_payment_start

### Trade, confirm payment received

grin_confirm_payment

### CODE REVIEW

**Review by chimp1984 — APPROVED** [review]
utACK

**Review by ripcurlx — APPROVED** [review]
utACK

**Comment by ripcurlx** [comment]
I'll re-enable the Grin support in the app as soon as the proposal is approved.

**Comment by ripcurlx** [comment]
@jmacxx Do we need some pricenode changes for it as well, or will it be offered as a fixed price only pair?
Bildschirmfoto 2021-11-24 um 10 39 44

**Comment by ghost** [comment]
It'll be like the BSQ market, where the price is determined by the offers in Bisq itself  GRIN is not on any of the big exchanges, so I think a feed would not be applicable.  Documented in the [wiki](https://bisq.wiki/Trading_GRIN#FAQ)

**Pull request merged**
