### PR TITLE
Fix api's createpaymentacct error handling

### PR DESCRIPTION
**Pull request by ghubstan**
- Add missing boilerplate error handling to `GrpcPaymentAccountsService`.

- Edit some `PaymentAccountForm` & `PaymentAccountTypeAdapter` exception messages that would be passed to CLI;  they should be in the same style as existing core api & cli err msgs.

This is the 16th in a chain of PRs beginning with https://github.com/bisq-network/bisq/pull/4793.  

PR https://github.com/bisq-network/bisq/pull/4821 should be reviewed before this one.

### CODE REVIEW

**Comment by ghubstan** [comment]
Force travis build.

**Comment by ghubstan** [comment]
Backing out the changes made to `BsqSendView` in commit 446bd32 does not affect the `sendbsq` functionality in the api or desktop, but the small bit of duplication resulting from this single file revert should be removed in a later PR.

**Review by sqrrm — COMMENTED** [review]
utACK

**Comment by ghubstan** [comment]
This PR is being closed after requested changes were committed in a the final, downstream PR (https://github.com/bisq-network/bisq/pull/4858) in this chain.

Merging of the final PR in the chain implies approval and merging of this PR.

**Pull request closed without merging**
