### PR TITLE
Add UTF8 for getBytes calls

### LINKED ISSUE #2729: Update prompt not shown on Windows
There are multiple reports of Windows 10 users not receiving the prompt to update to v1.0. Whereas Linux and macOS users are receiving the prompt.

### PR DESCRIPTION
**Pull request by ManfredKarrer**
Fixes https://github.com/bisq-network/bisq/issues/2729

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
@devinbileck Would be great if you could test that on Windows with whole smoke test (trade) as I cahnged all ocurrances of getByte(). I tested on regtest and all worked.

**Review by ripcurlx — APPROVED** [review]
ACK - Still works for me on macOS and tried it with the changed update message on Windows 10, which works as well.

**Comment by devinbileck** [comment]
ACK. Works for me as well on regtest using Windows 10.

**Review by devinbileck — COMMENTED** [review]
ACK

**Comment by ManfredKarrer** [comment]
Has anyone tested notifiactions? Not sure if the change there could break something.

**Comment by devinbileck** [comment]
Yes, I tested alert notifications as well as private messages (via arbitration). And also used some random UTF-8 characters in the messages. Didn't encounter any issues.

**Pull request merged**
