### PR TITLE
List MoX (MOX)

### PR DESCRIPTION
**Pull request by backupacctuname**
Official project URL: https://getmox.org/
Official block explorer URL: https://blockexplorer.getmox.org/

### CODE REVIEW

**Comment by backupacctuname** [comment]
closed and reopened to trigger CI

**Comment by blabno** [comment]
This is a privacy coin. How can the arbitration be conducted?

**Review by blabno — APPROVED** [review]
ACK

**Comment by backupacctuname** [comment]
An arbitrator could use the block explorer to address that : 
https://blockexplorer.getmox.org/tx/80a7c43fbfb10d92187da92e8aa08f1fc94f0613153dee09aea1b0191bcabc4f
given a transaction private key and an address you have the possibility to prove spending

**Pull request merged**
