### PR TITLE
Replace deprecated bisq explorer settings

### PR DESCRIPTION
**Pull request by ghost**
If user preferences were set to a federated explorer that has been retired, switch it to another explorer from the provided list.
Users can still choose their own explorer, or enter a custom explorer address (such as their local node).

### CODE REVIEW

**Review by ripcurlx — DISMISSED** [review]
utACK

**Comment by ripcurlx** [comment]
@jmacxx You missed to sign your commit. Everything else is looking fine.

**Comment by ghost** [comment]
@ripcurlx  :+1: Signed it now.

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
