### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by shuoer86**
Fix typos

### CODE REVIEW

**Comment by shuoer86** [comment]
@alejandrogarcia83 could you take a moment to help to review? Thank you very much.

**Review by alvasw — APPROVED** [review]
Nit

Please squash your commits and change the commit message to something like "Fix Code Comment Typos" or "Fix Typos in Code Comments". You can find our guide on how to write commit messages here: https://github.com/bisq-network/bisq/blob/master/CONTRIBUTING.md#write-well-formed-commit-messages .

**Review by alvasw — CHANGES_REQUESTED** [review]
Nit

Please squash your commits and change the commit message to something like "Fix Code Comment Typos" or "Fix Typos in Code Comments. You can find our guide on how to write commit messages here: https://github.com/bisq-network/bisq/blob/master/CONTRIBUTING.md#write-well-formed-commit-messages .

**Comment by alejandrogarcia83** [comment]
Please reopen this PR when it's ready.

**Comment by shuoer86** [comment]
@alejandrogarcia83 @alvasw thank you for your review. 
And I have squashed my commits. Could you reopen it?

**Pull request closed without merging**
