### PR TITLE
Allow seller to take any offers

### PR DESCRIPTION
**Pull request by ManfredKarrer**

### CODE REVIEW

**Review by sqrrm — APPROVED** [review]
utACK

**Review by ripcurlx — APPROVED** [review]
ACK - was able to re-produce it with Zelle in current master and it was fixed in this PR.

**Comment by ripcurlx** [comment]
☝️ Just improved layout of Zelle buyer form on the way to prevent scrolling

**Review by sqrrm — APPROVED** [review]
ACK

Looks good

**Comment by ripcurlx** [comment]
Just found a little detail that needed to be changed. Translations and references of March 15th needs to be changed to March 1st. And so the release build starts again 😉

**Pull request merged**
