### PR TITLE
Only use default currency if payment account available

### LINKED ISSUE #6157: When creating an offer it does not recognize the account currency
With current main branch version If the user has set up an account and has the offer book set to Show all currencies and creates an offer they get displayed the popup that they need to set up an account. Only if the user selects the currency of their account first they can create an offer.

### PR DESCRIPTION
**Pull request by ripcurlx**
Fixes #6157

### CODE REVIEW

**Comment by ripcurlx** [comment]
@chimp1984 @xyzmaker123 ☝️  Thanks for finding this issue 👍

**Comment by ripcurlx** [comment]
@xyzmaker123 Could you please give this a shot? Thanks!

**Review by ghost — APPROVED** [review]
ACK - I tested scenarios described in issue and everything worked properly.

**Review by bisq-github-admin-3 — APPROVED** [review]
utACK - based on https://github.com/bisq-network/bisq/pull/6160#pullrequestreview-953175371

**Pull request merged**
