### PR TITLE
Update all Pricenodes with new Tor V3 onions

### PR DESCRIPTION
**Pull request by wiz**
Pending merge of #4315 and rough consensus to proceed with migration plan in bisq-network/projects#35

wizpriceje6q5tdrxkyiazsgu7irquiqjy2dptezqhrtu7l2qelqktid (@wiz)
emzypricpidesmyqg2hc6dkwitqzaxrqnpkdg3ae2wef5znncu2ambqd (@Emzy)
devinpndvdwll4wiqcyq5e7itezmarg7rzicrvf6brzkwxdm374kmmyd (@devinbileck)
aprcndeiwdrkbf4fq7iozxbd27dl72oeo76n7zmjwdi4z34agdrnheyd (@mrosseel)
ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid (@alexej996)

### CODE REVIEW

**Review by sqrrm — COMMENTED** [review]
Are all price node operators ready for this change?

Are there any other effects of this, like the torv3 nodes running the bisq index?

**Comment by wiz** [comment]
This actually isn't a big deal since we will have both v2 and v3 onions running on the same pricenodes at the same time. We are tentatively planning the migration (to repoint old v2 onions) about 48 hours from now. If there are any issues we can revert this change before v1.3.8 release.

**Review by sqrrm — APPROVED** [review]
utACK

**Comment by twofaktor** [comment]
Hello, `http://wizpriceje6q5tdrxkyiazsgu7irquiqjy2dptezqhrtu7l2qelqktid.onion/getAllMarketPrices`

imagen

Is it discontinued?

**Pull request merged**
