### PR TITLE
List Ittrium (XIT)

### PR DESCRIPTION
**Pull request by IttriumCore**
- Official project URL: https://ittrium.io/ 
- Official block explorer URL: https://explorer.ittrium.io/
- Whitepaper Summary Video URL: https://youtu.be/ZHJNRHzYG6U

### CODE REVIEW

**Comment by IttriumCore** [comment]
Apologies in advance as this may appear as if I’m being inpatient.  I'm inquiring as to how long it might take before we’d know if Ittrium is to be approved on the bisq network or not?  

I only ask because Ittrium has been offered a discount to list on another DEX and we only have 2 days remaining to receive this discount.  If Ittrium was to be listed on Bisq, then we’d only be wasting capital paying to get listed on the other DEX. However, if our Bisq application was to be rejected then, depending on the timing we may miss out on the discount offered.  

Any info you could provide regarding approval/rejection time frames would be greatly appreciated.

**Comment by blabno** [comment]
@IttriumCore please rebase against master and resolve conflicts.

**Comment by IttriumCore** [comment]
@blabno conflicts have been resolved

**Comment by IttriumCore** [comment]
Hi @ManfredKarrer and @blabno 

Just been reading the ‘Fee model for Asset listing #42’ and believe this is a great way to deal with the issue of no trading volume.  I assume that all new listings will continue to be postponed until this proposal can be implemented (perhaps in the next release?).  If so, are you able to provide an estimated date or time frame before listing recommences?

Thanks in advance.

**Comment by ManfredKarrer** [comment]
@IttriumCore No we are not postponing and the DAO might need about 3 months to be launched on mainnet. We are just short on dev resources and reviewing and merging assets where >90% never get traded anyway has low prio for us. Thats why there is a bigger backlog. I just removed most of the assets we added in 0.7 as they never get traded. Not a productive investment of our time to add and remove assets....

**Comment by IttriumCore** [comment]
Thanks @ ManfredKarrer 
Totally understand how frustrating it must be to list assets that never trade.  I also appreciate that listing is a low priority given dev resources until the DAO is completed, however is there any way to expedite Ittrium’s listing?   We’d be happy to pay a listing fee to cover dev time or perhaps we could  provide a minimum amount of BTC liquidity for Ittrium (i.e. set up a minimum value of BTC buy orders for XIT)?

**Comment by IttriumCore** [comment]
Thanks @ManfredKarrer 
Totally understand how frustrating it must be to list assets that never trade.  I also appreciate that listing is a low priority given dev resources until the DAO is completed, however is there any way to expedite Ittrium’s listing?   We’d be happy to pay a listing fee to cover dev time or perhaps we could  provide a minimum amount of BTC liquidity for Ittrium (i.e. set up a minimum value of BTC buy orders for XIT)?

**Comment by IttriumCore** [comment]
Hello @ManfredKarrer, @blabno and @cbeams 

Are you able to advise if there was an issue with our pull request, if not, can you please advise why Ittrium was not added in the recent v0.9.0 release? 

I understand that Dev resources are limited but we have been patiently waiting for 7 weeks, in which time, there has been 2 releases.  Furthermore, we offered to pay for Dev time or provide a minimum amount of BTC liquidity for Ittrium (i.e. set up a minimum value of BTC buy orders for XIT), so it’s a little disappointing we weren’t listed, particularly as other coins got listed who submitted their pull-requests after ours.   

I appreciate it’s a privilege not a right that you list Ittrium on Bisq, however keeping us in limbo is frustrating.  Our preference is to only list on Bisq because we believe in the ‘real’ decentralized nature of the platform.  That said however, if you feel Ittrium will not be listed during the next release, I’d greatly appreciate if you could advise me as soon as possible so we can start making alternative arrangements to list elsewhere.

Kind Regards
Drew

**Comment by blabno** [comment]
You were supposed to rebase instead of merge master. Your branch must be composed of only a single commit.

Rebase, resolve conflicts and squash into single commit. Apart from that code looks OK.

**Comment by ManfredKarrer** [comment]
Close because of inactivity.

**Pull request closed without merging**
