### PR TITLE
Optimize DAO charts [7]

### PR DESCRIPTION
**Pull request by chimp1984**
Based on https://github.com/bisq-network/bisq/pull/5794

Use CompleteableFuture and do chart calculations in threads. Reduce calls to calculations.

### CODE REVIEW

**Comment by ripcurlx** [comment]
I'll review starting with https://github.com/bisq-network/bisq/pull/5795/commits/c7dd9a0e0a8ce5eb5ed33db7d5c1004045e4eb5f

**Review by ripcurlx — DISMISSED** [review]
utACK - Just one minor Codacy complaint, but besides that everything looks fine.

**Comment by chimp1984** [comment]
Merged/Rebased on master

**Review by ripcurlx — DISMISSED** [review]
ACK

**Review by ripcurlx — APPROVED** [review]
ACK

**Pull request merged**
