### PR TITLE
Hide text that is not applicable in take offer view

### PR DESCRIPTION
**Pull request by devinbileck**
When taking an offer that does not specify an amount range, "Check if offer is available" text was being displayed when it shouldn't be.

It was explicitly hiding the offerAvailabilityBusyAnimation, but not the offerAvailabilityLabel.

Fixes https://github.com/bisq-network/bisq/issues/1742

### CODE REVIEW

**Review by ManfredKarrer — CHANGES_REQUESTED** [review]
NACK.
I added more background info in #1742. We must not hide is but change the layout so that it is better visible to the user and update the button states so that the user does not fund his wallet before the offer availibility check is successfully completed.

**Comment by devinbileck** [comment]
@ManfredKarrer A fixed amount offer now waits until the offer has been confirmed to be available, as shown below:
image

Once confirmed, it will show the fund trade fields:
image

**Comment by ManfredKarrer** [comment]
A cool! Looks good to me! @ripcurlx - What do you think? I leave it to you to review/merge.

**Review by ManfredKarrer — APPROVED** [review]
utACK - I would prefer if @ripcurlx does the review/merge

**Review by ripcurlx — APPROVED** [review]
ACK - tested it on Regtest with a range and a single amount offer. Everything looking good!

**Comment by ripcurlx** [comment]
I'll merge it although Travis fails as it is related to the current Java 10 JDK not loaded issue.

**Pull request merged**
