### PR TITLE
Change unconfirmed popup to 24h after trade start.

### PR DESCRIPTION
**Pull request by ghost**
Ref: #6948
@pazza83 as discussed, here is the change to the unconfirmed trade popup:  

- Instead of 4 hours now is 24 hours.
- A button to resync is included.

Let me know if you want any wording, etc changes.

resync_popup

Existing conirmation prompt is shown before starting resync process:

resync_popup2

### CODE REVIEW

**Comment by pazza83** [comment]
Thanks @jmacxx 

With regards the following warning message:

294575239-2b4205f9-55c5-49a2-8c84-84d02fa9c810

Would it be possible for there to be a deposit transaction lookup prior to showing the message?

- If the deposit transaction was still unconfirmed no error message needs to be shown
- If the deposit transaction was confirmed on the blockchain but not showing in Bisq than an error message can be shown prompting the user to do an SPV resync

**Comment by ghost** [comment]
> Would it be possible for there to be a deposit transaction lookup prior to showing the message?

@pazza83 - done.

**Review by alvasw — APPROVED** [review]
Good!

utACK

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
