### PR TITLE
List DSTRA (DST) - UPDATE to v2

### PR DESCRIPTION
**Pull request by krestien**

### CODE REVIEW

**Comment by krestien** [comment]
Official project URL: https://dstra.io
Official block explorer URL: https://blocks.dstra.io

**Comment by blabno** [comment]
This asset has been listed by @fish-en. Can he issue this PR?

**Comment by krestien** [comment]
> This asset has been listed by @fish-en. Can he issue this PR?

We're both parts of the DSTRA Dev Team, you can see that I'm a legit member when viewing our Github at https://github.com/DSTRACoin/ - I made my contribution public for you.
Best Regards

**Comment by blabno** [comment]
@cryptoluka Please rebase against master and resolve conflicts.

**Comment by ManfredKarrer** [comment]
Close as no response from dev. Also we have a code freeze for new release soon.

**Pull request closed without merging**
