### PR TITLE
Add Octocoin

### PR DESCRIPTION
**Pull request by my-first**
### Ticker symbol:
888

### Official coin name:
Octocoin

### Official altcoin webpage where Bitsquare will be added as official exchange:
http://octocoinfoundation.org/resources

### URL of the block explorer:
https://chainz.cryptoid.info/octo/

### Example address:
8NiZ7kpdNT8rLMzi9QW6eupSXvknBwp94m

### Social media accounts like Twitter account, subreddit, etc.:
Octocoin Foundation: http://octocoinfoundation.org
Octocoin Download: http://getoctocoin.com
Octocoin Twitter: https://twitter.com/OctocoinProject

I have confirmed that the ticker does not conflict with https://en.wikipedia.org/wiki/ISO_421784

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
You have to add a PR for a address validation. See the forum post for details.

EDIT: Ah sorry I did not read the code changes. Seems you have added an address validation. Sorry was too fast without looking carefully...

**Comment by ManfredKarrer** [comment]
I just checked it but there was several issues. You have not tested it at all (one class was missing the .java so you even could not have compiled it). A test is failing as well. I will give you a second chance to fix that, but if there are still issues i will not add it.
I will update that in the requirements that in such case I will reject. I need to use my time better then testing not-tested committed code.

**Comment by my-first** [comment]
Oops, sorry for that silly mistake.  It's been a while since I've done work on JAVA.  That's what happens when I work late and manually try to do stuff through copy and paste.  I'll fix and make a new PR.

**Comment by ManfredKarrer** [comment]
Yes please run the unit test!

**Comment by my-first** [comment]
Fixes complete.

Verified that it builds and unit test are successful.

https://pastebin.com/1bsp0Yd2
https://pastebin.com/U7Q0kyra

**Pull request merged**
