### PR TITLE
Add percentage price to open offer view

### PR DESCRIPTION
**Pull request by chimp1984**
Add percentage price to open offer view.
Extract code from offer book to PriceUtil class for reuse

### CODE REVIEW

**Comment by chimp1984** [comment]
Another Travis issue:
```
Execution failed for task ':proto:extractIncludeProto'.

> Could not resolve all files for configuration ':proto:compileClasspath'.

   > Could not download lombok.jar (org.projectlombok:lombok:1.18.2)

      > Could not get resource 'https://repo.maven.apache.org/maven2/org/projectlombok/lombok/1.18.2/lombok-1.18.2.jar'.

         > Connection reset
```

**Comment by ripcurlx** [comment]
@chimp1984 Could you please resolve the conflicts?

**Comment by chimp1984** [comment]
@ripcurlx Done.

**Comment by ripcurlx** [comment]
🤔 looks like nothing got changed in this PR. Did you add the commits in https://github.com/bisq-network/bisq/pull/5001 already?

**Comment by chimp1984** [comment]
Yes #5001 was based on that. I close it.

**Pull request closed without merging**
