### PR TITLE
Rename provider repository

### PR DESCRIPTION
**Pull request by HenrikJannsen**

### CODE REVIEW

**Review by alejandrogarcia83 — DISMISSED** [review]
utACK

**Review by alejandrogarcia83 — DISMISSED** [review]
utACK

**Comment by alejandrogarcia83** [comment]
I can't merge this PR due to merge conflicts. Please resolve them. Thank you!

**Comment by HenrikJannsen** [comment]
Rebased

**Review by djing-chan — APPROVED** [review]
utACK

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
