### PR TITLE
Add monospace font support and optimize alignment for number columns

### LINKED ISSUE #1028: [UI] Mono font and list alignment
Please, switch the main font for lists to Mono Fonts, as it makes it much easier to read the values. Additionally, right align all columns with values to the right or even better center it to the comma.

bisq3

It is quite difficult to compare values column-wise if they aligned to the center with serif-font.  A really nice Font is **Fira Sans/Mono**. It is Mozilla's font and it is perfectly readable even at very small sizes.

### PR DESCRIPTION
**Pull request by ripcurlx**
This will fix https://github.com/bisq-network/exchange/issues/1028 and improve comparability within number columns.

### CODE REVIEW

**Comment by ripcurlx** [comment]
Unfortunately the rebasing, after I did already a couple of merges, somehow duplicated some of my own commits. I have to stop pushing my local commits to my own public repo when using --rebase. If it's a problem I could checkout a clean master branch and add all changes into one big commit.

**Review by cbeams — CHANGES_REQUESTED** [review]
NACK, per https://github.com/bisq-network/exchange/issues/1028#issuecomment-367323312

**Comment by ripcurlx** [comment]
@cbeams: As discussed with @ManfredKarrer, I've used Droid Sans Mono now and we'll keep it until we find a even better suited mono space font for Verdana.

**Review by ManfredKarrer — COMMENTED** [review]
Is is intended to use the new font also for non-number columns like in market/trades?
Is is intended to use the new font only at tables in the market and buy/sell screens? It is currently not used in: funds, portfolio and settings.

**Comment by ripcurlx** [comment]
At the moment I've only used them in columns where I saw a big advantage having this mono space aligned view. If in a table only numbers benefited from the alignment I only used the font for the numbers, but left the text with Verdana. If I had one column with text that I wanted to align, I used the mono space font in all columns not to have too much of a mix.

> Is is intended to use the new font also for non-number columns like in market/trades?

As mentioned above I think I'll revert this table view only to use the mono space for the numbers as it isn't super easy to support every localized date format and do it in a way that it is equally spaced.

> Is is intended to use the new font only at tables in the market and buy/sell screens? It is currently not used in: funds, portfolio and settings.

Atm I only used it in tables where I saw a big benefit, but I could expand it to more tableviews where it would help to scan through lists of numbers as well. 

@ManfredKarrer Maybe we could have a quick call on this tomorrow, as I'm afk today after lunchtime.

**Comment by ManfredKarrer** [comment]
@ripcurlx Sure ping me when its good for you.

**Comment by ManfredKarrer** [comment]
@ripcurlx 
I got a nullpointer at:
```final Optional<Offer> highestPriceOffer = allBuyOffers.stream().max(Comparator.comparingLong(o -> o.getPrice().getValue()));```

**Comment by ManfredKarrer** [comment]
We had a voice call to discuss the issue and came to good conclusions.
@ripcurlx Feel free to merge yourself as soon you are ready.

**Comment by ripcurlx** [comment]
I've implemented all changes discussed with @ManfredKarrer.

**Pull request merged**
