### PR TITLE
Add check for disputes for donation address

### PR DESCRIPTION
**Pull request by chimp1984**
Depends on https://github.com/bisq-network/bisq/pull/4134

### CODE REVIEW

**Comment by ripcurlx** [comment]
@chimp1984 Please have a look at the conflicts, so I can review and merge this PR for the next release. Thanks!

**Comment by sqrrm** [comment]
The first commit is no longer needed as it's now handled in the trade protocol.

The second commit I'm not sure it's a good idea to have. It adds complexity and doesn't really add much value. The main thing would be to find out that there is a bad address in use, but that could be done easier I think.

**Comment by chimp1984** [comment]
> doesn't really add much value. The main thing would be to find out that there is a bad address in use, but that could be done easier I think.

I think it does add value as it adds another protection level at the moment when the refund agent would do the payout to avoid invalid payouts.

**Comment by ripcurlx** [comment]
@chimp1984 If you resolve the conflicts I'm happy to merge this PR for v1.3.7. Thanks!

**Comment by chimp1984** [comment]
I will try to find time....

**Comment by chimp1984** [comment]
I did not had time for testing. It would require a bit of testing before release....

**Comment by chimp1984** [comment]
Replaces by #4516

**Pull request closed without merging**
