### PR TITLE
Show past deviation in monitor

### PR DESCRIPTION
**Pull request by chimp1984**
Improved seed monitor. Code only affects monitor module and partly seed nodes (to a small extent). The branch was used by most seed nodes already over the past weeks.

### CODE REVIEW

**Comment by ripcurlx** [comment]
> The branch was used by most seed nodes already over the past weeks.

@wiz can you please ACK that based on your experience on your seed nodes? Thanks!

**Comment by wiz** [comment]
ACK - we've been testing this over the past few weeks :+1:

**Review by wiz — APPROVED** [review]
ACK - we've been testing this over the past few weeks 👍

**Review by ripcurlx — APPROVED** [review]
utACK - Looked through the code and it looks fine. Testing ACK based on https://github.com/bisq-network/bisq/pull/4734#pullrequestreview-522171125

**Pull request merged**
