### PR TITLE
Remove awt dependencies

### PR DESCRIPTION
**Pull request by ghost**
Related to #4940 

Replace usage of awt classes wherever possible with the JavaFX equivalents.

- Do not use system tray.
- Remove usages of `java.awt.Desktop` for opening URIs.  Use `openSystemSpecific()` instead.
- Remove usages of `java.awt.GraphicsEnvironment`.  Use `javafx.stage.Screen` instead.
- Detect MacOS retina display by `Screen.getPrimary().getOutputScaleX() > 1.5;`

----

To open a URI we take a convoluted path from `GUIUtil.openWebPage` (desktop) to `Utilities.openURI` (common) to `DesktopUtil.browse` (common).  What do you think about simplifying this by moving DesktopUtil from common to desktop?

### CODE REVIEW

**Comment by ghost** [comment]
Could someone with MacOS check that the retina display is detected and the high res Bisq Icon is chosen as a result.  Also that links open up the browser correctly.

I did testing on Linux and Windows.

**Review by ripcurlx — DISMISSED** [review]
ACK

Just tested it on macOS and everything works the same as before :+1:

**Comment by ripcurlx** [comment]
Please resolve the conflict and it is good to get merged.

**Comment by ghost** [comment]
Merge conflict resolved.  Thanks for checking it on MacOS!

**Review by ripcurlx — APPROVED** [review]
ACK

**Pull request merged**
