### PR TITLE
Fix arbitrator language selection

### PR DESCRIPTION
**Pull request by devinbileck**
- Fix arbitrator language selection where using arrow keys to navigate the combobox would add the first language. (https://github.com/bisq-network/bisq/issues/354)
- Fix arbitrator language selection prompt text no longer appearing after selecting a language.

### CODE REVIEW

**Comment by devinbileck** [comment]
I just realized the same issue exists with the comboboxes for adding currencies and altcoins in the preferences view. Not sure yet if there are others. I will enter a separate PR to address those.

**Comment by ManfredKarrer** [comment]
I assume same issue will happen at comboboxes as they use internally a popup (new stage). Will require probably to overwrite base classes...

**Comment by devinbileck** [comment]
It only affects comboboxes that intentionally clear their value once you make a selection. So far, I believe it only affects just these 3 comboboxes mentioned.

**Comment by ripcurlx** [comment]
ACK - looking good. Thanks for the fix @devinbileck! It is kind of tricky with prompt text and comboboxes. I also ran into some issues during the re-design. But your workaround helps to fix this issue at least.

**Pull request merged**
