### PR TITLE
Display 2 decimal places for fiat trading fees

### LINKED ISSUE #3972: Trading fee decimals not displayed
### Description

After #3926 the trading fee prices converted to EUR is not displaying decimals when creating or taking an order. I'm using Bisq v1.2.7

### Expected behaviour

At least for EUR, where decimals have significant value, it's preferred to display one or two decimals.

### Screenshots

paste

CC @milesap

### PR DESCRIPTION
**Pull request by ghost**
Fixes #3972 

Fixes an issue where fiat trading fees were being rounded to the nearest whole dollar.

Tests pass, as did my visual sanity checks:

### CODE REVIEW

**Review by stejbac — COMMENTED** [review]
To avoid duplication, it might be better to use `DisplayUtils.formatAverageVolumeWithCode`. (I added that method specifically to restore the original behaviour of `formatVolumeWithCode` where needed.)

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - please see https://github.com/bisq-network/bisq/pull/3973#pullrequestreview-359423553

**Comment by ripcurlx** [comment]
@milesap Did you see https://github.com/bisq-network/bisq/pull/3973#pullrequestreview-359423553?

**Comment by ghost** [comment]
Sorry got distracted, pushed updated code per the review. @ripcurlx

**Review by ripcurlx — APPROVED** [review]

**Comment by ripcurlx** [comment]
ACK

Tested it on Mainnet and it works again as in v1.2.5-

**Pull request merged**
