### PR TITLE
Monitor release: Showing off

### PR DESCRIPTION
**Pull request by freimair**
see https://github.com/bisq-network/proposals/issues/62 for details

### CODE REVIEW

**Review by ripcurlx — APPROVED** [review]
utACK

**Review by ManfredKarrer — COMMENTED** [review]
In P2PNetworkLoad.java:

Why not use 
`buckets.putIfAbsent(className, new Counter());
buckets.get(className).increment();`

instead of 
`try {
                    buckets.get(className).increment();
                } catch (NullPointerException nullPointerException) {
                    buckets.put(className, new Counter());
                }`

**Comment by ManfredKarrer** [comment]
In P2PNetworkLoad.java:
Re:
`bucketsPerHost.put(connection.peersNodeAddressProperty().getValue(), buckets);`
It can be that connection.peersNodeAddressProperty() is not set yet. Maybe more safe if you add a check if it is nul null.

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Pull request merged**
