### PR TITLE
list bzedge

### PR DESCRIPTION
**Pull request by sennevb**
Official project URL:
https://getbze.com/

insight explorer : https://explorer.getbze.com/

### CODE REVIEW

**Review by blabno — CHANGES_REQUESTED** [review]
NACK apply Bisq code style

**Comment by sennevb** [comment]
@blabno  can you point me to a link or so, i dont know what you mean with "bisq code style"

**Comment by faneaatiku** [comment]
Hello. @blabno can we get a hint or a response on it ?

**Comment by blabno** [comment]
https://github.com/bisq-network/bisq/tree/master/.idea/codeStyles

**Comment by ripcurlx** [comment]
@sennevb Closing PR because of inactivity. Feel free to re-open when PR requirements are fulfilled.

**Pull request closed without merging**
