### PR TITLE
Add option to use different css for dev mode

### PR DESCRIPTION
**Pull request by sqrrm**
This is to help differentiate dev instances and live ones.
This can help devs avoiding silly mistakes.

Small thing, but a different color really helps sometimes.

### CODE REVIEW

**Comment by wiz** [comment]
Cool idea, obviously Testnet should be a different color. To take it even further tho, is the additional command line option even necessary? Seems like you could just check isDevMode() in the loadSceneStyles() and load the theme-dev.css

**Comment by sqrrm** [comment]
It would be a bit annoying to do UI development if the UI isn't looking like prod so I figured it's better to have it as a separate option.

**Comment by sqrrm** [comment]
@ripcurlx The codacy settings for css indentation seems off as well, it's expecting 2 characters rather than 4.

**Comment by ripcurlx** [comment]
> @ripcurlx The codacy settings for css indentation seems off as well, it's expecting 2 characters rather than 4.

I already updated this some time ago. I tried to re-analyze, but if it doesn't work I'll ignore this pattern here for now as well.

**Comment by ripcurlx** [comment]
@sqrrm I removed the pattern for now. Could you please force push to this branch so it is getting rebuilt in Codacy? Thanks!

**Comment by sqrrm** [comment]
@ripcurlx thanks, at least codacy is not complaining. Let's re-enable stuff if we notice there is a need for it to keep the balance of helpfulness and annoyance.

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
