### PR TITLE
Update tor, netlayer, jtorctl

### PR DESCRIPTION
**Pull request by freimair**
As always, these three come in one commit
- tor has been updated to the recently released version [0.4.1.6](https://blog.torproject.org/new-release-tor-0416)
- jtorctl has been updated to [1.4](https://github.com/JesusMcCloud/jtorctl/releases). It now features a callback that tells us whether the tor control connection is still alive
- netlayer has been upgraded to [0.6.6](https://github.com/JesusMcCloud/netlayer/releases/tag/0.6.6). It just adapts the new jtorctl and uses the updated tor version

### CODE REVIEW

**Comment by ripcurlx** [comment]
@freimair Did you experience any issues, while testing it on production?

**Comment by freimair** [comment]
no, no issues.

is just a minor Tor update with some bug fixes. Should be good.

**Review by ripcurlx — APPROVED** [review]
ACK - Rebased locally to current master and started the app and it looks like everything is working as before

**Comment by ripcurlx** [comment]
@freimair I have to revert this PR as @devinbileck had issues using this Tor version on Windows.
```
Nov-05 15:28:59.456 [NetworkNode-9999] ERROR b.n.p2p.network.TorNetworkNode: Tor node creation failed: net.freehaven.tor.control.TorControlTimeoutError: We did not receive a response after one minute of waiting. 
Nov-05 15:28:59.459 [JavaFX Application Thread] ERROR bisq.core.app.P2PNetworkSetup: onSetupFailed
```
As it is too risky to have it for this release I'm reverting this PR until we know more details why this is happening on Windows.

**Pull request merged**
