### PR TITLE
Fix for issue 1896

### LINKED ISSUE #1896: Update legacy assets with proper AddressValidator
I have split this into a separate issue from https://github.com/bisq-network/bisq/issues/1815#issuecomment-433112999.

A lot of legacy assets are using the deprecated DefaultAddressValidator which provides very basic and insufficient validation (non-null and non-empty). Any new asset implementations are required to provide their own AddressValidator implementation. To bring these legacy assets up to date and in order provide proper validation, they should be updated with an appropriate AddressValidator.

However, as part of https://github.com/bisq-network/bisq/pull/1861, a majority of these legacy assets will be delisted. So will need to review this once all untraded assets have been delisted.

### PR DESCRIPTION
**Pull request by niyid**
Removing references to deprecated DefaultAddressValidator.

- 7 coins were affected: Counterparty, Decred, EtherClassic, Namecoin, Siafund, Unobtanium, Zcoin
- EtherAddressValidator was extended to allow passing of i18n resource key.
- Message resource entries for validation errors were added to displayStrings.properties.

fixes #1896

### CODE REVIEW

**Comment by niyid** [comment]
Hi @ripcurlx,

As can be seen, I have created a new PR separately for issue 1896 as recommended.

Apologies for any inconvenience.

**Comment by niyid** [comment]
I am just working on the build as project **`core`** which has the i18n resource class **`bisq.core.locale.Res`** is not set up as a dependency for project **`assets`**; rather **`core`** is a dependency for **`assets`**.

**Review by freimair — APPROVED** [review]
Ack. Although I have not tested any small detail...

**Comment by ManfredKarrer** [comment]
@freimair Please use utACK in case you have not fully tested the PR...

**Pull request merged**
