### PR TITLE
Added interface and corresponding implementation to handle display of exceptions on failed vote reveal transaction

### LINKED ISSUE #3408: Vote Reveal - Silent Fail
I got this:

```
Oct-15 06:43:21.835 [JavaFX Application Thread] INFO  org.bitcoinj.wallet.Wallet: Completing send tx with 1 outputs totalling 0.00000596 BTC and a fee of 0.00 BTC/kB 
Oct-15 06:43:21.837 [JavaFX Application Thread] WARN  org.bitcoinj.wallet.Wallet: Insufficient value in wallet for send: needed 0.00001606 BTC more 
Oct-15 06:43:21.845 [JavaFX Application Thread] ERROR b.c.d.g.v.VoteRevealService: VoteRevealException{
     voteRevealTx=null,
     blindVoteTxId='3cf435e275b8e1518ea969fe90e0504bbed1d68135310b3c24546244fca90b5d',
     myVote=null
} bisq.core.dao.governance.votereveal.VoteRevealException: Exception at calling revealVote. 
Oct-15 06:43:24.448 [JavaFX Application Thread] INFO  b.c.d.m.DaoStateMonitoringService: Passed checkpoint Checkpoint {
     height=586920,
     hash=523aaad4e760f6ac6196fec1b3ec9a2f42e5b272
} 
```

Of course my BTC balance was vertically challenged  (euphemism for "too low"). If I didn't catch the exception in the logs, I would never have known there was an issue. Once I topped up, and on application restart, vote was published and information pop-up displayed.

I expected the earlier issue to have been reported with a pop-up as well.

I will fix it.

### PR DESCRIPTION
**Pull request by niyid**
Fixes issue #3408

EDIT: fixes #3408

### CODE REVIEW

**Review by freimair — CHANGES_REQUESTED** [review]
please clean up your commit history. There are three commits that add a comment, change it and then change it back.

Furthermore, please rebase your actual changes onto master instead of merging master into your feature branch

**Comment by freimair** [comment]
please implement the requested changes. thanks!

**Comment by niyid** [comment]
> please implement the requested changes. thanks!

Done. Thanks for your patience. I somehow missed your previous requests.

Rebased and commits squashed.

Regards.

**Comment by ripcurlx** [comment]
@niyid Please sign all your commits.

**Comment by freimair** [comment]
> Rebased and commits squashed.

... and push your contributions. Seems like you only did your changes locally.

**Comment by ripcurlx** [comment]
Closing PR as it wasn't tested once.
Testing it on Regtest it ~crashes~ it is only displaying the missing resource key when a failed vote reveal transaction occurs. Please fix and re-open it again if you've tested it. Also add how you tested it in the PR description. Thanks!

**Comment by niyid** [comment]
> Closing PR as it wasn't tested once.
> Testing it on Regtest it ~crashes~ it is only displaying the missing resource key when a failed vote reveal transaction occurs. Please fix and re-open it again if you've tested it. Also add how you tested it in the PR description. Thanks!

Great! Thanks for the feedback. THe resource key must have gotten missing during a merge.

**Pull request closed without merging**
