### PR TITLE
List Nano (NANO)

### PR DESCRIPTION
**Pull request by wendersonferreira**
- Official project URL: https://nano.org/
- Official block explorer URL: https://nanocrawler.cc/

### CODE REVIEW

**Comment by wendersonferreira** [comment]
Sorry to be inconvenient, is there any more steps that need to be taken?

**Comment by huey735** [comment]
Asset listing was put on hold - https://github.com/bisq-network/proposals/issues/166

**Comment by FernandoBatalha** [comment]
I await the release or new orders.

**Comment by FernandoBatalha** [comment]
@huey735 any news?

**Comment by FernandoBatalha** [comment]
@huey735 any news?

**Pull request closed without merging**
