### PR TITLE
List Horizen (ZEN)

### PR DESCRIPTION
**Pull request by tarrenj**
- Official project URL: https://horizen.global/

- Official block explorer URL: https://explorer.horizen.global/

Continuation of https://github.com/bisq-network/bisq/pull/1784

Resubmitting bisq-network/bisq-assets#114 from the old bisq-assets` repo, which had positive comments from @cbeams and @ManfredKarrer, but did not have a comment containing "ACK".

Tested with ./gradlew :assets:build

### CODE REVIEW

**Comment by tarrenj** [comment]
Rebased from master again, and used `--amend` to sign previous commit.

**Comment by tarrenj** [comment]
Rebased from master again

**Comment by tarrenj** [comment]
Rebased from master again

**Comment by blabno** [comment]
```
git fetch tarrenj
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

**Review by blabno — APPROVED** [review]
ACK

**Pull request merged**
