### PR TITLE
Fix darkmode color of warning-box

### PR DESCRIPTION
**Pull request by ghost**
Fixies: #3957

image
image

### CODE REVIEW

**Review by sqrrm — APPROVED** [review]
utACK

**Comment by sqrrm** [comment]
@ripcurlx Travis seems to not finish but how can I make it complete?

**Comment by ripcurlx** [comment]
@petrhejna Something weird is going on with your PR and Travis. Unfortunately re-run it on Travis and re-opening it didn't solve the problem. Could you please re-create your PR on current master? Thanks!

**Comment by sqrrm** [comment]
I could merge it now, @ripcurlx whatever you did it must've done something

**Pull request merged**
