### PR TITLE
Update 'reason for payment' warning instructions

### LINKED ISSUE #6711: Bad SEPA instructions - payment reason field cannot be empty in my bank
Bisq instructions clearly state that the payment reason field MUST be empty when sending a SEPA transfer.
However, my bank does not allow the payment reason field to be blank. It requires at least a single character, but I wouldn't be surprised if other banks required more. 
According to the [Table of Penalties](https://bisq.wiki/Table_of_penalties), not leaving the field empty would most likely constitute "Using unagreed payment reference" and result in a 10% penalty for the buyer.

Please reevaluate and clarify the instructions, perhaps add a statement that when the field can't be empty it should be a dash ("-") character or just the name of the account owner.

### PR DESCRIPTION
**Pull request by kiocos**
Fixes #6711 

Improves the warning message by providing additional instructions on how buyers should fill the payment reason in case they're required to do so.

### CODE REVIEW

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Comment by alejandrogarcia83** [comment]
@kiocosta Thank you for opening this PR. I can't merge your PR before your commits are signed. For more information see: https://github.com/bisq-network/bisq/blob/master/CONTRIBUTING.md#sign-your-commits-with-gpg

**Comment by kiocos** [comment]
hey @alejandrogarcia83 , thank you for your reply. I have signed the commit.

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Comment by alejandrogarcia83** [comment]
Congrats to your first merged PR in Bisq!

**Pull request merged**
