### PR TITLE
Permutation fix

### PR DESCRIPTION
**Pull request by sqrrm**
Change the permutation algo to check each permutation as it's created and minimize memory usage. Start with longer lists and remove one item per level. Avoid duplicates by not removing the same item twice.

### CODE REVIEW

**Review by wiz — APPROVED** [review]
Tested OK on jhgc seednode, however feedback is the same as testing chimp's PR where the proposal is rejected and then somehow approved 2 seconds later - is that expected?
```
Apr-29 09:04:04.178 [SeedNodeMain] WARN  b.c.d.g.v.VoteResultService: We have a proposal which was not part of our blind vote and reject it. Proposal ={}CompensationProposal{
     requestedBsq=455300,
     bsqAddress='B1F1qJTNUhVPukeqgee9WmLNBkMjm6DTFEY'
} Proposal{
     txId='8e24ad18fc892451e01e8032aa5725a750a6a3b2df152da74264160f3f8784cd',
     name='wiz',
dao-compensation/547',
     txId='8e24ad18fc892451e01e8032aa5725a750a6a3b2df152da74264160f3f8784cd',
     version=1,
     creationDate=Mon Apr 20 06:49:21 UTC 2020
}
```

```
Apr-29 09:04:06.408 [SeedNodeMain] INFO  b.c.d.g.v.i.IssuanceService:
################################################################################
We issued new BSQ to tx with ID 8e24ad18fc892451e01e8032aa5725a750a6a3b2df152da74264160f3f8784cd
Issued BSQ: 455300
Issuance type: COMPENSATION
################################################################################
```

**Review by wiz — APPROVED** [review]
ACK
Tested OK on a Bisq SPV node configured to use the above seednode running this PR. Pressing the "re-sync DAO from resources" button resulted in the cycle 12 vote results appearing with 23 blind votes as expected. Final state hashes match my other nodes:

DAO state @ `628132` = `7b61e887`
proposals @ `626977` = `24fa24222`
blind votes @ `627437` = `01d8e01b`

Screen Shot 2020-04-29 at 19 32 12

**Comment by chimp1984** [comment]
> DAO state @ `628132` = `7b61e887`
> proposals @ `626977` = `24fa24222`
> blind votes @ `627437` = `01d8e01b`

Can confirm those hashes with one full node and one lite node resynced from latest resources and using the new permutation algo.

**Comment by Emzy** [comment]
ACK
updated my bsq.emzy.de explorer.
https://bsq.emzy.de/tx.html?tx=43aceb251b56f1ecb42a6fa1532f3f14c4bf005344b543a126ff75b576ac8862
looks right.

**Review by ripcurlx — APPROVED** [review]
ACK

Also from my side

```
DAO state @ 628155 = 3b9fd182
proposal state @ 626977 = 24fa24222
blind votes @ 627437 = 01d8e01b
```

**Pull request merged**
