### PR TITLE
fix the wrong ticker name from SPACE to XSC in Coin second param

### PR DESCRIPTION
**Pull request by tlightsky**
we use a wrong param in the pr before, fix that in this pr

the pr before:
https://github.com/bisq-network/bisq/pull/1970

### CODE REVIEW

**Comment by ripcurlx** [comment]
@ManfredKarrer This change would cause issues if we have open offers/trades already, wouldn't it?

**Comment by ManfredKarrer** [comment]
Ticker symbol is used as ID and should not be changed. Requires extra testing. Don't want to invest that effort before we know that it is traded. >90% of added assets never are traded anyway. So I will not do the testing for that and others likely don't have enough context to test it correctly.

**Comment by tlightsky** [comment]
@ripcurlx @ManfredKarrer 
https://bisq.network/markets/?currency=space_btc
this is the trade page, seems no history till now, 
hope we can fix it before too late

**Comment by tlightsky** [comment]
@ManfredKarrer ok, so we should do it maybe after some trade happen?

**Comment by tlightsky** [comment]
@blabno hi, our ticker name need a small fix, 
can we merge this fix to prevent someone can't find our coin to trade

**Pull request closed without merging**
