### PR TITLE
(13/13) [BUGFIX] Validate Entry.receiversPubKey when adding a MailboxPayload

### PR DESCRIPTION
**Pull request by julianknutsen**
New commit is bdfe32b

The remove code checks to ensure these fields match, but the add code
never did. This could lead to a situation where a MailboxStoragePayload
could be added, but never removed.

### CODE REVIEW

**Review by chimp1984 — APPROVED** [review]
utACK

**Review by freimair — APPROVED** [review]
Ack

**Review by ripcurlx — APPROVED** [review]
utACK - Great set of changes @julianknutsen 👍

**Comment by ripcurlx** [comment]
Automatically closes https://github.com/bisq-network/bisq/pull/3608, https://github.com/bisq-network/bisq/pull/3607 and https://github.com/bisq-network/bisq/pull/3587

**Pull request merged**
