### PR TITLE
List Ittrium (XIT)

### PR DESCRIPTION
**Pull request by IttriumCore**
- Official project URL: https://ittrium.io/
- Official block explorer URL: https://explorer.ittrium.io/

### CODE REVIEW

**Comment by blabno** [comment]
Pre-sale https://ittrium.io/blog/2018/09/16/xit-pre-sale/

**Comment by FlexNote** [comment]
Is there any issue with Ittrium's masternode pre-sale?

**Comment by IttriumCore** [comment]
Just to be clear, the pre-sale is a pre-exchange-sale and not an ICO.

**Comment by blabno** [comment]
@ManfredKarrer what's your take?

**Comment by ManfredKarrer** [comment]
If tokens are sold its an ICO.

**Comment by IttriumCore** [comment]
Hi @ManfredKarrer, and @blabno

We have never sold tokens period, nor will we ever sell tokens.  The pre-exhange-sale only sold Ittrium (XIT) coins.

**Comment by ManfredKarrer** [comment]
So who sold at the pre-exhange-sale?

**Comment by tybiboune** [comment]
Hi! @ManfredKarrer @blabno , thanks for reconsidering, an ICO is a tokens sale... XIT is not a token, it's an actual coin, so this coins pre-sale is technically an OTC sale. The only difference being that it was OTC from the core Team of some pre-mined coins (again...not tokens)
If the blocking matter is "ICO", then it's definitely not the case.

**Comment by ManfredKarrer** [comment]
Naming is irrelevant. The SEC will apply the Howie test and ignore if you call your coin a token or a coin. We are not legal experts and don't ahve time and resources to evaluate each possible ICO coin. And we don't want to take legal risk by adding one which potentially will be interpreted as ICO. Hope you understand that.

**Comment by tybiboune** [comment]
I understand, but... The SEC could as well consider otc trades before listing on any exchange as 'ICO-like', how can you we know how they're gonna consider things exactly? When is a project funding gonna be considered prefunding or regular? And does an exchange price define the fact that a team is getting funds for development or not? Are there gonna be some 'to be considered as ICO' exchanges, in that case? they're gonna have fun seeking into exchanges history trades, with all those teams selling their own (including premined) coins... Tokens and coins aren't named the same for legal reasons, indeed, and ICOs are named as such for the same reasons. Moreover if the SEC is putting their nose here, it'd be better to have some legal experts on-board, and I'm saying this very sincerely...

**Comment by aburanne** [comment]
Hi! @ManfredKarrer @blabno  I'm XIT coin community member. We have been waiting for bisq for months and Devs were  working so hard for this way. I know because they were talking with us regularly about this subject. This is not first. 2nd time to reject. At the first somethings was wrong about coding and after they did everything right and request listing on bisq again we had very big hope. I sincerely telling you, our coin was not a token for ICO pre-sale.  XIT is a coin. If you accept this coin to your awesome app bisq, believe me it will be 100% right decision. Please accept our coin for the sake of XIT community. Thanks for reading this long words even you guys so busy, i know i am sure. Thanks.

**Pull request closed without merging**
