### PR TITLE
Update gradle-witness.jar

### LINKED ISSUE #1897: Resolve deprecated method in gradle-witness prior to moving to Gradle 5
Before moving to Gradle 5, we will need to resolve the following deprecated method in gradle-witness:
```
> Configure project :desktop
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_50pvy62xio1vz17f8pklhdf32.run(C:\Users\Devin\Documents\GitHub\devinbileck\bisq\desktop\build.gradle:18)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

It is a [known issue](https://github.com/signalapp/gradle-witness/issues/22) that is still outstanding.

We may want to consider alternatives to gradle-witness since its last activity was Nov 2014. I found https://github.com/matthewtamlin/retrial as a potential candidate, which states:

> Retrial was created to address the unresolved issues in Open Whisper Systems' gradle-witness plugin, and to provide a more convenient means of storing dependency checksums.

However, @cbeams mentioned the following in https://github.com/bisq-network/bisq/issues/1815#issuecomment-435598615:

> This is a really easy problem to solve, and we're already working from my fork of gradle-witness, so we might want to just patch this one as well instead of moving to something entirely different.
> 
> Per the commit comment at 27cc933, the gradle-witness.jar we're using today is built from the PR at signalapp/gradle-witness#26 (which comes from my fork). So we can just further patch the code there, issue another pull request to the canonical repository (to be good citizens), and rebuild and check in the new jar.

### PR DESCRIPTION
**Pull request by devinbileck**
I have built a new gradle-witness.jar from our new official bisq fork at https://github.com/bisq-network/gradle-witness which includes fixes for the following:
- Prevent printing "Verifying ..." messages to the console.
- Replace deprecated Task.leftShift(Closure) method with Task.doLast(Action).

Resolves: https://github.com/bisq-network/bisq/issues/1897

### CODE REVIEW

**Comment by ripcurlx** [comment]
ACK - works for me locally. But I leave it for @cbeams to merge as he knows more about possible additional implications.

**Comment by ManfredKarrer** [comment]
I leave it to @cbeams as well.... not my expertise...

**Comment by cbeams** [comment]
Thanks, @devinbileck. To be cautious, we should think about how we know that updates to this jar are legit. For example, I just built the jar against the same commit using Gradle 4.10.2 / OpenJDK 10.0.2 and got the following result:

```
$ sum build/libs/gradle-witness.jar
54082 18 build/libs/gradle-witness.jar
```

Whereas when I sync up to your PR branch and run the same checksum, I get a different value:

```
$ sum gradle/witness/gradle-witness.jar
57838 18 gradle/witness/gradle-witness.jar
```

So, while I trust you simply built the jar as you claim, there's no way of knowing right now that it's actually a representation of the sources at that commit. i.e. it could contain a trojan horse.

Ideally, we should set up Travis CI in our new gradle-witness fork and print out a checksum at the end of the build, so that we have something objective to check against when the jar it produces is checked in here. That assumes that building this jar is deterministic under the same Gradle / JDK, and I think it should be. I unzipped the jar and checked for properties files with dates in them, etc, and I didn't see anything. So it should be possible to get the exact same checksum on different machines and operating systems.

In the meantime, let's just see if we can align on the same checksum between our two versions of the jar. Did you build with Gradle 4.10.2 / OpenJDK 10.0.2 as well? I'm committing a Gradle wrapper pinned to 4.10.2 to make it a little easier.

**Comment by devinbileck** [comment]
Excellent points. I thought I had used Gradle 4.10.2 / OpenJDK 10.0.2, but now am second guessing. I will verify.

**Comment by devinbileck** [comment]
I confirmed I am using Gradle 4.10.2 / OpenJDK 10.0.2. I pulled from master with your latest commit and ran through the process again and got the same checksum that I got before.
```
Devin@Devin-Laptop MINGW64 ~/Documents/GitHub/bisq-network/gradle-witness (master)
$ git log -1
commit ecf0ffe77c270dc192a137ad373d2cfa8c7c5c38 (HEAD -> master, origin/master, origin/HEAD)
Author: Chris Beams <chris@beams.io>
Date:   Fri Nov 9 21:59:41 2018 +0100

    Add Gradle wrapper at v4.10.2

    See https://github.com/bisq-network/bisq/pull/1901#issuecomment-437493277

Devin@Devin-Laptop MINGW64 ~/Documents/GitHub/bisq-network/gradle-witness (master)
$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment 18.3 (build 10.0.2+13)
OpenJDK 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

Devin@Devin-Laptop MINGW64 ~/Documents/GitHub/bisq-network/gradle-witness (master)
$ ./gradlew build
> Task :compileJava NO-SOURCE
> Task :compileGroovy UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :assemble UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :compileTestGroovy NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build UP-TO-DATE

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 up-to-date

Devin@Devin-Laptop MINGW64 ~/Documents/GitHub/bisq-network/gradle-witness (master)
$ sum build/libs/gradle-witness.jar
57838    18
```

However, I then did a clean build and got a completely different checksum:
```
Devin@Devin-Laptop MINGW64 ~/Documents/GitHub/bisq-network/gradle-witness (master)
$ ./gradlew clean build
> Task :clean
> Task :compileJava NO-SOURCE

> Task :compileGroovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/Devin/.gradle/wrapper/dists/gradle-4.10.2-bin/cghg6c4gf4vkiutgsab8yrnwv/gradle-4.10.2/lib/groovy-all-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :processResources
> Task :classes
> Task :jar
> Task :assemble
> Task :compileTestJava NO-SOURCE
> Task :compileTestGroovy NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build

BUILD SUCCESSFUL in 5s
4 actionable tasks: 4 executed

Devin@Devin-Laptop MINGW64 ~/Documents/GitHub/bisq-network/gradle-witness (master)
$ sum build/libs/gradle-witness.jar
27807    18
```

Another clean build and yet another checksum:
```
Devin@Devin-Laptop MINGW64 ~/Documents/GitHub/bisq-network/gradle-witness (master)
$ ./gradlew clean build
> Task :clean
> Task :compileJava NO-SOURCE

> Task :compileGroovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/Devin/.gradle/wrapper/dists/gradle-4.10.2-bin/cghg6c4gf4vkiutgsab8yrnwv/gradle-4.10.2/lib/groovy-all-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :processResources
> Task :classes
> Task :jar
> Task :assemble
> Task :compileTestJava NO-SOURCE
> Task :compileTestGroovy NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build

BUILD SUCCESSFUL in 4s
4 actionable tasks: 4 executed

Devin@Devin-Laptop MINGW64 ~/Documents/GitHub/bisq-network/gradle-witness (master)
$ sum build/libs/gradle-witness.jar
21198    18
```

So perhaps a checksum is not reliable <s>and perhaps an md5sum would be better</s>?
**Edit:** Just realized md5sum encounters the same behaviour.
<s>
```
Devin@Devin-Laptop MINGW64 ~/Documents/GitHub/bisq-network/gradle-witness (master)
$ md5sum.exe build/libs/gradle-witness.jar
b1c06f0c1b74f9955a1cd2ed623c617e *build/libs/gradle-witness.jar
```
</s>

**Comment by devinbileck** [comment]
Aha! [This article](https://purpledevcat.com/2018/02/14/reproducible-builds-in-java.html) describes the issue and provides a simple solution and I verified it works.

**Comment by cbeams** [comment]
Right. We actually have this same configuration in Bisq's own build.gradle: https://github.com/bisq-network/bisq/blob/master/build.gradle#L206-L209.

Are you putting together a PR for that in the gradle-witness repo, then?

**Comment by devinbileck** [comment]
Yes, i will put together a PR.

**Comment by ghost** [comment]
from my side
<pre>
$ git log -1
commit ecf0ffe77c270dc192a137ad373d2cfa8c7c5c38
Author: Chris Beams <chris@beams.io>
Date:   Fri Nov 9 21:59:41 2018 +0100

    Add Gradle wrapper at v4.10.2
    
    See https://github.com/bisq-network/bisq/pull/1901#issuecomment-437493277
userz@DO790C:~/github/gradle-witness$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment 18.3 (build 10.0.2+13)
OpenJDK 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
userz@DO790C:~/github/gradle-witness$ ./gradlew build

BUILD SUCCESSFUL in 0s
3 actionable tasks: 3 up-to-date
userz@DO790C:~/github/gradle-witness$ sum build/libs/gradle-witness.jar 
56120    18
</pre>

**Review by cbeams — CHANGES_REQUESTED** [review]
NACK, per comments at https://github.com/bisq-network/gradle-witness/pull/1#pullrequestreview-173768999

**Review by cbeams — APPROVED** [review]
ACK

**Comment by cbeams** [comment]
Note that I squashed and force-pushed out the earlier commits updating gradle-witness.jar. All that remains is the one correct commit now.

**Pull request merged**
