### PR TITLE
Bump netlayer and tor-binary versions

### PR DESCRIPTION
**Pull request by cd2357**
Update dependencies to use tor v0.4.5.6

### CODE REVIEW

**Comment by ripcurlx** [comment]
@BtcContributor Could you please run it on Windows against Mainnet to see if it is connecting just fine?  Thanks!

**Comment by ripcurlx** [comment]
@wiz Could you give it a spin as well? Thanks!

**Review by ripcurlx — APPROVED** [review]
ACK - tested it on Mainnet (macOS 11.2.1)

**Comment by ripcurlx** [comment]
I did verify the tor binaries already in this PR https://github.com/bisq-network/tor-binary/pull/1

**Comment by BtcContributor** [comment]
ACK - tested it on Mainnet (Windows 10, latest updates)

**Comment by ripcurlx** [comment]
I'll merge it and test it when creating the binaries on Linux (Ubuntu), Windows 10 and macOS Big Sur once again.

**Pull request merged**
