### PR TITLE
Attempt to fix guava dependency issue

### PR DESCRIPTION
**Pull request by cbeams**
This is a quick attempt to fix the issue described by @jmacxx in Keybase
similar to what's described at
https://github.com/jeremylong/DependencyCheck/issues/3221.

It needs to be tested in the environment where the issue was observed
(Windows).

Fixes #replaceWithIssueNr, fixes #replaceWithIssueNr

Your PR description here.

### CODE REVIEW

**Comment by cbeams** [comment]
@BtcContributor, @jmacxx, please see if you're still able to repro the issue described at keybase://chat/bisq#testing/2466 with this fix in place, thanks!

**Review by ghost — APPROVED** [review]
ACK, tested on Windows and Ubuntu Linux.

**Comment by ghubstan** [comment]
I get the `NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableMultiset.toImmutableMultiset()'` on my ubuntu machine, and this PR resolves it.   

Branch master: my bisq runtime lib contains three guava jars.

master
My JVM loads two of them at startup;  this is the source of my runtime version conflict.

```
$ lsof -Pan -p <bisq-pid>
COMMAND   PID   USER   FD      TYPE             DEVICE  SIZE/OFF     NODE NAME
java    32694 hhhhhh   14r      REG              253,1   2703269 25298587 master/lib/guava-30.1-android.jar
java    32694 hhhhhh   26r      REG              253,1   2788302 25298447 master/lib/guava-28.2-jre.jar

```
`WalletService` calls guava's `ImmutableMultiset.toImmutableMultiset()` at line 586.  We want it to use `guava-28.2-jre.jar`'s ImmutableMultiset class, but when this method not found error occurs, the jvm is looking for this static method on `guava-30.1-android.jar`'s ImmutableMultiset class, and it is not there.


Branch fix-guava: my bisq runtime lib contains two guava jars. 

fix-guava
My JVM loads only one of them at startup (no runtime version conflict).

```
$ lsof -Pan -p <bisq-pid>
COMMAND   PID   USER   FD      TYPE             DEVICE  SIZE/OFF     NODE NAME
java    35660 hhhhhh   24r      REG              253,1   2874025 50594408 fix-guava/lib/guava-30.1.1-jre.jar
```

I did not go as far as find out what is pulling in the transitive `guava-30.1-android.jar` dependency in the master branch, but if it were found, it might have been excluded instead of requiring a guava upgrade.  

Tested ACK

**Comment by cbeams** [comment]
Closing as incorrectly submitted. I accidentally created the PR branch against the main repo, instead of my own. Consequently, I couldn't update the WIP commit due to force push restrictions on the main repo. I've resubmitted this as #5851.

@jmacxx, @ghubstan, thanks for your reviews and ACKs. Could you please re-ACK the new PR?

**Pull request closed without merging**
