### PR TITLE
Create mono repository

### PR DESCRIPTION
**Pull request by ripcurlx**
Based on the [RECONSOLIDATION-LOG](https://github.com/cbeams/bisq/blob/reconsolidation-dryrun/RECONSOLIDATION-LOG) by @cbeams and the [mono](https://github.com/chirhonul/bisq-desktop/tree/mono) branch by @chirhonul.

### CODE REVIEW

**Comment by ripcurlx** [comment]
Please @cbeams and @ManfredKarrer have a look at all the changes. It works for me so far. The only thing that is still open is that `gradle install` fails with `A POM cannot have multiple artifacts with the same type and classifier. Already have MavenArtifact bisq:zip:zip:null, trying to add MavenArtifact bisq:zip:zip:null.`

**Review by cbeams — APPROVED** [review]
ACK. Thanks so much for putting this together, @chirhonul and @ripcurlx.

There are a few changes I'd like to make to the readme regarding instructions for building and importing into IDEA, but don't have the time just now. @ManfredKarrer is traveling, so I'm not sure if he'll have time to review. I'll leave it to you when to merge. I can get my changes in by tomorrow for sure, but they can also be done as a separate PR.

I'll also rearrange the names of the repositories once this is merged, renaming the current `bisq-network/bisq` to something that gets it out of the way and renaming `bisq-network/bisq-desktop` to `bisq-network/bisq`. Sound good?

As I've said before, there are various improvements to the build that we can do to make it a more idiomatic multi-project build, but they can all come afterward. As it is, everything builds and imports cleanly for me (with the right instructions that I'll add to the readme), so thumbs up from my side.

**Comment by ripcurlx** [comment]
I think @ManfredKarrer would be fine with the PR if it works at least already for the two of us. He also knew what @chirhonul came up with in his mono branch. I'll merge it now, as I also want to start merging locally my other two branches I'm working on (redesign, java9/10) with the new structure.

**Comment by ripcurlx** [comment]
@cbeams The changes you mentioned sound fine with me! Thanks!

**Pull request merged**
