### PR TITLE
KingCoin

### PR DESCRIPTION
**Pull request by minerlab**
hi bisq team, please add KingCoin in your platform
Name: KingCoin
Ticker: KING
Algorithm: X11
bitcointalk: https://bitcointalk.org/index.php?topic=2273043.0
explorer1: http://lpool.name/explorer/KING
explorer2: https://thecryptopool.com/explorer/KING
explorer3: https://cryptohub.online/blocks_hist/KING/
example address: LQuwqu9VyiHvbskFvXExeykhgo3NpUWZm2
site: http://www.kingcoin.eu
telegram: https://t.me/joinchat/CyIjuQ4v1-o9LxDa9Bi2SQ
twitter: https://twitter.com/_King_Coin
reddit: r/Kingcoindev
If your answer is positive I will add bisq to the site as an official exchange.
thanks.

### CODE REVIEW

**Comment by xlp0rk0lx** [comment]
Of course. KingCoin team is very clear with user. Community start growning fast

**Comment by ManfredKarrer** [comment]
You did not run the test!

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.bisq.gui.util.validation.AltCoinAddressValidatorTest.testKING(AltCoinAddressValidatorTest.java:209)

**Comment by minerlab** [comment]
which test does not understand

**Comment by ManfredKarrer** [comment]
AltCoinAddressValidatorTest. Just run it. It fails

**Pull request closed without merging**
