### PR TITLE
List DeepOnion (ONION)

### PR DESCRIPTION
**Pull request by nezero**
List DeepOnion (ONION)

Official project URL: https://deeponion.org/
Official block explorer URL: https://explorer.deeponion.org/

### CODE REVIEW

**Review by blabno — APPROVED** [review]
ACK

**Comment by blabno** [comment]
Please squash into single commit

**Comment by nezero** [comment]
> Please squash into single commit

Squashed

**Comment by ripcurlx** [comment]
I overlooked that the travis build wasn't finished already. @nezero You need to put it into the correct alphabetical oder. 🤦‍♂️  Fixed it for you already.

**Comment by nezero** [comment]
> I overlooked that the travis build wasn't finished already. @nezero You need to put it into the correct alphabetical oder. 🤦‍♂️ Fixed it for you already.

Doh! Thanks for fixing.

**Pull request merged**
