### PR TITLE
[WIP] Dispute agents sign summary

### PR DESCRIPTION
**Pull request by chimp1984**
Depends on #4518

Adds signature and node address of dispute agent to summary message. With the node address we can look up the pubKey. The summary msg can be pasted into a tool to check if the signature is valid. 

This will help once refund agent revokes and reimbursement request need to be done. To make the statement of the requester verifiable they need to paste the summary message of the mediation and arbitration into the Github request. With that anyone can verify in the app if it is valid. 

Screen Shot 2020-09-11 at 23 55 42

Screen Shot 2020-09-12 at 00 16 44

### CODE REVIEW

**Comment by wiz** [comment]
Don't you need to add the full Trade ID into the message?

**Comment by wiz** [comment]
Don't you need to add the full Trade ID into the message? What about the payout addresses and other important info? Just signing "payout is X" is not very useful by itself.

**Comment by chimp1984** [comment]
@wiz Agree. Will add more details to summary text. For traders and dispute agents it is a but redundant as they have the dispute details available, but now its for sharing with otheres. Maybe I use the report instead of the summary text.

**Comment by chimp1984** [comment]
Screen Shot 2020-09-12 at 20 09 45

**Comment by chimp1984** [comment]
I will make a new PR with the 3 related PRs in the dispute domain combined

**Pull request closed without merging**
