### PR TITLE
AXE support + macOS icons prop

### PR DESCRIPTION
**Pull request by charlesrocket**
Ticker symbol: AXE
Official token name: Axe
Official block explorer URL: http://207.246.65.114:3001
Is it an Altcoin or a token: Altcoin
Official project URL: https://github.com/AXErunners/axe/wiki

PR was filed according https://github.com/bisq-network/docs/blob/master/exchange/howto/list-token.adoc

---

tray icon set suggestion:

bisq1
bisq2

Please review suggested icons for osx dark menu bar fix. I tried to outline the cat to preserve original mood, but couldn't archive desired quality on non-retina displays due the image size. IMO provided versions are acceptable for further deployment

---

feel free to use provided images for your PR in case of override

### CODE REVIEW

**Comment by charlesrocket** [comment]
please give some time to resolve conflicts before closing PR, humans from time to time facing problems working over 22 hours/day((

**Comment by cbeams** [comment]
Hey @charlesrocket, thanks for the PR. A couple things here:

1. Please separate this into two pull requests; one for adding AXE and the other for fixing the menu icon in dark mode (i.e. the fix for #1248).

2. Please submit both against this repository's `master` branch, vs the `Development` branch. I know you did this because you were following the instructions we put out there—I'm changing those instructions now, as we're doing away with the `Development` branch going forward. The best thing is to issue each pull request from a dedicated topic branch in your fork, i.e. `charlesrocket:list-axe-token` and `charlesrocket:fix-dark-menu-icon`, each having been branched directly from the latest HEAD of `bisq-network:master`.

3. Please follow the guidelines for Git commit messages at https://chris.beams.io/posts/git-commit#seven-rules, as requested in our [contributor guidelines](https://github.com/bisq-network/exchange/blob/master/CONTRIBUTING.md).

Thanks!

**Comment by charlesrocket** [comment]
@cbeams got it! everything will be submitted asap

**Comment by charlesrocket** [comment]
moved to https://github.com/bisq-network/exchange/pull/1257 and https://github.com/bisq-network/exchange/pull/1258

**Pull request closed without merging**
