### PR TITLE
Update Java options as described in #5609 and #5550

### PR DESCRIPTION
**Pull request by ripcurlx**
See https://github.com/bisq-network/bisq/issues/5550 and https://github.com/bisq-network/bisq/pull/5609.

### CODE REVIEW

**Comment by ripcurlx** [comment]
@chimp1984 @sqrrm @jmacxx Do we want to go higher on the max ram setting than 6G? @pazza83 had to add 32G to make it work for him.

**Comment by chimp1984** [comment]
Maybe 8G? @ghubstan What do you think?

**Comment by ghubstan** [comment]
> Maybe 8G? @ghubstan What do you think?

People using computers w/ just 4g RAM are SOL.  That said, 8g is OK.   Much better than 6g.

I'm using a 10g setting, and total native memory (on-heap + off-heap) use does not go over ~ 3.7g (so far).

**Review by sqrrm — APPROVED** [review]
utACK

**Pull request merged**
