### PR TITLE
Release/v1.2.5

### PR DESCRIPTION
**Pull request by ripcurlx**

### CODE REVIEW

**Review by sqrrm — APPROVED** [review]
utACK

**Review by sqrrm — CHANGES_REQUESTED** [review]
Didn't see conflict

**Review by sqrrm — APPROVED** [review]
utACK

**Comment by ripcurlx** [comment]
Because of this unsigned commit (https://github.com/bisq-network/bisq/pull/3881/commits/7b5128652a12d561b841ba8907f89499f8a32671) this branch can't be merged (we haven't activated the signed commit requirement on all branches yes - will do it right after this). So we temporarily deactivated the requirement for this branch and will activate it right after it again.

**Pull request merged**
