### PR TITLE
Add new api method 'editoffer'

### PR DESCRIPTION
**Pull request by ghubstan**
To help review from bottom to top, commits are listed here in bottom to top order.

- 1daf4715f843acdd816c90ee9ae0bf5aaf630a93 Add `OfferInfo` field `isActivated`, rpc `EditOffer` to `grpc.proto`

- 2b8b53bba86579d71e184aac38531e15f462084b Add server/core `editOffer`, adjust` getMyOffer(s)` impls
  Add `editOffer` to `GrpcOffersService`, `CoreApi`, `CoreOffersService`.
  Set `editOffer` call rate meter to 1 / minute.
  Use new `EditOfferValidator` to verify `editOffer` params OK.
  Adust `getMyOffer(s)` rpc impl and `OfferInfo` model to use `OpenOffer` for accessing activation state and trigger price.

- 9231e48c439debc44213132e4b3a7f540503cad0 Refactor GrpcClient: request building code moved into `bisq.cli.request` pkg
  Reduces size of `GrpcClient` while allowing for new, bot-friendly variations of the new grpc.editOffer method.  (Various combinations of `editoffer` parameters are allowed and disallowed; the bot-friendly grpc.editOffer variations help disambiguate those parameter combinations.)

- d2939cc5676ce840d6af771d0321b0ffe2579b7c Add new `EditOfferOptionParser` & test

- 2344285ed3d7afd098a2bcc5920d8e5083720d88 Add `editoffer` method help

- be249c5e795065c627afe320cd9aa01ab2121894 Add `editoffer` to CLI

- 929b28cb8cb1667f0d64d3eb1bd017e56ee2d37a Add `editoffer` api tests & minor apitest refactoring

This is the 3rd in a series of PRs, starting at https://github.com/bisq-network/bisq/pull/5570
https://github.com/bisq-network/bisq/pull/5571 Should be reviewed/merged before this one. 

The new `editoffer` method works, and is documented in `editoffer-help.txt`,  but some follow up work is needed.  
Next PR(s) will be:
- Adjust `getmyoffer(s)` CLI output for new '`enabled`' and '`trigger-price`' columns.
- Adjust apitest trading scripts to new `getmyoffer(s) `CLI output.
- Adjust apitest user guide for new `editoffer`, and to new `getmyoffer(s)` CLI output.

### CODE REVIEW

**Comment by ghubstan** [comment]
TODO in next PR:  Update api beta test guide and trading simulation script.

**Comment by ghubstan** [comment]
This codacy issue should be ignored because an apparent IDE bug will not allow me to use only `AVAILABLE`. 
```
core/src/main/java/bisq/core/api/CoreOffersService.java
Unnecessary use of fully qualified name 'State.AVAILABLE' due to existing static import 'bisq.core.offer.OpenOffer.State.AVAILABLE'
editedOffer.setState(State.AVAILABLE);

```

**Comment by ripcurlx** [comment]
> This codacy issue should be ignored because an apparent IDE bug will not allow me to use only `AVAILABLE`.
> 
> ```
> core/src/main/java/bisq/core/api/CoreOffersService.java
> Unnecessary use of fully qualified name 'State.AVAILABLE' due to existing static import 'bisq.core.offer.OpenOffer.State.AVAILABLE'
> editedOffer.setState(State.AVAILABLE);
> ```

I ignored the issue. Could you please try to force push again to re-trigger codacy? Thanks!

**Comment by ghubstan** [comment]
> TODO in next PR: Update api beta test guide and trading simulation script.

This TODO was to tell me what goes in the next PR.

**Comment by ghubstan** [comment]
File conflicts resolved in child PR https://github.com/bisq-network/bisq/pull/5666

**Pull request merged**
