### PR TITLE
Add Nequi payment method

### LINKED ISSUE #193: Add Nequi as a payment method (Colombia users)
Name: Nequi. https://www.nequi.com.co/

Description: Nequi is a fintech neobank that allows people to send money to anyone in any part of Colombia, and its very popular in here.

Type: Mobile.

Chargeback risk: None, once the money is send, its gone. Their support even states that if you have been scamed using Nequi, your only option is to inform the local authorities. https://comunidad.nequi.co/discussion/647/estafa

Privacy protection: High, to send money to someone else, you just need his phone number.

Duration: Instant from Nequi to Nequi, from payment processor (corresponsales bancolombia) to Nequi and instant from Bancolombia bank account to Nequi. About 1 to 2 working days from another bank to Nequi.

Region: Colombia only. The only currency supported is the Colombian peso.

Trading limits: For average joe user, Nequi will only allow you to trasact 7'000.000 COP, about 1800 USD, per month. I.e, if i´ve used Nequi for anything else, the maximun amount will decreaste. This will clear again back up to 7millon COP the next month. https://ayuda.nequi.com.co/hc/es/articles/115001872811-Quiero-saber-los-topes-de-mi-cuenta-Nequi

Fees: NONE. From another bank different from Bancolombia to Nequi, the initial bank migth charge something, but it varies from bank to bank. At least from Banco de Bogota to Nequi is less than 1$ in colombian pesos.

Fraud risk: Low. a Nequi user can do a man in the middle attack by using someone else's ID to open a Nequi account, since Nequi doesnt require you to show a physical ID to open an account, but i dont know how else could it help him to scam. Also, when you use Nequi, the app registers your money movement that gets ID'ed with a reference number, wich cannot be consulted from an outside source (mediator, arbitrator), its for internal use by Bancolombia. A screenshot can be taken but im not sure if there is a way to notarize a mobile screenshot.

Mandatory data: To open an account you will need an email, a phone number from Colombia and a national ID. Nequi also does biometrics with your face, but its for internal use. Opening an account its instant and they dont do any verification that would be requiered to be used in Bisq.

Aditional notes: Im proposing this method because Nequi is very popular on Colombia and there is no COP volumen in Bisq and i will volunteer in anything needed to set this method. With risk of putting a bad name on Colombian people (im Colombian anyway), people tend to be dishonest and try to fraud if the oportunity appears. I would suggest at least a 30% collateral for the 2/2 multisig, and i wouldnt mind at all at 50%. Also, to kickstart this. I would ask for a signed account under this method and i would put small trades to sign other people.

### PR DESCRIPTION
**Pull request by ghost**
Nequi is a Colombian payment method requiring only a phone number to be specified in the Bisq account.

Closes bisq-network/growth#193

(This PR depends on currently open PR #5721).

---

**Account creation:**
nequi_account_popup
nequi_account

**Buy BTC:**
nequi_buy_popup

**Sell BTC:**
nequi_sell_popup
nequi_sell_offer

**Make payment:**
nequi_make_payment

**Confirm payment:**
nequi_confirm_payment

### CODE REVIEW

**Comment by ghost** [comment]
Rebased to master, ready for review.

**Comment by ripcurlx** [comment]
@jmacxx Commits are missing your signature

**Review by ripcurlx — DISMISSED** [review]
utACK

**Comment by ghost** [comment]
Rebased and signed.  :sweat_smile:

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
