### PR TITLE
List SpaceCash (XSC)

### PR DESCRIPTION
**Pull request by tlightsky**
Official project URL: https://hspace.app
Official block explorer URL: https://hyperstats.info/

This is a resubmission of List SpaceCash (XSC) #1766 
have done the rebase of current master and conflict resolve

### CODE REVIEW

**Comment by tlightsky** [comment]
@blabno @ManfredKarrer

**Comment by blabno** [comment]
Squash those commits into a single one. Code looks good.

**Comment by tlightsky** [comment]
@blabno ok, combine the commits to single one and rebased again

**Review by blabno — APPROVED** [review]
ACK

**Pull request merged**
