### PR TITLE
Fix Set Password text button

### LINKED ISSUE #3379: password is not saving
Password is not saving!

is saving - only when you click "I have already done a buckup" not other buttons.

bisq_LI

### PR DESCRIPTION
**Pull request by BtcContributor**
Fixes #3379

Now it looks like this:

bisq10

### CODE REVIEW

**Review by wallclockbuilder — DISMISSED** [review]
UtAck

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - It is kind of critical that the user understands what the setting of the password will cause. We know that users hardly read text so we want to prevent the user making a mistake. Maybe the text for the call to action should be more something like `Set password (I have already made a backup)` 👈  @m52go any ideas on a perfect condensed wording?

**Comment by BtcContributor** [comment]
I didn't want to fill a button with too much text.

Maybe some part of the explanation text could be in bold?

We could also change from "Go to Account/Wallet seed" to "Make a backup".

**Comment by wallclockbuilder** [comment]
Other wallets e.g. BlueWallet, CoboVault deal with this by requiring the user to confirm the backup seed before setting the password. This way you know for sure they backed up the seed and also got the correct seed.

**Comment by wallclockbuilder** [comment]
For backups bisq can also verify. Ask user for backup location. Confirm backup directory signature matches current backup directory signature. Both signatures should match as long as both directories have the same files and structure.

**Comment by m52go** [comment]
> Maybe some part of the explanation text could be in bold?

I don't think that's possible, unfortunately.

> We could also change from "Go to Account/Wallet seed" to "Make a backup".

I like this suggestion. So maybe the green button can be "Set Password (I already made a backup)" and the other can be "Make Backup" which goes to `Account` > `Backup`. If it fits...

**Comment by BtcContributor** [comment]
Pushed changes as stated by @m52go, thanks!

**Review by ripcurlx — APPROVED** [review]

**Pull request merged**
