### PR TITLE
Remove Byteball in order to remove commons-codec.

### PR DESCRIPTION
**Pull request by blabno**
This asset is not traded anymore.

### CODE REVIEW

**Comment by blabno** [comment]
Well, it seems that p2p module depends on `org.apache.httpcomponents:httpclient` which in turn depends on `commons-codec`.

**Review by chimp1984 — APPROVED** [review]
utACK

**Comment by chimp1984** [comment]
> Well, it seems that p2p module depends on org.apache.httpcomponents:httpclient which in turn depends on commons-codec.

Ah damn. But remove it anyway, better to get one explicit dependency removed...

**Comment by battleofwizards** [comment]
Once we migrate to Java 11+ there is hope with the new standard HttpClient:
http://cr.openjdk.java.net/~chegar/httpclient/02/javadoc/api/java.net.http/java/net/http/package-summary.html
Maybe one day it could replace the Apache HttpClient.

**Pull request merged**
