### PR TITLE
Reactivate travis builds for future automatic testing

### PR DESCRIPTION
**Pull request by sgeisler**
* reactivate travis
* add bitcoinj as submodule

I'm not completely shure if adding bitcoinj as a maven moule is a good idea. But it was the cleanest way to reenable travis builds.

[See the working travis CI build here.](https://travis-ci.org/sgeisler/bitsquare/builds/171997049)

### CODE REVIEW

**Comment by mrosseel** [comment]
Did you use the correct branch of bitcoinj as detailed in the build instruction page?

$ git clone -b FixBloomFilters https://github.com/bitsquare/bitcoinj.git

**Comment by sgeisler** [comment]
I will re-check, but I thought is was the default branch of the bitsquare/bitcoinj repo.

EDIT: yes, the submodule has version 206b5b, which is the newest on FixBloomFilters.

**Comment by ManfredKarrer** [comment]
I would prefer to do that merge to the branch https://github.com/bitsquare/bitsquare/tree/TravisAndSubModules.
Master is used by some folks to run the release version so I don't want to break anything here or force devs to change their setup before it is not all completed.

**Comment by jonathancross** [comment]
Is this now obsolete per #855 ?

**Comment by ManfredKarrer** [comment]
I think so.

**Pull request closed without merging**
