### PR TITLE
Add optional txFeeRate parameter to api sendbsq

### PR DESCRIPTION
**Pull request by ghubstan**
If present in the api's `sendbsq` command, the parameter will override the fee service and custom fee rate setting for the BSQ transaction.

Also changed the `sendbsq` grpc return type to a lightweight TX proto wrapper.

Besides some small refactoring in the CLI, all the changes are adjustments for this new `sendbsq` parameter and its new grpc return value.

This is the 3rd in a chain of PRs beginning with https://github.com/bisq-network/bisq/pull/4884.
PR https://github.com/bisq-network/bisq/pull/4896 should be reviewed before this one.

### CODE REVIEW

**Review by sqrrm — COMMENTED** [review]
utACK

Cannot merge until previous PR has been acked, #4896

**Comment by ghubstan** [comment]
Force travis re-build after jar download failure.

**Comment by ghubstan** [comment]
Force travis build, hoping jar download will not fail.

**Comment by ghubstan** [comment]
Review and merged with https://github.com/bisq-network/bisq/pull/4966.

**Pull request closed without merging**
