### PR TITLE
List HTH

### PR DESCRIPTION
**Pull request by MichaelHDesigns**
Https://hthcoin.world 

Https://explorer.hthcoin.world

### CODE REVIEW

**Comment by MichaelHDesigns** [comment]
Ok it is now 1 single commit. My apologies!

**Comment by aejontargaryen** [comment]
https://docs.bisq.network/exchange/howto/list-asset.html#step-6-submit-your-pull-request :slightly_smiling_face:

**Comment by aejontargaryen** [comment]
"Make sure you do this from a dedicated topic branch in your fork named, for example, `list-foo-asset`. Do not submit your pull request directly from your master branch, as this can make things unnecessarily complex if and when there are merge conflicts."

**Comment by MichaelHDesigns** [comment]
This is not from the master branch. This is a fork from the master branch
 My personal github.

**Comment by aejontargaryen** [comment]
it just means to **make** and **use** a new branch from your fork to help distinguish "master from master" when merging.
`devilking6105:list-hth-asset` :v:

**Comment by MichaelHDesigns** [comment]
Ok so what do I need to do?

**Comment by blabno** [comment]
@devilking6105 create new local branch `list-hth-asset` and submit new PR.

**Comment by MichaelHDesigns** [comment]
Ok, thank you. I will get this fixed as soon as I can.

**Comment by blabno** [comment]
Rebase and resolve conflicts.

**Comment by blabno** [comment]
@ManfredKarrer close this PR as it has been resubmitted as https://github.com/bisq-network/bisq/pull/1926

**Comment by MichaelHDesigns** [comment]
so im not bombarding with commits, can you help explain why the Travis CL
test failed every single asset? i dont know if it is on my end or yours,
but i wont touch anything until i hear from you. Thank you

**Pull request closed without merging**
