### PR TITLE
(11/11) Clean up removeExpiredEntries

### PR DESCRIPTION
**Pull request by julianknutsen**
New commits start: bdef1e4

The first commit removes a check inside removeExpiredEntries that optionally skipped an Entry if it was a PersistableNetworkPayload. This is an invalid payload, but there weren't any guarantees around it. I've added tests to ensure it can never happen and cleaned up the removeExpiredEntries check.

The second commit cleans up the code structure and data structure usage to be easier to read and slightly more performant. Since this code runs on the UserThread it can be less conservative with the copy and iteration.

### CODE REVIEW

**Review by chimp1984 — APPROVED** [review]
utACK

**Review by freimair — APPROVED** [review]
Ack

**Review by ripcurlx — APPROVED** [review]
utACK - I don't merge this PR as the commits will be part of #3609 anyways. So I'll close it as soon as #3609 gets merged. Where is (10/10) 🤔 ?

**Comment by julianknutsen** [comment]
(10/10) was some small test code fixups in #3568. I needed @freimair to review to ensure it met his expectations. I'll be sending it out as a new PR since the design was approved. https://github.com/julianknutsen/bisq/commit/850cd9180213f396180b447d6164e7e8c3900ac2

**Pull request merged**
