### PR TITLE
Add API for payment started with XMR auto conf params

### LINKED ISSUE #7033: Cannot provide XMR tx id and tx key with RPC method ConfirmPaymentStarted
### Description

When using RPC method `ConfirmPaymentStarted` for XMR trades, user is not able to provide transaction id and transaction key.

#### Version

v1.9.14

### Steps to reproduce

RPC method `ConfirmPaymentStarted()` takes only one parameter (the `trade_id`).

### Expected behaviour

`ConfirmPaymentStarted()` should allow two additional (optional) parameters for transaction id and transaction key, `tx_id` (or`tx_hash`) and `tx_key`.
This would be consistent with how GUI works and improve user experience.

### Actual behaviour

API user cannot provide transaction id and transaction key with RPC method `ConfirmPaymentStarted()`

#### Device or machine

Debian, Bisq v1.9.14

### PR DESCRIPTION
**Pull request by ghost**
Fixes #7033

_Basedon / follow-on from #7023._

Allows `tx-id` & `tx-key` to be specified for XMR auto-confirm.

### CODE REVIEW

**Comment by dutu** [comment]
It works great, thank you!

**Review by alvasw — CHANGES_REQUESTED** [review]
Nit

We can simplify the null and `isEmpty` handling with `Optional<String>`s. Moreover `Optional`s enforce us to handle both cases and avoid `NullPointerException`s.

**Comment by dutu** [comment]
@jmacxx are we not going to have this change implemented?

**Comment by ghost** [comment]
I had to fix merge conflicts with the current master branch.  Also, I don't know how to implement @alvasw suggestion above.

**Comment by dutu** [comment]
From what I can see, you have implemented `null` and `isEmpty` checks in line with existing code done for other parameters. 

@alvasw, for consistency sake would it make more sense to change these checks based on your suggestions separately, when it's done for all parameters?

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
