### PR TITLE
Allow host as bitcoinRegtestHost parameter

### PR DESCRIPTION
**Pull request by devinbileck**
When using a remote regtest host, instead of having to pass
REG_TEST_SERVER to the bitcoinRegtestHost parameter and hard code the
host address within the code, allow the host to be specified by the
bitcoinRegtestHost parameter.

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
@devinbileck Can you merge in master? There have been some issue with a test class

**Comment by devinbileck** [comment]
@ManfredKarrer Done!

**Review by ripcurlx — APPROVED** [review]
utACK - But as I haven't touched part of this code yet, I'll leave it to @ManfredKarrer to merge.

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Pull request merged**
