### PR TITLE
List Denarius (D)

### PR DESCRIPTION
**Pull request by metaspartan**
List Denarius (D)

Official project URL: https://denarius.io
Official block explorer URL: https://chainz.cryptoid.info/d/ or https://coinexplorer.net/D

### CODE REVIEW

**Comment by metaspartan** [comment]
@ripcurlx @blabno - PR meets all guidelines and unlisted requirements.

**Comment by wiz** [comment]
@carsenk didn't you premine this coin? Bisq has a no-scam policy

**Comment by manosv** [comment]
@wiz no he didnt premine it. Dev-fund was 1M which already given to the community for Marketing purposes. Its not the first or the last coin with a Dev-fund and definitely its not a ICO like the ones that took REAL peoples money

**Comment by metaspartan** [comment]
> @carsenk didn't you premine this coin? Bisq has a no-scam policy

@wiz Lets not beat around the bush, I know you are just sour because your friend didn't like the fact that I stood up for myself against his unprofessional and ignorant comments in regards to my last PR.

It had a premine that was given away in bounties for marketing and services during launch, coming on almost 3 years ago, the largest wallet currently as seen on the richlist is the Cryptopia liquidation user funds.

Everything with the premine was transparent during the launch and Denarius had NO ICO or pre-launch. Denarius is not a scam.

Also, just to make sure it is here, @ripcurlx and @blabno already approved everything in the last PR (https://github.com/bisq-network/bisq/pull/3650), it just wasn't merged due to the missing verification/signing of the commit, which was not actually outlined within your article for listings, it is Signed/Verified now and matches all existing documentation and requirements for listing. 

Feel free to come join our community of over 5,000+ that have been actively supporting the chain and community for the past 2+ years at https://discord.gg/uRFzFts

**Comment by buzzkillb** [comment]
> @carsenk didn't you premine this coin? Bisq has a no-scam policy

Why are ETH and ETC listed since those had some juicy premines.

**Comment by c5yal8r** [comment]
@wiz Now come on.  Denarius has been around since 2017.  It has an active community, team and github development.  Did you not just hear how IPFS was implemented into the Denarius wallet.  Maybe you should check out @carsenk GitHub development for Denarius. https://github.com/carsenk/denarius

**Comment by wiz** [comment]
> @wiz Lets not beat around the bush, I know you are just sour because your friend didn't like the fact that I

I don't care about that, I'm simply stating that Bisq has a no scam policy. If the project is legit then your asset can get listed in Bisq but I need to push back after hearing about the premine because Bisq gets a lot of requests to add scams. Search the past issues and you will see what I mean, I push back against all new assets getting added to Bisq so don't feel special :wink:

**Comment by mr-fool** [comment]
> 
> 
> > @wiz Lets not beat around the bush, I know you are just sour because your friend didn't like the fact that I
> 
> I don't care about that, I'm simply stating that Bisq has a no scam policy. If the project is legit then your asset can get listed in Bisq but I need to push back after hearing about the premine because Bisq gets a lot of requests to add scams. Search the past issues and you will see what I mean, I push back against all new assets getting added to Bisq so don't feel special 😉

Is not premine is dev fund. If premine is your concern how come eth and zec are listed

**Comment by wiz** [comment]
> Is not premine is dev fund. If premine is your concern how come eth and zec are listed

Good point, we should delist those 2 right away

**Comment by c5yal8r** [comment]
> > @wiz Lets not beat around the bush, I know you are just sour because your friend didn't like the fact that I
> 
> I don't care about that, I'm simply stating that Bisq has a no scam policy. If the project is legit then your asset can get listed in Bisq but I need to push back after hearing about the premine because Bisq gets a lot of requests to add scams. Search the past issues and you will see what I mean, I push back against all new assets getting added to Bisq so don't feel special 😉

So then going with the assumption that any crypto that has a premine is a SCAM.  You must remove ALL crypto on your DEX that does have a premine.  

DASH 
ETH
ETC
to name just a few I see that are currently listed.

**Comment by manosv** [comment]
Dont forget to delist Bitcoin also.After all Satoshi has 1M . Right ?

**Comment by chimp1984** [comment]
Oh damn, seems we got the full kindergarten crew now. Be aware that any Bisq contributor can request to remove an altcoin. I think the level gets filled up to do that once its merged....

**Comment by metaspartan** [comment]
> > @wiz Lets not beat around the bush, I know you are just sour because your friend didn't like the fact that I
> 
> I don't care about that, I'm simply stating that Bisq has a no scam policy. If the project is legit then your asset can get listed in Bisq but I need to push back after hearing about the premine because Bisq gets a lot of requests to add scams. Search the past issues and you will see what I mean, I push back against all new assets getting added to Bisq so don't feel special 😉

That goes great for your cause...sounds real professional. You got your rebuttal.

> > Is not premine is dev fund. If premine is your concern how come eth and zec are listed
> 
> Good point, we should delist those 2 right away

You might as well just shut down Bisq, you will have no cryptos listed, with that attitude, You would need to remove Bitcoin too, if you are going to follow your own policy, Satoshi has a very very large premine.

**Comment by metaspartan** [comment]
> Oh damn, seems we got the full kindergarten crew now. Be aware that any Bisq contributor can request to remove an altcoin. I think the level gets filled up to do that once its merged....

Sounds like we have a ton of requests to make then ;)

**Comment by chimp1984** [comment]
> Sounds like we have a ton of requests to make then ;)

Not all shitcoiners are that annoying.

**Comment by metaspartan** [comment]
> > Sounds like we have a ton of requests to make then ;)
> 
> Not all shitcoiners are that annoying.

Not a shitcoiner or annoying, just persistent.

**Comment by mr-fool** [comment]
> Not all shitcoiners are that annoying.
You just have multiple sets of rules and are not applied fairly

**Pull request closed without merging**
