### PR TITLE
Add autogenerated entry by Intellij (2019.2)

### PR DESCRIPTION
**Pull request by ripcurlx**

### CODE REVIEW

**Comment by bodymindarts** [comment]
Do we care about line endings? Cause this file is missing a CR at the bottom. May as well add it.

**Comment by ripcurlx** [comment]
> Do we care about line endings? Cause this file is missing a CR at the bottom. May as well add it.

Atm we don't have it in other config files as well. No strong opinion about that. But to be consistent with the other files right now I'd push it as it is.

**Comment by battleofwizards** [comment]
@bodymindarts this file is auto generated by IntelliJ IDEA and for that reason it is not subject to the best practice you mentioned.

**Comment by chimp1984** [comment]
Ups... from slack: " to fix that annoying PREFERRED_PROJECT_CODE_STYLE open code style and change to project. it its already set, change ot other, apply and the change back to project. same with code stype/java. that fixed it for me. seems IDEA has from old versions the setting and does not rewrite it if not newly applied"

**Pull request merged**
