### PR TITLE
Add CelPay payment method

### LINKED ISSUE #231: Add CelPay as a Multi stablecoin currency payment method
## CelPay - Multi-currency (stablecoins)

Website: https://celsius.network/celpay/
Youtube explainer: https://www.youtube.com/watch?v=AS6IIsHb7bM
Celsius interest rates: https://celsius.network/rates/

### Background

This is a proposal for an Idea I had about using a the Celsius app to send and receive stablecoins for Bisq Traders. 

I am not 100% for it just think it would be good for discussion as an alternative to bank payments!

### Why

Celsius is a popular saving / earning crypto service. They report to have over $1 Billion in users deposits that they rehypothecate to earn interest for users. For example they pay interest on your deposited Bitcoin of about 5.9%. Remember though not your keys not your coins!

They have a feature called CelPay within the app that allows users to send payments to their Celsius contacts within the app or send them a payment link. This could be used for Bisq users to send stable coins to eachother.

The benefit of this is that you are:

- You are sending and receiving funds via a crypto app - no need for a bank 😃
- You earn interest on your deposited stable coin funds 
- Not much info needed to send payment

### Region

Celsius is available in over 100 countries

### Currencies

- USD Stablecoins; DAI, TrueUSD, USDC
- CAD Stablecoins; TrueCAD
- GBP Stablecoins; TrueGBP
- HKD Stablecoins; TrueHKD
- AUD Stablecoins; TrueAUD

### Chargeback risk

Low

### Size of user base

100,000+ active users 

### Data requirements

- You can send to phone contacts so Name / Mobile number is needed 

*name could really be anything. It is just something the buyer would name you as in their contact list. It is the mobile number that is important to link the payment to.

### Verification

Currently only a mobile app is available but soon a web app will be added and TLSNotary will be possible

### Duration

Instant (24 hours trade time)

### Fees

It is free to send and receive 

### Fraud risk

Low

### Payment amounts

$2,500 limit per 24 hours.

### Additional information

If added I would propose making it available for the following currencies:

USD, CAD, GBP, HKD, AUD

When offers where taken the buyer could then make the payment in any associated stablecoin equivalent supported by the app. It is only USD that has three options (DAI, TrueUSD, USDC). It easy in Celsius to set up wallet addresses for any stablecoin,

There would be the issue that you are using a stablecoin as a replacement for fiat on the fiat market, I do not think this would be an issue though as everyone who created a CelPay payment method would be aware of this.

If you want to try Celsius out let me know. Celsius are currently offering new users a $60 BTC bonus when you sign up with a referral code and deposit $200 in any supported crypto! 💲💲💲

### PR DESCRIPTION
**Pull request by ghost**
CelPay is a simple multi-currency payment method similar to Transferwise, requiring only an email address to be specified in the Bisq account.

Closes https://github.com/bisq-network/growth/issues/231

~(This PR depends on currently open PR #5696).~

---

**Account creation:**
celpay_account_popup

celpay_account

**Buy BTC:**
celpay_buy

**Buy BTC offer entry:**
celpay_buy_form

**Sell BTC:**
celpay_sell_popup

**Make payment:**
celpay_trade_payment

**Confirm payment:**
celpay_confirm_payment

### CODE REVIEW

**Comment by ghost** [comment]
Rebased to master, ready for review.

**Review by ripcurlx — DISMISSED** [review]
utACK

**Comment by ripcurlx** [comment]
@jmacxx It seems your commit is missing the signature

**Comment by ghost** [comment]
:thinking: must have lost the commit signature when rebasing, I'll keep an eye out for that in future.  Signed now.

**Comment by ripcurlx** [comment]
Closing as commits are already part of https://github.com/bisq-network/bisq/pull/5724

**Pull request closed without merging**
