### PR TITLE
Add popup reminder to inform users of trading rules

### PR DESCRIPTION
**Pull request by ghost**
Requested by the support team.
There has been an uptick of users including bitcoin txids in payment reference fields.

Once app has started, shows popup:

image

@w0000000t @pazza83 @leo816 @MwithM  :eyes:

### CODE REVIEW

**Comment by w0000000t** [comment]
Cool!
Myself, I would tweak it to make shorter and more straight to the point, so lazy users won't just skip it with "_eh don't want to read it all, let's just click the green button and be done with it_".

```
KNOW THE PENALTIES TO AVOID THE PENALTIES

Not following the trading rules [1] could make you lose money!
Make sure to check what the penalties [2] are, and have a chat with the support team [3] in case of doubts.
```

I would place the ALL CAPS warning directly in the green text title, for maximum impact and least text possible

**Comment by ghost** [comment]
@w0000000t I tried putting your all caps message in the title but there were a couple of reasons why it did not look good:

(a) it got truncated, and
(b) it seems way too harsh to be shouting in the popup title like that, at application startup.

So I prefer the all caps message in the text body, as shown in the OP.  :point_up: 

<details>
<summary>example, for reference</summary>


image


</details>

**Comment by ghost** [comment]
@ripcurlx any chance this can go in the coming release, v1.9.0?

**Review by ripcurlx — APPROVED** [review]
utACK - Code changes are looking fine 👍

**Pull request merged**
