### PR TITLE
Use same private_key in NewTor and RunningTor mode + Hiddenservice Fix

### LINKED ISSUE #2010: External Tor features does not announce its hidden service
When testing my external Tor implementation yesterday (during the testing of the 0.9 release candidate) I found, that in its current implementation, jtorctl does not announce a freshly generated ephemeral serivce to the Tor network.

Has been fixed in #2009, however, as jitpack is behaving kind of funny (jitpack/jitpack.io#3572), that fix is not ready to be included into Bisq as of now.

I recommend taking the
```- [Enable use of external Tor services](https://github.com/bisq-network/bisq/pull/1935)```
off the list of new features, until this issue gets closed by myself.

### PR DESCRIPTION
**Pull request by freimair**
- in consideration of #1055 and #1056 I enhanced jtorctl to accept the format of the private_key

- closes #2010. When using the external Tor feature, the hidden service never gets announced to the Tor network. Hence, it takes literally ages until its hidden service is accessible from outside. The new Netlayer+jtorctl releases now actively announce the service to the Tor network.

- and there is bad news: jitpack gives me some hard times. It refuses to build the correct commit when a tag is specified (jitpack/jitpack.io#3572), so the travis build is expected to fail.

I will give the guys at jitpack a few more days either to come back to me and fix the issue or hopefully, this mysterious caching timeout hits and everything is fine again.

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Please update from master. We just merged the release branch...

**Comment by freimair** [comment]
finally, all seems to work as expected.

**Comment by ManfredKarrer** [comment]
Will review when back from holiday in January...

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Pull request merged**
