### PR TITLE
Basic support for version 2 transactions. 

### PR DESCRIPTION
**Pull request by oscarguindzberg**
Cherry pick https://github.com/bitcoinj/bitcoinj/commit/850f21960723dfcb664f795404f3f42004bd32eb
Fixes https://github.com/bisq-network/bisq/issues/1832

Don't merge until:
- https://github.com/bisq-network/bitcoinj/pull/16 is merged
- A new bisq's bitcoinj and bisq's libdohj release is created and bisq is updated to use the new release versions.

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
I added WIP prefix to make clear that this PR is not ready for merge.

**Comment by ManfredKarrer** [comment]
The BitcoinJ PR is merged but we would require the libdohJ version update (in both Bisq and libdohJ). We could wait also until libdohJ is removed and we update to 0.14.7 if that is not too far in the future.

**Comment by oscarguindzberg** [comment]
Removed WIP label.
Ready to be merged once https://github.com/bisq-network/bisq/pull/2478 is merged

**Comment by ManfredKarrer** [comment]
@ripcurlx Lets delay that after release so we keep test efforts low.

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Pull request merged**
