### PR TITLE
Verify the assumption that a HashMap orders keys.

### PR DESCRIPTION
**Pull request by christophsturm**
to better understand the inconsitent hash problem that we currently have. @bodymindarts

### CODE REVIEW

**Comment by bodymindarts** [comment]
Nack. Can we test each case against a hard coded `byte[]`? Then we will see if a JVM update or something like that changes what we expect.

**Comment by christophsturm** [comment]
well that test just verifies what we talked about, and you can always add another test that uses a byte array.

**Comment by bodymindarts** [comment]
Afaict internally `LinkedHashMap` is [being used](https://github.com/protocolbuffers/protobuf/blob/f9d8138376765d229a32635c9209061e4e4aed8c/java/core/src/main/java/com/google/protobuf/MapField.java#L171) which actually preserves order and would thus make this test fail. In other words the behaviour is different depending on if we create it then serialize it (all key-orders lead to same bytes), or de-serialize it from the wire (due to `LinkedHashMap` internally it becomes order sensitive).

Its really funny that the whole of Bisq only works due to an implementation detail of the Java pb library (meaning hashes are reproducible on different nodes). Even in the reference implementation of protobuf (golang) a non-order-preserving map type is being used.

**Comment by bodymindarts** [comment]
I don't really see how this test is useful. What would be actionable if it breaks?
In order for bisq to remain stable it is not really important that insert order is deterministic. Its much more important that order remains stable during the deserialize -> reserialize process. If _that_ breaks down bisq is completely broken.

**Comment by christophsturm** [comment]
this test does not really test any of our own code. its just an investigation and documentation on how protobuf behaves with maps.

**Comment by ripcurlx** [comment]
@christophsturm Is this intended for discussion purpose only?

**Comment by christophsturm** [comment]
it was the result of a discussion but it could also be useful as documentation,.

**Pull request closed without merging**
