### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by wallclockbuilder**
Fixes typo in test function name.

### CODE REVIEW

**Review by ripcurlx — DISMISSED** [review]
utACK

**Comment by ripcurlx** [comment]
@wallclockbuilder You have to sign your commits for them to be able to get merged.

**Comment by wallclockbuilder** [comment]
Ok. On it.

**Comment by wallclockbuilder** [comment]
> @wallclockbuilder You have to sign your commits for them to be able to get merged.

Fixed.

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
