### PR TITLE
Add backup operator for seeds 3f3cu2yw7u457ztq and fl3mmribyxgrv63c

### PR DESCRIPTION
**Pull request by devinbileck**

### CODE REVIEW

**Review by ManfredKarrer — COMMENTED** [review]
utACK

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - I think it is better to use my GitHub handle in that case: @ripcurlx

**Comment by devinbileck** [comment]
Fair enough - updated. I wasn't sure if the intention is to tie it to a GitHub account or Slack account in order to notify in case of issue.

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
