### PR TITLE
Add front matter to issue_template.md

### PR DESCRIPTION
**Pull request by huey735**
I added semanticly relevant front matter to the issue_template.md
so that it explicit that it should be reserved for reporting bugs
or unintentional behaviours from the software.

### CODE REVIEW

**Comment by huey735** [comment]
#5346 broke the Github issues @sqrrm. I think I also need to rename issue_template.md to bug_report.md. Should I do it here or create a new PR?

**Comment by ripcurlx** [comment]
I just have ignored the file from Codacy. Could you please force push to re-trigger the Codacy check? Thanks!

**Comment by huey735** [comment]
Done.

**Review by ripcurlx — DISMISSED** [review]
utACK

**Comment by ripcurlx** [comment]
You missed to sign the commit

**Review by ripcurlx — DISMISSED** [review]
utACK

**Comment by ripcurlx** [comment]
https://github.com/bisq-network/bisq/pull/5352/commits/5322629fa552cbd83925493c36068ebddaca6aa1 is not signed yet

**Comment by huey735** [comment]
Oh. How can I fix that?

**Comment by ripcurlx** [comment]
I've just ignored the other file as well in codacy. Could you please force push again? Thanks!

**Review by ripcurlx — APPROVED** [review]
utACK

**Pull request merged**
