### PR TITLE
Add transferwise account

### PR DESCRIPTION
**Pull request by chimp1984**
Implements https://github.com/bisq-network/proposals/issues/243

### CODE REVIEW

**Comment by ripcurlx** [comment]
@chimp1984 Can you please force-push again. I did remove the pattern for this file for now, but kept it in general as it is good practice in other cases.

**Comment by chimp1984** [comment]
I guess close/reopen triggers it as well...

**Comment by chimp1984** [comment]
Force push did not work either, added a new commit....

**Review by sqrrm — APPROVED** [review]
utACK

**Pull request merged**
