### PR TITLE
List Doichain (DOI)

### PR DESCRIPTION
**Pull request by NiKrause**
- Official project URL: http://www.doichain.org
- Official block explorer URL: http://explorer.doichain.org

### CODE REVIEW

**Comment by blabno** [comment]
Please provide link to a transaction in your explorer showing that arbitration is possible.

**Comment by blabno** [comment]
Code looks good. No sign of ico.

**Comment by NiKrause** [comment]
I hope this is what you are looking for:
https://explorer.doichain.org/tx/3e66f2315e543dad38b2d0fb33dd746aa957e7f9388c688fbae75e1cd53d75d6

**Review by blabno — APPROVED** [review]
ACK

**Pull request merged**
