### PR TITLE
Add info popup about Argentinian Peso market prices.

### PR DESCRIPTION
**Pull request by ghost**
@HenrikJannsen [requested](https://github.com/bisq-network/bisq-pricenode/pull/15#issuecomment-1666597874) we display some info about the new ARS blue rate to users.

----

This will show at application startup and can be dismissed with the "Don't show again" option.

bluedollar

----

FYI 50% of [pricenodes](https://github.com/bisq-network/roles/issues/14) are currently providing blue market rates for ARS, the remaining 50% have not yet updated.

### CODE REVIEW

**Comment by alvasw** [comment]
This won't affect the majority of our users. We can show the dialog at start-up to users with an ARS payment account and additionally to everyone when they navigate to the ARS currency. What do you think?

**Comment by ghost** [comment]
I would think showing the news popup at startup helps attract users to the ARS market!  (Personally I don't think its an inconvenience, especially since there's a `Don't show again` option).

> show the dialog at start-up to users with an ARS payment account

Likely very few users would see it; bear in mind there have only been 10 lifetime trades.  Also weigh the challenge of testing all possible payment methods for ARS.

Happy enough to implement those changes if that's what the community wants.  @rodvar @pazza83 your thoughts?

**Comment by alvasw** [comment]
I agree with you!

**Review by alvasw — APPROVED** [review]
utACK

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Comment by rodvar** [comment]
Awesome guys!!!

**Pull request merged**
