### PR TITLE
[WIP] Redesign

### PR DESCRIPTION
**Pull request by ripcurlx**
I've created this pull request to keep everyone up-to-date on the redesign progress and to push myself a little bit to get it done as quickly as possible 😉 

## Open Tasks

- [ ] Check all forms to use material design style
  - [ ] Fiat Account View - Add new account
  - [ ] Altcoin Account View - Add new account
- [x] Show currency label also if there are no offers available (OfferBook, OfferBookChart,...)
- [ ] Check if rendering intensive views can be delayed not to conflict with ripple effect in e.g. tabs
- [x] Fix height in Offer Book View to prevent scrollbar
- [ ] Adapt Create Offer screen, that there won't be scrolling necessary
- [ ] Use ButtonBar for all buttons to have consistent positioning
- [x] Show error below TextField instead of a popup 
- [x] Fix ComboBox selected values not shown in some cases
- [x] Use tabs in account section instead of toggle button group left
- [ ] Style Date Picker

## Optional
- [ ] Add ripple effect for main navigation
- [ ] Clean up css colors
- [ ] Clean up css classes

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
@ripcurlx As discussed on phone I created a release branch and merged that PR into it. Can you close that PR and make new PRs to the release branch?

**Comment by ManfredKarrer** [comment]
Merged into release-candidate-0.9.0 branch.

**Comment by cbeams** [comment]
@ripcurlx, now that this PR is closed, what is the best way to provide feedback on the redesign before we merge and release the 0.9.0 branch?

I ran through the app from the head of the `release-candidate-0.9.0` branch earlier today and found a number of UI issues. Mostly minor stuff like spacing, placement of drop-down menus, etc., but some more significant things, too, like restyling the `Trades` graph to match the style of the `Offer Book` graph. Do you have a TODO list somewhere that already includes these things? I don't want to spam you with a bunch of stuff you already know about and already plan to fix.

**Comment by ManfredKarrer** [comment]
@cbeams It is still too early for feedback...too much open known stuff by ourself... but yes the release candidate is where the latest code is in. As soon @ripcurlx is ready we will do a cross check with @pedromvpg and then ask for review and testing. Might take another week...

**Comment by cbeams** [comment]
Perfect, thanks.

**Comment by ripcurlx** [comment]
@cbeams I created an [issue](https://github.com/bisq-network/bisq/issues/1857), which I'll update on the go until we are ready for a bigger testing cycle.

**Pull request closed without merging**
