### PR TITLE
Resolve issues with javacv

### PR DESCRIPTION
**Pull request by devinbileck**
This should resolve the UnsatisfiedLinkError encountered on macOS in #7166.
It should also further reduce the bundled javacv library size. Only my linux machine, the total included libs are now down to ~323 MB.

### CODE REVIEW

**Comment by devinbileck** [comment]
I am looking into why this is still failing.

**Review by HenrikJannsen — DISMISSED** [review]
From build error output:
```
QrCodeProcessorTest > process_ValidQrCodeFrame_ReturnsDecodedText() FAILED
    java.lang.UnsatisfiedLinkError at QrCodeProcessorTest.java:41
        Caused by: java.lang.UnsatisfiedLinkError at QrCodeProcessorTest.java:41

QrCodeProcessorTest > process_NonQrCodeFrame_ReturnsEmptyOptional() FAILED
    java.lang.RuntimeException at QrCodeProcessorTest.java:52
        Caused by: java.lang.UnsatisfiedLinkError at QrCodeProcessorTest.java:52

QrCodeProcessorTest > process_InvalidFrame_ReturnsEmptyOptional() FAILED
    java.lang.RuntimeException at QrCodeProcessorTest.java:68
        Caused by: java.lang.UnsatisfiedLinkError at QrCodeProcessorTest.java:68
 ```

**Review by HenrikJannsen — DISMISSED** [review]
utACK

**Comment by HenrikJannsen** [comment]
@devinbileck Could you resolve the conflicts? I deactivated it as well in my past PRs...

**Review by HenrikJannsen — APPROVED** [review]
utACK

**Pull request merged**
