### PR TITLE
Remove reference to non-functioning BSQ explorer

### PR DESCRIPTION
**Pull request by ghost**
wizbsq

The (@wiz) BSQ explorer is no longer functioning.
Remove it from the list of available explorers.
If a user already had that explorer selected, choose the next available one from the list.

### CODE REVIEW

**Comment by wiz** [comment]
I reported the issue a few times over the years, but I have been unable to upgrade Bisq since ~2 years ago, because it stopped working with external Tor on FreeBSD.

If this is the response then that's great for us, mempool.space will simply stop supporting Bisq.

**Comment by ghost** [comment]
Hi wiz!  I will look into why Bisq is not working on FreeBSD.

**Comment by ghost** [comment]
> Hi wiz! I will look into why Bisq is not working on FreeBSD.


I installed FreeBSD and attempted to build Bisq.  Unfortunately the [gradle/javafx build ecosystem](https://github.com/JabRef/jabref/issues/9745) [only supports Linux/Mac/Windows](https://github.com/bisq-network/bisq/issues/4180).  However, it is possible to build on Linux and move the source+jars over to FreeBSD where it will run OK.  I successfully ran [bisq-pricenode](https://github.com/bisq-network/bisq-pricenode), [bisq-seednode](https://github.com/bisq-network/bisq/tree/master/seednode), and [bisq-statsnode](https://github.com/bisq-network/bisq/tree/master/statsnode) (the latter two using external rather than built-in Tor).  I did not try the GUI as my FreeBSD system did not  have a windowing environment.

ref: https://github.com/bisq-network/bisq/issues/4419, https://github.com/bisq-network/bisq/issues/2969

---

So anyway the infrastructure can run on FreeBSD.  If there are other reasons why 2/3 BSQ explorers are currently non-functional (and the 3rd having impaired performance), it can be discussed perhaps in a project proposal. (cc @pazza83)

**Comment by pazza83** [comment]
Hi @wiz It would be great if mempool.space can continue to provide support for Bisq by way of maintaining https://bisq.markets/ 

Would also be good if all the BSQ explorers showed consistent data. Not sure what would be needed from me, tagging in @Emzy also.

**Comment by wiz** [comment]
@pazza83 I'm glad that mempool.space was able to develop a proper BSQ explorer for Bisq and operate the bisq.markets website over the years, but it's time to pass the torch on to who wants to takeover this responsibility for the community.

Bisq has a fork of The Mempool Open Source Project up at https://github.com/bisq-network/mempool and I've created https://github.com/bisq-network/mempool/pull/1 that will update the project to the point before we remove Bisq support. Now the maintainers of Bisq can takeover this role of maintaining the BSQ explorer.

**Comment by pazza83** [comment]
@wiz thanks for developing the explorer and markets website and transitioning things smoothly. 

@jmacxx would you be able/interested to run a BSQ explorer for users? Then we could keep with 3 explorers in total?

**Review by alvasw — APPROVED** [review]
utACK

@wiz Thank you very much for running everything over the last years!

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
