### PR TITLE
added XVG

### PR DESCRIPTION
**Pull request by ghost**
added Verge/XVG to list of available cryptocurrencies

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Please follow that protocol for adding an altcoin:
https://forum.bitsquare.io/t/how-to-add-your-favorite-altcoin/46

**Comment by vergecurrency** [comment]
@manfredkarrer added blockexperts, we can add bitsquare to our website, vergecurrency.com the moment the pr is merged. also, where would you like the input on validating addresses?  also any interest in an i2p option? i can make a new branch and look into it.

**Comment by vergecurrency** [comment]
pub/script is 30/33

**Comment by ManfredKarrer** [comment]
Input validation is still not used yet but once i add it i will request it. Have added it, but yourP PR added it to the wrong list.
i2p would be basically interesting but to support both Tor+i2p is impractical, so not considered. But if you are experienced with Tor we could need help in that area (e.g. China is blocked, would be great to find a solution to get aound that like pluggable transports,...)

**Comment by ManfredKarrer** [comment]
https://github.com/bitsquare/bitsquare/commit/73131e0c188883d7858fab9b7c37b4557cd5c456

**Comment by vergecurrency** [comment]
yeah i saw that, didnt notice the second list. i added another block explorer as well, in a new pr. maybe that should be mentioned to devs that add altcoins, to include a blockchain explorer with the symbol next to the title.. i noticed all the other chain explorers are btc only. 

yeah i can see where having support for i2p would be impractical. another approach could be an i2p only version in a seperate repo or branch.. very nice work so far, i have bitsquare running on my win and nix boxes, and it seems to be sturdy. after dinner i will do some testing =]

i am pretty experienced with tor, so i can also create some more nodes.. maybe specifically in HK for chinese users?

**Comment by ManfredKarrer** [comment]
Ah r u in HK? That issue in China would be really great if we can solve. Maybe its easy and you just go over VPN, but I don't have any dev there who could test and see how to get that solved. I will try also to get in touch with Tor devs to see what they recommend.

**Comment by vergecurrency** [comment]
no i am not in china, but i am familiar with the great wall. i will talk to someone i know there later today.

**Pull request closed without merging**
