### PR TITLE
Check if selected proposal is null

### LINKED ISSUE #2627: Voting on proposal threw a NullPointerException
I wasn't able to reproduce it again, but somehow the selected Item was reset (maybe through an update in the background).
```
java.lang.NullPointerException
	at bisq.desktop.main.dao.governance.proposals.ProposalsView.onAccept(ProposalsView.java:432)
	at bisq.desktop.main.dao.governance.proposals.ProposalsView.lambda$showVoteOnProposalWindow$9(ProposalsView.java:343)
	at java.base/java.util.Optional.ifPresent(Optional.java:172)
	at bisq.desktop.main.overlays.windows.SelectProposalWindow.lambda$addContent$2(SelectProposalWindow.java:192)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
´´´

### PR DESCRIPTION
**Pull request by ripcurlx**
Fixes #2627.

### CODE REVIEW

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Comment by ManfredKarrer** [comment]
@ripcurlx Could you reproduce the issue? Can it be that the user clicks on the icon in the table but no proposal is selected and therefore no voting will be applied? I am not sure if the icon would reflect correctly the domain state or if it gets changed by the mouse click. If so there might be a risk that the domain state is different as the UI state...

**Comment by ripcurlx** [comment]
> @ripcurlx Could you reproduce the issue? Can it be that the user clicks on the icon in the table but no proposal is selected and therefore no voting will be applied? I am not sure if the icon would reflect correctly the domain state or if it gets changed by the mouse click. If so there might be a risk that the domain state is different as the UI state...

I just found the problem (block parsing while the popup is open) and will implement it in a better way (update the open popup)

**Comment by ManfredKarrer** [comment]
Ah yes with a new block the table gets updated and selection is lost... that is annoying anyway but have not found a easy fix for that.... maybe to not clear selction would be first step.

**Comment by ripcurlx** [comment]
> Ah yes with a new block the table gets updated and selection is lost... that is annoying anyway but have not found a easy fix for that.... maybe to not clear selction would be first step.

To not mess too much with the existing UI code I'm closing and re-opening the selected proposal window after a new block has been parsed by selecting the same proposal if it still exists.

**Review by ManfredKarrer — COMMENTED** [review]
utACK

Should be tested good. Not 100% sure if the handling of the selction/hide is covering all situations correctly from the timing behaviour...

**Comment by ripcurlx** [comment]
> utACK
> 
> Should be tested good. Not 100% sure if the handling of the selction/hide is covering all situations correctly from the timing behaviour...

For that I was using the onHidden trigger. Worked for me now during testing except after having a proposal window open until the next cycle starts because of the current logic (doesn't break anything if it is closed).  If we want to be on the 100% safe side, we could just hide the window after a new block was parsed.

**Comment by ManfredKarrer** [comment]
I will test as well... please wait with merge a bit

**Comment by ManfredKarrer** [comment]
@ripcurlx Tested more and seems all Ok. But found another bug.
Could you apply that patch?

```Index: desktop/src/main/java/bisq/desktop/main/dao/governance/proposals/ProposalsView.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- desktop/src/main/java/bisq/desktop/main/dao/governance/proposals/ProposalsView.java	(date 1554388467000)
+++ desktop/src/main/java/bisq/desktop/main/dao/governance/proposals/ProposalsView.java	(date 1554394709000)
@@ -204,6 +204,8 @@
 
         selectedProposalSubscription = EasyBind.subscribe(tableView.getSelectionModel().selectedItemProperty(), this::onSelectProposal);
 
+        daoFacade.addBsqStateListener(this);
+
         sortedList.comparatorProperty().bind(tableView.comparatorProperty());
         tableView.setPrefHeight(100);
         root.getScene().heightProperty().addListener(sceneHeightListener);
@@ -304,7 +306,7 @@
     private void addListenersAfterParseBlockChainComplete() {
         daoFacade.getActiveOrMyUnconfirmedProposals().addListener(proposalListChangeListener);
         daoFacade.getAllBallots().addListener(ballotListChangeListener);
-        daoFacade.addBsqStateListener(this);
+
         bsqWalletService.addBsqBalanceListener(this);
 
         phaseSubscription = EasyBind.subscribe(daoFacade.phaseProperty(), this::onPhaseChanged);
@@ -314,10 +316,6 @@
         listItems.forEach(ProposalsListItem::cleanup);
         listItems.clear();
 
-        fillListItems();
-    }
-
-    private void fillListItems() {
         if (daoFacade.phaseProperty().get().ordinal() < DaoPhase.Phase.BLIND_VOTE.ordinal()) {
             // proposal phase
             List<Proposal> list = daoFacade.getActiveOrMyUnconfirmedProposals();
```

**Comment by ripcurlx** [comment]
@ManfredKarrer Just applied your patch

**Pull request merged**
