### PR TITLE
List Sovereign Coin (SOV)

### PR DESCRIPTION
**Pull request by sovgithub**
Author: Michael Howlett <business@hthcoin.world>
Date:   Thur Nov 1 16:00:00 2018 -0800

    List Sovereign Coin (SOV)

Sovereign Coin Webpage  https://sovcore.org/

Sovereign Coin Block Explorer   http://explorer.sovcore.org/

### CODE REVIEW

**Comment by cbeams** [comment]
Please squash to a single commit.

**Comment by sovgithub** [comment]
Squashed

**Comment by blabno** [comment]
@sovgithub please rebase against master and resolve conflicts.

**Review by blabno — CHANGES_REQUESTED** [review]
NACK no PRs from master

**Comment by ManfredKarrer** [comment]
Close as no response from dev. Also we have a code freeze for new release soon.

**Comment by sovgithub** [comment]
Fixed and new Pull request made
https://github.com/bisq-network/bisq/pull/1969

**Pull request closed without merging**
