### PR TITLE
List Bitmark (BTM)

### PR DESCRIPTION
**Pull request by piratelinux**
Official project URL: http://bitmark.io
Official block explorer URL: http://explorer.bitmark.co

Sorry for the 3rd attempt! I am on the move and keep forgetting. I am telling the other developers to remind me this time.

I will rely on the automated tests to see if it builds because I don't have Java 10 on my system.

### CODE REVIEW

**Comment by aejontargaryen** [comment]
@piratelinux commits need to be squashed into single commit.

**Comment by piratelinux** [comment]
Ya I was just thinking of that. I will do now.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
@piratelinux Don't request a review if your branch still has conflicts.

**Comment by piratelinux** [comment]
I think the squashing worked now? I don't remember requesting review. Sorry.

**Comment by piratelinux** [comment]
Just checking...Are you waiting for me? Because I think I already did the request changes, so when will this be reviewed? Thanks

**Comment by blabno** [comment]
How do I search for specific transaction?

**Review by blabno — CHANGES_REQUESTED** [review]
NACK reformat code according to Bisq codestyle

**Comment by piratelinux** [comment]
Bisq codestyle?

This explorer can be used to look up a transaction: https://chainz.cryptoid.info/btm/

Is that fine or should we modify our explorer on explorer.bitmark.co?

**Comment by blabno** [comment]
Yes, Bisq has it's own code style. It's defined here https://github.com/bisq-network/bisq/tree/master/.idea/codeStyles

I do not care about the url structure of the explorer. I don't see any search input where I could type the transaction id.

**Comment by piratelinux** [comment]
Hi, for the explorer, I made some changes on a "dev" page: http://explorer.bitmark.co/index-dev.php. I am waiting for approval from someone, but it should soon be on explorer.bitmark.co. It allows for searching of txids, block hashes, or block numbers, and for txids it show the full block info (all transactions and amounts getting sent to the outputs). If you need more detailed transaction info (such as list of all inputs and values) then I can add that too.

For the code style, I looked through it and saw some properties like BLANK_LINES_BEFORE_PACKAGE and SOFT_MARGINS. But I think it satisfies it. I compared with other pull requests that were merged, and perhaps one problem is that I'm using tabs (automatic with emacs) in one place instead of spaces for indentation: https://github.com/bisq-network/bisq/pull/2078/files#diff-a500a9d38e9f89cca4fa053aab070da6R27. Is that the only issue?

**Comment by blabno** [comment]
Please use IntelliJ Idea which has free community edition available and format the code according to provided code style. We are not going to tell to what needs to be fixed on each line.

As to explorer you have to explain how arbitrators can verify if transaction has taken place or not between two given addresses.

**Comment by piratelinux** [comment]
So I tried IntelliJ, imported the main directory, imported the Project.xml code style. I see some errors/warnings but not sure if it's related to code style. Any more hints would be useful since this is quite tedious for small details...

For the explorer, sure I can add more details about the input addresses, to make sure you can identify the sending address(es).

**Comment by ManfredKarrer** [comment]
@piratelinux I cleaned up for you. 
Here is the Bisq donation address where you can pay for doing your work!
1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7

**Comment by piratelinux** [comment]
Thanks, finally! I updated the explorer by the way: http://explorer.bitmark.co

**Pull request merged**
