### PR TITLE
 Add blockchair mainnet and testnet explorers

### PR DESCRIPTION
**Pull request by eboukamza**
This feature add blockchair.com in blockchain explorer list.

I think is valuable for Bisq users because:

- Website load fast
- Show useful data like mempool size, estimated priority of a transaction in the mempool.
- Has an user-friendly UI/UX
- Has a testnet explorer too.

### CODE REVIEW

**Comment by sqrrm** [comment]
@wiz I don't know anything about this explorer. Do you think it's a reasonable one to add?

**Comment by eboukamza** [comment]
another good point is than if added, bisq could be mentioned in their site.

> For all the apps and services who put links to Blockchair we offer several neat things:
>    We'll mention your product on our About page
    We'll add your product to the "Useful links" sections across the website on pages like this (for all the coins you'll be linking to Blockchair)
    … and you'll make your users happy as they won't have to deal with those crappy block explorers anymore!

>Besides this, the backlinks will increase awareness of your product and improve your SEO.

see https://blockchair.com/referral

Than could make bisq grow.

**Review by wiz — APPROVED** [review]
ACK

**Review by sqrrm — APPROVED** [review]
utACK

**Pull request merged**
