### PR TITLE
Add toggle for displaying volume in tradestatistics chart in USD

### PR DESCRIPTION
**Pull request by chimp1984**
Adds a toggle to show trade statistics volume in USD instead of BTC

Screen Shot 2021-01-08 at 16 43 00
Screen Shot 2021-01-08 at 16 43 06

### CODE REVIEW

**Comment by Conza88** [comment]
Does it have to be USD? 😅
Anyway to provide fiat choice without being too hard?

**Comment by chimp1984** [comment]
It need to be fiat currency sufficiently trades, so EUR or USD are the only one which always got some volume. We calculate the historical price based on those trades. The calculation is a bit expensive so I dont want to do it for multiple currencies. Also for most USD price is kind of the main price metric. Does not mean any endoresement of USD of course - the biggest shitcoin in fiat land. ;-)

**Review by sqrrm — APPROVED** [review]
utACK

**Comment by cbeams** [comment]
Glad to see this feature. I just tweeted about it here: https://twitter.com/cbeams/status/1357298837052866560, and added a a follow-on feature request at #5154.

**Pull request merged**
