### PR TITLE
Set custom security deposit when cloning an offer

### PR DESCRIPTION
**Pull request by ripcurlx**
I tried to re-produce the issues mentioned by @BtcContributor, but wasn't able to do so.

Bildschirmfoto 2021-05-31 um 10 25 36
Bildschirmfoto 2021-05-31 um 10 25 32
Bildschirmfoto 2021-05-31 um 10 25 23
Bildschirmfoto 2021-05-31 um 10 25 19

### CODE REVIEW

**Comment by ripcurlx** [comment]
@BtcContributor Could you please give it a try again, as I wasn't able to re-produce the issue you found.

**Comment by ghost** [comment]
Tested, ACK.

**Comment by BtcContributor** [comment]
After seeing that also @jmacxx was not seeing any problem I tested again by deleting my app data folder.
In this case I can confirm that everything works as expected.

Honestly not sure why...

**Comment by ripcurlx** [comment]
> After seeing that also @jmacxx was not seeing any problem I tested again by deleting my app data folder.
> In this case I can confirm that everything works as expected.
> 
> Honestly not sure why...

That is really pretty weird behavior 🤔 

Let's keep an eye on this issue during the testing time on master until the next release.

**Review by sqrrm — APPROVED** [review]

**Pull request merged**
