### PR TITLE
Add API call to get DAO status

### PR DESCRIPTION
**Pull request by ghost**
Expose `DaoFacade.isDaoStateReadyAndInSync` status to API clients.

---

```
getdaostatus

NAME
----
getdaostatus - get DAO status

SYNOPSIS
--------
getdaostatus

DESCRIPTION
-----------
Returns the operating status of the Bisq DAO:
true - DAO is ready and in sync
false - DAO is not ready

At startup the status will return false until the DAO has completed synchronizing.
Trading operations should not be performed when the status is false.
While running, the status can be used to determine if DAO is in sync with the seed nodes.

EXAMPLES
--------
$ ./bisq-cli --password=xyz --port=9998 getdaostatus
```

### CODE REVIEW

**Comment by dutu** [comment]
Just wanted to point out, there seams to be no call rate metering.

**Comment by dutu** [comment]
I have applied the changes on top of v1.9.14 and currently using the new gRPC method. Everything working well!!

**Review by alvasw — CHANGES_REQUESTED** [review]
Nit

`getdaostatus` is missing in the `/bisq-cli --help`output.

**Comment by dutu** [comment]
Should rate metering be included as well?
https://github.com/bisq-network/bisq/blob/8dda8b2464a053e2007b4f1266e36ce9113d5da9/daemon/src/main/java/bisq/daemon/grpc/GrpcWalletsService.java#L401-L426

**Comment by ghost** [comment]
`--help` text change and rate metering added.

**Review by alvasw — APPROVED** [review]
ACK

Tested:
- `bisq-cli --help`  
- `bisq-cli getdaostatus --help`  
- `bisq-cli getdaostatus`
- Rate Limiting

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
