### PR TITLE
Support external Tor hostname

### PR DESCRIPTION
**Pull request by alvasw**
This PR requires https://github.com/bisq-network/netlayer/pull/18.

### CODE REVIEW

**Comment by alejandrogarcia83** [comment]
@alvasw The build fails.

**Comment by alejandrogarcia83** [comment]
@gabernard Could you please merge https://github.com/bisq-network/netlayer/pull/18?

**Comment by alvasw** [comment]
> @alvasw The build fails.

I couldn't target the latest netlayer commit because https://github.com/bisq-network/netlayer/pull/18 was not merged.

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
