### PR TITLE
List PENG (PENG)

### PR DESCRIPTION
**Pull request by ghost**
- Official project URL: https://pengcoin.io && https://github.com/coinpeng/pengcore
- Official block explorers: https://coinexplorer.net/PENG && http://149.28.12.158:88

### CODE REVIEW

**Comment by ghost** [comment]
@blabno I created a seperate PR for this asset as you requested in #2879 PR.

**Comment by blabno** [comment]
Change the commit message to conform to our guidelines and the code looks ok.

**Comment by ghost** [comment]
> Change the commit message to conform to our guidelines and the code looks ok.

@blabno Done. In case you need it:

Link to random transaction (1): https://www.coinexplorer.net/PENG/transaction/3ae121103db60e686ad701e3a5498664c699c688d70eb36438dbf2b3dabb1b4c
Link to random transaction (2): http://149.28.12.158:88/tx/c252dcc8fbb944f98746d61d6d06a7f96743433b5d0e1e2bb5ec61934041d217

**Comment by blabno** [comment]
You have changed only the PR title. Please change commit message.

**Pull request closed without merging**
