### PR TITLE
Refactor TakeBuyBTCOfferTest to replace sleep with loops

### PR DESCRIPTION
**Pull request by alyokaz**
Replace the use of Thread.sleep with while loops for asynchronous method calls

### CODE REVIEW

**Review by alvasw — CHANGES_REQUESTED** [review]
Code wise everything is fine!

Please reformat your code with an IDE or add the needed white space, so the code style matches with the existing.

```diff
             var timeout = System.currentTimeMillis() + 3000;
-            while(bobClient.getOffersSortedByDate(USD, true).size() < 1){
+            while (bobClient.getOffersSortedByDate(USD, true).size() < 1) {
                 sleep(100);
-                if(System.currentTimeMillis() > timeout)
+                if (System.currentTimeMillis() > timeout)
                     fail(new TimeoutException("Timed out waiting for Offer to be added to OfferBook"));
-            };
-            
-            List<OfferInfo> alicesUsdOffers  = aliceClient.getMyOffersSortedByDate(BUY.name(), USD);
+            }
+
+            List<OfferInfo> alicesUsdOffers = aliceClient.getMyOffersSortedByDate(BUY.name(), USD);
             assertEquals(1, alicesUsdOffers.size());
```
And
```diff
             do {
                 alicesUsdOffers = aliceClient.getMyOffersSortedByDate(BUY.name(), USD);
                 sleep(100);
-                if(System.currentTimeMillis() > timeout)
-                   fail(new TimeoutException("Timed out waiting for Offer to be removed from OfferBook"));
-            } while(alicesUsdOffers.size() > 0);
+                if (System.currentTimeMillis() > timeout)
+                    fail(new TimeoutException("Timed out waiting for Offer to be removed from OfferBook"));
+            } while (alicesUsdOffers.size() > 0);
 
             assertEquals(0, alicesUsdOffers.size());
```

**Comment by alyokaz** [comment]
Amended formatting as requested.

**Review by alvasw — APPROVED** [review]
utACK

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
