### PR TITLE
Tweak wording for takeOffer.fundsBox.isOfferAvailable

### PR DESCRIPTION
**Pull request by maxim-belkin**
Minor wording tweak. This message is automatically displayed before the buyer can take the offer, so it makes sense to say {that Bisq is} checking if the offer is still available.

### CODE REVIEW

**Comment by ripcurlx** [comment]
@m52go ☝️ Could you please review this one? Thanks!

**Comment by m52go** [comment]
Makes sense :+1:

utACK

**Review by ripcurlx — APPROVED** [review]
utACK

**Comment by maxim-belkin** [comment]
Thank you both for approving and merging!

**Pull request merged**
