### PR TITLE
Fix for handling of modal window closing

### PR DESCRIPTION
**Pull request by r8d8**
Related to #1042

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Thanks for the PR!
I assume you have tested it with some popups that it does not break anything and that it solves the issue on those Linux Desktops, right? Usually I prefer such PR to Development branch because master is used by users who run from source but as it is a small isolated change I will merge it, once you confirm me the above.

**Comment by r8d8** [comment]
@ManfredKarrer, 
tested on Arch and Ubuntu both using AwesomeWM. 
Let's make it into development, not to risk with master branch.
Will close this PR and reopen it into development, ok?

**Comment by ManfredKarrer** [comment]
Yes better make it to dev. Not a high urgent bug fix anyway. thanks

**Comment by ManfredKarrer** [comment]
@r8d8 No need for a new PR I will merge via console to dev

**Comment by ManfredKarrer** [comment]
Merged: https://github.com/bisq-network/exchange/commit/41cf028f7ea2404d572cb3941c365295c9cac284

**Pull request closed without merging**
