### PR TITLE
Refactor BisqEnvironment - change type of ignoreLocalBtcNode to boolean

### PR DESCRIPTION
**Pull request by lusarz**

### CODE REVIEW

**Comment by freimair** [comment]
can we have a 
```
  --ignoreLocalBtcNode
        If set, a Bitcoin core node running locally will be ignored
```

instead of 

```
  --ignoreLocalBtcNode=<value>
        If set to true a Bitcoin core node running locally will be ignored
```
while you are at it?

**Review by freimair — CHANGES_REQUESTED** [review]
can we have a 
```
  --ignoreLocalBtcNode
        If set, a Bitcoin core node running locally will be ignored
```

instead of 

```
  --ignoreLocalBtcNode=<value>
        If set to true a Bitcoin core node running locally will be ignored
```
while you are at it?

**Comment by lusarz** [comment]
Conflicts resolved.

I think we can do `--ignoreLocalBtcNode` instead of `--ignoreLocalBtcNode=<value>`, but we should consider situation when someone pass for example `--ignoreLocalBtcNode=false`. I propose to create dedicated issue for that and discuss it a bit there.

**Review by freimair — APPROVED** [review]
agreed.

Ack.

**Pull request merged**
