### PR TITLE
List CatalansCoin (CAT)

### PR DESCRIPTION
**Pull request by catalanscoin**
* Official project URL: http://catalanscoin.com
 * Official block explorer URL: http://explorer.catalanscoin.com

### CODE REVIEW

**Comment by blabno** [comment]
Is this privacy coin?

**Comment by catalanscoin** [comment]
Yes, It is a code fork from turtlecoin (cryptonote currency). Is there anything you need?

**Comment by blabno** [comment]
You have to tell us how the arbitration can be done.
You have to add code that urges users about what info about the transaction do they need to save in case the trade lands in a dispute. Look at i.e. Arqma impl https://github.com/bisq-network/bisq/commit/e4bd07959be4df07b42a4b09a31f175ae4711fe7

**Comment by ripcurlx** [comment]
Closing this PR because of no response for more than 30 days. @catalanscoin feel free to re-open anytime after addressing https://github.com/bisq-network/bisq/pull/2834#issuecomment-509523799.

**Pull request closed without merging**
