### PR TITLE
Remove nodes

### PR DESCRIPTION
**Pull request by devinbileck**
No need to merge this right away as I will keep them running for a while longer.

### CODE REVIEW

**Comment by devinbileck** [comment]
Not stale

**Review by alejandrogarcia83 — DISMISSED** [review]
utACK

**Comment by alejandrogarcia83** [comment]
Hi @devinbileck!
I'm sorry for the delay. Could you please rebase this PR against master again? I tried to do it myself but it breaks the GPG signature. Thank you!

**Comment by HenrikJannsen** [comment]
We should also remove persisted entries like done in `BisqSetup.maybeUpgradeBsqExplorerUrl` with other retired nodes.

**Review by alejandrogarcia83 — APPROVED** [review]
utACK

**Pull request merged**
