### PR TITLE
Tweak popup text and trade rules for USPMO payment method

### PR DESCRIPTION
**Pull request by wiz**
Screen Shot 2020-08-01 at 4 10 10

### CODE REVIEW

**Comment by m52go** [comment]
Looks good - we came up with the text together.

**Comment by cd2357** [comment]
Is this shown only to buyers, or to both buyers and sellers?

**If only to buyers:**
* `BTC buyers must ...` => `You (as a BTC buyer) must...`
  * seems more user-friendly and less "legalese"
* `... if there is a trade dispute, you will be required to send ..` => `... if there is a trade dispute, you (as a BTC Buyer) will be required to send..`
  * same reason as above, seems more user-friendly

**If shown to both:**
* `... if there is a trade dispute, you will be required to send ..` => `... if there is a trade dispute, the BTC Buyer (USPMO sender) will be required to..`
  * clarifies even more which of the two (buyer or seller) the "you" referes to

Just a few suggestions, I'm not a native EN speaker, and have no idea how USPMO works, so take this with a grain of salt :)

**Comment by wiz** [comment]
It's shown when creating a payment account, so all users see the terms, but these terms only apply for trades where you are the buyer, so I think the usage of "you" makes sense here.

And since this establishes the official Bisq policy for the USPMO payment method, it's intended to be "legalese", and follows the similar style used in terms for Monero and other payment methods that have special terms.

**Review by ripcurlx — APPROVED** [review]
utACK

**Comment by leo816** [comment]
It looks good to me, the only thing that I would add is to warn the seller not to confirm he received the payment until he has cashed the USPMO. USPS requires a US Money Order to be at least 60 days old before someone may submit the refund paperwork. 
So two things:

- We should remind the BTC Seller that a USPMO is eligible for cancellation 60 days after printed, and that the Seller should at least check the date before closing the trade. I have seen some examples where the dates are unclear (attaching a picture for reference)

- Not to confirm with the "payment received" button until they've fully cashed it.

US Postal Money Order

**Pull request merged**
