### PR TITLE
Add new Monero explorer xmrblocks.bisq.services with onion

### PR DESCRIPTION
**Pull request by devinbileck**
As per https://github.com/bisq-network/proposals/issues/257

### CODE REVIEW

**Comment by devinbileck** [comment]
I am still having some issues with the node that I am trying to resolve. But if we want to get this in for release, I will try to get it running as soon as I can. Not sure if we can filter it until it is ready?

**Review by chimp1984 — APPROVED** [review]
utACK

**Comment by chimp1984** [comment]
> I am still having some issues with the node that I am trying to resolve. But if we want to get this in for release, I will try to get it running as soon as I can. Not sure if we can filter it until it is ready?

Great thanks! I would suggest that we wait until you are ready.

**Comment by devinbileck** [comment]
I resolved the issues. The node should now be functional on clearnet and Tor.

**Review by wiz — APPROVED** [review]
ACK - Tested OK
http://devinxmrwu4jrfq2zmq5kqjpxb44hx7i7didebkwrtvmvygj4uuop2ad.onion/api/outputs?txhash=d51dfd7e176e2ee7f1d295f2843f63fc8fc2f5ce8464ddeab03a9c1cc201e2a1&address=85q13WDADXE26W6h7cStpPMkn8tWpvWgHbpGWWttFEafGXyjsBTXxxyQms4UErouTY5sdKpYHVjQm6SagiCqytseDkzfgub&viewkey=b22a15db9ee376c57e656f508b55f195b14b1c0d4b814f394506930f3407cb07&txprove=1
https://xmrblocks.bisq.services/api/outputs?txhash=d51dfd7e176e2ee7f1d295f2843f63fc8fc2f5ce8464ddeab03a9c1cc201e2a1&address=85q13WDADXE26W6h7cStpPMkn8tWpvWgHbpGWWttFEafGXyjsBTXxxyQms4UErouTY5sdKpYHVjQm6SagiCqytseDkzfgub&viewkey=b22a15db9ee376c57e656f508b55f195b14b1c0d4b814f394506930f3407cb07&txprove=1

**Review by sqrrm — APPROVED** [review]

**Pull request merged**
