### PR TITLE
Add wallet info view

### PR DESCRIPTION
**Pull request by chimp1984**
Add wallet info view with balance, xpub keys, hd paths and button to open wallet details

### CODE REVIEW

**Comment by chimp1984** [comment]
Screen Shot 2020-12-10 at 18 44 20

**Review by ripcurlx — DISMISSED** [review]
ACK

Please force push to re-trigger codacy checks (I remove two patterns to check for)

**Comment by chimp1984** [comment]
Merged and rebased on master

**Review by ripcurlx — APPROVED** [review]
ACK

Tested it on Regtest

**Pull request merged**
