### PR TITLE
List Noteblockhain [NTBC]

### PR DESCRIPTION
**Pull request by exoboosters**
This is in continuation with the Issue opened by our team earlier - https://github.com/bisq-network/bisq/issues/2792

Official Project website: https://www.notebc.com/
Official Block Explorer: http://explorer.notebc.io/

### CODE REVIEW

**Comment by exoboosters** [comment]
Corrected the class definition in NoteBlockchainTest.java

**Review by blabno — CHANGES_REQUESTED** [review]
NACK please squash the commits into single one.

**Comment by exoboosters** [comment]
Thank you @blabno Squashed the commits.

**Comment by ripcurlx** [comment]
@blabno Is besides the squashed commits something left for this PR to ACK it?

**Comment by blabno** [comment]
Looks good.

**Pull request merged**
