### PR TITLE
Add HalCash

### PR DESCRIPTION
**Pull request by ManfredKarrer**
Depends on:
https://github.com/bisq-network/bisq-common/pull/32
https://github.com/bisq-network/bisq-core/pull/144

### CODE REVIEW

**Comment by ripcurlx** [comment]
bildschirmfoto 2018-08-14 um 17 59 36
Editing of HalCash offer doesn't work properly atm. The price is updated, but the amount stays the same.

**Comment by ripcurlx** [comment]
I just recognized that the min amount is updated. Just looked like an error having a min-max range of 50-50.

**Comment by ManfredKarrer** [comment]
Hm... yes thats not good. I will have a look

**Review by ripcurlx — APPROVED** [review]
ACK - Tested it locally and everything worked except some edge cases when editing an offer. When the edit offer change discussed in Zoom is implemented everything is OK from my side.

**Pull request merged**
