### PR TITLE
Issue #3231 Fix

### PR DESCRIPTION
**Pull request by niyid**
Fixed sorting in views with TableView instances with no implemented sort.

### CODE REVIEW

**Comment by wiz** [comment]
Thanks for fixing this issue, haven't tested yet but looks good so far. Could you please fix the following?
- Swap the title and description of this PR, so that the title is "Fixes sorting in views with TableView instances with no implemented sort" and the description is "fixes #3231"
- Squash the 3 commits into a single commit
- The PR branch should not be named "master" but instead something like "fix-table-sort" to identify what it does

**Review by wiz — CHANGES_REQUESTED** [review]
Could you please fix the following:
- Swap the title and description of this PR, so that the title is "Fixes sorting in views with TableView instances with no implemented sort" and the description is "fixes #3231"
- Squash the 3 commits into a single commit
- The PR branch should not be named "master" but instead something like "fix-table-sort" to identify what it does

**Comment by niyid** [comment]
OK. I will get to it.

**Comment by freimair** [comment]
closed as duplicate of https://github.com/bisq-network/bisq/pull/3319

**Pull request closed without merging**
